### ISSUE TITLE
Neuron's multisig is preferably compatible with ckb-cli

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#1]
https://github.com/nervosnet/neuron-internal/issues/1289

**Comment by Keith-CY** [comment]
I've learned that there's a new [rust SDK](https://github.com/nervosnetwork/ckb-sdk-rust) under development, should we follow this one instead of [ckb-cil](https://github.com/nervosnetwork/ckb-cli)? @quake

**Comment by Keith-CY** [comment]
More info:

The feature requested in the internal issue has been enabled in neuron with PR https://github.com/nervosnetwork/neuron/pull/2324

It sets two steps to go finished a multisig transaction in neuron
1. construct a multisig tx and sign by someone, then export it from neuron for the next signer
2. Receive a partially signed multisig transaction and sign to make the transaction valid

Now we are going to support partially signed tx exported from other tools, like [ckb-cli](https://github.com/nervosnetwork/ckb-cli). But an alternative is under development([rust SDK](https://github.com/nervosnetwork/ckb-sdk-rust)). 

ckb-cli is generally used while rust SDK is promising, which one should we follow

**Comment by quake** [comment]
The rust SDK is not an end-user oriented tool, and there is no restriction on the format of multi-signature tx export, please follow the ckb-cli export format.

**Comment by Keith-CY** [comment]
> The rust SDK is not an end-user oriented tool, and there is no restriction on the format of multi-signature tx export, please follow the ckb-cli export format.

Got it

**Comment by Keith-CY** [comment]
> Which `ckb-cli` commands should we be compatible with? @Keith-CY I found no command we should adapt.

`add-multisig-config` is used to load the config file exported from neuron, `build-multisig-address` to export a config file

Ref: https://github.com/nervosnetwork/ckb-cli/blob/c97c31cab3f347fb03b4d49cbe7347e124a19685/src/subcommands/tx.rs#L104-L109

**Comment by yanguoyu** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/12881040/177262046-01334319-fc41-46e7-ba7d-5e226a7edc29.png">
This is created by ckb-cli. Ckb-cli is not supported long addresses. Should we wait for it supports long addresses and then be compatible with it? Or we can import multisig config with short addresses.
If I add-multisig-config with long addresses, it will throw an error.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/12881040/177263997-c752ebc7-4fea-4a3b-a542-98780b255645.png">

**Comment by quake** [comment]
@yanguoyu could you try ckb-cli v1.0.0? 

https://github.com/nervosnetwork/ckb-cli/releases/tag/v1.0.0

**Comment by yanguoyu** [comment]
@quake OK, It seems doesn't release an executable file. Should I compile it by myself?

**Comment by yanguoyu** [comment]
It works well, but I transmit long addresses. But the output file includes short addresses.
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12881040/177278353-00da6329-ee02-4794-a3d5-5c2c8bc7f105.png">

**Comment by quake** [comment]
> @quake OK, It seems doesn't release an executable file. Should I compile it by myself?
It looks like this release forgot to package the binary files, we will look into this issue, and you may try to compile with command before it's resolved.
```
cargo build --release
```

**Comment by quake** [comment]
> It works well, I transmit long addresses, but the output file includes short addresses. <img alt="image" width="1019" src="https://user-images.githubusercontent.com/12881040/177278353-00da6329-ee02-4794-a3d5-5c2c8bc7f105.png">

I think it's a bug, we should use the new format in v1.0.0 by default, will resolve it later. But I think neuron should also be compatible with parsing older versions address format.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2442

**Comment by yanguoyu** [comment]
`cli tx send command`'s fields in the tx file should be snake style. Neuron's output tx file writes with `camel` style.
So Neuron will not compatible with ckb-cli on `tx send` command currently.

**Comment by Cedar67** [comment]
Test Results: Verified on PR https://github.com/nervosnetwork/neuron/pull/2442.
Verified CKB cli version: v1.0.0
Test case & results: https://github.com/nervosnetwork/neuron/pull/2442#pullrequestreview-1041233496

**Comment by Cedar67** [comment]
This PR will be merged into the next release version.
