### ISSUE TITLE
Mark `create asset account` and `destroy asset account` in history

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#10]
![image](https://user-images.githubusercontent.com/7271329/164164160-2bb02ea3-0c7c-4fa4-bd4b-d3c29b19e95a.png)

The tx marked `udt sending usdc` is a tx to destroy an asset account and the tx marked `udt sent 0 usdc` is a tx to create an asset account. It's kind of confusing that sending 0 usdc. We could mark them `create/destroy usdc account` explicitly.

**Comment by qiweiii** [comment]
@Keith-CY, hi is there anyone doing this, if not i could try!

Just to confirm:
`udt sending 0 usdc` => Type: `Destroy USDC Account`, Amount: `0 USDC`
`udt sent 0 usdc` => Type: `Create USDC Account`, Amount: `0 USDC`
and this only occur when amount is 0, is this correct?

**Comment by Keith-CY** [comment]
> @Keith-CY, hi is there anyone doing this, if not i could try!
> 
> Just to confirm: `udt sending 0 usdc` => Type: `Destroy USDC Account`, Amount: `0 USDC` `udt sent 0 usdc` => Type: `Create USDC Account`, Amount: `0 USDC` and this only occur when amount is 0, is this correct?

Hi @qiweiii, we really appreciate your passion and the PR is welcome!

The rule is not related to `sending/sent 0` since `sending/sent` is determined by transaction confirmations and `0` is from the balance of the asset account.

The rules underlying are as follows,

1. there are no sUDT(UDT Token) Asset Accounts among inputs of the transaction but one sUDT(UDT Token) Asset Account in outputs => `Create sUDT Asset Account`, better with sUDT's name;
2. there is one sUDT(UDT Token) Asset Account among inputs of the transaction while there're no sUDT(UDT Token) Asset Accounts in outputs => `Destroy sUDT Asset Account`;
3. there are no CKB Asset Accounts(a cell having Anyone-can-pay lock script while its type script is null) among inputs of the transaction but one CKB Asset Account in outputs => `Create CKB Asset Account`;
4. there is one CKB Asset Account among inputs of the transaction while there're no CKB Asset Accounts in outputs => `Destroy CKB Asset Account`

Whether an asset account is in inputs/outputs can be checked in https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/tx/transaction-service.ts#L364-L418, `sudtInput` is the asset account in inputs and `sudtOutput` is the asset account in outputs.

**Comment by qiweiii** [comment]
@Keith-CY Thanks! These rules make more sense now, but I have a few questions after reading the code:

1. is `Create CKB Asset Account` a subcase of `Create sUDT Asset Account`?  (Just need to know whether I should use `sudtInput` to check whether it's a CKB asset account)
2. Does `input.typeHash IS NOT NULL` imply a cell's type script is not null?

**Comment by Keith-CY** [comment]
> is Create CKB Asset Account a subcase of Create sUDT Asset Account? (Just need to know whether I should use sudtInput to check whether it's a CKB asset account)

Not exactly, the difference between `CKB Asset Account` and `sUDT Asset Account` is that `sUDT Asset Account`'s `type script` is a `sudt type script`, mentioned in https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md#sudt-cell, while `CKB Asset Account`'s `type script` is `null`, ref: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0026-anyone-can-pay/0026-anyone-can-pay.md#create-an-anyone-can-pay-cell, so `sudtInput` cannot be regarded as a `CKB Asset Account`

The filter to find `sUDT Asset Account` out is https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/tx/transaction-service.ts#L361-L363, similarly, the filter to find `CKB Asset Account out is
```
const ckbAssetAccountInput = anyoneCanPayInputs.find(
    i => i.transactionHash === tx.hash && !i.typeScript()
)
```

---

> Does input.typeHash IS NOT NULL imply a cell's type script is not null?

As mentioned above, `CKB Asset Account`'s type script is `null`, so anyone-can-pay input could have no type scripts.

The select clause `input.typeHash IS NOT NULL` here is because we only care about `sUDT Asset Account` before. For the feature mentioned in this issue, we should care about `null` `type script` too to find out `CKB Asset Account`.

**Comment by qiweiii** [comment]
@Keith-CY Thanks for explaining these details and pointing out the references.

I have put up a PR [here](https://github.com/nervosnetwork/neuron/pull/2342), please check it out when you are free
