### ISSUE TITLE
Signing messages by a hardware wallet requires a password, which is undesired

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#101]
The password dialog pops up on signing a message by ledger, which is undesired.

The UI code(https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/SignAndVerify/index.tsx#L347-L356) shows a `HardwareSign` dialog for the hardware wallet should be displayed instead of the `PasswordDialog`

The service code(https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/sign-message.ts#L24-L33) shows the `password` argument is not used on signing a message by a hardware wallet.

Now, the password dialog shows on signing messages by a hardware wallet, and an arbitrary password works because it will be discarded finally.

So there should be a bug in the UI

Besides, I noticed the feature `sign a message by a hardware wallet` is in the list of test cases, but the bug was not reported yet, need help from @Cedar67

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2581

**Comment by Cedar67** [comment]
> nervosnetwork/neuron#2581

Neuron crashes when the `Sign` button is clicked on the Neuron page.

Hardware wallet: Nano X
App in Ledger: v0.5.5

Crash log:
[error-report.zip](https://github.com/Magickbase/neuron-public-issues/files/10663613/error-report.zip)

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/64718893/216987750-bd8f4660-f8f3-4f83-9fe3-46e90ad13836.png">

**Comment by yanguoyu** [comment]
> > [nervosnetwork/neuron#2581](https://github.com/nervosnetwork/neuron/pull/2581)
> 
> Neuron crashes when the `Sign` button is clicked on the Neuron page.
> 
> Hardware wallet: Nano X App in Ledger: v0.5.5
> 
> Crash log: [error-report.zip](https://github.com/Magickbase/neuron-public-issues/files/10663613/error-report.zip)
> 
> <img alt="image" width="1126" src="https://user-images.githubusercontent.com/64718893/216987750-bd8f4660-f8f3-4f83-9fe3-46e90ad13836.png">

Can you sign the message success now?

**Comment by Cedar67** [comment]
> > > [nervosnetwork/neuron#2581](https://github.com/nervosnetwork/neuron/pull/2581)
> > 
> > 
> > Neuron crashes when the `Sign` button is clicked on the Neuron page.
> > Hardware wallet: Nano X App in Ledger: v0.5.5
> > Crash log: [error-report.zip](https://github.com/Magickbase/neuron-public-issues/files/10663613/error-report.zip)
> > <img alt="image" width="1126" src="https://user-images.githubusercontent.com/64718893/216987750-bd8f4660-f8f3-4f83-9fe3-46e90ad13836.png">
> 
> Can you sign the message success now?

It is now normal without errors.

**Comment by Cedar67** [comment]
Verified and ready for Pre-release.
