### ISSUE TITLE
Prevent restarting built-in nodes when linking external nodes

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#102]
Current problems：
When the user starts the external node locally and an exception occurs, the connection to the built-in main network node will be restarted without prompt.

Suggestion：
1.If the user starts a local node, do not do a built-in node restart.
2.Add pop-ups prompt when the CKB version of Neuron is inconsistent or the --indexer parameter is not added.
The copy is as follows：
Inconsistent versions
[en]Node synchronization failed, please check the local node version
[cn]节点同步失败，请检查本地节点版本
Without '--indexer' parameter [Add --indexer parameter document link jump]
[en]Please add ['--indexer'](https://github.com/nervosnetwork/ckb-indexer) parameter to start local node
[cn]请添加 ['--indexer'](https://github.com/nervosnetwork/ckb-indexer)参数来启动本地节点 

The style is shown in the figure below：
![index](https://user-images.githubusercontent.com/122437870/217703694-f4e53602-da93-4b08-bb9b-9387fc87e115.png)

**Comment by Danie0918** [comment]
@Keith-CY Please check the solution of the issue

**Comment by Danie0918** [comment]
@yanguoyu @Cedar67

**Comment by yanguoyu** [comment]
I will try to judge whether the ckb node is started by `Neuron` or external by:
If RPC `local_node_info ` return success when starting `Neuron`, I will mark that the node is started externally, and it will not restart auto when the node is stopped.

On the other hand, I will check whether the ckb node version is the same as `Neuron`, maybe the version is not the same, but it's compatible, so we shouldn't show `Node synchronization failed`, and only show suggestion like `version is not same`

**Comment by Danie0918** [comment]
Combined with the comments, the adjustments are as follows：

1.If the user starts a local node, do not do a built-in node restart.
2.Add pop-ups prompt when the CKB version of Neuron is inconsistent or the --indexer parameter is not added.
The copy is as follows：

Inconsistent versions
[en]The node version is inconsistent with Neuron, please use after confirmation
[cn]节点版本与Neuron不一致，请确认后使用

Without ['--indexer'](https://github.com/nervosnetwork/ckb-indexer) parameter [Add --indexer parameter document link jump]
[en]Please add ['--indexer'](https://github.com/nervosnetwork/ckb-indexer) parameter to start local node
[cn]请添加 '--indexer'参数来启动本地节点

Prompt to use the system native UI, the example is as follows ：
![page1](https://user-images.githubusercontent.com/122437870/220591223-1d378b23-f561-4e6e-a947-93732ab1d4b7.png)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2610
