### ISSUE TITLE
Neuron keeps black screen on Fedora 37 with discrete graphics

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#105]
![photo_2023-02-18_14-23-10](https://user-images.githubusercontent.com/7271329/219845396-4c8a69d4-55fe-4bcf-a2e2-424d773df749.jpg)

But it works well before using discrete graphics

-----------------

The user packaged Neuron locally and found it worked.

**Comment by Danie0918** [comment]
Users can use the development version of the wallet to solve problems, and after 2 weeks of observation without further feedback can be closed
