### ISSUE TITLE
Sqlite run failed on M1 with version Ventura 13.1.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#106]
We need to try to run arm64 `Neuron` on M1 with version Ventura 13.1 to try to fix https://github.com/nervosnetwork/neuron/issues/2575.

**Comment by yanguoyu** [comment]
May be happened if the M1's OS version is bigger than 13. Because 13.0.1 (22A400) also has this problem.

**Comment by Keith-CY** [comment]
Neuron@v0.106.0(arm64) works well on my Macbook Pro(apple m1 max) with MacOS 13.2.1 (22D68)

**Comment by seinfeld** [comment]
Same here:

- Alert messages.codes.SQLITE_MISUSE
- sync failed, please check network

Sqlite run failed on M1 with version Ventura 13.2.1 Imported wallet with seed phrase.

**Comment by devchenyan** [comment]
> Same here:
> 
> * Alert messages.codes.SQLITE_MISUSE
> * sync failed, please check network
> 
> Sqlite run failed on M1 with version Ventura 13.2.1 Imported wallet with seed phrase.

**Comment by devchenyan** [comment]
> Same here:
> 
> * Alert messages.codes.SQLITE_MISUSE
> * sync failed, please check network
> 
> Sqlite run failed on M1 with version Ventura 13.2.1 Imported wallet with seed phrase.

@seinfeld  you can download [MacOS x64 version](https://github.com/nervosnetwork/neuron/releases/download/v0.106.0/Neuron-v0.106.0-x64.dmg). It  works for me

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2609
