### ISSUE TITLE
New design for Neuron-Receive

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#109]
[Receive]
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1864%3A13008&t=TLikx7wuSB94hPgE-0

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2621 Ready for review @devchenyan @JeffreyMa597 @Keith-CY

**Comment by littleLip520** [comment]
The first round of testing is completed，After the problem（[165](https://github.com/Magickbase/neuron-public-issues/issues/166)） is fixed, perform regression testing again
