### ISSUE TITLE
Addresses in address book are duplicated

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#11]
Commit: [58a7e3](https://github.com/nervosnetwork/neuron/commit/58a7e37becc5692a48288627dd9c96d4bc49fb54)

![image](https://user-images.githubusercontent.com/7271329/164165376-726ee6e7-8889-493f-940e-71a5f525e1fa.png)

**Comment by yanguoyu** [comment]
我看了下逻辑，应该是数据库里面有重复数据，我又看了下保存地址的逻辑。总共有2处会保存地址：https://github.com/nervosnetwork/neuron/blob/50e112e67b9de1e679a8e8fd5a4a68c12557f17b/packages/neuron-wallet/src/services/addresses.ts#L30 和 https://github.com/nervosnetwork/neuron/blob/50e112e67b9de1e679a8e8fd5a4a68c12557f17b/packages/neuron-wallet/src/services/addresses.ts#L148。第二处在保存前判断了是否存在，而且每次也只是保存一个，所以不可能是这里的问题。
第一处的保存最终追踪到最后都是通过 [checkAndGenerateAddresses](https://github.com/nervosnetwork/neuron/blob/50e112e67b9de1e679a8e8fd5a4a68c12557f17b/packages/neuron-wallet/src/services/wallets.ts#L98) 这个调用，有以下几种情况会 check and save:
1. 创建新钱包
2. [广播交易](https://github.com/nervosnetwork/neuron/blob/50e112e67b9de1e679a8e8fd5a4a68c12557f17b/packages/neuron-wallet/src/services/transaction-sender.ts#L97)
3. [同步交易](https://github.com/nervosnetwork/neuron/blob/50e112e67b9de1e679a8e8fd5a4a68c12557f17b/packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts#L200)

`创建新钱包` 和 `广播交易` 是两种 UI 操作，不可能重复出现。
我本地出现这种情况是在前 30 个地址就已经重复，所以不可能是`广播交易` 和 `同步交易` 保存了重复的地址。
`同步交易` 时的 `walletId` 是从 `HdPublicKeyInfo` 表里面查找出来的，应该也不会出现 `创建新钱包` 和 `同步交易` 出现保存一样的地址。

@Keith-CY 有没有什么其他想法呢？

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/164984269-0de418a7-0959-418a-b283-ea34de292131.png)
我遇到的情况是第一个地址就重复了, 逻辑方面我还没看, 不过要解决这个问题, 是不是在 https://github.com/nervosnetwork/neuron/blob/50e112e67b/packages/neuron-wallet/src/database/chain/entities/hd-public-key-info.ts#L23 加上一个 `unique` 的限制就可以了

**Comment by yanguoyu** [comment]
> ![image](https://user-images.githubusercontent.com/7271329/164984269-0de418a7-0959-418a-b283-ea34de292131.png) 我遇到的情况是第一个地址就重复了, 逻辑方面我还没看, 不过要解决这个问题, 是不是在 https://github.com/nervosnetwork/neuron/blob/50e112e67b/packages/neuron-wallet/src/database/chain/entities/hd-public-key-info.ts#L23 加上一个 `unique` 的限制就可以了

得把 walletId 和 publicKeyInBlake160 组合 `unique ` 才行，因为有可能导入一样的钱包。

**Comment by Keith-CY** [comment]
我昨天重试了几种操作都没能复现这个问题, 因为我遇到的情况是前两个地址, 只有收款操作, 就出现了重复, 要么是创建钱包的时候产生了多余地址, 要么是同步的时候产生了多余地址.

我的印象里第一次收款, 余额总数是正确的, 也就是地址没重复, 所以创建钱包的时候应该也是正确的, 只能是同步的时候多次创建了地址

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2344

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2351

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/173222741-ace1c83e-f051-45f4-9f90-46341642ad74.png)
Unresolved

**Comment by yanguoyu** [comment]
> ![image](https://user-images.githubusercontent.com/7271329/173222741-ace1c83e-f051-45f4-9f90-46341642ad74.png) Unresolved

A new wallet or existing Wallet?

**Comment by Keith-CY** [comment]
> > ![image](https://user-images.githubusercontent.com/7271329/173222741-ace1c83e-f051-45f4-9f90-46341642ad74.png) Unresolved
> 
> A new wallet or existing Wallet?

An existing wallet, created by a pre-released v0.103.0 Neuron these days to verify functions, and found the repeated addresses in the released v0.103.0 Neuron

**Comment by yanguoyu** [comment]
I print some logs when saving addresses, I found they are saved in different processes. So when saving at the main process and saving at child processes, it will happen.
I will resolve it on two side

- [ ] Add a variable for creating sync child process, avoid create more than one sync process
- [ ] Do not check and save address in sync process and send message to main process to `checkAndSave`

<img width="728" alt="image" src="https://user-images.githubusercontent.com/12881040/174921551-b90d61a3-b5bc-449c-b45b-1058b73e3591.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/12881040/174921464-de689d89-e726-45b8-8329-0e6440d7bfc3.png">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2430

**Comment by Cedar67** [comment]
It has been released and validated with the v0.103.2
