### ISSUE TITLE
New design for Neuron-History

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#112]
[History]
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=767-8143&t=3or59J7zyaYq1XGs-0

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2637

**Comment by littleLip520** [comment]
The first round of testing is completed，After the problem（[165](https://github.com/Magickbase/neuron-public-issues/issues/169)） is fixed, perform regression testing again
