### ISSUE TITLE
Use `macos-latest` for packaging

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#123]
`macos-11` was specified by https://github.com/nervosnetwork/neuron/commit/4275a3de3a5ba623de33dfc48052f75a532b1590 because `macos-latest` was randomly assigned to `macos-11` or `macos-12`, and these two environments have different dependencies, it would be difficult to fit these two.

Now `macos-latest` is assigned to `macos-12` and we can update the workflow for it
![image](https://user-images.githubusercontent.com/7271329/229769713-927197fb-a440-4781-985a-483956fe99b8.png)

**Comment by WhiteMinds** [comment]
I simply replaced "macos-11" with "macos-latest" in https://github.com/nervosnetwork/neuron/commit/5b7f4cdd02294883d110f65a0426b6073674777a, and everything seems to be working fine based on the current results: https://github.com/nervosnetwork/neuron/actions/runs/4899407459.

I'm not sure what happened before, but I think maybe the issue has been resolved by this pull request: https://github.com/nervosnetwork/neuron/pull/2627.
@Keith-CY, could you provide more information to supplement?

**Comment by Keith-CY** [comment]
> I simply replaced "macos-11" with "macos-latest" in [nervosnetwork/neuron@5b7f4cd](https://github.com/nervosnetwork/neuron/commit/5b7f4cdd02294883d110f65a0426b6073674777a), and everything seems to be working fine based on the current results: [nervosnetwork/neuron/actions/runs/4899407459](https://github.com/nervosnetwork/neuron/actions/runs/4899407459).
> 
> I'm not sure what happened before, but I think maybe the issue has been resolved by this pull request: [nervosnetwork/neuron#2627](https://github.com/nervosnetwork/neuron/pull/2627). @Keith-CY, could you provide more information to supplement?

It's fixed by upgrading `electron-builder` from `22.14.5`(https://github.com/nervosnetwork/neuron/blob/4275a3de3a5ba623de33dfc48052f75a532b1590/packages/neuron-wallet/package.json#L86) to `23.6.0`(https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/package.json#L87)

---

It was a hotfix(https://github.com/nervosnetwork/neuron/commit/4275a3de3a5ba623de33dfc48052f75a532b1590) during release(https://github.com/nervosnetwork/neuron/pull/2627) by degrading `macos-latest` to `macos-11` because `python2`, which is required by `electron-builder@22.14.5`, was removed from `macos-12`. And at that time, the reliance to `python2` was fixed in `electron-builder@23.0.2`(https://github.com/electron-userland/electron-builder/issues/6606#issuecomment-1062436795).

Then we have 3 options:
1. upgrade `electron-builder` to 23.0.2
2. introduce `python2` into github runner manually
3. set `macos-11` explicitly

Because it was during a release, option 1 was not acceptable.
Because `python2` will not be relied on in future versions, option 2 was not worth it.

So option 3 was taken as a hotfix.

**Comment by WhiteMinds** [comment]
It seems that i just need to revert the previous changes.

PR: https://github.com/nervosnetwork/neuron/pull/2664
