### ISSUE TITLE
Fix adapt light client

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#125]
- [x] Adapt multisig.
- [x] Hide the data set when the node is light, and clear all synchronized data
- [x] Some cell dep is not in block 0, we need to fetch these transactions.
- [x] Add export light client log.
- [x] Can clear light client sync data
- [x] Some APIs are not in light client, so we need to adapt these APIs. `get_header_by_number`, `get_live_cell`, `get_blockchain_info`

**Comment by Dawn-githup** [comment]
- [ ] After installing Microsoft Visual C++, the detection prompts that it is not installed.
 - [ ] The input of trading information does not show up on the neuron.

##### optimization
 - [ ] Creating a new wallet, allowing it to sync from the latest block.

**Comment by Keith-CY** [comment]
Send a timelock transaction to local wallet and the record will be added in `customized assets`, but `method not found` error will be thrown on clicking the `claim` button

https://user-images.githubusercontent.com/7271329/231666718-398c02db-68e7-41e5-94a2-15906b272963.mov

**Comment by Dawn-githup** [comment]
### overview
 - [ ] Transactions can be found on light nodes, but cannot be retrieved from the full node that the light node is connected to.
 - [ ] The input for transaction details is displaying abnormally

### send
 - [ ] Currently, setting the setLock function can cause the output lock script to be collected by users, but time locks sent by non-inherited wallets cannot be collected by the wallet.

### Receive 
- [ ] Using seven different accounts, the amount of change can be multiplied by 12 on each account.

### nervos dao
- [ ] The amount of CKB not displayed in the locked field when deposting does not match the amount of CKB in the lock script
- [ ] The current APC is 0.
- [ ] "Deposit" progress bar doesn't budge.
- [ ] "Withdraw" button prompts error message saying "Method Not Found."
- [ ] CKB interest has always been 0
- [ ] The next compensation cycle will start in approximately NaN days

### cutomized Assets
- [ ] turn into a new sudt asset account, need fetchTx
- [ ] Transfer to a sUDT asset account did not attempt successfully
- [ ] Send mnft, prompt method not found
- [ ] claim failed

### asset account
- [ ] Report of transfer failure: there isn't accountwallet a...
- [ ] Send report Insufficient
- [ ] Create an asset Account and report an error, fetchTransaction is required

### tools
- [ ] Clean data Delete data from light nodes

### perference
##### data
- [ ] When the network type is the light node test network, the current path is the main network, and it is expected to be a light node
##### network
- [ ] Synchronize multi-signature information, synchronize wallet information, and the main network node will be closed. Currently, there is no synchronization of multi-signature addresses
- [ ] If port 9000 is occupied, the error message is not obvious, and the user cannot locate the cause of the error
- [ ] Switch the light node (test network) to main, and currently the light node will not be shut down

### close wallet
- [ ] At present, the main node will be shut down, while the light node has not been shut down

**Comment by Keith-CY** [comment]
Clearing cache(without rebuild index) during synchronization wipes **history before this action** out.

![image](https://user-images.githubusercontent.com/7271329/231715364-577af4b0-3bf3-47f0-bef0-00a37bab1ed1.png)

---

Screenshot from another PC 
![image](https://user-images.githubusercontent.com/7271329/231715641-afd52fb4-a006-44b6-bf67-164aa8abbf7f.png)

---

Transactions before 2023-03-31 are lost

**Comment by Keith-CY** [comment]
There were two SUDT assets in `customized assets`, they were sent from godwoken bridge(https://testnet.bridge.godwoken.io/#/v1/)

![image](https://user-images.githubusercontent.com/7271329/231717754-2ee3b30f-f34a-4a15-9685-391e3cde268e.png)

When I tried to convert one into a SUDT account, `unknown outpoint` error appeared. It usually happens when an input has been consumed. So I cleared cache and tried again, still got this error

**Comment by Keith-CY** [comment]
> There were two SUDT assets in `customized assets`, they were sent from godwoken bridge([testnet.bridge.godwoken.io/#/v1](https://testnet.bridge.godwoken.io/#/v1/))
> 
> ![image](https://user-images.githubusercontent.com/7271329/231717754-2ee3b30f-f34a-4a15-9685-391e3cde268e.png)
> 
> When I tried to convert one into a SUDT account, `unknown outpoint` error appeared. It usually happens when an input has been consumed. So I cleared cache and tried again, still got this error

---

This error is reproduced on two computers, should be related to synchronization logic
![image](https://user-images.githubusercontent.com/7271329/231725387-a097d8a9-6d77-4c2d-b54e-3dc35b50c69e.png)

**Comment by yanguoyu** [comment]
> When I tried to convert one into a SUDT account, `unknown outpoint` error appeared. It usually happens when an input has been consumed. So I cleared cache and tried again, still got this error

This is because of this: `Some cell dep is not in block 0, we need to fetch these transactions.`
I have not fixed it yet.

**Comment by Keith-CY** [comment]
> 

Ah I see, I was misled by my experience about `unknown outpoint`

**Comment by yanguoyu** [comment]
> Currently, setting the setLock function can cause the output lock script to be collected by users, but time locks sent by non-inherited wallets cannot be collected by the wallet.

Because the timelock script is not predictable, the light client will not support show timelock cells. Shall we disable timelock when sending `ckb` for the light client? @Keith-CY 

> If port 9000 is occupied, the error message is not obvious, and the user cannot locate the cause of the error

The Port 9000 is occupied include two conditions:
1. The user has started `ckb-light-client` locally by themself.
2. The user uses Port 9000 for other servers.
How should we prompt better for users?

**Comment by Keith-CY** [comment]
> > Currently, setting the setLock function can cause the output lock script to be collected by users, but time locks sent by non-inherited wallets cannot be collected by the wallet.
> 
> Because the timelock script is not predictable, the light client will not support show timelock cells. Shall we disable timelock when sending `ckb` for the light client? @Keith-CY
> 
> > If port 9000 is occupied, the error message is not obvious, and the user cannot locate the cause of the error
> 
> The Port 9000 is occupied include two conditions:
> 
> 1. The user has started `ckb-light-client` locally by themself.
> 2. The user uses Port 9000 for other servers.
>    How should we prompt better for users?

@Danie0918 @Sven-TBD please list the all inaccessible assets in light client mode and add prompts no sending/receiving them.

For instance, when the user tries to send someone with timelock, the prompt `please inform receiver to check the assets in full node mode` should appear beneath the address field, as we did before
![image](https://user-images.githubusercontent.com/7271329/233248338-1b4ccc74-dcb4-4fb7-a60c-fc6f85a8c4b1.png)

Meanwhile, a prompt should be displayed in the `customized assets` panel when neuron is in light client mode, to let users know some assets are only visible in full node mode(with a button/link to network config)

**Comment by yanguoyu** [comment]
> Meanwhile, a prompt should be displayed in the `customized assets` panel when neuron is in light client mode, to let users know some assets are only visible in full node mode(with a button/link to network config)

As I know, currently when `Neuron` use `ckb-light-client`, it will not support collecting `cheque`, `locktime` cells, and sending SUDT to other users' `ACP` address.

**Comment by Danie0918** [comment]
> > > Currently, setting the setLock function can cause the output lock script to be collected by users, but time locks sent by non-inherited wallets cannot be collected by the wallet.
> > 
> > 
> > Because the timelock script is not predictable, the light client will not support show timelock cells. Shall we disable timelock when sending `ckb` for the light client? @Keith-CY
> > > If port 9000 is occupied, the error message is not obvious, and the user cannot locate the cause of the error
> > 
> > 
> > The Port 9000 is occupied include two conditions:
> > 
> > 1. The user has started `ckb-light-client` locally by themself.
> > 2. The user uses Port 9000 for other servers.
> >    How should we prompt better for users?
> 
> @Danie0918 @Sven-TBD please list the all inaccessible assets in light client mode and add prompts on sending/receiving them.
> 
> For instance, when the user tries to send someone with timelock, the prompt `please inform receiver to check the assets in full node mode` should appear beneath the address field, as we did before ![image](https://user-images.githubusercontent.com/7271329/233248338-1b4ccc74-dcb4-4fb7-a60c-fc6f85a8c4b1.png)
> 
> Meanwhile, a prompt should be displayed in the `customized assets` panel when neuron is in light client mode, to let users know some assets are only visible in full node mode(with a button/link to network config)

I understand that there are 2 requirements here, when the user is in light node mode
1. Users need to be prompted when receiving/sending assets that cannot be accessed by light nodes
2. Prompt users in custom assets that some assets are only visible in full node mode and provide a button to jump to network settings

Here are a few questions
1. How to find the assets that light nodes cannot access?
2. Does history need to add similar hints?
3. Do asset accounts need to add similar prompts?

**Comment by Keith-CY** [comment]
> > > > Currently, setting the setLock function can cause the output lock script to be collected by users, but time locks sent by non-inherited wallets cannot be collected by the wallet.
> > > 
> > > 
> > > Because the timelock script is not predictable, the light client will not support show timelock cells. Shall we disable timelock when sending `ckb` for the light client? @Keith-CY
> > > > If port 9000 is occupied, the error message is not obvious, and the user cannot locate the cause of the error
> > > 
> > > 
> > > The Port 9000 is occupied include two conditions:
> > > 
> > > 1. The user has started `ckb-light-client` locally by themself.
> > > 2. The user uses Port 9000 for other servers.
> > >    How should we prompt better for users?
> > 
> > 
> > @Danie0918 @Sven-TBD please list the all inaccessible assets in light client mode and add prompts on sending/receiving them.
> > For instance, when the user tries to send someone with timelock, the prompt `please inform receiver to check the assets in full node mode` should appear beneath the address field, as we did before ![image](https://user-images.githubusercontent.com/7271329/233248338-1b4ccc74-dcb4-4fb7-a60c-fc6f85a8c4b1.png)
> > Meanwhile, a prompt should be displayed in the `customized assets` panel when neuron is in light client mode, to let users know some assets are only visible in full node mode(with a button/link to network config)
> 
> I understand that there are 2 requirements here, when the user is in light node mode
> 
> 1. Users need to be prompted when receiving/sending assets that cannot be accessed by light nodes
> 2. Prompt users in custom assets that some assets are only visible in full node mode and provide a button to jump to network settings
> 
> Here are a few questions
> 
> 1. How to find the assets that light nodes cannot access?
> 2. Does history need to add similar hints?
> 3. Do asset accounts need to add similar prompts?

The prompts for senders should be displayed in both full-node and light-client modes because whether the assets are visible depends on the receiver, not the sender. So senders should be informed how the receiver can verify it.

The prompts for receivers only show in light-client mode because full-node reveals all assets.

**Comment by Keith-CY** [comment]
> How to find the assets that light nodes cannot access?

- timelock assets in customized assets
- cheque assets in customized assets
- unknown sudt assets in customized asset

> Does history need to add similar hints?

It would be considerate to show these hints on the history page

> Do asset accounts need to add similar prompts?

When sending `sudt` to others, the `sudt` only appears when the receiver has a corresponding asset account.

The underlying mechanism is that only a known `script` will be synced in the light client mode. If receiver doesn't have the corresponding asset account, it doesn't know the sudt script to sync

**Comment by yanguoyu** [comment]
> When sending sudt to others, the sudt only appears when the receiver has a corresponding asset account.

Neuron with `ckb-light-client` will not support sending `sudt` to other users' ACP address,  because we cannot get the cell that lock script is other user's ACP lock script. The user can only send to with lock 162 `ckb` or extra 142 `ckb`.

**Comment by Keith-CY** [comment]
> > When sending sudt to others, the sudt only appears when the receiver has a corresponding asset account.
> 
> Neuron with `ckb-light-client` will not support sending `sudt` to other users' ACP address, because we cannot get the cell that lock script is other user's ACP lock script. The user can only send to other users with lock 162 `ckb` or extra 142 `ckb`.

To be more precise, it takes a long time to fetch receiver's `asset account` cell which is not user friendly, so the function is disabled

**Comment by Keith-CY** [comment]
A detail can be considered but left for optimization in the future

If a sudt/secp256k1 is received, it will be listed in `customized assets` and can be 
1. turned into an asset account
2. transfer to an asset account
![image](https://user-images.githubusercontent.com/7271329/235062118-7cb5265c-ae46-43fc-b9a7-5dcc08a487d1.png)

Option 2 allows the user to send to the other's asset account(by inputting an address), which is disabled in `asset account tab` because it takes time to fetch the receiver's cell.

![image](https://user-images.githubusercontent.com/7271329/235062361-c9348d7a-f3ab-42c9-a135-0973e3c68316.png)

So the interaction can be changed to disable inputting that the user can only pick up an internal asset account to send.

**Comment by yanguoyu** [comment]
> So the interaction can be changed to disable inputting that the user can only pick up an internal asset account to send.

https://github.com/nervosnetwork/neuron/pull/2653

**Comment by yanguoyu** [comment]
> Create a new wallet, optimize the spacing of mnemonic word arrangement 

The new-ui will use a new design, so it will not optimize currently.

> Error message indicating port allocation is in use is not prominent, making it difficult for users to identify the cause of the error

It's duplicated with https://github.com/Magickbase/neuron-public-issues/issues/135

**Comment by yanguoyu** [comment]
> After clearing data, switching accounts, data synchronization needs to start from 0 ？

Currently, we can clean the current wallet block number when you clear data, then when you switch to another wallet, it will start from the last. But for the current wallet, it will start from 0.  @Dawn-githup  What do you think about this?

**Comment by Dawn-githup** [comment]
> > After clearing data, switching accounts, data synchronization needs to start from 0 ？
> 
> Currently, we can clean the current wallet block number when you clear data, then when you switch to another wallet, it will start from the last. But for the current wallet, it will start from 0. @Dawn-githup What do you think about this?

The scenario where users simultaneously use two wallets is not frequent, and if it can be optimized, it would be more user-friendly.

**Comment by Dawn-githup** [comment]
# Third-stage testing and verification of neurons

### Overview
- [ ] The input for transaction details only displays 10 accounts
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/976ca2d1-054d-4407-9851-2f0f1cfbc916)

### Send---set LockTime
- [ ] Light node mode reminder does not display data
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/824d9c08-b78e-48fd-abb4-c148d3418d27)

### Receive---address book
- [ ] Using 7 accounts can generate 12 additional accounts.
- Generate 12 accounts, while the height of newly generated accounts lags behind the latest synchronization height
`
idx:0,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqg29eguzu82zwt7vpgufdy8flzn8zcc84gd2cnfl codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:1,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqgjvu6anzc02uvpukw76gy82cr4q9gmnkgy6a60l codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:2,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqg5whj7pnrcrlkg022l0d9tf9zy7rphaacckzdpz codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:3,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqgkszkyznz7fdywa6ke30j5fdemgu7g2dgaluahr codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:4,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqg67qldecchzx6395uftttf2xwz3g3dfgq0jqgzz codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:5,sync blockNo:9234000 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqftecfefxzktryqnfw80p0dquf52s890cqflrsfm codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:6,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqfwl5nte3hnsrx24nfnf40a825ft59naqghp4hh7 codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:7,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqfjesgentwcw8qpeytk48dqjch7qxgfltgzweg3q codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:8,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqfm438cfjq9qvwmh7ha6a8tlvnswdwqtlcwt7lhr codeHash:0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356
idx:9,sync blockNo:9329146 ckb address:ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnw
`

### perference---data
- [ ] Windows: After clearing data, the light node starts normally, but the synchronization information remains stuck at 0
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/8cbc5e32-3bfe-4309-b5bf-0bc6bbc10336)
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/b2ce515a-6ea6-46b9-93c6-3cf94ff5c5fa)

- [ ] Mac: Synchronized, but balance not refreshed
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/993040af-69c0-4d89-b748-009e2d9cc765)
logs:
[no-sync-after-remove-data.zip](https://github.com/Magickbase/neuron-public-issues/files/11505916/no-sync-after-remove-data.zip)

### tools---clean data
- [ ] Light nodes are out of sync after clearing data
- [ ] After clearing all data, the imported account did not resynchronize from 0

### nervos dao---deposit
- [ ] Confirm the progress bar problem
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/4128fdd0-42f4-4497-bcb6-eb0fb9461e17)

### Environmental installation---windows
- [ ] Two dependent C++installations are required to use
- [ ] Add environment variable path;% SystemRoot%\system32;% SystemRoot%;% SystemRoot%\System32\Wbem;
- [ ] May require documentation for user convenience

**Comment by yanguoyu** [comment]
> The input for transaction details only displays 10 accounts

It's a feature.

> Two dependent C++installations are required to use
 Add environment variable path;% SystemRoot%\system32;% SystemRoot%;% SystemRoot%\System32\Wbem;

duplicate with https://github.com/Magickbase/neuron-public-issues/issues/134

**Comment by yanguoyu** [comment]
> Light nodes are out of sync after clearing data
 After clearing all data, the imported account did not resynchronize from 0
Windows: After clearing data, the light node starts normally, but the synchronization information remains stuck at 0

Fixed by https://github.com/nervosnetwork/neuron/pull/2675
