### ISSUE TITLE
Migration along with ckb@v0.108.1 should be warned

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#127]
There is a migration along with ckb@v0.108.x, and it happens silently if a migration was executed before(as migration along with ckb@v0.106.x)

However, the migration may fail for various reasons, and users have to re-sync from scratch, which is annoying. So an alert is desired before the migration to inform users about the potential exception, as mentioned at https://github.com/nervosnetwork/neuron/pull/2517#issuecomment-1303005526

Besides, the detection of migration failure can be more precise. In my case, the migration failed in 4 minutes

```
[2023-04-08 16:13:21.578] [info]  CKB migrate:	starting...
[2023-04-08 16:13:21.579] [info]  CKB:	process closed
[2023-04-08 16:16:51.570] [info]  CKB migrate:	process process exited with code 0
```

But the prompt of `migrating` disappeared 40 mins later

Ref: https://github.com/nervosnetwork/ckb/releases/tag/v0.108.1

**Comment by Danie0918** [comment]
PRD: https://hx7bx9.axshare.com/#g=1&p=99

**Comment by yanguoyu** [comment]
There exist three conditions when the user uses the latest version:
1. They download the latest `Neuron` and use it first. It will not need to migrate.
2. They download the latest `Neuron` but set the data path as older data's path, it will prompt the user to migrate.
3. They upgrade the `Neuron` from `0.106` to above `0.108`, it will prompt the user to migrate.
4. They upgrade the `Neuron` from below `0.105` to above `0.108`, it will prompt the user to migrate once.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2651
