### ISSUE TITLE
Update RPC method of get fee rate statistics

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#128]
The name was fixed in CKB by https://github.com/nervosnetwork/ckb/pull/3924 and will be delivered in v0.109.0. The API call in neuron could be updated accordingly.

SDK: https://github.com/ckb-js/ckb-sdk-js/pull/608/files#diff-7e0bff06c2d2a7416106877046dc6a1e4bc0168aeb280ec58b8a583af6f4a2aaR10
Neuron

**Comment by JeffreyMa597** [comment]
PR: https://github.com/ckb-js/ckb-sdk-js/pull/613
