### ISSUE TITLE
 detail button should add loading state after click

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#129]
step 1：open transaction page
step2: click the detail button  three times in a row
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/26523791/232663529-fe5d02c1-ae2d-4b72-b8fe-00da1f83d056.png">
step3: three detail window pop up
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/26523791/232663665-06562993-53c0-4d5f-910f-9dd51af1bf92.png">

**Comment by Danie0918** [comment]
PRD: https://hx7bx9.axshare.com/#g=1&p=99

**Comment by WhiteMinds** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2656
