### ISSUE TITLE
Specify path of chain's data in Setting panel

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#13]
Issue: https://github.com/nervosnetwork/neuron/issues/2249

**Comment by Keith-CY** [comment]
![Image](https://user-images.githubusercontent.com/7271329/174492192-6035ce27-45d6-4bd7-8d62-c7c6815311fc.png)

1. Add the fourth tab `Data/数据`
2. `CKB Node Data/节点数据`(chain data in the screenshot) | current path to the data | `Set/设置` Button
3. `CKB Indexer Data/Indexer 数据) | current path to the data | `Set/设置` Button
4. Move `clear cache` from `general` to `data`
5. Use the native dialog to set the path of data
6. `Clear cache by rebuilding ckb-indexer` will remove data in `CKB Indexer Data` and `Clear all synchronized data` will remove data in `CKB Node Data`.

**Comment by Keith-CY** [comment]
Please review this feature and post any questions here. @yanguoyu @Cedar67 @sonycs

**Comment by yanguoyu** [comment]
After reset the path of the data, we should move existing data to the set path or recreate data?
If move data, it may need a long time when copy ckb-data, we should show the copy process.

**Comment by Keith-CY** [comment]
> After reset the path of the data, we should move existing data to the set path or recreate data? If move data, it may need a long time when copy ckb-data, we should show the copy process.

Can we detect the progress of copying files? Or we can just prompt users to do the copy manually, it's determined by users to start from the synchronized data or start from the scratch.

**Comment by yanguoyu** [comment]
Show accurate progress it's maybe complex. let the user copy manually sounds good.

**Comment by Keith-CY** [comment]
> Show accurate progress it's maybe complex. let the user copy manually sounds good.

Well, we can add a dialog after the path is set

`Please move CKB Node(or Indexer, based on the operation) Data {{prev_path}} to {{current_path}}, or Neuron has to synchronize from scratch/请将 CKB Node(Indexer, 取决于实际修改的数据)数据 {{prev_path}} 移动至 {{current_path}}, 否则 Neuron 需要重新同步`

with two buttons
`Data have been moved/数据转移完成`, `Synchronize from scratch/重新同步`

**Comment by FrederLu** [comment]
1、The logic of the resync button should be better understood by the user: after clicking the button, the data will be downloaded again and the data will be saved in the new path. However, users should know that the resynchronized data is actually duplicated with the previous data, and the synchronization will take up a certain amount of time and disk space.

2、The data transfer completion button is also directly clickable. Does it automatically help users migrate data after clicking? If it is recommended that the user manually migrate the data, the logic of this button feels a bit strange.

**Comment by Keith-CY** [comment]
> 1、The logic of the resync button should be better understood by the user: after clicking the button, the data will be downloaded again and the data will be saved in the new path. However, users should know that the resynchronized data is actually duplicated with the previous data, and the synchronization will take up a certain amount of time and disk space.

> 2、The data transfer completion button is also directly clickable. Does it automatically help users migrate data after clicking? If it is recommended that the user manually migrate the data, the logic of this button feels a bit strange.

Agree, we should info users about the difference between these two actions

<code>
Please move CKB Node(or Indexer, based on the operation) Data from {{prev_path}} to {{current_path}} and then click on "Data have been moved" to start from the previously synchronized block; Or click on "Synchronize from scratch" to start with synchronizing from scratch. /请将 CKB Node(Indexer, 取决于实际修改的数据)数据从 {{prev_path}} 移动至 {{current_path}}然后点击 "数据转移完成" 开始从已知区块同步; 否则点击 "重新同步" 开始重新同步

Attention: Synchronize from scratch won't remove previously downloaded CKB Node(or Indexer) Data.
注意: 重新同步不会删除当前已同步的 CKB Node(Indexer) 数据.
</code>

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2433

**Comment by Keith-CY** [comment]
Add a detail, support opening directory by clicking an open icon next to the file path @Keith-CY 

Ref: https://www.electronjs.org/zh/docs/latest/api/shell#shellopenpathpath

**Comment by yanguoyu** [comment]
> Add a detail, support opening directory by clicking an open icon next to the file path @Keith-CY
> 
> Will start the work after [nervosnetwork/neuron#2433](https://github.com/nervosnetwork/neuron/pull/2433) is merged
> 
> Ref: https://www.electronjs.org/zh/docs/latest/api/shell#shellopenpathpath

Added by https://github.com/nervosnetwork/neuron/pull/2433/commits/3b6e9db935d02e054e28790ff0c317c4e48b719d

**Comment by Cedar67** [comment]
> > Add a detail, support opening directory by clicking an open icon next to the file path @Keith-CY
> > Will start the work after [nervosnetwork/neuron#2433](https://github.com/nervosnetwork/neuron/pull/2433) is merged
> > Ref: https://www.electronjs.org/zh/docs/latest/api/shell#shellopenpathpath
> 
> Added by [nervosnetwork/neuron@3b6e9db](https://github.com/nervosnetwork/neuron/commit/3b6e9db935d02e054e28790ff0c317c4e48b719d)

The Open Icon is automatically very small when the path character is long (more than three lines).  @yanguoyu 
Suggestion: Keep icon fixed size.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/64718893/177102781-b629dbb3-1121-42ef-b112-c6f77d5d4b9b.png">

**Comment by yanguoyu** [comment]
> > > Add a detail, support opening directory by clicking an open icon next to the file path @Keith-CY
> > > Will start the work after [nervosnetwork/neuron#2433](https://github.com/nervosnetwork/neuron/pull/2433) is merged
> > > Ref: https://www.electronjs.org/zh/docs/latest/api/shell#shellopenpathpath
> > 
> > 
> > Added by [nervosnetwork/neuron@3b6e9db](https://github.com/nervosnetwork/neuron/commit/3b6e9db935d02e054e28790ff0c317c4e48b719d)
> 
> The Open Icon is automatically very small when the path character is long (more than three lines). @yanguoyu Suggestion: Keep icon fixed size.
> 
> <img alt="image" width="894" src="https://user-images.githubusercontent.com/64718893/177102781-b629dbb3-1121-42ef-b112-c6f77d5d4b9b.png">

Fixed by https://github.com/nervosnetwork/neuron/pull/2433/commits/17df920dd9dca81b95587fb4d2581df9a6d951e7

**Comment by Cedar67** [comment]
> > > > Add a detail, support opening directory by clicking an open icon next to the file path @Keith-CY
> > > > Will start the work after [nervosnetwork/neuron#2433](https://github.com/nervosnetwork/neuron/pull/2433) is merged
> > > > Ref: https://www.electronjs.org/zh/docs/latest/api/shell#shellopenpathpath
> > > 
> > > 
> > > Added by [nervosnetwork/neuron@3b6e9db](https://github.com/nervosnetwork/neuron/commit/3b6e9db935d02e054e28790ff0c317c4e48b719d)
> > 
> > 
> > The Open Icon is automatically very small when the path character is long (more than three lines). @yanguoyu Suggestion: Keep icon fixed size.
> > <img alt="image" width="894" src="https://user-images.githubusercontent.com/64718893/177102781-b629dbb3-1121-42ef-b112-c6f77d5d4b9b.png">
> 
> Fixed by [nervosnetwork/neuron@17df920](https://github.com/nervosnetwork/neuron/commit/17df920dd9dca81b95587fb4d2581df9a6d951e7)

Verified that it has been fixed.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/64718893/177108426-7f360942-d3eb-4afd-adb8-345a9e6d4705.png">

**Comment by Cedar67** [comment]
Test Results: Verified.
Test version: https://github.com/nervosnetwork/neuron/pull/2433
Test case & results: https://docs.google.com/spreadsheets/d/1J2ENPt3lkikBncv-NN_cSaquhsX_0xDSR1GiVhBBNho/edit#gid=1293167941
