### ISSUE TITLE
get_fee_rate_statics may return null when the node just started running

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#133]
From the [API](https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_fee_rate_statics), we know get_fee_rate_statics may return null.

And actually, it also may return null.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/12881040/233590849-46caa6e3-a3b2-4450-affa-7fd6d9ccbaf1.png">

We should change the return type of [get_fee_rate_statics](https://github.com/ckb-js/ckb-sdk-js/blob/338d4c4e1d68cb2f17cd9d970eb4e562fd299ef1/packages/ckb-sdk-rpc/src/Base/index.ts#L354)

**Comment by JeffreyMa597** [comment]
PR: https://github.com/ckb-js/ckb-sdk-js/pull/612

**Comment by yanguoyu** [comment]
And we also need to add judgment https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/utils/hooks/useGetCountDownAndFeeRateStats.ts#L24, it may crash when the res is null.

**Comment by yanguoyu** [comment]
> And we also need to add judgment https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/utils/hooks/useGetCountDownAndFeeRateStats.ts#L24, it may crash when the res is null.

Fixed in https://github.com/nervosnetwork/neuron/pull/2663/files#diff-f37e7e236f3c01e71dfd2658abbf25ba7b6e97c256b011f9a1d25599a15ba613
