### ISSUE TITLE
Detect new upgrade on launch

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#139]
The detection of a new version to upgrade can be run on launch silently and prompt users to upgrade if possible.

This eager strategy acquaints users with new standards and functions timely.

**Comment by Keith-CY** [comment]
Please consider this feature as a priority.

**Comment by Danie0918** [comment]
Considering the frequency of software updates and the effect of alerts, it would be a better solution for us to use pop-up alerts here.Note that for the current pop-up content it is recommended to use server-side configuration instead of getting the text in the github release so that users can get the core content of the release faster.

Requirement Contents：The style of the pop-up window can follow the design of the new UI
1.Automatically detects the version when opening Neuron Wallet and prompts the user to upgrade with a pop-up when a new version is available.（The detection limit needs to be set so as not to hog the performance of the user's device in the absence of network or service anomalies.）
2.When the user cancels the upgrade or closes the popup, it is logged locally and no longer pops up unless a new version is pushed.
3.The content of the upgrade instructions can be edited and pushed to the user on the server side, and the text of the corresponding language version is displayed according to the user's current language version.

![new_page_1](https://github.com/Magickbase/neuron-public-issues/assets/122437870/603f1289-29a0-4131-aa3a-3f9a0774dbb7)

Any other suggestions or questions about the above requirements?
@Keith-CY @yanguoyu

**Comment by yanguoyu** [comment]
@Magickbase/developers

**Comment by Keith-CY** [comment]
> Considering the frequency of software updates and the effect of alerts, it would be a better solution for us to use pop-up alerts here.Note that for the current pop-up content it is recommended to use server-side configuration instead of getting the text in the github release so that users can get the core content of the release faster.
> 
> Requirement Contents：The style of the pop-up window can follow the design of the new UI 1.Automatically detects the version when opening Neuron Wallet and prompts the user to upgrade with a pop-up when a new version is available.（The detection limit needs to be set so as not to hog the performance of the user's device in the absence of network or service anomalies.） 2.When the user cancels the upgrade or closes the popup, it is logged locally and no longer pops up unless a new version is pushed. 3.The content of the upgrade instructions can be edited and pushed to the user on the server side, and the text of the corresponding language version is displayed according to the user's current language version.
> 
> ![new_page_1](https://user-images.githubusercontent.com/122437870/245714329-603f1289-29a0-4131-aa3a-3f9a0774dbb7.png)
> 
> Any other suggestions or questions about the above requirements? @Keith-CY @yanguoyu

The excerpt can be distilled from the release note in a preconcerted format, so the server to push message can be avoided.

**Comment by yanguoyu** [comment]
Should we download it auto when finding a new version? Then if the user wants to update, they will not need to wait to download the version.

**Comment by Danie0918** [comment]
> Should we download it auto when finding a new version? Then if the user wants to update, they will not need to wait to download the version.

This is a sensitive operation, if the automatic download of updates usually requires the user to manually turn on.

**Comment by yanguoyu** [comment]
> > Should we download it auto when finding a new version? Then if the user wants to update, they will not need to wait to download the version.
> 
> This is a sensitive operation, if the automatic download of updates usually requires the user to manually turn on.

Only auto download, but the update action is still controlled by users.

**Comment by Danie0918** [comment]
> > Considering the frequency of software updates and the effect of alerts, it would be a better solution for us to use pop-up alerts here.Note that for the current pop-up content it is recommended to use server-side configuration instead of getting the text in the github release so that users can get the core content of the release faster.
> > Requirement Contents：The style of the pop-up window can follow the design of the new UI 1.Automatically detects the version when opening Neuron Wallet and prompts the user to upgrade with a pop-up when a new version is available.（The detection limit needs to be set so as not to hog the performance of the user's device in the absence of network or service anomalies.） 2.When the user cancels the upgrade or closes the popup, it is logged locally and no longer pops up unless a new version is pushed. 3.The content of the upgrade instructions can be edited and pushed to the user on the server side, and the text of the corresponding language version is displayed according to the user's current language version.
> > ![new_page_1](https://user-images.githubusercontent.com/122437870/245714329-603f1289-29a0-4131-aa3a-3f9a0774dbb7.png)
> > Any other suggestions or questions about the above requirements? @Keith-CY @yanguoyu
> 
> The excerpt can be distilled from the release note in a preconcerted format, so the server to push message can be avoided.

This is also possible, so that we need to pay attention to the github release version of the text to be written in the general format, the pop-up window only need to get the summary part of the content.

**Comment by Danie0918** [comment]
> Should we download it auto when finding a new version? Then if the user wants to update, they will not need to wait to download the version.

It is better not to download automatically without the user's permission, this may be against the user's will and at the same time may make the user feel that the software is not secure.

**Comment by Keith-CY** [comment]
I've checked some applications and found the strategy of update is configurable

![Pasted Graphic 19](https://github.com/Magickbase/neuron-public-issues/assets/7271329/0f74324b-5f52-4392-a8d0-98776cce57b3)

It would be flexible.

Besides, a dialog informing users to upgrade is a bit brute, IMO.
I would like a silent `update` badge on the screen, like the `update to latest` in the window of docker, or `update telegram` at the left bottom corner of Telegram. Just my personal opinion.

**Comment by Keith-CY** [comment]
Some other update check configuration
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/aafc4740-d260-4beb-8a26-2f9e27659d96)
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/3b5348c6-11c5-479d-90e1-a06883f4cc1f)
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/ddd9bbbb-3d29-496c-b78a-c7bb840df1b6)

**Comment by Danie0918** [comment]
After thinking about it, I think adding upgrade pop-ups at software startup would indeed be a bit too forceful, and the software doesn't have a strong need for users to upgrade, but more of a need for users to spontaneously upgrade to get a better experience. I think it is not necessary to add automatic download and installation settings, because users still need to manually click on the upgrade and installation and need to be prompted by the pop-up window. Therefore, the following are the requirements after the update:

1. Add a new version prompt to the settings in the left menu to detect when the software is launched.
2. When the new version is prompted, users click Settings for the first time and the page slides to the General column.
3. Add a new version version number prompt in the version bar, and a new version upgrade pop-up window appears when you click Check Update.
4. The new version prompt of the settings in the left menu bar is not prompted after clicking on it, regardless of whether it is upgraded or not, and the software is saved locally until a different new version prompt is available.
5. The new version prompt in the general section of the settings page, when not upgraded to a new version, need to always show.



![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/fc78b8b1-2692-4683-9d81-967a43479234)

**Comment by Keith-CY** [comment]
> After thinking about it, I think adding upgrade pop-ups at software startup would indeed be a bit too forceful, and the software doesn't have a strong need for users to upgrade, but more of a need for users to spontaneously upgrade to get a better experience. I think it is not necessary to add automatic download and installation settings, because users still need to manually click on the upgrade and installation and need to be prompted by the pop-up window. Therefore, the following are the requirements after the update:
> 
> 1. Add a new version prompt to the settings in the left menu to detect when the software is launched.
> 2. When the new version is prompted, users click Settings for the first time and the page slides to the General column.
> 3. Add a new version version number prompt in the version bar, and a new version upgrade pop-up window appears when you click Check Update.
> 4. The new version prompt of the settings in the left menu bar is not prompted after clicking on it, regardless of whether it is upgraded or not, and the software is saved locally until a different new version prompt is available.
> 5. The new version prompt in the general section of the settings page, when not upgraded to a new version, need to always show.
> 
> ![Image](https://user-images.githubusercontent.com/122437870/248716453-fc78b8b1-2692-4683-9d81-967a43479234.png)

LGTM, except 
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/71e3a7e6-ae99-4397-8c93-12fb12fb8086)
Will `new version v0.112.0` and `check for update` show simultaneously?

**Comment by Danie0918** [comment]
> > After thinking about it, I think adding upgrade pop-ups at software startup would indeed be a bit too forceful, and the software doesn't have a strong need for users to upgrade, but more of a need for users to spontaneously upgrade to get a better experience. I think it is not necessary to add automatic download and installation settings, because users still need to manually click on the upgrade and installation and need to be prompted by the pop-up window. Therefore, the following are the requirements after the update:
> > 
> > 1. Add a new version prompt to the settings in the left menu to detect when the software is launched.
> > 2. When the new version is prompted, users click Settings for the first time and the page slides to the General column.
> > 3. Add a new version version number prompt in the version bar, and a new version upgrade pop-up window appears when you click Check Update.
> > 4. The new version prompt of the settings in the left menu bar is not prompted after clicking on it, regardless of whether it is upgraded or not, and the software is saved locally until a different new version prompt is available.
> > 5. The new version prompt in the general section of the settings page, when not upgraded to a new version, need to always show.
> > 
> > ![Image](https://user-images.githubusercontent.com/122437870/248716453-fc78b8b1-2692-4683-9d81-967a43479234.png)
> 
> LGTM, except ![image](https://user-images.githubusercontent.com/7271329/248717894-71e3a7e6-ae99-4397-8c93-12fb12fb8086.png) Will `new version v0.112.0` and `check for update` show simultaneously?

It would be better to change here to upgrade now.So here you need to add another requirement, when there is a new version, check the upgrade strain upgrade now.

![setting](https://github.com/Magickbase/neuron-public-issues/assets/122437870/6e29e273-5db3-4852-a92f-70ae5e807581)

**Comment by Keith-CY** [comment]
> > LGTM, except Will `new version v0.112.0` and `check for update` show simultaneously?
> 
> It would be better to change here to upgrade now.So here you need to add another requirement, when there is a new version, check the upgrade strain upgrade now.
> 
> ![setting](https://user-images.githubusercontent.com/122437870/249012546-6e29e273-5db3-4852-a92f-70ae5e807581.png)

👍

**Comment by Keith-CY** [comment]
Let's make the decision and go further

**Comment by Danie0918** [comment]
@Kirl70 Please add the style of version update prompt based on the new version of Neuron UI.

https://github.com/Magickbase/neuron-public-issues/issues/139#issuecomment-1608587084

**Comment by Kirl70** [comment]
I suggest simplifying the text for the updated version to maintain a consistent style.
<img width="542" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/df65d811-9ddb-40ed-8c71-2f6371b8de29">
<img width="539" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/787ec8e1-5614-4b9f-aef1-763d6a1772fa">

The specific update information will be displayed in a pop-up dialog:
<img width="568" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/0fb10cc2-a9c6-4b51-9674-8e73ea86d0f4">


If we add the version text, it will create a large blank space in the language selection box:
<img width="661" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/031fb3be-1cdb-4133-b3e2-8e361eb21b9f">

**Comment by Danie0918** [comment]
> I suggest simplifying the text for the updated version to maintain a consistent style. <img alt="image" width="542" src="https://user-images.githubusercontent.com/106060898/250471842-df65d811-9ddb-40ed-8c71-2f6371b8de29.png"> <img alt="image" width="539" src="https://user-images.githubusercontent.com/106060898/250471874-787ec8e1-5614-4b9f-aef1-763d6a1772fa.png">

Yes, it is possible.Note here that the version number shows the new version number to be updated.In addition, tips need to be added to the left-hand side menu bar again to help users discover new versions.

**Comment by Kirl70** [comment]
The adjustment has been made to display the version number that can be updated when there is an update.
A small red dot will appear on the left sidebar if there are updates. Additionally, I previously made notes on the display rules. Please review them to see if any adjustments or additions are needed.
<img width="936" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/18fc14cf-a888-4d80-b840-f0e7cb8ed21d">

**Comment by JeffreyMa597** [comment]
> The adjustment has been made to display the version number that can be updated when there is an update.
> A small red dot will appear on the left sidebar if there are updates. Additionally, I previously made notes on the display rules. Please review them to see if any adjustments or additions are needed.
> https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1165%3A13586&mode=design&t=Y9gRzk3jlYfnm2sv-1

@Kirl70  When we collapse the sidebar, how should it be displayed?

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2769

**Comment by JeffreyMa597** [comment]
@Kirl70 This font is Apple-specific. Please help to handle it.
<img width="1135" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/22511289/413be645-15fb-4bc9-8aa2-e8eb009f63ba">

**Comment by Kirl70** [comment]
> @Kirl70 This font is Apple-specific. Please help to handle it. <img alt="image" width="1135" src="https://user-images.githubusercontent.com/22511289/253160543-413be645-15fb-4bc9-8aa2-e8eb009f63ba.png">

Please use the default system font for regular text.
Reference:
https://github.com/Magickbase/visual-style-guide/issues/2#issuecomment-1233977778

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2783

**Comment by yanguoyu** [comment]
@FrederLu
https://github.com/nervosnetwork/neuron/pull/2783 is the PR for testing no update.
https://github.com/nervosnetwork/neuron/pull/2787 is the PR for testing that has an update.
