### ISSUE TITLE
workflow of exporting tx could be refined

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#14]
https://user-images.githubusercontent.com/7271329/166436902-0b6ac137-518d-47a4-9a43-0887d2c10c99.mov

1. sign and export tx could be disabled when the password is empty
2. canceling `sign and export` leads to an incorrect error `Unable to save JSON File`
3. `export` should not dismiss the dialog directly until the user confirms to save the tx.

commit id: db2c6496

**Comment by yanguoyu** [comment]
> export should not dismiss the dialog directly until the user confirms to save the tx.

I saw `create sudt account` also dismiss the dialog before opening `passwordRequest` dialog.

**Comment by Cedar67** [comment]
[Verified in Windows OS.](https://github.com/nervosnetwork/neuron/pull/2406#pullrequestreview-1000115449)
