### ISSUE TITLE
Claim is missing the label for the first input box

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#147]
@Dawn-githup Please add detail for this problem in this issue.

**Comment by Dawn-githup** [comment]
cutomized Assets——>sudt——>claim
![image](https://github.com/Magickbase/neuron-public-issues/assets/77844990/731e5b43-7842-447e-9bc3-267a96962a85)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2661
