### ISSUE TITLE
Signed status is not correct

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#15]
https://user-images.githubusercontent.com/7271329/166437831-9d6b9a93-1d6c-442e-a5f0-b30b067c60be.mov

The address is 2-of-3.

When I import a 1-signed tx to a 2-of-3 address, the signed status is `signed`, which is incorrect

commit id: db2c6496

**Comment by yanguoyu** [comment]
I fixed it at https://github.com/nervosnetwork/neuron/pull/2347/files#diff-22750f04134df128ad9594d9b1ef2d8d179597b2d5de3eae2ad9f2ff07d13f22.
