### ISSUE TITLE
Optimize the interaction of calendar

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#151]
As mentioned at https://github.com/nervosnetwork/neuron/pull/2592#issuecomment-1455297243

The selected `year`, `month` will not be effective if it's saved before `day` is selected, which is weird and prone to select `tomorrow`.

Say the pre-picked time is `2023/05/17`, and `2024/07` are selected, however, `2023/05/17` will be saved if `save` is clicked without selecting `day`

https://github.com/Magickbase/neuron-public-issues/assets/7271329/4c9884d3-86f1-4340-a9d3-44f73e9b7425

**Comment by WhiteMinds** [comment]
I feel that not automatically changing the value when switching between years and months is a common behavior and quite reasonable. It seems more like an interaction design rather than a logical bug.
If we want to optimize this, perhaps we should have the "Save" button initially disabled until the user manually makes a change.
In this way, providing a default value for tomorrow might not be necessary, and we can omit the default value but offer a shortcut button like "Tomorrow" to assist in quickly selecting a value.

@Danie0918 @Keith-CY What do you think about this?

**Comment by WhiteMinds** [comment]
https://github.com/Magickbase/neuron-public-issues/assets/9160743/94c2622a-9629-4ee7-9494-97fb512eaf79

The overall effect would be like this. I think if the goal is to prevent saving unintended values, it might be better to provide a time preview near the save button. That way, users can have a better understanding of the value they are about to save.
The follow was just an example, and the actual style needs to be determined by the designer:

<img width="634" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/9160743/3ccda986-c3ea-4da9-a500-3a1546a69735">

**Comment by yanguoyu** [comment]
I think it's better to disable `save` when the user does not select any date. Otherwise, the user may confuse with the new date.

**Comment by Keith-CY** [comment]
Any idea from @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
Calendar selection is indeed a common function that needs to be protected against accidental touches, especially when it affects transactions.
There are 2 situations here:
1. When no date is selected, the "Save" button is not displayed, and the "Cancel" button is changed to "Close"
2. After selecting the date, the user needs to be prompted to select the date. Here, the style 2 mentioned in the XX comment is used. It is recommended to change "save" to "lock to"
![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/4aae912c-3b79-40e4-89b1-bc9b688a19cf)

**Comment by WhiteMinds** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2674 

Please have @Danie0918 review the effect presentation in the PR to ensure it meets the expectations.
