### ISSUE TITLE
Allow packaging without certificates

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#154]
This suggestion is from https://github.com/nervosnetwork/neuron/pull/2674#issuecomment-1558731539

PRs come from other repo will not package apps because the certificates for package is only accessible inside nervosnetwork/neuron.

But PRs from other contributors are welcome, and allowing **packaging for test** facilitates verification.

So we may update the workflow of https://github.com/nervosnetwork/neuron/blob/develop/.github/workflows/package_for_test.yml to make it available without certificates.

Following are the ideas proposed in the original comment

> 1. use fail-fast: false
> 2. Check if it is the main repository before executing Package for MacOS, and automatically skip if it is not
> 3. Check for the presence of necessary secrets before executing Package for MacOS, and output a warning message if they are missing
> 4. Automatically switch to non-signing mode and output a warning when the required signing secrets are missing

I think option 4 is more reasonable because `package for macos` is necessary during verification, so it can not be skipped.

Any idea from contributors? @WhiteMinds @yanguoyu @JeffreyMa597 @devchenyan @homura @zhangyouxin @IronLu233

**Comment by homura** [comment]
Vote up for option 4, I also suggest that we should only sign when releasing, not every `push`, to avoid the case of a canary version but with a signature

**Comment by Keith-CY** [comment]
> Vote up for option 4, I also suggest that we should only sign when releasing, not every `push`, to avoid the case of a canary version but with a signature

I think `signature` on apps(excludes releases) from our team is still necessary because these packages may be distributed as an insider one for feedback, and `signature` guarantees the distributor.

Checksums in the release note can be used to distinguish `release`. **How to check checksum** will be delivered on the download page(https://lb84z6.axshare.com/#g=1&p=%E4%B8%8B%E8%BD%BD%E9%92%B1%E5%8C%85)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2693

**Comment by yanguoyu** [comment]
Open an unsigned App on Mac os:
1. After opening an unsigned App, the system will notice that you can not open the App because the system cannot verify the developer. Then you can open `System Preferences ▸ Security & Privacy -> General -> Still Open`

<img width="250" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/97d79998-4dc3-4ea0-9622-1ca69aa2ec26">

There seems to be no problem with Windows.

If you encounter any issues that cannot be opened with the unsigned package, please append a comment.

**Comment by FrederLu** [comment]
https://github.com/nervosnetwork/neuron/actions/runs/5251984962
Download `Neuron-Mac-arm64.zip`, after unzipping, it will prompt that the package is damaged.
<img width="256" alt="image" src="https://github.com/nervosnetwork/neuron/assets/25676576/8173b1ae-4817-40e0-8a32-54c6b3a4822f">

**Comment by yanguoyu** [comment]
> https://github.com/nervosnetwork/neuron/actions/runs/5251984962 Download `Neuron-Mac-arm64.zip`, after unzipping, it will prompt that the package is damaged. <img alt="image" width="256" src="https://user-images.githubusercontent.com/25676576/245380300-8173b1ae-4817-40e0-8a32-54c6b3a4822f.png">

Try these steps:
1. Open a terminal
2. sudo xattr -d com.apple.quarantine /Applications/Neuron.app
3. restart Neuron

**Comment by Keith-CY** [comment]
CI blames about the permission at https://github.com/nervosnetwork/neuron/actions/runs/5347657156/jobs/9696452185?pr=2740#step:10:173
