### ISSUE TITLE
Wrong wallet mode displayed.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#157]
Open the wallet on the Mac for the first time, without manually setting the wallet mode, the day/night mode of the wallet will follow the device system.
It is found that the device is in day mode by default, but the wallet is displayed in night mode, which does not follow the system display.
<img width="812" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2a7d0b06-63d8-442b-ba37-c72626114774">

**Comment by yanguoyu** [comment]
I think maybe you have changed the theme before. You can try to verify by opening `/Users/username/Library/Application Support/Neuron/settings.json`, if you have changed it before, you can find the `themeSource` field,

**Comment by FrederLu** [comment]
```json
{
    "locale": "zh",
    "ckbDataPath": "/Users/Faye/Library/Application Support/Neuron/chains/mainnet",
    "testnetLightDataPath": "/Users/Faye/Library/Application Support/Neuron/chains/light/testnet",
    "themeSource": "dark"
}
```
According to the directory, it is found that there is indeed ` "themeSource": "dark"` information, and it will follow the system display mode after removal.

This problem no longer exists, close the issue.
