### ISSUE TITLE
New UI menu bar issues

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#158]
- [ ] Style problem after mouse hover。The icon in the screenshot is not set as a clickable style when the mouse hovers over it (small hand)
<img width="172" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b85f9873-3b29-45d2-bbf3-1e7f7a1aa7ae">
<img width="217" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/22315c5b-d749-47a0-80a6-abd57e95098e">

https://github.com/Magickbase/neuron-public-issues/assets/25676576/e1e02cd8-3a17-4580-a655-7c03a8db28e0

---

- [ ] When the mouse hovers over the experiment icon, the display is blank.
<img width="254" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8963b9a8-4999-4599-8bab-713684170c3c">

---

- [ ] The length of the wallet name is too long, especially when switching between Chinese and English.

<img width="470" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e1aa8e24-9105-410f-a3e3-8f285de3f176">
<img width="275" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/895f43a4-1342-449a-a96f-6f8b3af210b5">
<img width="389" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/4f64b2b3-9bde-4a2c-8246-446a97b9ed7a">

**Comment by JeffreyMa597** [comment]
@Keith-CY @yanguoyu For the interaction of the mouse turning into a cursor when hovering over a button, we may have such scenes in many places of our wallet app now. Whether we need to turn into a cursor or not, I think we may need to unify it in the new UI. I see that in some places of our code, it turns into a cursor, while in other places it does not.

**Comment by Keith-CY** [comment]
> @Keith-CY @yanguoyu For the interaction of the mouse turning into a cursor when hovering over a button, we may have such scenes in many places of our wallet app now. Whether we need to turn into a cursor or not, I think we may need to unify it in the new UI. I see that in some places of our code, it turns into a cursor, while in other places it does not.

It could be decided by @Danie0918 @Sven-TBD @Kirl70 

---

In the past versions, the `hand` icon was disabled to make Neuron more `native`(in the past, `hand` was only used on web pages), but the `hand` icon is more clear for interaction and used in many applications, too. Maybe it's the new trend.

I'm not sure about it, so it could be confirmed by PM and designer

**Comment by Kirl70** [comment]
I think using a `hand` icon can help users quickly understand that the area where the mouse hovers is a functional option. This aspect is clearly demonstrated in the new design:
<img width="783" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/848bc81a-0a13-45f4-9e3a-31be3c140fc9">

If the `hand` icon is disabled, on certain pages, it may be necessary to add text or icons to indicate to users that the current area is clickable. However, from a design perspective, this may make the page less concise:
<img width="743" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/96d3abfa-1d4f-4230-80e6-248b70f0f14d">

Furthermore, I have compared it with two other desktop applications, both of which use a `hand` icon:
<img width="617" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/4d5760ab-6cc9-4a6e-96ae-dfa87c8b3d67">

<img width="1353" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/41c97776-a2a4-45be-92a2-bd312f45c82d">

**Comment by yanguoyu** [comment]
According to [Kirl70](https://github.com/Kirl70)'s suggestion, we can remove `cursor: default !important;` that matches `*`

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2709

**Comment by FrederLu** [comment]
Verified.
