### ISSUE TITLE
Problems with the new UI overview page

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#159]
- [ ] 1、The lack of a mask layer effect is an overall problem, and other pages also need to have it.
<img width="832" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/51f000bd-42c0-4450-85db-32248ec14684">
<img width="1019" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6a927fda-0859-46ca-8f4e-9b936091bd5d">

---
- [ ] 2、The default style of the day/night switch button does not need to display the hover state.
<img width="194" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fd1e7180-2552-486b-a5cb-fd9732a72a29">
<img width="245" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b348a919-c5ca-4ea2-ae38-b55486ddb7b9">

---
- [ ] 3、The style of the mouse hover day/night button (or synced) needs to be changed to a small hand, which is now displayed as a mouse pointer.
<img width="441" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/438b8694-0b63-4af2-982d-a1cdb91ce6a4">

---
- [ ] 4、When the synchronization is abnormal (red font), the small red dot is missing before the copy.
<img width="457" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5b1e1311-058c-4d17-8c91-a536965a5b87">
<img width="401" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2484d828-4293-4f16-b4ff-01a3aaed3739">
<img width="326" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/19476cae-c304-4aac-8b10-b5690c21c2f8">

---
- [ ] 5、The center of the `i` icon needs to be consistent with the text, and the back `X` is smaller than the UI draft.
<img width="842" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/269617ee-443b-45b5-baa1-ca0859ee12c6">
<img width="687" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/340f9319-155d-476f-8dd6-019c659945e1">

---
- [ ] 6、When creating or importing a wallet, there is a lack of screenshot prompts.
<img width="289" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/63ffdf7c-376e-49f9-9745-2695eed31c30">

---
- [ ] 7、`Looking for preset trusted blocks` is displayed abnormally.
<img width="244" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e10ed691-d2ba-47e3-a996-7d6dbb0067c3">
<img width="420" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/897e4dfb-7639-4e0d-bd9f-9261b6b01ac0">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by FrederLu** [comment]
Problems 1 and 3 still exist.

---
Problem 6 has been improved, but the prompt time is too short, and there is no need to prompt when switching wallets at the same time, and the information is only prompted at the initial entry.

![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/e9b711f7-c42c-4201-8e98-1fbd9dcc4771)

https://github.com/Magickbase/neuron-public-issues/assets/25676576/68bbc652-01da-4f33-a314-885b3778ce34

**Comment by devchenyan** [comment]
Problems 1 : The mask layer and the whole background are the same background color. so it's not a problem
![image](https://github.com/Magickbase/neuron-public-issues/assets/11756869/3dcff47b-dacb-4ba6-b8ca-9a5e8979135c)

**Comment by FrederLu** [comment]
> Problems 1 : The mask layer and the whole background are the same background color. so it's not a problem @FrederLu ![image](https://user-images.githubusercontent.com/11756869/248558853-3dcff47b-dacb-4ba6-b8ca-9a5e8979135c.png)


@devchenyan  @Kirl70 
Now the function is not implemented.
<img width="790" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d56dd12f-f985-4ceb-910b-959f56fadcf4">

**Comment by Kirl70** [comment]
> > Problems 1 : The mask layer and the whole background are the same background color. so it's not a problem @FrederLu ![image](https://user-images.githubusercontent.com/11756869/248558853-3dcff47b-dacb-4ba6-b8ca-9a5e8979135c.png)
> 
> @devchenyan @Kirl70 Now the function is not implemented. <img alt="image" width="790" src="https://user-images.githubusercontent.com/25676576/248603780-d56dd12f-f985-4ceb-910b-959f56fadcf4.png">

The purpose of the mask layer is to ensure that the information on top of the mask layer remains visible at the forefront, regardless of page scrolling. The header mask layer should be present on all operational pages. Additionally, on this particular page, there should also be an mask layer for the bottom buttons.

<img width="743" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/16118c36-8432-4ec1-a925-5040d8d88a43">

<img width="1023" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/07200a44-5052-42e7-bb14-f2435e503cdd">

**Comment by devchenyan** [comment]
Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c .

**Comment by FrederLu** [comment]
> Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit [nervosnetwork/neuron@3edf8bb](https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c) .

After the top is sucked, each page remains fixed when sliding. Now it is found that the top of the "Transaction History" and "Settings" pages will move when sliding.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/2c8ef931-0483-4dfc-a2ad-1627af0ce28f

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by devchenyan** [comment]
Packaging for test is done in [5461287659](https://github.com/nervosnetwork/neuron/actions/runs/5461287659)

**Comment by FrederLu** [comment]
Verified.
