### ISSUE TITLE
Style issue in balance module

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#162]
- [ ] 1、Now when the mouse hovers over the amount to evoke copying, the mouse can only be moved from the leftmost end of the amount. It is expected that you can hover from any position of the amount.
<img width="818" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/53c635bd-ea91-4db2-b309-6b47d909895f">

---
- [ ] 2、When the mouse moves to 👀, the hover style is missing, and the click is invalid.
<img width="640" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e12471c4-a0a9-40e7-aef6-3df8c28682cb">

---
- [ ] 3、When the amount is small, the copied and copied information and icons are displayed incompletely.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/777192bd-a3ac-47b6-8e9a-f12e95b6cb94)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/2048c321-ef02-4ad6-9dc9-b164b99fee28)

---
- [ ] 4、The black shadows do not completely block out the digits.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/b33eeb70-540b-4b89-b97d-98623f84b1fe)

**Comment by JeffreyMa597** [comment]
@Kirl70 Can you help optimize this part of the design? Also, this copied mask is a universal feature that may need to consider other places where copying is used and apply the same style. If you don't want the same style applied in other places where copying is needed, please let me know. Thx.

**Comment by Kirl70** [comment]
> @Kirl70 Can you help optimize this part of the design? Also, this copied mask is a universal feature that may need to consider other places where copying is used and apply the same style. If you don't want the same style applied in other places where copying is needed, please let me know. Thx.

Set a minimum width so that if it's less than 72px, only the icon is displayed without the text. As shown in the image:
<img width="627" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/cdad0b7b-9e20-48cb-b862-4b0139be9784">


You can use the same style in places with similar functionality.

**Comment by JeffreyMa597** [comment]
> You can use the same style in places with similar functionality.

Thx. How about the `border-radius` which was mentioned in the issue? Should we changed it？

**Comment by Kirl70** [comment]
> > You can use the same style in places with similar functionality.
> 
> Thx. How about the `border-radius` which was mentioned in the issue? Should we changed it？

In the design, the overlay here is positioned 4px to the left of the number, rather than aligned with the number.
![image](https://github.com/Magickbase/neuron-public-issues/assets/106060898/033493b4-223c-45ae-a6ec-2c13bc25119d)

**Comment by FrederLu** [comment]
The balance copy function needs to be available when it is displayed, and the copy function should not be available when the balance is hidden, but it is currently available.
<img width="446" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b37d5a29-79ea-4182-afab-e733a28c7454">
<img width="234" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/04f6c09d-7203-4e84-97d7-7d42cb29112a">

**Comment by FrederLu** [comment]
Verified.
