### ISSUE TITLE
UI issue for Send page

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#165]
1. lack of placeholder
2. After entering a custom price, the prompt copy is different from the UI
<img width="1058" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/1bc7bbc2-470d-4c73-9a79-081c5254f6f9">
UI design:
1.
<img width="331" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/221001b0-615e-4a13-91c8-fa1f5fd57e80">
2.
<img width="354" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/32c41ee7-7c59-4e9a-9684-bb3cf6e8f3dd">

**Comment by littleLip520** [comment]
3.The bottom button is not fixed after the window is minimized
acture
<img width="988" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/4718fca3-0172-4ea0-a3ff-eeca06ba139a">

UI：
<img width="689" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/4e39cd35-fd24-4ca9-84ed-f59b0ee7a025">

**Comment by littleLip520** [comment]
4.remark should have Maximum Input Limit
<img width="1110" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/71b19775-632a-4488-a87d-8e78f604fe11">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by littleLip520** [comment]
verified.  problem 2 should stay consistent with the status quo. problem 4 don't have Maximum Input Limit for now
