### ISSUE TITLE
Issues for receive page

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#166]
1.The bottom cpoy button is not fixed after the window is minimized
2.Clicking the Remarks Modify button is not working, you need to press Enter to modify the Remarks
<img width="998" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/63c48602-6870-48ea-b25b-adbb117c18ad">
UI design:
1.
<img width="850" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/9bd252d3-8832-4e86-b21e-eee380df1ce0">

**Comment by littleLip520** [comment]
3.The copy text and display position should be consistent with the UI design
acture:
<img width="740" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/3c396183-8bba-48bd-8ac2-fcd133000ee9">
UI:
<img width="270" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/81b4dd5c-3e2b-4e21-a598-de52ad5ee94f">

**Comment by JeffreyMa597** [comment]
1、The height of `Tips` will be contained by the total height, and it is showed default. Both of the buttons will be seen when we close this `Tips`.

<img width="1202" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/22511289/54c4b4c1-8ff0-4e23-bbe0-d0bd5ae7ba0e">
<img width="1198" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/22511289/01ec4d4a-4ba6-4f7c-814f-54c385c2ffb5">

2、@Danie0918 Please help to confirm the actions of the `Remark` button:
    currently:
    A、to Edit:  we can start editing remarks by moving the mouse over the input box or clicking the `Eidt` button.
    B、to Save: press Enter.
    
   So, do I need to change the existing interaction?

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2723

**Comment by Danie0918** [comment]
> 2、@Danie0918 Please help to confirm the actions of the `Remark` button: currently: A、to Edit: we can start editing remarks by moving the mouse over the input box or clicking the `Eidt` button. B、to Save: press Enter.
> 
> So, do I need to change the existing interaction?

Here I suggest keeping the interaction of the old version, where you can edit by clicking the edit button and enter the content to take effect without a carriage return.
![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/27a453b5-d7ea-4107-a974-f669b85a5371)

**Comment by littleLip520** [comment]
> 1、The height of `Tips` will be contained by the total height, and it is showed default. Both of the buttons will be seen when we close this `Tips`.
> 
> <img alt="image" width="1202" src="https://user-images.githubusercontent.com/22511289/246322180-54c4b4c1-8ff0-4e23-bbe0-d0bd5ae7ba0e.png"> 

question 1 is about minimizing, not about 'Tips'. you can see my first screenshot, I have already close the tips, the button still din't show up in minimize window

**Comment by JeffreyMa597** [comment]
> Here I suggest keeping the interaction of the old version, where you can edit by clicking the edit button and enter the content to take effect without a carriage return.

Okay, 1、We will periodically save the content entered by the user automatically or by pressing enter.
2、Clicking the edit button to edit.

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2723

**Comment by littleLip520** [comment]
verified 1-4.
5. after click revert address button, the copy message will display very shortly when move the mouse to address

https://github.com/Magickbase/neuron-public-issues/assets/26523791/43eb3652-acf4-46c9-9ef0-e98e17b626bd

**Comment by Danie0918** [comment]
> verified 1-4. 5. after click revert address button, the copy message will display very shortly when move the mouse to address
> 
>  revert.address.mp4

@Kirl70 Maybe we can adjust the interaction scheme here to avoid misuse. For example, instead of providing floating layer copy, how about adding a copy button icon next to the conversion address?

**Comment by Kirl70** [comment]
The floating copy tooltip will also appear on other pages, as it follows a consistent interaction style. Here, we can separate the copy address feature and place it independently.
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=468%3A5835&mode=design&t=ZMyJtNJgYtdfgBmk-1
<img width="411" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/e033a58d-e7c9-42d3-82e5-226131f82254">

**Comment by Danie0918** [comment]
> The floating copy tooltip will also appear on other pages, as it follows a consistent interaction style. Here, we can separate the copy address feature and place it independently. https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=468%3A5835&mode=design&t=ZMyJtNJgYtdfgBmk-1 <img alt="image" width="411" src="https://user-images.githubusercontent.com/106060898/250440341-e033a58d-e7c9-42d3-82e5-226131f82254.png">

It's cool.However, the text suggests using the previous text:

[currently short address]Turn into full version format.
[currently long address]Turn into deprecated format.

**Comment by Kirl70** [comment]
> > The floating copy tooltip will also appear on other pages, as it follows a consistent interaction style. Here, we can separate the copy address feature and place it independently. https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=468%3A5835&mode=design&t=ZMyJtNJgYtdfgBmk-1 <img alt="image" width="411" src="https://user-images.githubusercontent.com/106060898/250440341-e033a58d-e7c9-42d3-82e5-226131f82254.png">
> 
> It's cool.However, the text suggests using the previous text:
> 
> [currently short address]Turn into full version format. [currently long address]Turn into deprecated format.


Already adjusted:

<img width="352" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/e42cc0b8-6a57-440e-b0cc-f3b79ccb7b5e">
<img width="336" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/ceec0061-6fd6-480b-ae18-d3d690896cf9">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2757
