### ISSUE TITLE
Recent activities style questions

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#168]
- [ ] 1. The title spacing between the left and right ends of the recent income and expenditure needs to be adjusted.
<img width="859" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1e5b6901-c5a0-4dac-8ed3-61ddca446528">
<img width="1118" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9947bbc0-ed5f-4d81-b233-c25489333cf0">

---
- [ ] 2.When the node is deactivated and the network is disconnected at the same time, the page is missing and the network is abnormal.
<img width="802" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f31d77ed-74b8-4038-be37-e3f15bb5f262">

---
https://github.com/Magickbase/neuron-public-issues/assets/25676576/a9e3ccc1-50f0-4b8a-9426-bd75f348d8b3

- [ ] 3.The spacing between the headings when there is no data and the headings when there is data in the recent balance should be consistent.
- [ ] 4.Showing/hiding amounts should not affect heading spacing.
- [ ] 5.When the mouse hover is displayed/hidden, the mouse style needs to be replaced with a hand.

---
<img width="284" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/186b2e4c-7174-49e8-be22-4a462c2308e7">

https://github.com/Magickbase/neuron-public-issues/assets/25676576/e8271dfd-60fb-4178-9524-852bf32a7bee
- [ ] 6.The title's right spacing has changed and should be relatively fixed.
- [ ] 7.When updating data, the front icon needs to show the effect of rotation.
- [ ] 8.The rotated icon should not affect the left alignment of the `Status` text.

---
- [ ] 9.When UDT data appears in the recent income and expenditure, data alignment exception occurs, and CKB is normal.
<img width="954" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/265476b5-d13e-4b37-9394-44c1f41324b6">

**Comment by FrederLu** [comment]
@Danie0918 @yanguoyu @Keith-CY @Kirl70 
Points to be confirmed:
In the recent income and expenditure, if the type is `create sudt asset account`, whether `+` needs to be displayed in front of the amount.
<img width="954" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/265476b5-d13e-4b37-9394-44c1f41324b6">

The screenshot below is the previous screenshot：
<img width="786" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/bf36f5fd-85b4-4144-acd2-440e4042593b">
<img width="1185" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d1a433e2-1b57-4f6d-a0ae-770c52feb70c">

**Comment by Danie0918** [comment]
Display+ would be better.

**Comment by FrederLu** [comment]
> PR: [nervosnetwork/neuron#2735](https://github.com/nervosnetwork/neuron/pull/2735)
> 
> Item 2 has been confirmed by the product manager, we needn't consider this situation. Cause the data come from our local database.

When verifying the relevant pr, it is found that problem 5 still exists.

**Comment by FrederLu** [comment]
Verified.
