### ISSUE TITLE
issues for history page

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#169]
1. confirming status icon didn't show up after doing transaction
2. Remark display in wrong place
<img width="1236" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/923740c6-1de4-4102-b481-81b61f2927a7">
UI design:
<img width="1192" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/db4a04f7-ae26-4f7c-9a1b-d5bac59cbcde">

**Comment by littleLip520** [comment]
3. copy amount function is not working
actual:
<img width="965" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/8eea86b8-f5d6-41c0-b4c2-b79964aff32d">
UI:
<img width="949" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/88a888be-1161-4973-bea9-0a310003706a">

**Comment by littleLip520** [comment]
4.copy action in history detail page ，text should only display "copy"
<img width="934" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/58f23715-becb-436c-894b-ef0fba36d761">
UI：
<img width="939" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/63798992-f326-41e5-ac4d-2b45151d7c5a">

**Comment by littleLip520** [comment]
5. address information page, success message didn't show up after clicking copy button
<img width="643" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/7068d3db-8f70-40b1-ac50-5234edcccd13">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2721

**Comment by littleLip520** [comment]
verified  bug 1-5.
6.  The display style of the amount is wrong（UDT type transactions）
<img width="610" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/58a7d533-0571-417b-b1ee-7c06574df0f1">

7. When the amount is small, the copy pattern display is abnormal, it is best to keep the minimum copy pattern
<img width="947" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/d4206d5e-6bd4-4ba4-927c-0e2f9c8b0468">

**Comment by JeffreyMa597** [comment]
> verified bug 1-5. 6. The display style of the amount is wrong（UDT type transactions） <img alt="image" width="610" src="https://user-images.githubusercontent.com/26523791/246986437-58a7d533-0571-417b-b1ee-7c06574df0f1.png">
> 
> 7. When the amount is small, the copy pattern display is abnormal, it is best to keep the minimum copy pattern
> 
> <img alt="image" width="947" src="https://user-images.githubusercontent.com/26523791/246988455-d4206d5e-6bd4-4ba4-927c-0e2f9c8b0468.png">

@littleLip520  These issues have been fixed in other PRs, please check. Thx.
6、https://github.com/Magickbase/neuron-public-issues/issues/168 
7、https://github.com/Magickbase/neuron-public-issues/issues/162

**Comment by littleLip520** [comment]
already have another bug track problem 6,7. so close this bug.
