### ISSUE TITLE
Hover/Click transaction style exception.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#170]
- [ ] 1、When the mouse hovers over a single transaction, it needs to have a UI draft style, and at the same time set the mouse to a clickable hand style.
<img width="708" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/db5d22e1-da8e-429c-861b-08b57e4e5b52">

---
- [ ] 2、The style is abnormal after the mouse clicks a single transaction.
<img width="976" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f22c22e8-51f1-4025-84b9-435e394fa4c8">

---
- [ ] 3、There is now an issue with transaction detail styling (day/night) after double click. The following operation is changed to click after the mouse hovers (refer to the first point above).

https://github.com/Magickbase/neuron-public-issues/assets/25676576/a31691ab-f35c-4ec2-bd5c-c517b332f84f

**Comment by JeffreyMa597** [comment]
@Danie0918 Please confirm whether the details popup of "Recent Income and Expenses" on the homepage and the transaction history details should be the same content or not. In our old application, they look the same. It's just that the content of this popup seems to have not been processed by the new UI design.

If so: 
1、Should this popup be processed into a page like the transaction history details or kept as a popup?
2、If it is processed into a page like the transaction history details, there is currently no return function. Only the breadcrumb at the top is provided. Do we need to consider adding a return function or just provide the breadcrumb to route to the transaction history?

**Comment by Danie0918** [comment]
> Please confirm whether the details popup of "Recent Income and Expenses" on the homepage and the transaction history details should be the same content or not. In our old application, they look the same. It's just that the content of this popup seems to have not been processed by the new UI design.
> 
> If so: 1、Should this popup be processed into a page like the transaction history details or kept as a popup? 2、If it is processed into a page like the transaction history details, there is currently no return function. Only the breadcrumb at the top is provided. Do we need to consider adding a return function or just provide the breadcrumb to route to the transaction history?

Yes, the popup should be treated as a page like the transaction history details.

Regarding the return function here is really needed, only the breadcrumbs are not obvious  enough. @Kirl70 
![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/635ad8e2-9586-4de2-9bd4-4d4030eb69f8)

**Comment by Kirl70** [comment]
The corresponding pages have been added and the return style has been adjusted. The following pages, which previously had breadcrumbs, have also been modified accordingly: `Transaction History / Transaction Details`  `Nervos DAO / Transaction Details`  `Asset Account / Transaction Details`
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=17798%3A39356&t=FjVJk3xEm1BBsbff-1
<img width="734" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/0c6f0a14-1ebe-4044-9574-36cb5aad82ae">

In the previous version, I didn't notice that the recent transactions list was clickable because there were no indications on the page. We should change the mouse to a clickable gesture when the mouse is moved to the list. What do you think? @Danie0918 
<img width="792" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/02e72cb5-5cc3-4590-b8ca-8adb441555ea">

**Comment by Danie0918** [comment]
> In the previous version, I didn't notice that the recent transactions list was clickable because there were no indications on the page. We should change the mouse to a clickable gesture when the mouse is moved to the list. What do you think?

Okay, this change to a hand gesture is reasonable. @JeffreyMa597

**Comment by JeffreyMa597** [comment]
> In the previous version, I didn't notice that the recent transactions list was clickable because there were no indications on the page. We should change the mouse to a clickable gesture when the mouse is moved to the list. What do you think?
> 
> Ok, this change to a hand gesture is reasonable. @JeffreyMa597

Okay, based on my understanding, the original interaction of double-clicking to open details will be deprecated and replaced by single-clicking to open details. Am I right?

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2725

**Comment by FrederLu** [comment]
> PR: [nervosnetwork/neuron#2725](https://github.com/nervosnetwork/neuron/pull/2725)

When viewing transaction details on the 'Overview' page, the options in the left column should remain the same.
<img width="1199" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/089515ec-5de7-43a5-829d-e34d118ee3bb">
<img width="863" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6b78a621-1c71-4ae8-a25c-aba3ec3ae414">

---
When the mouse hovers over the data, the mouse has a style, but the hovered data still lacks the style selected by the UI (the background color of the data changes).
<img width="965" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/da62f3d2-cf4e-45ee-927e-9a3983a8fcda">
<img width="1433" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9a96eb02-91c7-475f-bf42-430be5c6a9ca">

**Comment by FrederLu** [comment]
> > PR: [nervosnetwork/neuron#2725](https://github.com/nervosnetwork/neuron/pull/2725)
> 
> When viewing transaction details on the 'Overview' page, the options in the left column should remain the same. <img alt="image" width="1199" src="https://user-images.githubusercontent.com/25676576/247021335-089515ec-5de7-43a5-829d-e34d118ee3bb.png"> <img alt="image" width="863" src="https://user-images.githubusercontent.com/25676576/247021237-6b78a621-1c71-4ae8-a25c-aba3ec3ae414.png">


Now the first point in the remark information still exists, and when you click on the detailed information on the overview page, the left column will still jump to display the transaction details in the transaction history.

**Comment by JeffreyMa597** [comment]
> Now the first point in the remark information still exists, and when you click on the detailed information on the overview page, the left column will still jump to display the transaction details in the transaction history.

Turning to the `transaction detail page` is expected when you are on the `overview` page.

**Comment by FrederLu** [comment]
> > Now the first point in the remark information still exists, and when you click on the detailed information on the overview page, the left column will still jump to display the transaction details in the transaction history.
> 
> After clicking the transaction items, turning to the `transaction detail page` is expected, not the `transaction history`, when you are on the `overview` page. [#170 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/170#issuecomment-1594590004)

@Danie0918 @Kirl70
Now when viewing the transaction details on the overview page, `Transaction History` will be selected in the left column. This is based on the logic modification of the details displayed in the pop-up window before, but through the current UI design, it is found that `Overview` should be selected in the left column at this time. Is this according to The latest UI design?
<img width="1429" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/49465001-5c65-4878-b722-aa35875af1ef">
 
https://github.com/Magickbase/neuron-public-issues/assets/25676576/35640a37-07be-43eb-adf1-7df6913e4e28

**Comment by Danie0918** [comment]
> @Danie0918 @Kirl70 Now when viewing the transaction details on the overview page, `Transaction History` will be selected in the left column. This is based on the logic modification of the details displayed in the pop-up window before, but through the current UI design, it is found that `Overview` should be selected in the left column at this time. Is this according to The latest UI design? If it need to follow the latest UI design, this part needs to be modified by @JeffreyMa597 . <img alt="image" width="1429" src="https://user-images.githubusercontent.com/25676576/250901626-49465001-5c65-4878-b722-aa35875af1ef.png">
> 

The transaction history under Overview should remain under the Overview menu.

**Comment by JeffreyMa597** [comment]
> The transaction history under Overview should remain under the Overview menu.

Got it. Updated.

**Comment by FrederLu** [comment]
Verified.
