### ISSUE TITLE
In Nervos DAO, when there is a decimal when choosing to deposit in CKB, keep 8 digits

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#172]
Currently, when depositing CKB in Nervos DAO, 8 digits are not reserved when the amount is selected to drag the amount with the slider, which may confuse users.This appears in both the current version V0.106.0 and the new UI.

![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/1a6a70e2-4e2c-4948-9774-c6258c1e31c6)

**Comment by WhiteMinds** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2722

**Comment by FrederLu** [comment]
Verified.
