### ISSUE TITLE
Some styling issues on the settings page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#173]
- [ ] 1、In addition to `General`, there are alignment problems in the titles of `Wallet`, `Network`, `Data` and the following copywriting.

<img width="858" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2a9fb0d1-fcb3-45ba-8e90-c692c59723ae">
<img width="1017" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/220956bd-d6b3-4350-9bed-17aa02054457">

---
- [ ] 2、The size and style of the edit wallet popup window are different from the UI.
<img width="859" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/58dc082a-aff2-451d-b10e-06be77ed8e08">
<img width="1439" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b6a65475-79a2-4e7e-b19d-99f7fcb78d44">

---
- [ ] 3、The position of `select file` in the imported Keystore file is abnormal.
<img width="769" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ac3c36ce-9988-4ce8-8885-b9d29d43ad7a">
<img width="768" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/34447313-f48e-4c8f-bcfa-3fe205cdc1ab">

---
- [ ] 4、The `!` icon is missing before the json file format exception prompt.
<img width="732" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/66b4a2b8-6be5-4f54-ab48-19d85308b23d">
<img width="858" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/4bd9ff4b-3b58-4e87-8358-23de63bc8811">

---
- [ ] 5、On the `Please connect the device and select the model` interface, the length of the option box is shorter than that on the UI.
<img width="775" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/07038a6a-5065-4ff2-ae19-36506d1014d1">
<img width="792" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8886cd54-eaf7-4344-a3d9-b4b191b382ae">

---
- [ ] 6、The check for update pop-up window is abnormal.
<img width="545" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e5bc7496-9318-4e1f-bbd9-93042101a1fa">
<img width="645" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/53e73750-1ea6-4c8c-b2a8-6391e57053c6">

---
- [ ] 7、The prompt information is missing at the top after updating the wallet information and saving it.
<img width="290" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1f0e432b-e773-46f2-8a12-167de784a965">

---
- [ ] 8、The input box of the backup/delete wallet pop-up window lacks prompt copy (note the color of the copy), and there is no need to show/hide button.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/8d716848-adde-479e-b2d6-1eceefe27c8b)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/0683797e-8344-47ad-b441-3e5ae9f7337f)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/2585ef29-ebbe-4bc7-9a25-4a052924a388)

---
- [ ] 9、The copywriting and UI are not unified, and there is a lack of `import` copywriting.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/59d156d5-a7d1-4dcc-a62e-496ac6ec820d)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/64ec1e80-4422-4af4-ac9c-ce36dcad0189)

---
- [ ] 10、Missing dynamic icons on load.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/a591a60e-407d-4572-84db-0c1f791598e7)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/b5db3a67-dd69-4ea0-bea1-701d1c355808)

---
- [ ] 11、There must be `v` before the version number; the version number does not need to be displayed after the system voice;

![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/04cbc025-c3ca-4775-8a2d-0be9df237c1c)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/7b74c9ef-91dc-45ce-b2e8-65481c513a1d)

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by FrederLu** [comment]
Verified.
