### ISSUE TITLE
Styling issues with network settings

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#174]
- [ ] 1、The pop-up window size of `Add Network` and `Edit Network` does not match the size on the UI.
<img width="577" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e52fd4ee-aa4a-45b7-a6d4-51f18e0de052">
<img width="1174" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/0dc402d5-ef7e-47c1-ad91-61b2bdec9880">

---
- [ ] 2、There is an error in the text on the `Edit Network` pop-up window.
<img width="871" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5cddf9f8-3d55-4140-abae-24cdd182e23b">
<img width="687" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c104026b-dc6a-471d-86c2-7caf8a1b07fd">

---
- [ ] 3、There is a problem with the style of the "Delete Network" secondary confirmation pop-up window.
<img width="1000" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/0a4c54c9-f67b-4a52-9c45-3aeadb8f9456">
<img width="431" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/199606b0-b634-4b75-afe2-1cfc7559c6db">

---
The `RPC Address` and `Network Name` in the `Add Network` pop-up window should be empty by default, but now it will save and display the information of the last operation:
- [ ] 4、After adding the network, call the pop-up window for adding the network for the second time;
- [ ] 5、First invoke the `Edit Network` pop-up window, and then invoke the `Add Network` pop-up window;

---
- [ ] 6、After editing the network information and saving it, the top prompt information is missing.
<img width="278" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/72d7c538-2317-4bdf-a3e0-b6c763c592ac">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by FrederLu** [comment]
Verified.
