### ISSUE TITLE
Data setting style problem.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#175]
<img width="451" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/75199054-19ce-4b6d-aa77-ba72061d606d">

https://github.com/Magickbase/neuron-public-issues/assets/25676576/3c477d0c-e6f0-43b4-aee0-dcadf51ac186

- [ ] 1、When the mouse hovers over the `ℹ️` icon, the mouse needs to be set as a hand.
- [ ] 2、Evoke `Cache` details, after sliding the page, the next time you hover the `Cache` icon, the page will jump.

---
- [ ] 3、The color of the prompt text in the ckb node data must be consistent with that of the icon.
- [ ] 4、Prompt message The color of the underlying color block is too dark and needs to be adjusted.
<img width="732" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/3badd4ad-91f5-4f7e-a008-9c0647e0206a">
<img width="1018" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/195db1b9-931a-48f1-bf82-436a479e89fe">

<img width="745" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9b90e972-69c4-4db2-9034-82aceeffae6a">
<img width="758" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/968d4010-92ca-406f-8a75-3b6e66c36410">

---
- [ ] 5、The pop-up window style for the second confirmation of data transfer confirmation is abnormal, refer to the pop-up window style in the UI draft (for specific copy and style, please ask the design or pm).
- [ ] 6、After clicking the `data transfer complete` button, the dynamic icon is displayed too large, which makes the position of the button copy offset.
<img width="894" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/39f13068-9698-4885-8212-f95dc889f969">

---
- [ ] 7、After clearing the cache, the pop-up window (1 place) and prompt information (2 places) are missing.
<img width="965" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/005d3882-b5e6-45c3-8d82-2cf03cda6182">

---
- [ ] 8、The button copy in the pop-up window needs to be consistent with the UI.
<img width="728" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fe1753f0-224c-40db-84bc-a39e6cf9c9d5">
<img width="660" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/10a1d04c-e04c-49c7-99fb-ff086c08e1ba">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by FrederLu** [comment]
1、The position of the prompt box arrow is abnormal, it should be aligned! icon.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/b5c6fd20-5c7a-4fce-9d27-52dd35864d1e)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/276042cc-cbeb-4489-9670-d74e9fc2058e)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/0269173e-f74d-400d-8c4c-2d48fabbe2fc)

---
2、It is better for the text of the prompt `Continue` to be the same as `Confirm` in the text of the button.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/633efcaf-68c4-4aa4-a934-4d6f4bf2ba87)


---
3、Pay attention to the Refresh Cache text and the color of the front icon.
At the same time, the icon here cannot be clicked, and the mouse hove effect can be removed. This pop-up window distinguishes between full nodes and light nodes.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/da79654c-9028-4da2-8262-46b6a79628c5)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/d6ef71db-2129-40b2-967c-7b9f487d8399)
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/6e363ab5-c4e5-4250-bdcb-e161b3e34e94)

**Comment by devchenyan** [comment]
Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c .

**Comment by FrederLu** [comment]
Verified.
