### ISSUE TITLE
Refactoring With Lumos

### ISSUE THREAD

**Issue by homura** [Magickbase/neuron-public-issues#177]
## Background

Currently, there are several Lumos modules was reimplemented in Neuron, this results in higher maintenance cost for Neuron as the reimplementation causes us to rewrite unit tests

## List

- neuron-wallet
  - [x] `LumosCell` -> `lumos/base/Cell` - not compatible
  - [x] `LumosCellQuery` -> `lumos/ckb-indexer/QueryOptions` - compatible
     - [x] https://github.com/nervosnetwork/neuron/pull/3163
  - [x] `IndexerCacheService.fetchTxMapping` -> `TransactionCollector` with grouped transaction feature
     - [x] Move to backlog
- [x] #187
- [x] many `HexString === HexString` -> `bytes.equal` to avoid `0xAA !== 0xaa`
     - [x] Not found / Not important for now
- [x] `shannonToCKB`, `sudtValueToAmount`-> `BI.formatUnit`
   - [x] https://github.com/nervosnetwork/neuron/pull/3114
   - [x] https://github.com/nervosnetwork/neuron/pull/3119
   - [x] https://github.com/nervosnetwork/neuron/pull/3126
   - [x] https://github.com/nervosnetwork/neuron/pull/3129
- [x] `models/blake2b` -> `lumos/base/utils/blake2b`
- [x] `models/multisig` -> `lumos/base/since`
   - [x] https://github.com/nervosnetwork/neuron/pull/3156
- [x] refactor all the  `ckb indexer url` with the `ckb url`, since the CKB Indexer has been integrated into CKB
   - [x] https://github.com/nervosnetwork/neuron/pull/3170
- [x] `models/keys` -> `@ckb-lumos/hd`
   - [x] https://github.com/nervosnetwork/neuron/pull/3152
- `@nervosnetwork/ckb-sdk-x` can be refactored with the lumos
  - [x] #202
    - [x] https://github.com/ckb-js/lumos/pull/560
    - [x] https://github.com/nervosnetwork/neuron/pull/2843 (in test)
    
  - [x] #201
    - [x] https://github.com/nervosnetwork/neuron/pull/2801
    - [x] https://github.com/nervosnetwork/neuron/pull/2802
    - [x] https://github.com/nervosnetwork/neuron/pull/2803
    - [x] https://github.com/nervosnetwork/neuron/pull/2814
    - [x] https://github.com/nervosnetwork/neuron/pull/2817
  - [x] the global variable [`ckbCore`](https://github.com/nervosnetwork/neuron/blob/baee37ba9efd087457bb90f210374dab1d489444/packages/neuron-ui/src/services/chain.ts#L3)
     - [x] https://github.com/nervosnetwork/neuron/pull/3138
     - [x] https://github.com/nervosnetwork/neuron/pull/3142
     - [x] https://github.com/nervosnetwork/neuron/pull/3145
  - [x] @nervosnetwork/ckb-sdk-utils
     - [x] https://github.com/nervosnetwork/neuron/pull/3149

**Comment by zhangyouxin** [comment]
We can seperate these tasks to small issues so that it is easy to write smaller PRs and can be parallelly executed by different team members.

**Comment by homura** [comment]
> We can seperate these tasks to small issues so that it is easy to write smaller PRs and can be parallelly executed by different team members.

OK, I'll transform the plan section into TODO list

**Comment by homura** [comment]
> IndexerCacheService.fetchTxMapping -> TransactionCollector with grouped transaction feature

The CKB indexer offers a feature `group_by_transaction` that allows the grouping of indexed transactions by their transaction hashes instead of having an array with multiple identical transactions. This feature is useful for scenarios where the `io_index` [has not cared](https://github.com/nervosnetwork/ckb-indexer/issues/21)

We can simplify the [`fetchTxMapping`](https://github.com/nervosnetwork/neuron/blob/4d1b3bbb3540a833c974b770f6758daf0efbb291/packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts#L72-L142) as follows to reduce unnecessary lines and IO

```js
const grouped = get_transactions({
  search_key: {
    lock: ...,
    group_by_transaction: true,
    limit: no_limit_here
  }
})

grouped.forEach(({tx_hash}) => {
   mappingsByTxHash.set(tx_hash, [...])
})
```

This is a small improvement, so I suggest we move the point to the backlog

**Comment by twhy** [comment]
> > IndexerCacheService.fetchTxMapping -> TransactionCollector with grouped transaction feature
> 
> The CKB indexer offers a feature `group_by_transaction` that allows the grouping of indexed transactions by their transaction hashes instead of having an array with multiple identical transactions. This feature is useful for scenarios where the `io_index` [has not cared](https://github.com/nervosnetwork/ckb-indexer/issues/21)
> 
> We can simplify the [`fetchTxMapping`](https://github.com/nervosnetwork/neuron/blob/4d1b3bbb3540a833c974b770f6758daf0efbb291/packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts#L72-L142) as follows to reduce unnecessary lines and IO
> 
> ```js
> const grouped = get_transactions({
>   search_key: {
>     lock: ...,
>     group_by_transaction: true,
>     limit: no_limit_here
>   }
> })
> 
> grouped.forEach(({tx_hash}) => {
>    mappingsByTxHash.set(tx_hash, [...])
> })
> ```
> 
> This is a small improvement, so I suggest we move the point to the backlog

Agree ^-^
