### ISSUE TITLE
Unable to detect hardware wallet

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#178]
When importing the ledger nano x hardware wallet, the detection prompt is abnormal.
<img width="646" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/257ca5ab-e353-4a06-8fff-062caf7b474d">
<img width="671" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/457fec8c-fc8d-4928-8d04-20c19f1e287f">
<img width="822" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/92129e49-a780-42ed-a124-8aa24ccbc794">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2716

**Comment by FrederLu** [comment]
Verified.
