### ISSUE TITLE
Version update problem

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#179]
- [x] 1、Detected that the pop-up window of a new version does not match the UI.
<img width="739" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/65e00bbd-9c3d-4af4-9e74-8326c8ee99b4">
<img width="1439" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2ce3f73d-33b2-4e9c-ac09-ee62f0d838ef">

---
- [ ] 2、The update check should be terminated after clicking `Cancel` in the check for update link. Now it won't terminate and still shows the `New Version Detected` popup.
<img width="324" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/be477496-1995-4e0a-baa4-35348cd85add">

 ---
- [ ] 3、After clicking the `Cancel` button in the download pop-up window of "New Version Detected" to close the pop-up window, the pop-up window of `Currently the latest version` should not be displayed later.
<img width="507" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9175c23d-79a5-491b-94b0-5f32fb76d262">
<img width="447" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/50fbe734-11aa-41f9-97b0-628a84c742ea">

 ---
- [ ] 4、The update failed to prompt that the style of the pop-up window is wrong. For details, please refer to the verification failure style on the UI (for specific copy and style, please find pm or design confirmation).
<img width="276" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9ec859be-6e49-4876-9444-d3990b837661">
<img width="695" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c0d7fdf5-fd7b-462c-aa99-9313728a49ce">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by FrederLu** [comment]
After merging develop, the version is already the latest. It is necessary for developers to help set the version to facilitate the verification of the UI modification of the update interface.

**Comment by devchenyan** [comment]
> After merging develop, the version is already the latest. It is necessary for developers to help set the version to facilitate the verification of the UI modification of the update interface.

Please head to https://github.com/nervosnetwork/neuron/pull/2736

**Comment by FrederLu** [comment]
> > After merging develop, the version is already the latest. It is necessary for developers to help set the version to facilitate the verification of the UI modification of the update interface.
> 
> Please head to [nervosnetwork/neuron#2736](https://github.com/nervosnetwork/neuron/pull/2736)


Questions 1 and 2 have been verified through the package in the above pr, but the package will not be downloaded after clicking the `Install Update` button, so the subsequent process cannot be verified (questions 3 and 4 cannot be verified).
<img width="674" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b383d279-cce3-44cb-9b88-2dc0b00abcb6">

**Comment by devchenyan** [comment]
Packaging for test is done in [5411586293](https://github.com/nervosnetwork/neuron/actions/runs/5411586293) for commit https://github.com/nervosnetwork/neuron/commit/5e1c9970d07817f550db65fd8b207e971f5cad37 .

**Comment by FrederLu** [comment]
> Packaging for test is done in [5412522332](https://github.com/nervosnetwork/neuron/actions/runs/5412522332) for commit [nervosnetwork/neuron@5559f03](https://github.com/nervosnetwork/neuron/commit/5559f03d33fa630866def5804a11df4d4e6ae981) .

After downloading a new package, the interface becomes unresponsive after clicking the Update Install button.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/4f30b73c-ab7e-4122-9cf1-9ab81f792be2

**Comment by devchenyan** [comment]
Packaging for test is done in [5461287659](https://github.com/nervosnetwork/neuron/actions/runs/5461287659)

**Comment by FrederLu** [comment]
Verified.
