### ISSUE TITLE
Hardware money does not support backup.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#182]
Hardware money does not support backup. If it is a hardware wallet backup button, it needs to be hidden. If it is not hidden, clicking it will not work.
<img width="949" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/a4f1691f-2c83-4e76-aa29-4380778d8b76">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2708

**Comment by devchenyan** [comment]
Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c .

**Comment by FrederLu** [comment]
Verified.
