### ISSUE TITLE
Specify start point to sync when a wallet is imported and synced in light-client mode

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#183]
The start point of light-client subscription is configurable, which makes it possible to synchronize from a specific block number. With the function, the following feature can be adapted to shrink the progress of synchronization in light-client mode:

- If the wallet is imported: provide an optional prompt with the first receive address when importing a wallet, and inform the user to check the block number of the first transaction (on ckb explorer) to fill in. Neuron can be configured to start synchronization from **block number of the first transaction - N**(N is an internal deviation from the assumed start point)

- If the wallet is newly generated: subscription starts from the current tip block number

**Comment by Keith-CY** [comment]
> ![](https://user-images.githubusercontent.com/122437870/254178439-358b2ef5-6175-4bef-ad71-ff371c0a5a75.png)
> 
> I designed a popup window about this requirement, but it seemed a bit complicated and uncertain considering the process of needing the user to find the blocks and fill them in themselves. Can we automatically determine the starting block and synchronize it without having to go through the user's filling and confirmation?

`Light client mode only synchronizes blocks related to transactions under the current wallet` has no relation to the `start point of synchronization`.

> Can we automatically determine the starting block and synchronize it without having to go through the user's filling and confirmation?

It relies on an external service, e.g. CKB explorer, so we cannot set the start point without user's approval. And even it's approved to fetch data from CKB Explorer, the data should be confirmed by the user.

So I would suggest showing the first address and informing user to locate the earliest block where the address appeared, with a copy button and concise description + link to the tutorial on the troubleshooting page

**Comment by yanguoyu** [comment]
After the user enters the block number, we can show a link for the user that shows the block number detail to confirm.
Just like https://explorer.nervos.org/block/10487248

**Comment by Danie0918** [comment]
[Updated][https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639662537](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639662537)

**Comment by Kirl70** [comment]
Design Draft:

Setting Synchronization Blocks Popup
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=21119%3A41473&mode=design&t=s3UwTuKJiLeC1Hfl-1
1-23～1-25 <img width="1499" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/acf8e641-1132-4d26-b077-ad41edb823c2">

Setting Synchronization Blocks Entry
 https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1023%3A15152&mode=design&t=s3UwTuKJiLeC1Hfl-1
<img width="218" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/ca51ee12-2f17-4ef9-aee4-4efba6e26b18">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2786
