### ISSUE TITLE
The multisig address's balance is not correct after send some txs with light client.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#185]
### What happened

Because the light client API https://github.com/nervosnetwork/ckb-light-client#get_transactions has some differences with ckb node. So we need to change the getter of tx_hash when the node is light client at https://github.com/nervosnetwork/neuron/blob/v0.110.1/packages/neuron-wallet/src/services/multisig.ts#L191. Otherwise Neuron can not remove dead cell with multisig address with the light client.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2711

**Comment by littleLip520** [comment]
blocked by issue https://github.com/Magickbase/neuron-public-issues/issues/196

**Comment by yanguoyu** [comment]
You can test it by sending a tx from multisig address to another address.

**Comment by littleLip520** [comment]
verified
