### ISSUE TITLE
`HexUtils` -> `@ckb-lumos/codec` - compatible

### ISSUE THREAD

**Issue by homura** [Magickbase/neuron-public-issues#187]
- `HexUtils.toHex` -> [`bytes.hexify`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#hexify)
- `HexUtils.removePrefix` + `HexUtils.addPrefix` -> [`bytes.concat`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#concat-1)
- `HexUtils.byteLength` -> [`bytes.bytify().length`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#bytify)
- `HexUtils.fromBuffer` -> remove, not in use

**Comment by yanguoyu** [comment]
I couldn't find the corresponding API from @ckb-lumos/codec that can replace `HexUtils `, Could you describe it in more detail?

**Comment by zhangyouxin** [comment]
> * `HexUtils.toHex` -> [`bytes.hexify`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#hexify)
> * `HexUtils.removePrefix` + `HexUtils.addPrefix` -> [`bytes.concat`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#concat-1)
> * `HexUtils.byteLength` -> [`bytes.bytify().length`](https://lumos-website-git-develop-magickbase.vercel.app/api/modules/codec.html#bytify)
> * `HexUtils.fromBuffer` -> remove, not in use

The `removePrefix` and `addPrefix` functions utilize string slicing or concatenation, whereas the `bytes.concat` function concatenates multiple `BytesLike` parameters. Looks like these functions serve different purposes?

**Comment by zhangyouxin** [comment]
And from the usages of `HexUtils.toHex`, they are always dealing with `HexDecimals`, such as `BlockNumber`, `EpochNumber` etc, so I could make use of `BI.from(param).toHexString`, it looks more appropriate to me

**Comment by homura** [comment]
https://github.com/nervosnetwork/neuron/pull/2718
