### ISSUE TITLE
The style of the data is abnormal when switching nodes.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#193]
When switching from a full node to a light node, the style of the data is abnormal.
<img width="909" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/941b8c54-5513-4ef8-95a8-34cca8f833c4">

**Comment by devchenyan** [comment]
Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c .

**Comment by FrederLu** [comment]
Verified.
