### ISSUE TITLE
The prompt box is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#194]
The prompt for editing a network only needs to be prompted when editing, not when adding a network.
<img width="337" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d2c542fa-13e6-4cbe-ba83-86c7b05a8405">

**Comment by devchenyan** [comment]
Packaging for test is done in [5408143725](https://github.com/nervosnetwork/neuron/actions/runs/5408143725) for commit https://github.com/nervosnetwork/neuron/commit/3edf8bb334ed62ee37476e470fa7c45a6507398c .

**Comment by FrederLu** [comment]
Verified.
