### ISSUE TITLE
The balance of the multi-signature address is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#195]
Use the latest release 0.110.1 wallet, and use the test node full node to synchronize data;
There is a balance in the multi-signature address, but when transferring money through neuron, it prompts that the balance is insufficient;
The balance did not recover after clearing the cache;

[neuron_debug_1687170677564.zip](https://github.com/Magickbase/neuron-public-issues/files/11787147/neuron_debug_1687170677564.zip)
[multisig-config_1687177409498.json.zip](https://github.com/Magickbase/neuron-public-issues/files/11788067/multisig-config_1687177409498.json.zip)

https://pudge.explorer.nervos.org/address/ckt1qpw9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn32sqtuch8xmddtkx2aaxmvzwkwfqmchwl5y5gcqs6eq
https://pudge.explorer.nervos.org/transaction/0x91fa13cdac86dad791246a5048c3e95cec0db303eda3d6c4b6695b127dff1f62
<img width="194" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f5a09531-132f-4203-8ea0-32ff5931cc25">

<img width="788" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/34d0e82d-c73a-416c-b026-4a0f9636b949">
<img width="959" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6b0f0ac8-eed2-4656-be69-4ac6fdd3c9db">

**Comment by yanguoyu** [comment]
I have download release 0.110.1 and import the same multisig address, it shows the right balance.

**Comment by yanguoyu** [comment]
Could you try to upload the local database file? You can find it at `/Users/username/Library/Application Support/Neuron/cells/cell-0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606.sqlite`

**Comment by FrederLu** [comment]
> Could you try to upload the local database file? You can find it at `/Users/username/Library/Application Support/Neuron/cells/cell-0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606.sqlite`

[cell-0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606.sqlite.zip](https://github.com/Magickbase/neuron-public-issues/files/11795047/cell-0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606.sqlite.zip)

**Comment by yanguoyu** [comment]
When there exists the same multisig config in a different wallet, it will create the same [MultisigOutput](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/database/chain/entities/multisig-output.ts) entity at once. Then SQLite saves failed.
I will fix it by removing duplicate multisig config and removing duplicate entities when syncing multisig cells.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2732
