### ISSUE TITLE
Redundant dependencies in modules

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#198]
There're some project-scope dependencies specified in modules, such as

```
"eslint": "8.38.0",
"eslint-config-prettier": "8.8.0",
"eslint-plugin-prettier": "4.2.1",
"lint-staged": "13.2.1",
"prettier": "2.8.7",
```

I would prefer to list them in the root `package.json`

How do you think about it @yanguoyu @homura @WhiteMinds @JeffreyMa597 @devchenyan @zhangyouxin

**Comment by WhiteMinds** [comment]
Agreed, their versions should be the same.

**Comment by homura** [comment]
LGTM, lift `devDependencies` would save the disk space and make code style more consistently

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2741

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2742
