### ISSUE TITLE
Update comment for `packaging for test is done` instead of open a new one

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#199]
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/aaeb4520-bcac-497a-a0c6-d9f41731db8b)

Now there are multiple comments to inform developers that new packages are ready for test, but it overwhelms discussions.

The existing comment can be updated to make the thread clear, as `codecov` and `vercel` did.

![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/acef455c-6053-460a-a2cb-8c1d9e10c682)
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/a7698941-67b8-4430-99b3-6aa0a2ea8a24)

Ref:
- Update a comment: https://github.com/thollander/actions-comment-pull-request#update-a-comment

**Comment by yanguoyu** [comment]
we can optimize for test packaging with https://github.com/Magickbase/neuron-public-issues/issues/189. After that, If testers want to test a PR, they can comment with `/package` to trigger action to start a package. And the package result will append to the comment. @FrederLu  How do you think? 
CC @Keith-CY  @homura 

The step of package is:
1. Subscribe to the command of `package` by https://github.com/marketplace/actions/slash-commands
2. Trigger package action by the `package` command.
3. After package success, append comment by  https://github.com/marketplace/actions/create-or-update-comment

**Comment by Keith-CY** [comment]
> we can optimize for test packaging with #189. After that, If testers want to test a PR, they can comment with `/package` to trigger action to start a package. And the package result will append to the comment. @FrederLu How do you think? CC @Keith-CY @homura
> 
> The step of package is:
> 
> 1. Subscribe to the command of `package` by [github.com/marketplace/actions/slash-commands](https://github.com/marketplace/actions/slash-commands)
> 2. Trigger package action by the `package` command.
> 3. After package success, append comment by  [github.com/marketplace/actions/create-or-update-comment](https://github.com/marketplace/actions/create-or-update-comment)

LGTM

**Comment by yanguoyu** [comment]
And I will change [notarize](https://github.com/electron/notarize/tree/v1.2.4#method-notarizeopts-promisevoid)'s tool to `notarytool`. Could you help me to add `teamId ` into GitHub.secret? @Keith-CY

**Comment by Keith-CY** [comment]
> And I will change [notarize](https://github.com/electron/notarize/tree/v1.2.4?rgh-link-date=2023-06-27T01%3A24%3A17Z#method-notarizeopts-promisevoid)'s tool to `notarytool`. Could you help me to add `teamId ` into GitHub.secret? @Keith-CY

It's been set as `TEAM_ID` conforming to the name style of other secrets

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2754
