### ISSUE TITLE
Support sending sudt with creating a cell for reciever

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#20]
We've implemented sending sudt to an asset account, which requires receiver to have a cell with sudt/acp scripts to receive sudt amount.

We didn't support sending sudt to secp256k1 address because a cell with secp256k1 lock script is limited to be unlocked by its owner, so we cannot append receiver's secp256k1 cell in input and sender has to provide another cell to make up the sudt/secp256k1 cell for the receiver. That was weird for normal users.

With yokai preveiling in users, sending sudt with extra ckb to create a cell holding sudt amount become acceptable, so neuron will enable it too.

There're two kinds of sending sudt in neuron
1. sending sudt to secp256k1 address, which will use a cheque lock script to provide a temporary cell for receiver, and will be withdrawn after receiver claims the sudt amount, the temporary cell will turn back to sender
2. sending sudt to sudt/acp cell of receiver. This requires receiver to have a live cell, or an error will be thrown.

After enabling sending sudt with an extra cell, we can support any addresses.

---

### For the first case: sending to secp256k1 address

Before: will prompt sender that 162 ckbytes lock temporarily
![image](https://user-images.githubusercontent.com/7271329/168460732-8c07d7c7-c2c5-4982-bf23-19b2a57f92b0.png)

After: will ask user to lock or send with 162 ckbyes
![image](https://user-images.githubusercontent.com/7271329/168460765-22a51e7f-0e91-466e-a590-6df5bd51e891.png)
1. option 1 is `Lock 162 CKBytes temporarily, and tooltip of info icon is the same as before.
2. option 2 is `Send extra 162 CKBytes along with {{asset name}}`, and tooltip of info icon is `Extra 162 CKBytes will be sent along with {{asset name}} to hold the asset/额外 162 CKBytes 将与 {{asset name}} 一同发给收款方用于维持资产.`

---

### For the second case: sending to sudt/acp address but no live cells found

Before: will prompt user that `no asset accounts found`
![image](https://user-images.githubusercontent.com/7271329/168460971-a35b6c99-5034-4171-8304-7a13b46e245f.png)

After: will ask user to send extra xxx CKBytes to create an asset account for receiver
![image](https://user-images.githubusercontent.com/7271329/168461049-17cefbed-fcda-49ef-901f-8265735c6fff.png)
When receiver's live cell is not found, show this checkbox with label `Send extra {{xxx}} CKBytes to create an asset account for receiver/额外发送 {{xxx}} CKBytes 为收款方创建资产账户`

---

### For other cases: any other addresses

![image](https://user-images.githubusercontent.com/7271329/168461141-6a5628b7-9282-4032-bbf1-cf155aa3c9e2.png)

Checkbox with label: `Receive address has an unknown lock script, please make sure receiver knowns how to handle it, and extra {{xxx}} CKBytes will be sent along with {{asset name}} to hold the asset/收款地址包含未知 Lock Script, 请确保接收者知道如何处理该资产, 额外 {{xxx}} CKBytes 将与 {{asset name}} 一同发给收款方用于维持资产`

---

All checkboxes or radios only appear with valid addresses.

**Comment by Keith-CY** [comment]
This is a feature request from nervos foundation that we should support more composition of type script/lock script.

The most basic composition is `sudt/secp256k1` as mentioned in case 1. Because secp256k1 lock script can only be unlocked by its owner(verified by a signature), sender has to provide an extra cell for the receiver to hold the asset.

Now that we provide a cell with an arbitrary lock script for the receiver, we could support any addresses(Case 2 and Case 3)

All details are elaborated in the issue.

Expected to be done in 3 weeks(1.5 for development, 1 for test, and 0.5 for resilience) and assigned to @yanguoyu @Cedar67 , is that ok?

@qiweiii could also take part in for better understanding of `sudt type script`, `secp256k1 lock script`, and other lock scripts like [omni lock script](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1) used by [yokai](https://www.yokaiswap.com/)

**Comment by Keith-CY** [comment]
Any questions about the feature could be appended in this issue.

**Comment by yanguoyu** [comment]
ok, It looks reasonable so far. Then if the sender doesn't care extra ckb charge, he can send to any validation address.

**Comment by yanguoyu** [comment]
When sending to an unknown script, should we notify the sender that the receiver should know how to use the sudt asset?

**Comment by Keith-CY** [comment]
> When sending to an unknown script, should we notify the sender that the receiver should know how to use the sudt asset?

Good point, let's add a caveat in the label, like `Receive address has an unknown lock script, please make sure receiver knowns how to handle it, and extra {{xxx}} CKBytes will be sent along with {{asset name}} to hold the asset/收款地址包含未知 Lock Script,  请确保接受者知道如何处理该资产, 额外 {{xxx}} CKBytes 将与 {{asset name}} 一同发给收款方用于维持资产`

**Comment by qiweiii** [comment]
Just to clarify my understanding:

Previously we do support sending sudt to secp256k1 address, it's just a bit weired for users, as sender's 162 ckb will be locked temporarily (used to somehow create a temporary cell with cheque lock script for the receiver), and receiver has to claim the sudt amount.

So the main aim here is to allow sender to send sudt directly without temporarily lock sender's ckb and needing receiver to claim it.

The solution is that, instead of temporarily lock 162 ckb and get back later, sender can *choose* to lose 162 ckb, so neuron help create an asset account for receiver, so also no need for receiver to claim it.

For all three cases, we create `a cell with an arbitrary lock script` that can be unlocked by any kind of address

@Keith-CY @yanguoyu Are these correct?

**Comment by Keith-CY** [comment]
> Just to clarify my understanding:
> 
> Previously we do support sending sudt to secp256k1 address, it's just a bit weired for users, as sender's 162 ckb will be locked temporarily (used to somehow create a temporary cell with cheque lock script for the receiver), and receiver has to claim the sudt amount.
> 
> So the main aim here is to allow sender to send sudt directly without temporarily lock sender's ckb and needing receiver to claim it.
> 
> The solution is that, instead of temporarily lock 162 ckb and get back later, sender can _choose_ to lose 162 ckb, so neuron help create an asset account for receiver, so also no need for receiver to claim it.
> 
> For all three cases, we create `a cell with an arbitrary lock script` that can be unlocked by any kind of address
> 
> @Keith-CY @yanguoyu Are these correct?

Exactly

**Comment by yanguoyu** [comment]
`For other cases: any other addresses`
The option checkbox must be checked, if not user can't create a transaction. Should we set it checked and disabled or only a tip but not a checkbox?

**Comment by Keith-CY** [comment]
> `For other cases: any other addresses` The option checkbox must be checked, if not user can't create a transaction. Should we set it checked and disabled or only a tip but not a checkbox?

We should leave the checkbox unchecked, but still generate the transaction while disabling the `submit` button, until the user checks it.

**Comment by yanguoyu** [comment]
If send sUDT to a secp256k1 address, extra CKBytes only need 142. Cheque need 162 CKBytes because of cheque's args is 40 bytes.

**Comment by yanguoyu** [comment]
Does `CKB` acp account need these options?

**Comment by Keith-CY** [comment]
> Does `CKB` acp account need these options?

For me, it’s unnecessary, I can simply use receiver’s secp256k1 address to send CKB along with providing a cell.

**Comment by yanguoyu** [comment]
- [ ] acp/ckb -> secp256k1 address: Create a secp256k1 lock cell
- [ ] acp/ckb -> acp/ckb address: Receive address exist is ok, else throw error.
- [ ] acp/ckb -> unknow address: throw error
- [ ] acp/sudt -> secp256k1 address: Cheque lock cell or secp256k1/sudt cell
- [ ] acp/sudt -> acp/sudt: Send to exist acp/sudt cell, or create a acp/sudt cell
- [ ] acp/sudt -> unknow address: create a unknow/sudt cell

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2400

**Comment by merakmember** [comment]
when can this feature be used? so I can send sudt to yokai/forcebridge

**Comment by Cedar67** [comment]
The following scenarios were verified and passed on https://github.com/nervosnetwork/neuron/pull/2400

✅ 1 - acp/sudt -> secp256k1 address: Cheque lock cell or secp256k1/sudt cell.
✅ 2 - acp/sudt -> acp/sudt:
- > Send to exist acp/sudt cell.
- > create a acp/sudt cell.

✅ 3 - acp/sudt -> unknow address: create a unknow/sudt cell.
✅ 4 - acp/ckb -> secp256k1 address: Create a secp256k1 lock cell.
✅ 5 - acp/ckb -> acp/ckb address:
- > Send to exist address
- > Send to unknow address: throw error
