### ISSUE TITLE
Problems with New design for Neuron Multisig Address-tips  and UI bugs

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#205]
1.In multisig addresses pop-up box line dividers can disappear by clicking  anywhere in  line ,expected result is it can not be changed by clicking.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/7258af9d-dd1c-4ad3-ace6-a4b465b3a11f

2.In multisig addresses pop-up box when balance is 0CKB，it can not show 0.
<img width="759" alt="截屏2023-06-28 11 56 23" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/052d5430-4323-43e1-8f39-8738ee0d77ea">

3.In multisig addresses pop-up box  the first checkbox does not have choose all feature.

<img width="670" alt="截屏2023-06-29 11 30 03" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/3626ff35-b7b8-4064-b11c-63deb3b858bf">

4.In delete multisig addresses  tip pop-up box ,the description is not 
same with  new UI design document.
<img width="664" alt="截屏2023-06-28 14 40 47" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/b4ed0f61-9f19-4f50-9092-dad913617d3d">

5.In send CKB from multisig addresses pop-up box,when click delete button ,then 0 can not be deleted.
<img width="744" alt="截屏2023-06-28 14 44 02" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/98ecd048-1147-47cd-9562-3a6677d7e5c3">

6.In send CKB from multisig addresses pop-up box,when send balance greater than residual amount，it does not show the tip.
<img width="695" alt="截屏2023-06-28 14 45 28" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/0f52b0c9-be05-4980-ba84-f841fa06a2ca">

7.In send CKB from multisig addresses pop-up box,when  the receive is 
multisig address itself it does not show invalid address tip.
<img width="745" alt="截屏2023-06-28 14 50 36" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/de0d3e43-d5db-43c8-a61f-1921431e003f">

8.In send CKB from multisig addresses pop-up box,positioning cursor can back to head when delete delete any letter . It is not convenient to use and look information.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/91c74c3f-1aaf-498d-8400-0a2cd251e923

9.Input box lost tips
<img width="685" alt="截屏2023-06-29 15 59 26" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ed454ba6-c244-4156-89e5-d289a9abcb74">
<img width="649" alt="截屏2023-06-29 16 01 10" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d03ae659-6c8b-4385-bcf9-01fd45606c51">

**Comment by silySuper** [comment]
1.Verified
2.Verified
3.This  checkbox can choose all now，but in UI design it says when we choose all only delete can be clicked,actually 0CKB does not satisfy this requriment.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/f3f4ea49-5453-45c6-8f6f-c8ab3c84aab8


4.Verified
5.Verified
6.The problem exists as before
<img width="672" alt="截屏2023-07-11 17 09 17" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/a5c15dfc-3c0a-4fb9-a9d2-0d9b78a4cd86">

7.The problem exists as before
<img width="673" alt="截屏2023-07-11 17 09 37" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6c1b7aa8-0d4b-4b4a-9dcc-98b179520631">

8.Verified
9.Verified

**Comment by devchenyan** [comment]
6. Because multiple transfers are supported, the insufficient balance is indicated at the total amount below. This is not a bug.

**Comment by Danie0918** [comment]
7.Transactions here are submitted normally, so there is no need for restrictions. As for the reminder text, it doesn't need to be added in this UI version, because it is also designed to the page of Send, so it is recorded by my side for subsequent optimization.
