### ISSUE TITLE
Problems with New design for Neuron Multisig Address-search function

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#207]
1.In the same Multisig Address search box ，alias supports fuzzy search，but address does not.Maybe we can enhance the search  or add tips to users.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/fcceb80f-c6a9-41c7-9b2f-346b1c8903ac

**Comment by Danie0918** [comment]
Adding fuzzy search to the address is helpful and will reduce what the user has to type, and is recommended.

**Comment by silySuper** [comment]
Only  the second half  supports fuzzy  address search,considering that the differences between multisig addresses  are in the second half,the change is allowed.Verified.
