### ISSUE TITLE
new UI asset accounts issues 

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#208]
1.receive address should only copy icon

actual:
<img width="716" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/ddbe1047-9a4e-46b1-9697-3022b6e5e047">
UI:
<img width="657" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/283dca1a-5896-4ee2-be58-e3e482265348">

2. input should have placeholder hint
actual:
<img width="1248" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/13b0fdc3-0336-4a52-a83d-2b366e797bb3">
UI:
<img width="923" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/73660bb0-93ce-438c-b783-e3a1523228a0">

3. miscalculation of transaction costs
<img width="1164" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/bcfd97f1-1ef1-47a1-8b83-37b2228633f1">

4.  required tips always show up , it will block SUDT asset transactions(asset a to asset b ).

<img width="1005" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/03b0d0f7-51a7-4c2a-942b-d9bfe2a851fe">

**Comment by littleLip520** [comment]
5.CKB asset do transaction to normal receive address，occur Insufficient balance
<img width="1095" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/26523791/7f9a642a-ab1c-488c-8a47-b4144c3a3e2b">

**Comment by devchenyan** [comment]
Packaging for test is done in [5503265700](https://github.com/nervosnetwork/neuron/actions/runs/5503265700).

**Comment by silySuper** [comment]
1.实际效果：
Lost copy icon
<img width="676" alt="截屏2023-07-17 11 14 20" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/2bba86b7-868d-45fd-888b-792c5e3d3d94">
UI设计：
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/9d4f75a4-b4e3-4572-9cac-11818a3154ae)

2.Verified，pass
3.Verified，pass
4.Verified，pass
5.Verified，pass

**Comment by yanguoyu** [comment]
> 1.实际效果： Lost copy icon <img alt="截屏2023-07-17 11 14 20" width="676" src="https://user-images.githubusercontent.com/25971273/253847562-2bba86b7-868d-45fd-888b-792c5e3d3d94.png"> UI设计： ![image](https://user-images.githubusercontent.com/25971273/253895603-9d4f75a4-b4e3-4572-9cac-11818a3154ae.png)
> 
> 2.Verified，pass 3.Verified，pass 4.Verified，pass 5.Verified，pass

For the first question, reference to https://github.com/Magickbase/neuron-public-issues/issues/166#issuecomment-1617206975

**Comment by Danie0918** [comment]
1 is a UI error, ignore it.
