### ISSUE TITLE
the  102 CKB deposit  check can be walkaround if you  double click the checkbox

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/neuron-public-issues#209]
https://github.com/Magickbase/neuron-public-issues/assets/26523791/2d4f8c73-198a-4d20-bdf7-2ce8a500b1c1

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2772 also fixed this issue.

**Comment by silySuper** [comment]
Verified
