### ISSUE TITLE
Add retry and heartbeat detection for ckb and ckb-indexer process.

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#21]

**Comment by Keith-CY** [comment]
We may start this feature

**Comment by yanguoyu** [comment]
- [ ] http://localhost:8118
Use `get_tip` to test whether it's alive.
If there is no response at recent 10 seconds, call https://github.com/nervosnetwork/neuron/blob/85acab71accd9d44c669549aef2a1117dd14cc08/packages/neuron-wallet/src/services/indexer.ts#L131 to restart it.
- [ ] http://localhost:8114 when selected network's remote is `http://localhost:8114` and redist is ready
Use `get_tip_block_number ` to test whether it's alive.
If there is no response at recent 10 seconds, call https://github.com/nervosnetwork/neuron/blob/85acab71accd9d44c669549aef2a1117dd14cc08/packages/neuron-wallet/src/services/node.ts#L174 to restart it.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2422

**Comment by Cedar67** [comment]
Test Results: Verified.
verified environment: Windows OS
test case & results: https://github.com/nervosnetwork/neuron/pull/2422#pullrequestreview-1005880380
