### ISSUE TITLE
Add an action to update assumed valid target periodically

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#211]
The `CKB_NODE_ASSUME_VALID_TARGET` defined at https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env#L120 is used on launching the built-in CKB node to boost performance.

It's expected to be at least 7 days before the release day and was updated manually. It introduced a mental burden in the release workflow, so it's expected to be updated automatically by the CI.

The following work will be done:
1. add a script to fetch the hash of a block minted 1 day ago;
2. add a CI to run the script when a PR is opened from `rc/*` to `master,` and the update should open a new PR to the `rc/*`

It may take a long time to merge `rc/*` into `master` so that `assumed valid target` is more than 7 days before the release day, but it's acceptable IMO.

Or the script could be run on merge from `rc/*` to `master` and the commit is adopted on the `main` while the script sets 7 days before rather than 1 day before.

**Comment by yanguoyu** [comment]
1. Write a shell command to update `CKB_NODE_ASSUME_VALID_TARGET`. 
      1. Get the tip header block number, and get the block hash with (the header block number - 10000)
      2. Read the env file and update the `CKB_NODE_ASSUME_VALID_TARGET`
2. create an action to create PR to the `rc/*` branch
      1. trigger event: pull_request opened
      2. use https://github.com/technote-space/create-pr-action to create a PR to update the `assume valid target`

**Comment by Keith-CY** [comment]
>    1. Get the tip header block number, and get the block hash with (the header block number - 10000)

IMG, the rc-branch should be fully tested for a week, so the `tip block hash` could be set when the PR is open

> create an action to create PR to the rc/* branch

Does it mean trigger an action run when the PR from rc/* to main is opened

> Write a shell command

Personally a JavaScript script is preferred because it's easy for reviewers and maintainers, and JavaScript is supported in GitHub runner with https://github.com/actions/github-script

**Comment by yanguoyu** [comment]
> Does it mean trigger an action run when the PR from rc/* to main is opened

yes, but I believe the trigger event can be set as `ready-for-review` currently. After the pr is ready for review, it will merge soon.

> Personally a JavaScript script is preferred because it's easy for reviewers and maintainers, and JavaScript is supported in GitHub runner with https://github.com/actions/github-script

Javascript is also no problem, I will wrap the process into a npm command. Then we only need to `npm run update:valid:target` to change the local env file.

**Comment by Keith-CY** [comment]
> > Does it mean trigger an action run when the PR from rc/* to main is opened
> 
> yes, but I believe the trigger event can be set as `ready-for-review` currently. After the pr is ready for review, it will merge soon.
> 
> > Personally a JavaScript script is preferred because it's easy for reviewers and maintainers, and JavaScript is supported in GitHub runner with [actions/github-script](https://github.com/actions/github-script)
> 
> Javascript is also no problem, I will wrap the process into a npm command. Then we only need to `npm run update:valid:target` to change the local env file.

Triggered by `ready-for-review` is a good idea

**Comment by yanguoyu** [comment]
https://github.com/technote-space/create-pr-action not support `ready-for-review` event. So I will use other actions to achieve it.

- [X]  Change the local file.
- [ ]  Add and commit
- [ ] Create PR(Not yet started)

 I have found some action plugins to add and commit, but because of https://github.com/actions/runner/issues/667 
the commit could not be verified. So there are two ways to avoid this.
1. Refer to https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c, and we can use github script
2. Use crazy-max/ghaction-import-gpg@v2 to verify the commit, but it needs us to set the GPG to the environment.

Cause of we currently only update one file, I would prefer the first resolution.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2773

**Comment by Keith-CY** [comment]
The timing to update `assume valid target` is set `ready for review` on `master` branch, but `changelog` is expected to be updated at `rc/v*` branch. The `assume valid target` will be included in changelog, so it's better to update `assume valid target` on `rc/v*` branch

**Comment by yanguoyu** [comment]
> The timing to update `assume valid target` is set `ready for review` on `master` branch, but `changelog` is expected to be updated at `rc/v*` branch. The `assume valid target` will be included in changelog, so it's better to update `assume valid target` on `rc/v*` branch

How about when trigger on the create event or the push event on the `rc/v*` branch?

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2874
