### ISSUE TITLE
`Deposit all` doesn't work when the fee rate is updated

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#216]
https://github.com/Magickbase/neuron-public-issues/assets/7271329/ddccc967-f649-421b-9c04-42a3736591ce

The fee turns into 0 when fee rate is updated

**Comment by yanguoyu** [comment]
This issue may occur in the current interaction mode. Currently, when the deposit value change, Neuron will check whether the deposit value is bigger than the max deposit value, if so, the deposit value will change to the max deposit value, or else generate a transaction with the current deposit value.

### When this issue will occur:
At first, we enter a bigger value than the max deposit value, it will change to the max deposit value. But if the `suggestFeeRate` becomes less, the max deposit value will increase. Then generating a transaction with the last max deposit value will fail because the remaining ckb can not hold a cell.
It will generate success until the `suggestFeeRate` becomes bigger than the first `suggestFeeRate`.

I propose to add a max button to let the user set deposit all ckb, and when the user selects deposit all, the input will be disabled and the input value set as the max deposit value.
On the other hand, I propose the `Slide` component below the deposit input is used for changing the deposit percent but not the deposit value, then selecting 100% percent is the same as selecting deposit all.

@Danie0918 What do you think?

**Comment by Danie0918** [comment]
> @Danie0918 What do you think?

The main problem we have here is that the maximum deposit value no longer satisfies the current transaction conditions when the suggestedFeeRate changes. For this problem, you proposed point 2 optimization which I think can work, suggesting to optimize the sliding component for changing the deposit percentage, where the amount and fee of the input box changes dynamically and sums up to the set deposit percentage. The button for the maximum value is not necessary for the current interaction and can be left out.

**Comment by yanguoyu** [comment]
> > @Danie0918 What do you think?
> 
> The main problem we have here is that the maximum deposit value no longer satisfies the current transaction conditions when the suggestedFeeRate changes. For this problem, you proposed point 2 optimization which I think can work, suggesting to optimize the sliding component for changing the deposit percentage, where the amount and fee of the input box changes dynamically and sums up to the set deposit percentage. The button for the maximum value is not necessary for the current interaction and can be left out.

Then we will remove the logic that set the deposit to the max deposit value when the user enters over than the max deposit value, if they want to deposit all, they can slide the slider to 100%.
Is that what you mean?

**Comment by Danie0918** [comment]
> Then we will remove the logic that set the deposit to the max deposit value when the user enters over than the max deposit value, if they want to deposit all, they can slide the slider to 100%. Is that what you mean?

Yes, the suggestedFeeRate is out of the user's control, when the user chooses to drag to the maximum, the user's expectation is to deposit the maximum amount, so when the suggestedFeeRate changes the maximum entered should change accordingly to ensure that the transaction takes place.

**Comment by yanguoyu** [comment]
> > Then we will remove the logic that set the deposit to the max deposit value when the user enters over than the max deposit value, if they want to deposit all, they can slide the slider to 100%. Is that what you mean?
> 
> Yes, the suggestedFeeRate is out of the user's control, when the user chooses to drag to the maximum, the user's expectation is to deposit the maximum amount, so when the suggestedFeeRate changes the maximum entered should change accordingly to ensure that the transaction takes place.

Cool, I will resolve this issue with these steps:
1. If the deposit value is bigger than the max, warn the user that the amount is not enough, and they can deposit all by sliding the slider to 100%
2. Change the slider value to percent, if the slider value is 100%, means deposit all. So when the `suggestedFeeRate` changes, the deposit value will also change.
3. For other slider values, the deposit value will calculate by `slider value` * `max`, to keep the deposit value stable, the max deposit value here will calculate by stable `suggestedFeeRate`(2000).

@Keith-CY @Danie0918 @FrederLu

**Comment by yanguoyu** [comment]
> It should work.
> 
> But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?

Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s.
Do you mean we can fix the `fee rate`?

**Comment by Keith-CY** [comment]
> > It should work.
> > But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?
> 
> Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s. Do you mean we can fix the `fee rate`?

The solution comes from https://github.com/nervosnetwork/neuron/pull/2760 and I found it's easy and clear

**Comment by yanguoyu** [comment]
> > > It should work.
> > > But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?
> > 
> > 
> > Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s. Do you mean we can fix the `fee rate`?
> 
> The solution comes from [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) and I find it's easy and clear

They are different problems, https://github.com/nervosnetwork/neuron/pull/2760 fix the problem of when should we generate tx, but here is resolve how to generate tx.

**Comment by Keith-CY** [comment]
> > > > It should work.
> > > > But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?
> > > 
> > > 
> > > Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s. Do you mean we can fix the `fee rate`?
> > 
> > 
> > The solution comes from [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) and I find it's easy and clear
> 
> They are different problems, [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) fix the problem of when should we generate tx, but here is resolve how to generate tx.

Correct me if I'm wrong.

The problem is introduced by regenerating a transaction with a user-specified amount and a chain-specified fee rate by the following steps:

1. the max amount is specified by user, and a transaction is generated
2. a smaller fee rate is specified by the chain, and a transaction is failed to generate because less than 61 CKB will be left due to `Δfee_rate`

If step 2 is prohibited, there won't `Δfee_rate` and less than 61 CKB left. In this case, the transaction to send is only generated when the amount is updated manually, with the `suggested fee rate` at that time

**Comment by Keith-CY** [comment]
> > > > > It should work.
> > > > > But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?
> > > > 
> > > > 
> > > > Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s. Do you mean we can fix the `fee rate`?
> > > 
> > > 
> > > The solution comes from [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) and I find it's easy and clear
> > 
> > 
> > They are different problems, [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) fix the problem of when should we generate tx, but here is resolve how to generate tx.
> 
> Correct me if I'm wrong.
> 
> The problem is introduced by regenerating a transaction with a user-specified amount and a chain-specified fee rate by the following steps:
> 
> 1. the max amount is specified by user, and a transaction is generated
> 2. a smaller fee rate is specified by the chain, and a transaction is failed to generate because less than 61 CKB will be left due to `Δfee_rate`
> 
> If step 2 is prohibited, there won't `Δfee_rate` or less than 61 CKB left. In this case, the transaction to send is only generated when the amount is updated manually, with the `suggested fee rate` at that time

Simply to say, the `suggested fee rate` is cached when the dialog is open

**Comment by yanguoyu** [comment]
> > > > > > It should work.
> > > > > > But IMO it can be resolved simply by fixing the `fee rate` when the `amount` is set. Is this solution not enough for the case?
> > > > > 
> > > > > 
> > > > > Of cause, if the `fee rate` is fixed, there will be no problem. Currently, the `fee rate` will change every 30s. Do you mean we can fix the `fee rate`?
> > > > 
> > > > 
> > > > The solution comes from [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) and I find it's easy and clear
> > > 
> > > 
> > > They are different problems, [nervosnetwork/neuron#2760](https://github.com/nervosnetwork/neuron/pull/2760) fix the problem of when should we generate tx, but here is resolve how to generate tx.
> > 
> > 
> > Correct me if I'm wrong.
> > The problem is introduced by regenerating a transaction with a user-specified amount and a chain-specified fee rate by the following steps:
> > 
> > 1. the max amount is specified by user, and a transaction is generated
> > 2. a smaller fee rate is specified by the chain, and a transaction is failed to generate because less than 61 CKB will be left due to `Δfee_rate`
> > 
> > If step 2 is prohibited, there won't `Δfee_rate` or less than 61 CKB left. In this case, the transaction to send is only generated when the amount is updated manually, with the `suggested fee rate` at that time
> 
> Simply to say, the `suggested fee rate` is cached when the dialog is open and a transaction has been generated, until the `amount` is updated

Of cause, if the `fee rate` is fixed until users change the value, it also can resolve this issue. But it will change the original logic, is it reasonable? I'm not sure. 

@Danie0918 What do you think?

**Comment by yanguoyu** [comment]
On the other hand, it also happens on the send page, if the users select max to send, the max sends ckb will also change every 30s because the `fee rate` will change every 30s.

**Comment by Keith-CY** [comment]
> On the other hand, it also happens on the send page, if the users select max to send, the max sends ckb will also change every 30s because the `fee rate` will change every 30s.

Personal idea: a checkbox for `send all` is 100% clearer than the slider

**Comment by Danie0918** [comment]
Can you describe the rules and requirements here about suggestedFeeRate? I'm not sure that a fixed rate is consistent with the original design intent here. @yanguoyu

**Comment by yanguoyu** [comment]
> Can you describe the rules and requirements here about suggestedFeeRate? I'm not sure that a fixed rate is consistent with the original design intent here. @yanguoyu
> 
> In my opinion suggestedFeeRate should be dynamic to help close deals, then using a fixed rate here doesn't meet expectations.

`suggestedFeeRate` gets from the blockchain by rpc. It is used for users to let the tx broadcast easily, if the fee rate is small, the tx may broadcast slowly. Currently, the `suggestedFeeRate` will get from the rpc every 30s.

**Comment by Danie0918** [comment]
> > Can you describe the rules and requirements here about suggestedFeeRate? I'm not sure that a fixed rate is consistent with the original design intent here. @yanguoyu
> > In my opinion suggestedFeeRate should be dynamic to help close deals, then using a fixed rate here doesn't meet expectations.
> 
> `suggestedFeeRate` gets from the blockchain by rpc. It is used for users to let the tx broadcast easily, if the fee rate is small, the tx may broadcast slowly. Currently, the `suggestedFeeRate` will get from the rpc every 30s.
In that case, I'd recommend still using changing the logic here in Nervos DAO and Send to change dynamically when the maximum value is selected.

**Comment by yanguoyu** [comment]
So, what should we finally do? @Danie0918 @Keith-CY 

Add a max button to set max, and keep the dynamic fee when the users select deposit max?

**Comment by Danie0918** [comment]
> So, what should we finally do? @Danie0918 @Keith-CY
> 
> Add a max button to set max, and keep the dynamic fee when the users select deposit max?

It's better to adjust the logic of the slider, the current interaction already meets the needs of the maximum value. Dynamically change the amount when the slider reaches the maximum. @Keith-CY

**Comment by Keith-CY** [comment]
> > So, what should we finally do? @Danie0918 @Keith-CY
> > Add a max button to set max, and keep the dynamic fee when the users select deposit max?
> 
> It's better to adjust the logic of the slider, the current interaction already meets the needs of the maximum value. Dynamically change the amount when the slider reaches the maximum. @Keith-CY

LGTM

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2772
