### ISSUE TITLE
Supporting cell management

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#218]
This issue comes from https://github.com/Magickbase/neuron-public-issues/issues/56#issuecomment-1626710809

---

【Cell Management】This page will display all live cells and allows users to manage them.

1. The entry will be placed next to the balance under the overview page, where the balance still shows the full balance and needs to be prompted when there is a locked balance, click to view to enter the cell management page.
2. The Cell Management page displays the number and list of live cells and allows for the management of these cells.
	- List Title：Display date, type, amount and status and support sorting.
	- Operation:Support view details, open in browser, lock/unlock and spend.
	- Batch operation：The user can select the cells to be manipulated by clicking on the entry or select all cells for batch manipulation.
3. Locking or unlocking the cell requires verification of the wallet password.
4. The spend cell will jump to the send page and bring in the full amount (including fees).

![cell_management](https://github.com/Magickbase/neuron-public-issues/assets/122437870/9a994960-49f1-4350-8f8c-072c210a1ee6)

**Comment by Keith-CY** [comment]
> Display date, type, amount and status and support sorting

Please add the definition of `type`, `amount`

**Comment by Keith-CY** [comment]
A `description` field could be added to annotate a cell, similar to description of an address

**Comment by Keith-CY** [comment]
**Support view details** leads to a window of transaction, which is a bit confusing and indirect.

What if show the detail of the cell, including `outpoint`, `capacity`, `lock script`, `type script`, `data`, and the transaction can be navigated by clicking `outpoint`

**Comment by yanguoyu** [comment]
> Locking or unlocking the cell requires verification of the wallet password.

It's necessary to input the password when locking or unlocking because the result is only for the local wallet.

**Comment by yanguoyu** [comment]
1. Add a table `cell_local_info` to save the cell description and lock status
2. Add an API to get current wallet live cells from the `output` table
3. Add an API to save or update `cell_local_info`
4. Change the API `generate` tx to use the appointed live cell.

**Comment by Danie0918** [comment]
> > Locking or unlocking the cell requires verification of the wallet password.
> 
> It's necessary to input the password when locking or unlocking because the result is only for the local wallet.
> 
> > The spend cell will jump to the send page and bring in the full amount (including fees).
> 
> Can this action use other cells? @Danie0918

This one operates on selected cells and does not contain additional cells.

**Comment by yanguoyu** [comment]
> > Locking or unlocking the cell requires verification of the wallet password.
> 
> It's necessary to input the password when locking or unlocking because the result is only for the local wallet.

What do you think about this? @Danie0918

**Comment by Danie0918** [comment]
> > > Locking or unlocking the cell requires verification of the wallet password.
> > 
> > 
> > It's necessary to input the password when locking or unlocking because the result is only for the local wallet.
> 
> What do you think about this? @Danie0918

That's how it's currently designed, what's the problem?

**Comment by yanguoyu** [comment]
> > > > Locking or unlocking the cell requires verification of the wallet password.
> > > 
> > > 
> > > It's necessary to input the password when locking or unlocking because the result is only for the local wallet.
> > 
> > 
> > What do you think about this? @Danie0918
> 
> That's how it's currently designed, what's the problem?

My mistake, necessary -> unnecessary.

**Comment by Danie0918** [comment]
> 

For unlocking and locking we generally consider it to be a sensitive operation that will have an impact on the user's subsequent use of the balance, plus password verification to ensure that it is not a misuse. In addition, when it comes to the operation of user's assets, it is better to have a password verification to show the security of the software.

Besides, there are batch operations offered here, so even unlocking and unlocking multiple cells only requires one verification, which is not very burdensome for the user.

**Comment by yanguoyu** [comment]
> > 
> 
> For unlocking and locking we generally consider it to be a sensitive operation that will have an impact on the user's subsequent use of the balance, plus password verification to ensure that it is not a misuse. In addition, when it comes to the operation of user's assets, it is better to have a password verification to show the security of the software.
> 
> Besides, there are batch operations offered here, so even unlocking and unlocking multiple cells only requires one verification, which is not very burdensome for the user.

The action only affects local data, but not chain data. Maybe we can simply add a confirm dialog but not enter a password?

**Comment by Danie0918** [comment]
> > > 
> > 
> > 
> > For unlocking and locking we generally consider it to be a sensitive operation that will have an impact on the user's subsequent use of the balance, plus password verification to ensure that it is not a misuse. In addition, when it comes to the operation of user's assets, it is better to have a password verification to show the security of the software.
> > Besides, there are batch operations offered here, so even unlocking and unlocking multiple cells only requires one verification, which is not very burdensome for the user.
> 
> The action only affects local data, but not chain data. Maybe we can simply add a confirm dialog but not enter a password?

I understand what do you mean, but when it comes to operations involving user assets, I'd still recommend adding password verification. Although this is only for the local effect, but the user software has an impact on the use, it is best to need to verify that the operation is for my own.

**Comment by yanguoyu** [comment]
> > > > 
> > > 
> > > 
> > > For unlocking and locking we generally consider it to be a sensitive operation that will have an impact on the user's subsequent use of the balance, plus password verification to ensure that it is not a misuse. In addition, when it comes to the operation of user's assets, it is better to have a password verification to show the security of the software.
> > > Besides, there are batch operations offered here, so even unlocking and unlocking multiple cells only requires one verification, which is not very burdensome for the user.
> > 
> > 
> > The action only affects local data, but not chain data. Maybe we can simply add a confirm dialog but not enter a password?
> 
> I understand what do you mean, but when it comes to operations involving user assets, I'd still recommend adding password verification. Although this is only for the local effect, but the user software has an impact on the use, it is best to need to verify that the operation is for my own.

Once enter the password, users may think wheter this action will effect their assets. By the way, verify that the operation is for my own does not need password. We can check whether the lock script is owner the current wallet.

**Comment by Danie0918** [comment]
> Once enter the password, users may think wheter this action will effect their assets. By the way, verify that the operation is for my own does not need password. We can check whether the lock script is owner the current wallet.

'Once enter the password, users may think wheter this action will effect their assets. 'This is really a point to consider as well. But for passwords, can we use it as a kind of easy authentication for web2 user habits instead of treating it as a very serious security measure.

**Comment by yanguoyu** [comment]
Does the cell manage page need to show `multisig / locktime` or `cheque` cells? Because these cells can not spent before `unlock` or `claim`. So `lock`, `unlock`, and `spent` actions are useless for these cells. @Danie0918

**Comment by Danie0918** [comment]
> Does the cell manage page need to show `multisig / locktime` or `cheque` cells? Because these cells can not spent before `unlock` or `claim`. So `lock`, `unlock`, and `spent` actions are useless for these cells. @Danie0918

Cells need to be displayed, but selection and further actions such as lock, unlock, and spent  actions are not supported.

**Comment by Danie0918** [comment]
> Does the cell manage page need to show `multisig / locktime` or `cheque` cells? Because these cells can not spent before `unlock` or `claim`. So `lock`, `unlock`, and `spent` actions are useless for these cells. @Danie0918

![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/14620f06-e3b5-44b6-87e2-31f612829410)

For this case, the cell can't be selected and spent, it only offers to view the details, so I plan to add an icon hint to make it easier for the user to understand the situation.

Can you help me add what I might meet? I need to provide the corresponding text to prompt the user. If there is already existing copy here, please provide it. @yanguoyu

**Comment by yanguoyu** [comment]
> Can you help me add what I might meet?

1. Cheque cells should be claimed before using it.
2. We should wait for the end time to unlock the multisig / locktime cells.
3. DAO cells should be withdrawn before using it.
4. `The spend cell will jump to the send page and bring in the full amount (including fees).` Will this action only support sending ckb? If so, for sudt cells, they are better to send and receive at the asset account page. Otherwise, it will become complex with sending sudt and ckb at the same time.

If I think of other assets, I will append to here.

**Comment by Danie0918** [comment]
The UI has been updated. @yanguoyu 
URL:[https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=22441-10468&mode=design](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=22441-10468&mode=design)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2859
