### ISSUE TITLE
Abnormal blank page style

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#223]
Empty pages for custom assets are not working as expected.
<img width="1131" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/285b2172-0edc-4a48-a012-8933e051afcb">

@Kirl70 Does the empty page use a style similar to the one below? What is the default prompt text?
<img width="832" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/96a404f8-749c-4291-a165-bf8c44e65490">

**Comment by Kirl70** [comment]
> Empty pages for custom assets are not working as expected. <img alt="image" width="1131" src="https://user-images.githubusercontent.com/25676576/253855734-285b2172-0edc-4a48-a012-8933e051afcb.png">
> 
> @Kirl70 Does the empty page use a style similar to the one below? What is the default prompt text? <img alt="image" width="832" src="https://user-images.githubusercontent.com/25676576/253856467-96a404f8-749c-4291-a165-bf8c44e65490.png">

Yes, the empty pages should use a consistent style, and the text can be the same as the old version's prompt text.
<img width="1197" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/31a109f8-4b2c-423c-bccd-ec0a826d691c">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by FrederLu** [comment]
Verified.
