### ISSUE TITLE
The button style on the page is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#224]
1、The default color of the view details button is abnormal, and it is necessary to distinguish the front and rear of the mouse hover, and the current style does not distinguish by default.
<img width="990" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8af3b91e-dab0-403f-a27e-c66304cbaec2">
<img width="1191" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/896f8ac4-592c-4d6c-9367-0bd2ce0c5673">

---
2、When the asset button is `unrecognized asset` and `locked`, the prompt information is missing when the mouse hovers.
<img width="431" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/04f44275-f6e0-4418-9a98-df8eb459ae38">
<img width="425" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/dddbbe75-07cb-438e-a024-f2dc98b47c2b">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by FrederLu** [comment]
Verified.
