### ISSUE TITLE
The page is abnormal when switching pagination.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#225]
When you click on the last page of a tab (switch/jump to the last page), you should still stay on the current page, and now you will jump to the overview page.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/eacfc887-f92d-4d8b-8732-a51acd7cbb85

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by FrederLu** [comment]
Verified.
