### ISSUE TITLE
Custom assets page abnormal problem.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#228]
1、After clicking on the first line of information, it is found that the dividing line between the first line and the second line has been removed.
<img width="993" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ce84b031-2976-473d-9c8e-7727c01fbfa9">
<img width="995" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f878bf2f-6669-4b99-a21b-9002600397d0">

---
2、When receiving assets, the `Confirm` button cannot be clicked after entering the account name in the account details.
<img width="961" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f9b28dc7-a5f3-4a13-baec-a66aa96edfd9">
<img width="685" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/05bac077-b33b-4e32-8ecd-bd7be224a9a4">

---
3、The color of the border does not match the UI.
<img width="850" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e51050d0-eed7-4939-80ee-1915bec8514d">
<img width="1132" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d35b16b4-79a7-447b-983e-fc57f6040220">

---
4、Refer to the UI draft to modify the color of the cursor when entering, and the prompt text is missing when no information is entered.
<img width="871" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d6a83810-96e0-4d6b-b876-9c245df01596">
<img width="1416" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b4c0aaf4-4674-446f-a49d-ad148adf5a1c">

<img width="702" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e298c696-8395-45b2-90ca-31e2fe63742b">
<img width="685" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/406fd7ca-28d9-4dbb-97ef-14b0a5b2c325">
<img width="680" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e89bc57b-6d55-4d8a-999d-94005f99c29f">
<img width="684" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b190e821-df25-42de-8d35-aad61db3cf3c">

---
5、After performing operations on custom assets (claim/migration/withdraw/send),page do not need to jump to the transaction history page, and stay on the current custom asset page and give prompts based on the above specific operations.

<img width="750" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ed5cd78c-2dbd-4931-ab54-0c219019b5ec">
<img width="893" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/139d195f-bae2-4bf0-8300-49a2fd3b1b47">

---
6、There are 3 problems in the video:
1. Remove the `*` after the title in the interface of `convert to new sUDT asset account` and `transfer to sUDT account`;
2. Selecting the token ID information in `Convert to a new sUDT asset account` should not be able to slide left and right, and it is very easy for the ID not to be displayed abnormally;
3. The prompt message of too long account information in `Convert to a new sUDT asset account` does not match the UI.
<img width="979" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/428028ce-9be0-4434-98aa-2e40f31bb6f9">
<img width="949" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c0176a48-0007-4b7f-9b0b-2bd4e778373b">

https://github.com/Magickbase/neuron-public-issues/assets/25676576/dfcd8e0d-9131-45f1-a498-8425aaf6a0c4

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by FrederLu** [comment]
> [nervosnetwork/neuron#2791](https://github.com/nervosnetwork/neuron/pull/2791)

>---
>5、After performing operations on custom assets (claim/migration/withdraw/send),page do not need to jump to the transaction history page, and stay on the current custom asset page and give prompts based on the above specific operations.
><img width="750" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ed5cd78c-2dbd-4931-ab54-0c219019b5ec">
><img width="893" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/139d195f-bae2-4bf0-8300-49a2fd3b1b47">

No. 5 still exists

---
1、There is no need to display the `*` symbol here.
<img width="679" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/719ea26d-4206-435e-9aa4-14f7f75caa17">

2、The default tooltip is missing from the input box.
<img width="703" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/14b98c71-2043-4817-ade4-d009fd4606bc">

**Comment by FrederLu** [comment]
Verified.
