### ISSUE TITLE
Transfer to sUDT account Style issue.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#229]
1、The default style of the address box is abnormal, please refer to the UI style modification.
<img width="732" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/04ba7e1f-abf0-4ba5-b0f9-7613219b95dc">
<img width="938" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8bfda60c-2b62-4744-9e30-a9fa8d8532d3">

---
2、When the information in the input box is abnormal, the missing color of the input box changes, and the spacing and font of the abnormal prompt information are too small, refer to the UI style.
<img width="680" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8d96e50f-a5f4-47d0-b0c7-631bbf2b082d">
<img width="1006" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ae3caba5-f3cc-4589-8471-a962882dd26a">

---
3、If there is an abnormal prompt on the interface, after closing it, it should restore the default (clear the abnormal prompt) next time you open it. Now if you need to switch the left column in the video to clear the prompt.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/9d45114d-3d83-4670-a313-baa3c067ccda

---
4、When one bit is deleted on the basis of the normal address, the prompt information displays abnormality. It is expected to display `Please enter a testnet address` (note: this prompt is only used for the test network, and the test network information cannot be displayed on the main network).
<img width="679" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/32cb796a-4bfa-4f34-9179-c8c902d3ac49">

---
5、After opening the wallet for the first time migration, the `Transfer to sUDT account` pop-up window for entering the password cannot be invoked.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/19ad4d4a-6067-4328-b94f-67b4486b1c31

<img width="720" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/13e355be-013c-4784-8afb-15e64bdfd47c">
<img width="1008" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fd747d75-7e31-4812-bcc7-25a72e72bd4a">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by FrederLu** [comment]
> [nervosnetwork/neuron#2791](https://github.com/nervosnetwork/neuron/pull/2791)

>---
>3、If there is an abnormal prompt on the interface, after closing it, it should restore the default (clear the abnormal prompt) next time you open it. Now if you need to switch the left column in the video to clear the prompt.

>https://github.com/Magickbase/neuron-public-issues/assets/25676576/9d45114d-3d83-4670-a313-baa3c067ccda

The problem still exists.

**Comment by devchenyan** [comment]
Packaging for test is done in [5760840604](https://github.com/nervosnetwork/neuron/actions/runs/5760840604).

**Comment by FrederLu** [comment]
> fixed: [nervosnetwork/neuron#2791](https://github.com/nervosnetwork/neuron/pull/2791)
> 
> Packaging for test is done in [5760840604](https://github.com/nervosnetwork/neuron/actions/runs/5760840604).

Verified.
