### ISSUE TITLE
The style of NFT turning into a pop-up window is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#230]
<img width="1240" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5665ff0d-e289-40c3-a234-5dafd03dbdf2">
<img width="1066" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5a5b9238-1ecc-4962-8551-049510761ae0">

**Comment by devchenyan** [comment]
Packaging for test is done in [5654779120](https://github.com/nervosnetwork/neuron/actions/runs/5654779120)

**Comment by FrederLu** [comment]
> Packaging for test is done in [5654779120](https://github.com/nervosnetwork/neuron/actions/runs/5654779120)

For the address display style, please refer to the UI style.
<img width="740" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/70489a7e-df4c-46e8-9332-ffa080af1b9d">
<img width="1023" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/760d5ef1-7ef0-4fe0-96b7-ba64672db11c">

**Comment by devchenyan** [comment]
> > Packaging for test is done in [5654779120](https://github.com/nervosnetwork/neuron/actions/runs/5654779120)
> 
> For the address display style, please refer to the UI style. <img alt="image" width="740" src="https://user-images.githubusercontent.com/25676576/256463751-70489a7e-df4c-46e8-9332-ffa080af1b9d.png"> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/25676576/256463966-760d5ef1-7ef0-4fe0-96b7-ba64672db11c.png">

It's not a bug. For the sake of interactivity and friendliness, I've communicated with the UI designer that I don't need to use the ellipsis display.

**Comment by FrederLu** [comment]
> > > Packaging for test is done in [5654779120](https://github.com/nervosnetwork/neuron/actions/runs/5654779120)
> > 
> > 
> > For the address display style, please refer to the UI style. <img alt="image" width="740" src="https://user-images.githubusercontent.com/25676576/256463751-70489a7e-df4c-46e8-9332-ffa080af1b9d.png"> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/25676576/256463966-760d5ef1-7ef0-4fe0-96b7-ba64672db11c.png">
> 
> It's not a bug. For the sake of interactivity and friendliness, I've communicated with the UI designer that I don't need to use the ellipsis display.

Well, just confirm that the style can be displayed in multiple lines.
Problem verification passed.
