### ISSUE TITLE
There is abnormal data when the wallet is initialized.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#232]
When the wallet is opened and initialized (switching nodes), abnormal negative data should not appear in the recent balance sheet status column.
<img width="1194" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/61c924b3-950a-44a3-a5b4-0bc05d9668ed">

**Comment by Danie0918** [comment]
Only the style in the confirmation needs to be preserved, the difference in block height from the transaction does not need to be shown to the user.

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2785

**Comment by FrederLu** [comment]
When the wallet is initialized, the `confirmation count` needs to be hidden, but when there are normal transaction confirmations, the `confirmation count` is missing in the `overview` and `transaction history`.
Currently, the `confirmation times` in all scenarios are hidden.

![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/ecac49f1-994e-4048-a63f-1211def8e200)


![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/aa5ca32a-c55b-47fc-bc60-1cd61dfa8bb9)


![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/55c45a0e-84d4-4056-b116-6637043cb12e)


![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/bc8f6dd7-abd3-49c7-a5d9-5f315ad69f2a)

From the screenshot above, you can see the information of `Confirmation Times` in the transaction details of `Confirming`.

**Comment by devchenyan** [comment]
fixed: https://github.com/nervosnetwork/neuron/pull/2785

Packaging for test is done in [5760975779](https://github.com/nervosnetwork/neuron/actions/runs/5760975779).

**Comment by FrederLu** [comment]
> fixed: [nervosnetwork/neuron#2785](https://github.com/nervosnetwork/neuron/pull/2785)
> 
> Packaging for test is done in [5760975779](https://github.com/nervosnetwork/neuron/actions/runs/5760975779).

Verified.
