### ISSUE TITLE
Neuron app has flash quit when  click pop window

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#233]
When top right corner shows is connecting light node，click  one record in overview page，then pop up error window，click this window，the app quit.May be when we click this error window ,let
 node continue to synchronize  is better. 

https://github.com/Magickbase/neuron-public-issues/assets/25971273/1658b732-9905-471c-8b97-8558cf976b96

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2785

**Comment by silySuper** [comment]
Verified
