### ISSUE TITLE
The prompt style needs to be updated.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#234]
The exception prompt style is still the previous style and needs to be updated.
<img width="800" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d389ba9b-0481-48c3-a8f9-480e47a804db">
<img width="1001" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/191cdc59-7e2e-49fc-84c8-84042f6f8ab8">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2785

**Comment by FrederLu** [comment]
> 1、This pop-up can be left unchanged after communicating with @Danie0918 2、fixed: [nervosnetwork/neuron#2785](https://github.com/nervosnetwork/neuron/pull/2785)

Verified.
