### ISSUE TITLE
The first sync is missing notification.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#235]
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1457-10785&mode=design&t=18qLIEx3AulDAxkp-0
Missing prompt for reinstalling after syncing or uninstalling wallet for the first time.
<img width="890" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e4f1da72-7b24-4df9-a40c-c7eb5556c46a">

**Comment by Keith-CY** [comment]
I found the storage requirement `30GB` is out of date, it's about 53GB now, and we may add a github action to update it periodically

**Comment by Danie0918** [comment]
Will be fixed in #255
