### ISSUE TITLE
In send page,when send max balance,only chosed unit price shows fee

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#237]
In send page,when send max balance,only chosed unit price shows fee,others show 0 actually. In expect,others show the calculated cost.
<img width="1109" alt="截屏2023-07-25 15 55 55" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/290ceb4e-c691-41ea-89ea-31e24ca640b4">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2789

**Comment by silySuper** [comment]
Verified
