### ISSUE TITLE
Transaction details style modification.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#239]
The address copy style in the transaction detail input/output needs to be modified, and the style can refer to the copy style of the receiving address. Note that there are 2 entries for transaction details (overview and transaction history).
<img width="995" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/32a3e1f4-443d-4049-860d-cb69021e9b99">
<img width="972" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e8298d43-dcba-49dd-88f7-3b7757c6614d">
<img width="979" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/0ff93ed6-e203-4b22-b840-530633344e60">
<img width="981" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/726f8883-5fa2-41db-acad-f0ee495d1966">

UI：
<img width="885" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/4e1f7abe-485e-414a-889f-4472c4d8c7d2">

---
The copy icon is missing after the transaction hash in the basic information, and the icon also needs to be overwritten when copying the hash.
<img width="1424" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6ce1db47-d991-45a0-8fb5-6b45018e059f">
<img width="702" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8f475f70-1b54-4c35-8738-203dbbd46fbd">

---
Only numbers are hidden, `CKB` still needs to be displayed.
<img width="909" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/42dc7b04-1677-40a7-a591-7e678a13265e">
<img width="701" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/8fadf026-2dd4-4e28-b3db-9b9f75b6acaa">

---
The color change style is missing at the hover to the logo.
<img width="959" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9ba5c9e0-8ea8-4efe-8d19-2a4c40858881">
<img width="819" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d6d8b5ac-e271-4177-94fa-47817ef852fb">

---
The copy style at the footstep lock needs to be modified to remove the overwriting copy style:

1. Add a copy button at the corresponding position, and the mouse style changes when hovering;
2. After clicking, the information will be reproduced and there will be a prompt message at the top;
<img width="1291" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/76f7d74e-b2db-47c1-9ba1-4e36c14b48d5">
<img width="904" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/aa7f6033-4e3d-4df5-9390-388a10b9c60d">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2793

**Comment by FrederLu** [comment]
> [nervosnetwork/neuron#2793](https://github.com/nervosnetwork/neuron/pull/2793)
> The copy style at the footstep lock needs to be modified to remove the overwriting copy style:
       1、Add a copy button at the corresponding position, and the mouse style changes when hovering;
       2、After clicking, the information will be reproduced and there will be a prompt message at the top;

1、Now the copy button is added, but the interaction while copying is not as expected.
<img width="724" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/512a4728-315f-45e0-9e7f-897dfa70abbb">
<img width="767" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ae26df6e-94e8-43a6-8ddb-3f1cbea88bb3">

>The address copy style in the transaction detail input/output needs to be modified, and the style can refer to the copy style of the receiving address. Note that there are 2 entries for transaction details (overview and transaction history).

2、This problem still exists. It was possible to copy before, but now it cannot be copied.
Here is the copied style that needs to be modified.
<img width="989" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b20a3a4d-9af5-456a-8935-357fb6357067">

**Comment by yanguoyu** [comment]
These may be fixed in https://github.com/nervosnetwork/neuron/pull/2795. I will check again.

**Comment by devchenyan** [comment]
Here's the fix for the problem on page 【History Detail】, not page 【Nervos DAO / Transaction Detail】

**Comment by FrederLu** [comment]
> Here's the fix for the problem on page 【History Detail】, not page 【Nervos DAO / Transaction Detail】

Ok, the transaction details are all grouped together, and we will deal with this issue together after DAO verification.

**Comment by FrederLu** [comment]
Verified.
