### ISSUE TITLE
Styling issues on the receive page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#242]
<img width="971" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1b0d3798-4576-4fcb-a2ad-64ad7b28504b">

1. The center of the prompt icon needs to be aligned with the center of the first line of text；
2. The edit icon for notes should not be partially obscured when the window is reduced；
3. After clicking the `Hide` button, CKB does not need to be displayed in a new line, and it can be displayed in parallel with the amount；

<img width="927" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b0cc6cd5-f11f-4d92-a8a0-4da715e99eb6">
<img width="744" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/de0c51c4-71d1-417e-b393-26ea2de5bbc2">

---
The style of the receiving address of the hardware wallet is abnormal.
<img width="986" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1421c3bc-9f02-4b4b-be69-52bd84e7e197">
<img width="764" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/be00b2b1-051b-4b5a-bd8e-e220baa646f3">

---
<img width="710" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c6edfb0d-4896-4aba-a2a0-ee20719bdd40">
<img width="715" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f661f059-7378-4d3a-9d62-24f72ef20d6a">
<img width="712" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/ff8edecd-bd32-4246-bfce-195a11c18548">
<img width="1232" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6c06d687-1c1c-4cbf-8ba7-e3c2eddb0d6b">

1. Hash briefly displays style reference UI；
2. The center of the prompt icon is consistent with the center of the following text;
3. For prompt copy, please refer to UI copy;
4. After the verification is passed, the button copy needs to be changed;
5. The font color needs to be `#333333`;

<img width="622" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/3705f0ce-1aa6-4d78-a11b-4697b8657d6f">
<img width="548" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/491cc29f-c2ba-4c11-acf0-fccfef7bba0f">

**Comment by yanguoyu** [comment]
> ![image](https://github.com/Magickbase/neuron-public-issues/assets/12881040/d8b1e2f5-9d35-4832-be10-b7ad175893e0)

I don't know where the unexpected is in this image.

**Comment by yanguoyu** [comment]
For code reuse, I fixed it at https://github.com/nervosnetwork/neuron/pull/2795.

**Comment by FrederLu** [comment]
Verified.
