### ISSUE TITLE
Styling Issues on Transaction History Page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#243]
<img width="992" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6b39f086-e874-4bce-82f9-c34a26c764b7">

1. The wallet name is too long and lacks abbreviated style, and lacks hover style (font color changes, hover shows complete information)；
2. The right margin of the "Action" text is too small；

UI：
<img width="755" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/f8550c3b-9c54-46ba-9599-31c9e6d97636">
<img width="748" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2db88845-a938-4781-b002-6f6d517f4c75">

---
Missing expand/collapse effect after click area.
<img width="970" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9220a418-5b29-4766-9798-b6b7b05fd472">

---
After the amount is hidden, there is no longer a copy function.
<img width="962" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/53ed20c6-f02e-4536-9a00-e96a24b01936">

---
The interface data displayed abnormally before synchronizing data, resulting in abnormal layout information.
<img width="965" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9db6e398-9f21-4392-8a13-58e33f4f6b73">

---
https://github.com/Magickbase/neuron-public-issues/assets/25676576/7dc0e8ab-254e-4e7f-8128-81ebd7972fdb

<img width="919" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e6753bf5-7302-4ee0-975b-3cb6518b5c1c">
The font color does not change to `#00C891`  when there are 2 mouse hovers in the video.

---
The coverage of the hover transaction hash is too long, as long as overwritten the copy icon.
<img width="958" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/99c492b6-9611-4a60-9e20-849cbfd311e8">
<img width="966" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fd6303c3-2154-4df9-a795-979a4da7e0f3">

**Comment by FrederLu** [comment]
> 

<img width="715" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/a190cd39-738d-4987-b4c9-f3031d5eb182">

@Kirl70 
Does it stay 8-bit visually through the UI?

**Comment by Kirl70** [comment]
Yes, to ensure that different transaction types are fully displayed, it's best to abbreviate the wallet name when the minimum width is reached, showing only the first 8 characters.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2797

**Comment by FrederLu** [comment]
There is a clickable effect when the mouse hovers the arrow, but there is no effect when the mouse is clicked.
<img width="968" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/48cea24b-3573-45b4-8966-650d08547fdb">
<img width="954" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1c833325-3b62-4749-8d0a-f45c59abbdd5">

**Comment by yanguoyu** [comment]
> There is a clickable effect when the mouse hovers the arrow, but there is no effect when the mouse is clicked. <img alt="image" width="968" src="https://user-images.githubusercontent.com/25676576/258391115-48cea24b-3573-45b4-8966-650d08547fdb.png"> <img alt="image" width="954" src="https://user-images.githubusercontent.com/25676576/258391263-1c833325-3b62-4749-8d0a-f45c59abbdd5.png">

Fixed

**Comment by FrederLu** [comment]
Verified.
