### ISSUE TITLE
Problems with New design for Neuron asset accounts-tips and UI bugs

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#244]
1.In accounts detail pop up window，when account name is larger than 16 chars,the tip is not same with new UI design document.The problem also in create account page.
<img width="674" alt="截屏2023-07-26 11 04 41" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d20cf8d1-e620-4fae-98e9-fe9fd8ca36c4">

2.When accounts detail are edited successfully ,new UI  requires to pop  operation successful tip.But it does not have.

actual:

https://github.com/Magickbase/neuron-public-issues/assets/25971273/347e6576-b609-46a8-a82b-f1e53e7df997

UI document:
<img width="954" alt="截屏2023-07-26 11 07 41" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d8d89df6-5f34-40ba-96bd-183024c80c6b">

3.When create account successfully ,new UI  requires to pop  operation successful tip.But it does not have.
actual:

Uploading 屏幕录制2023-07-26 11.13.04.mov…

UI document:

<img width="885" alt="截屏2023-07-26 15 42 40" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/e6aba8c8-d541-408d-83e1-9fcb54ad6bfd">

4.When the decimal place is 31  in account detail,and the account has tokens.
A.UI number shows abnormal.
<img width="1082" alt="截屏2023-07-26 15 47 52" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/1a143e80-f614-401a-9b65-8f1e92089ddb">
B.delete button is lost
<img width="683" alt="截屏2023-07-26 11 43 57" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/97c43185-fb15-4a24-a2a7-a8a536e47086">

**Comment by devchenyan** [comment]
4-B:
The token type needs to be CKB or the account balance needs to be 0 for the delete button to be displayed.

like: `isCKB || balance === 0`

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2791

**Comment by silySuper** [comment]
1.Verified
2.Accounts detail  edit can not be confirmed .

https://github.com/Magickbase/neuron-public-issues/assets/25971273/17d50cbb-4730-4dc4-ae57-f74fc615d57e

3.New account can not be created.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/cabe322f-ea08-4e2a-b6e2-b1a4096a068d


4.Verified

**Comment by devchenyan** [comment]
2、3 were fixed with https://github.com/Magickbase/neuron-public-issues/issues/228.

Packaging for test is done in [5750138599](https://github.com/nervosnetwork/neuron/actions/runs/5750138599).

**Comment by silySuper** [comment]
2.Verified
3.When is creating account,it pop up create account successfully.In expect,the tip need show when create account is finished.


https://github.com/Magickbase/neuron-public-issues/assets/25971273/0c58830b-026f-425d-813c-bb51688b7a08

**Comment by devchenyan** [comment]
Packaging for test is done in [5760840604](https://github.com/nervosnetwork/neuron/actions/runs/5760840604).

**Comment by silySuper** [comment]
Verified.
