### ISSUE TITLE
In transaction history detail page,sudt records copy balance to pages  shows NaN.

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#245]
1.sudt record copy balance to pages shows NaN.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/3854b863-0530-4de4-8390-ebc920ad9900

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2785

**Comment by silySuper** [comment]
The data copied is not  intact.


https://github.com/Magickbase/neuron-public-issues/assets/25971273/cd31b2da-015c-4735-81c1-a4ae4dba0c45

**Comment by devchenyan** [comment]
fixed: https://github.com/nervosnetwork/neuron/pull/2785

Packaging for test is done in [5760975779](https://github.com/nervosnetwork/neuron/actions/runs/5760975779).

**Comment by silySuper** [comment]
Packaging for test is done in [5760975779] has fixed NaN problem，but 31 number shows abnormal again.

<img width="1059" alt="截屏2023-08-04 18 52 19" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/f66bb774-e57f-4542-92cc-b655effe673f">
