### ISSUE TITLE
Nervos Dao page style issue.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#246]
When the white background is selected, the font color of `completed` is abnormal when it is not selected; similarly, when `deposits` is not selected, the font needs to be `#8DA394`.
<img width="669" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/beebbe21-2a90-44c3-b70f-a98d5aff730e">
<img width="439" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/12a4eb3d-3943-44fc-9f5e-40d5babd8f5b">
UI：
<img width="605" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/cf6a4584-3abd-4568-a6e4-5cd85a68a225">

---
Replication should not work when CKB data is hidden.
<img width="1006" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fde53c55-9e60-447e-b627-7020f1cf3227">

---
When the mouse hover screenshots 3, the mouse style needs to be replaced with a hand like the UI.
<img width="1023" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/70fb8747-5483-4b5b-a3a9-7a18d3a240b5">

---
Copywriting needs to refer to UI modification.
<img width="1149" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c6b74907-43f0-40f6-9eec-955aa0addf5b">
UI：
<img width="485" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e87d28a9-7bf5-45c3-a3d4-087416d421be">

---
Button copywriting needs to refer to UI modification.
<img width="590" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/4d5a3e8c-e834-4695-85ae-c5eec7a6d71d">
<img width="763" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/787fdbf8-c38b-4cfc-a270-dafbb2c3eddb">

---
The style of the transaction details page is missing. Note that both `deposites`  `unlocked` and `withdrawn` need to be modified.

https://github.com/Magickbase/neuron-public-issues/assets/25676576/51aa0c2b-79ce-446f-89ef-0a5493107d77

<img width="995" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/a3f254a8-e608-427f-bff3-d17bf0c0dbe4">

UI link
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1164-11677&mode=design&t=CZ4Kyc3D1qlJeJRH-0

---
The copy style at the footstep lock needs to be modified to remove the overwriting copy style:

1. Add a copy button at the corresponding position, and the mouse style changes when hovering;
2. After clicking, the information will be reproduced and there will be a prompt message at the top;
<img width="1005" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/de0afdca-5fae-4515-80af-ef8cc358cb2d">
UI：
<img width="950" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/bf357d41-756e-4109-af82-ce7d4ed64c73">

---
The prompt text is missing.
1
<img width="708" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/7c9fdf93-bdd9-4b28-a780-ad55c05052f8">
<img width="647" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/2e00f26f-8931-4ee5-897a-a2e0df84234f">
2
<img width="680" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9f66d44b-5356-481f-8065-ff8519cc7c90">
<img width="637" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/6a7033c7-2804-467b-b563-03f50cdc672f">
3、The data maintains the original logic, and the text format needs to be adjusted.
<img width="573" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/80ba40a1-9c63-43fb-a1a7-53124e4f4821">
<img width="706" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/4c0c9b3a-829e-4dee-9cb8-0308d84e2cde">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2795

**Comment by FrederLu** [comment]
The icons in the Dao transaction details need to be modified.
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/ab26c89e-91ac-4607-83f8-74aa3ea28e23)

**Comment by yanguoyu** [comment]
> 1、The icons in the Dao transaction details need to be modified. ![Image](https://user-images.githubusercontent.com/25676576/258753375-ab26c89e-91ac-4607-83f8-74aa3ea28e23.png)
> 
> 2、The icon below needs to be right-aligned with the icon above. ![Image](https://user-images.githubusercontent.com/25676576/258756158-d969c776-55e8-4483-bd2d-ce9b0335a48f.png)
> 
> 3、Script information should be displayed without line breaks as much as possible. ![Image](https://user-images.githubusercontent.com/25676576/258756985-1902e6a1-b99c-4113-8b42-7ac40f5388bb.png)
> 
> ![Image](https://user-images.githubusercontent.com/25676576/258757338-75680aac-eb1a-4fb4-b369-bc97b26daecc.png)

Fixed

**Comment by FrederLu** [comment]
Verified.
