### ISSUE TITLE
The latest version prompt box problem.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#247]
When the pop-up window of `Currently the latest version` is displayed on the settings page, there is no need to keep prompting when switching to other pages and then returning to the settings page.
This week (7.24-7.28) test package link  https://github.com/nervosnetwork/neuron/actions/runs/5640501484
<img width="375" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/0387611c-cc4e-4dfd-8c38-b6822eeb342b">

https://github.com/Magickbase/neuron-public-issues/assets/25676576/4eb35ba7-9c44-4df6-bcba-723646a022c6

**Comment by yanguoyu** [comment]
It's also fixed by https://github.com/nervosnetwork/neuron/pull/2783

**Comment by FrederLu** [comment]
Verified.
