### ISSUE TITLE
`check for updates` is not able to be clicked

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#25]
The button was covered by other element.

Ref: https://github.com/nervosnetwork/neuron/issues/2372

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2405

**Comment by Cedar67** [comment]
Regression test result: Verified on PR https://github.com/nervosnetwork/neuron/pull/2405
Environment: MacOS
Test record:

https://user-images.githubusercontent.com/64718893/171124374-26841192-f572-4a6d-9c0d-68ba2255d681.mov
