### ISSUE TITLE
Problems with detect new upgrade on launch

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#251]
【Has update when starting 】
1.Actual UI shows different with UI document.
Actual:
<img width="534" alt="截屏2023-07-28 09 52 56" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/28e9b5a1-bbe0-4d1b-85e7-b677bfec284b">

UI document:
<img width="832" alt="截屏2023-07-28 09 56 02" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/f1f73990-6c6c-44bb-a50d-2c7d4d9367eb">

2.When I cancel update in midway,the version revert to old version ,which is not inconsistent with PM requirement.
Actual:

https://github.com/Magickbase/neuron-public-issues/assets/25971273/9a10ddf6-c8af-4994-b0b0-5d1a0d7d234f

In expect:

<img width="836" alt="截屏2023-07-28 15 22 03" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/dc42c694-0a49-4297-aeaa-f7d9e4ab933f">

【No update when starting but has update when checking by manual】
1.When a new version is fetched, I clicked update and then cancel in midway,the new version does not  be displayed,which is not inconsistent with PM requirement.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/8f1e4e24-ff47-4407-9b05-f76188b5d25a

In expect:

<img width="902" alt="截屏2023-07-28 15 18 08" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/465b18d1-c185-4902-a749-12e365f6ea05">

**Comment by silySuper** [comment]
1.When I click update in both situation，both pop up error  window. @yanguoyu 


https://github.com/Magickbase/neuron-public-issues/assets/25971273/00d3f0af-a528-476d-b2a6-e07eede2f25f

2.Small UI issues:
A.when put away the sidebar in Has update when starting  situation，in expect we  can see a red hot,but actually not.

https://github.com/Magickbase/neuron-public-issues/assBets/25971273/afdc30a6-8c79-4a59-a12b-ad892d2292a0

B.in expect update at once has update icon,but  actually not.
actually:
<img width="1068" alt="截屏2023-08-01 11 04 23" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/8b097aed-b753-440c-8454-13c9e6f2d843">




<img width="809" alt="截屏2023-08-01 11 00 48" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/df7d147b-d545-4306-8431-0f33c3ff9a7a">

**Comment by yanguoyu** [comment]
>  1.When I click update in both situation，both pop up error window. @yanguoyu
 
This is not a problem, maybe you open the `Neuron` from the `read-only` volume. You can try to move `Neuron` to your hard disk.

**Comment by silySuper** [comment]
1.It does not work for me to move to application,but  execute xattr -dr com.apple.quarantine app path works.
【Has update when starting 】
When I clicked update it ,it shows download over.Where is download progress bar？


https://github.com/Magickbase/neuron-public-issues/assets/25971273/b8144ab0-3431-461a-b05d-e8d03b6bb98e

**Comment by yanguoyu** [comment]
> 1.It does not work for me to move to application,but execute xattr -dr com.apple.quarantine app path works. 【Has update when starting 】 When I clicked update it ,it shows download over.Where is download progress bar？
> 
>  2023-08-01.16.22.53.mov

If you have downloaded the updater file before, it will cache on your computer, you can try to delete it and try again.
The cache file can be found at `/Users/<uername>/Library/Application Support/Caches`.

**Comment by silySuper** [comment]
If I click update one time,then cancel firstly,secondly I click update again,the update schedule has not changed.Last version does not have this phenomenon.

Because the video is too big and can not upload,so I  attach a picture.The schedule stay unchangeable in entire video.
<img width="1168" alt="截屏2023-08-01 18 39 01" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/5f5e0dbf-d501-4631-9764-4f6ac489d3a7">

**Comment by silySuper** [comment]
Can not update again  bug is verified.

**Comment by yanguoyu** [comment]
> Small UI issues:
> B.in expect update at once has update icon,but actually not.

These two problem has fixed.

**Comment by yanguoyu** [comment]
@silySuper  Any problems with this feature?

**Comment by silySuper** [comment]
Verified
