### ISSUE TITLE
The collection address book data overlap is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#253]
When the number of digits after the decimal point of the amount in the receiving address book is too long, an exception occurs that overlaps with the total number of transactions.
<img width="973" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/dde8d897-fa49-4a75-8613-ecbf4ed0e78a">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/neuron/pull/2798

**Comment by FrederLu** [comment]
Verified.
