### ISSUE TITLE
Show estimation of synchronization metrics on Neuron's page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#255]
This issue comes from https://github.com/nervosnetwork/neuron/discussions/2647

---

It declares 2 functions:

1. show the metrics of fully synchronized Neuron
	1. tip block number
	2. disk usage/block size
	3. assumed valid target block number
2. link to the metrics page on the download page, or prompt the link when synchronization starts from scratch;
3. optional, add a calculator to estimate the remaining time by uploading log file

**Comment by Danie0918** [comment]
[PRD](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774675520)

【Show estimation of synchronization metrics on Neuron's page】

- Requirement Description:Full node synchronization requires a large amount of disk space and a long synchronization time, so the estimated metrics data is helpful for users.

![show_estimation_of_synchronization_metrics_on_neuron_s_page](https://github.com/Magickbase/neuron-public-issues/assets/122437870/fdc37210-4a7f-40bd-8ffc-2806227ca5fb)

- Requirement Contents
1. The disk space sets timed tasks to update the data each time a new version is released.
2. Optimization Setting-Data Display, change the original path display to disk occupancy display.
3. Click Set Path or the Set Path popup appears when synchronizing for the first time (including reinstallation).
4. Add Estimated Synchronization Time button, click to upload logs to calculate estimated synchronization time.

**Comment by yanguoyu** [comment]
> Optimization Setting-Data Display, change the original path display to disk occupancy display.

Then users can not open the set ckb node path? If we should display the disk left space, this may be limited by the system. For MacOS, the app can only view the appointed directory.

> Add Estimated Synchronization Time button, click to upload logs to calculate estimated synchronization time.

Where will these elements show? And app can get the app's log without the user's upload.
<img width="238" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/5914683b-067a-4881-9d4d-0c51019bb14d">

Additionally, the indexer data has been removed.

**Comment by Kirl70** [comment]
> 
> Then users can not open the set ckb node path? If we should display the disk left space, this may be limited by the system. For MacOS, the app can only view the appointed directory.
> 

If it's not possible to retrieve the remaining disk space, how about displaying the space occupied by Neuron? This could help users understand how much disk space is being used.

<img width="763" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/2e614f07-7e82-4933-9929-d21bdff99e34">

**Comment by Keith-CY** [comment]
I must missed something.

The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.

**Comment by Danie0918** [comment]
> I must missed something.
> 
> The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.

This is an additional requirement to help users understand disk space usage.

**Comment by Keith-CY** [comment]
> > I must missed something.
> > The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.
> 
> This is an additional requirement to help users understand disk space usage.

But the usage of disk is dynamically growing, how can Neuron get the latest estimation without a network requset

**Comment by Danie0918** [comment]
> > > I must missed something.
> > > The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.
> > 
> > 
> > This is an additional requirement to help users understand disk space usage.
> 
> But the usage of disk is dynamically growing, how can Neuron get the latest estimation without a network requset

The used capacity here is obtained based on the permissions of the software, and is the space already used rather than the estimated space.

**Comment by Keith-CY** [comment]
> > > > I must missed something.
> > > > The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.
> > > 
> > > 
> > > This is an additional requirement to help users understand disk space usage.
> > 
> > 
> > But the usage of disk is dynamically growing, how can Neuron get the latest estimation without a network requset
> 
> The used capacity here is obtained based on the permissions of the software, and is the space already used rather than the estimated space.

I see, and just checked the detailed requirements. So there will be 2 functions
1. show the estimation of disk usage on the page, the estimation
2. show available disk space on user's computer and show the `insufficient disk space` alert when `available disk <= minimal requirement`
Am I right

**Comment by Danie0918** [comment]
> > > > > I must missed something.
> > > > > The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.
> > > > 
> > > > 
> > > > This is an additional requirement to help users understand disk space usage.
> > > 
> > > 
> > > But the usage of disk is dynamically growing, how can Neuron get the latest estimation without a network requset
> > 
> > 
> > The used capacity here is obtained based on the permissions of the software, and is the space already used rather than the estimated space.
> 
> I see, and just checked the detailed requirements. So there will be 2 functions
> 
> 1. show the estimation of disk usage on the page, the estimation
> 2. show available disk space on user's computer and show the `insufficient disk space` alert when `available disk <= minimal requirement`
> 
> Am I right

Yes.

**Comment by Danie0918** [comment]
> > Then users can not open the set ckb node path? If we should display the disk left space, this may be limited by the system. For MacOS, the app can only view the appointed directory.
> 
> If it's not possible to retrieve the remaining disk space, how about displaying the space occupied by Neuron? This could help users understand how much disk space is being used.
> 
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/106060898/279627819-2e614f07-7e82-4933-9929-d21bdff99e34.png">

In this way, we can display the used space and help users to understand the data storage situation when the disk space is not available.What do you think?  @yanguoyu

**Comment by Keith-CY** [comment]
> > > > > > I must missed something.
> > > > > > The feature request is to show the disk usage on neuron's project page, not inside neuron. It's used to inform users about the minimal requirements before they download neuron.
> > > > > 
> > > > > 
> > > > > This is an additional requirement to help users understand disk space usage.
> > > > 
> > > > 
> > > > But the usage of disk is dynamically growing, how can Neuron get the latest estimation without a network requset
> > > 
> > > 
> > > The used capacity here is obtained based on the permissions of the software, and is the space already used rather than the estimated space.
> > 
> > 
> > I see, and just checked the detailed requirements. So there will be 2 functions
> > 
> > 1. show the estimation of disk usage on the page, the estimation
> > 2. show available disk space on user's computer and show the `insufficient disk space` alert when `available disk <= minimal requirement`
> > 
> > Am I right
> 
> Yes.

Cool, I would add a detail about showing `insufficient disk space`. An exception will be thrown from ckb node when disk space runs out

> IO error: No space left on device

**Comment by Danie0918** [comment]
UI:https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28438-27646&mode=design&t=AY5lLSGCmoHUwzpQ-0

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/3005

**Comment by Keith-CY** [comment]
As mentioned in the top message

> link to the metrics page on the download page, or prompt the link when synchronization starts from scratch;

There is still some work on the project page.

**Comment by Danie0918** [comment]
> As mentioned in the top message
> 
> > link to the metrics page on the download page, or prompt the link when synchronization starts from scratch;
> 
> There is still some work on the project page, an obvious, real-time disk usage along with the download link.

PRD:https://ndephi.axshare.com

**Comment by Keith-CY** [comment]
Any update on this @PainterPuppets

**Comment by Danie0918** [comment]
> Any update on this @PainterPuppets

Expected to submit pr today.

**Comment by PainterPuppets** [comment]
> Any update on this @PainterPuppets

Submitted.

**Comment by Danie0918** [comment]
PR：https://github.com/Magickbase/websites/pull/74
