### ISSUE TITLE
The style is wrong after the mouse hovers.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#257]
The styling of the arrows is missing in the diagram compared to the UI.
Package link https://github.com/nervosnetwork/neuron/actions/runs/5795865816
<img width="978" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/81b9b4ac-d113-4d3a-82a9-d40dd7c2f6e3">
<img width="988" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/998fbb86-519e-442b-994e-93fcbea355c1">

UI：
<img width="1076" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/0696878a-4ffe-4196-83c2-3e6c695bcf61">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2799

**Comment by FrederLu** [comment]
When the interface is minimized, the left part of the frame is intercepted.

![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/f9539989-ae9b-4025-83fc-9cb753cc7174)

**Comment by yanguoyu** [comment]
> When the interface is minimized, the left part of the frame is intercepted.
> 
> ![Image](https://user-images.githubusercontent.com/25676576/259319106-f9539989-ae9b-4025-83fc-9cb753cc7174.png)

Fixed https://github.com/nervosnetwork/neuron/pull/2799#issuecomment-1670600256

**Comment by FrederLu** [comment]
Verified.
