### ISSUE TITLE
Text needs to be hidden.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#258]
The prompt text on the empty transaction history page is repeated and needs to be hidden.
<img width="989" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/c1632165-bd11-4ab2-88e5-37321a846c22">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2799

**Comment by FrederLu** [comment]
Verified.
