### ISSUE TITLE
The prompt style of data export needs to be modified.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#259]
<img width="924" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/7c0a4d72-fb7c-4b5f-b525-abbfd4e637d2">
<img width="493" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e1299cee-a8b0-4f51-9579-2932b1d6c8f7">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2800

**Comment by FrederLu** [comment]
Verified.
