### ISSUE TITLE
Slow syncing on the MacOS

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#26]
Describe: Two days in sync with 7% blocks.
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/64718893/171321292-05fb0fd7-9ee1-43ba-9367-e5c82315405a.png">

Neuron Version: 0.101.0 & 0.103.0
CKB node Version: testnet 0.103.0

Neuron log:
[neuron_debug_1654049053144.zip](https://github.com/Magickbase/neuron-public-issues/files/8810786/neuron_debug_1654049053144.zip)

Device info:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/64718893/171316759-43f24d89-66ce-46bd-88ca-a47b7afdb888.png">

**Comment by Keith-CY** [comment]
It's probably related to the performance of the machine(2CPUs 8GB).

Synchronization of CKB node consumes resources dramatically, maybe you can keep ckb node running and stop neuron until ckb node reaches tip block number.

**Comment by Cedar67** [comment]
It should be caused by PC resources. Neuron sync in about 3 hours for the following higher resource allocation.
<img width="207" alt="image" src="https://user-images.githubusercontent.com/64718893/173187827-9a41599e-ddc7-45ab-8638-5364e6e65073.png">
