### ISSUE TITLE
The width of the minimized window needs to be adjusted.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#260]
When the window is minimized, 3 columns of asset information need to be visible in `Asset Account`.
<img width="1207" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/61016476-88b5-4b74-ac8f-e331c022cc38">

<img width="690" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9219b5ca-8dd6-4d71-ab11-d3dfb1eaff6d">

**Comment by yanguoyu** [comment]
fixed https://github.com/nervosnetwork/neuron/pull/2799#issuecomment-1670600256

**Comment by FrederLu** [comment]
Verified.
