### ISSUE TITLE
The clear cache check box is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#261]
The clear cache check box is abnormal on the `Linux` device.
<img width="492" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/fdd26af9-6d8f-4b58-8a5d-bb065b2262d5">
<img width="466" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/28669589-1c4f-4c01-85c6-687ffe2d2fed">

<img width="745" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/bf734a56-71ed-45c9-a799-3b3c56b8d05e">

**Comment by FrederLu** [comment]
similar situation
![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/51dbc22f-4d37-49f6-845f-6c5a75a5472d)

![Image](https://github.com/Magickbase/neuron-public-issues/assets/25676576/3dba0635-8bbb-4aa5-8891-71e3c2252e05)

**Comment by yanguoyu** [comment]
Fixed https://github.com/nervosnetwork/neuron/pull/2799#issuecomment-1670600256

**Comment by FrederLu** [comment]
Verified.
