### ISSUE TITLE
Clicking the edit button does not work as expected.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#262]
Clicking the edit button should not delete the information just entered(223).
<img width="964" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d2c8ebe2-98fb-41cd-b7e7-115805e95f98">

Can refer to logic
<img width="968" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/b432e612-3811-4980-ba09-de865aa83f06">

**Comment by yanguoyu** [comment]
I can't get the point. Could you upload a video?

**Comment by yanguoyu** [comment]
I got that, the bug happened on the history page, I mistakenly thought it at receiving page.

**Comment by yanguoyu** [comment]
Fixed https://github.com/nervosnetwork/neuron/pull/2799#issuecomment-1670600256

**Comment by FrederLu** [comment]
> Fixed [nervosnetwork/neuron#2799 (comment)](https://github.com/nervosnetwork/neuron/pull/2799#issuecomment-1670600256)

Verified.
