### ISSUE TITLE
【Compatibility-Windows】CKB node needs  specific version of Microsoft VC++ Redistributable to run，but the pop up window does not show which VC++ versions are available.  

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#263]
For example：
 1.After I installed  this version，app still shows install VC++ pop up window.
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/6bc321e1-4cf9-4e6d-82e2-0181b89c8b31)
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/86c3c8df-1290-4335-a391-6f4417cd4167)
2.But if I installed this version ,it is OK,not pop up window.
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/7206ba9a-b087-424c-aaca-2c80d8656331)

In my opinion,to help user easier to use this app,it is better to indicate which VC++ versions are available.

**Comment by yanguoyu** [comment]
@Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb?
@Danie0918 How to more clear notice to users?

**Comment by Keith-CY** [comment]
> @Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb? @Danie0918 How to more clear notice to users?

It's specified neither in CKB release note nor in [Download from release](https://docs.nervos.org/docs/basics/guides/ckb-on-windows/#download-from-releases). But a link in [Download from release](https://docs.nervos.org/docs/basics/guides/ckb-on-windows/#download-from-releases) points to [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by yanguoyu** [comment]
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 The title is `Microsoft Visual C++ Redistributable latest supported downloads`, Should we notice the users to download the latest version from https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022? @Danie0918 @Keith-CY 

<img width="908" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/052dce2d-3d68-440c-ab15-6fe9a45cc744">

**Comment by Danie0918** [comment]
> @Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb? @Danie0918 How to more clear notice to users?

Add minimum version requirements, if any.
---
By the way,I had this doubt before, but solved it by downloading the latest version. But this is always a threshold for users, as C++ is not a component that comes with the system, can we get rid of this dependency?

**Comment by Danie0918** [comment]
> https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 The title is `Microsoft Visual C++ Redistributable latest supported downloads`, Should we notice the users to download the latest version from https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022? @Danie0918 @Keith-CY
> 
> <img alt="image" width="908" src="https://user-images.githubusercontent.com/12881040/259936517-052dce2d-3d68-440c-ab15-6fe9a45cc744.png">

Downloading the latest version is the most versatile option.

**Comment by yanguoyu** [comment]
> > @Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb? @Danie0918 How to more clear notice to users?
> 
> Add minimum version requirements, if any.
> 
> By the way,I had this doubt before, but solved it by downloading the latest version. But this is always a threshold for users, as C++ is not a component that comes with the system, can we get rid of this dependency?

Should we replace `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170` with `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022`? Or by another way to tell users to download the latest version?

**Comment by Danie0918** [comment]
> > > @Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb? @Danie0918 How to more clear notice to users?
> > 
> > 
> > Add minimum version requirements, if any.
> > By the way,I had this doubt before, but solved it by downloading the latest version. But this is always a threshold for users, as C++ is not a component that comes with the system, can we get rid of this dependency?
> 
> Should we replace `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170` with `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022`? Or by another way to tell users to download the latest version?

The two links above will point to the same page, so replacing the links is unnecessary and we need to tweak the prompt text.

[Text-en]The network nodes in Neuron rely on C++ components, so please install the latest version of Microsoft Visual C++Redistributable for x64 to ensure that the software runs properly.

[Text-cn]Neuron 中的网络节点依赖C++组件,请安装 x64 最新版本的 Microsoft Visual C++Redistributable 来保证软件正常运行。

**Comment by yanguoyu** [comment]
> > > > @Keith-CY Does the VC++ Redistributable have a minimum version requirement for ckb? @Danie0918 How to more clear notice to users?
> > > 
> > > 
> > > Add minimum version requirements, if any.
> > > By the way,I had this doubt before, but solved it by downloading the latest version. But this is always a threshold for users, as C++ is not a component that comes with the system, can we get rid of this dependency?
> > 
> > 
> > Should we replace `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170` with `https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022`? Or by another way to tell users to download the latest version?
> 
> The two links above will point to the same page, so replacing the links is unnecessary and we need to tweak the prompt text.
> 
> [Text-en]The network nodes in Neuron rely on C++ components, so please install the latest version of Microsoft Visual C++Redistributable for x64 to ensure that the software runs properly.
> 
> [Text-cn]Neuron 中的网络节点依赖C++组件,请安装 x64 最新版本的 Microsoft Visual C++Redistributable 来保证软件正常运行。

`x64` should remove, someone may use x86.

**Comment by yanguoyu** [comment]
Fixed https://github.com/nervosnetwork/neuron/pull/2805#issuecomment-1674320870

**Comment by silySuper** [comment]
Verified
