### ISSUE TITLE
Questions related to transaction details.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#264]
package link  https://github.com/nervosnetwork/neuron/actions/runs/5824367440
1、The selected style of the left column should be retained when entering the `Transaction Details` from the `Overview` or `Transaction History`.
<img width="1198" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/a16c7b28-e7bd-4d41-b437-cc2204648909">
<img width="1115" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/5a84b015-4c91-43e9-86ce-65c1a0d7a262">
<img width="1192" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/1c038519-c735-4c0d-8563-1be39addbd7b">
<img width="1190" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/afad58b0-e8f0-49c1-af72-6aef1d754fc4">

---
2、In night mode `Transaction Details` (entered from `Overview` or `Transaction History`), the style when the mouse hovers over the address is abnormal. Refer to the styles in Nervos Dao.
<img width="990" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9f6ed04c-d493-45da-8749-fa6ca7cd8ce2">
<img width="912" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/9e23c385-f078-4a90-bd1e-61e6bf584aa9">

---
3、The font color of the detailed text in the address information in night mode needs to be adjusted.
<img width="843" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e024ad14-a296-4775-8088-6bc13a7f4e1a">

**Comment by yanguoyu** [comment]
Fixed https://github.com/nervosnetwork/neuron/pull/2805#issuecomment-1674320870

**Comment by FrederLu** [comment]
Verified.
