### ISSUE TITLE
Style issue with multisig addresses.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#266]
1、The font style of multi-signature address confirmation needs to be adjusted in night mode.
<img width="492" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/e81dda4b-783a-4a52-9471-c366fa8d9fae">

---
2、The prompt style of exporting transaction information in multi-signature needs to be adjusted.
<img width="745" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/700f33c1-a726-4156-941d-0ffa05b0e277">

---
3、The style of the prompt box needs to be adjusted when multi-signature confirms the transaction information of other addresses.
<img width="704" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/90ccae37-51e1-4898-8425-5b48bbfc71db">

**Comment by yanguoyu** [comment]
Please test it by https://github.com/nervosnetwork/neuron/pull/2806#issuecomment-1678588067 result.

**Comment by FrederLu** [comment]
> Please test it by [nervosnetwork/neuron#2806 (comment)](https://github.com/nervosnetwork/neuron/pull/2806#issuecomment-1678588067) result. @FrederLu

All 3 issues in the current issue have been fixed.

At the same time, it was also found that the old pop-up window was still displayed when confirming other json files.
<img width="1176" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/d7f1bc7b-6b87-4da6-979c-617788e51907">

---
Confirm, should the `script` information in the summary be clickable? 
Now mouse hover will be set to clickable state, but click has no effect. Checked the old version (V0.110.1) and found the same problem.
<img width="680" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/10a7f1a9-e299-4aeb-a47e-f59fb94f8fe1">

**Comment by yanguoyu** [comment]
> > Please test it by [nervosnetwork/neuron#2806 (comment)](https://github.com/nervosnetwork/neuron/pull/2806#issuecomment-1678588067) result. @FrederLu
> 
> All 3 issues in the current issue have been fixed.
> 
> At the same time, it was also found that the old pop-up window was still displayed when confirming other json files. <img alt="image" width="1176" src="https://user-images.githubusercontent.com/25676576/260893412-d7f1bc7b-6b87-4da6-979c-617788e51907.png">
> 
> Confirm, should the `script` information in the summary be clickable? Now mouse hover will be set to clickable state, but click has no effect. Checked the old version (V0.110.1) and found the same problem. <img alt="image" width="680" src="https://user-images.githubusercontent.com/25676576/260893699-10a7f1a9-e299-4aeb-a47e-f59fb94f8fe1.png">

@devchenyan

**Comment by devchenyan** [comment]
> > Please test it by [nervosnetwork/neuron#2806 (comment)](https://github.com/nervosnetwork/neuron/pull/2806#issuecomment-1678588067) result. @FrederLu
> 
> All 3 issues in the current issue have been fixed.
> 
> At the same time, it was also found that the old pop-up window was still displayed when confirming other json files. <img alt="image" width="1176" src="https://user-images.githubusercontent.com/25676576/260893412-d7f1bc7b-6b87-4da6-979c-617788e51907.png">
> 
> Confirm, should the `script` information in the summary be clickable? Now mouse hover will be set to clickable state, but click has no effect. Checked the old version (V0.110.1) and found the same problem. <img alt="image" width="680" src="https://user-images.githubusercontent.com/25676576/260893699-10a7f1a9-e299-4aeb-a47e-f59fb94f8fe1.png">

1. Packaging for test is done in [5880231970](https://github.com/nervosnetwork/neuron/actions/runs/5880231970).

2. The script tag is not clickable.

**Comment by FrederLu** [comment]
Verified.
