### ISSUE TITLE
【Compatibility-Windows】The address of sign shows abnormal when window is lessen.

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#267]
1.The address of sign shows abnormal when window is lessen，address option is separated from drop-down box
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/bb66b058-9a3c-4bab-be62-b0fd0ba546bf)

2. A small UI issues  in mutisign page.The check box display is incomplete.
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/dd6cd1d9-da97-45b2-9133-ae0a1b3fe4d3)

**Comment by yanguoyu** [comment]
> A small UI issues in mutisign page.The check box display is incomplete.

This problem may be the same as https://github.com/Magickbase/neuron-public-issues/issues/261. Do you use the latest package?

**Comment by silySuper** [comment]
No，I plan to use one package to check function and UI firstly，then verify all bugs in other packages.OK,if some problems has fixed before ,I will change to new package to continue check function and UI.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2809
