### ISSUE TITLE
【Compatibility-Windows】Copy transaction hash style is different from other copy style in transaction history page and Nervos DAO page

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#268]
Copy transaction hash style in transaction history page and Nervos DAO page needs to click copy icon and style is different from copy other information in windows and linux.
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/4d7ce8fa-56df-4241-9bc4-cc78a5d1271d)
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/a12ae9de-4467-4d9d-9786-8c54346b5ca1)

copy other information in Windows:
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/3c39d61e-f02c-42ea-8bce-cc9ea1045036)

copy transaction hash in Linux:
<img width="1287" alt="截屏2023-08-15 17 02 11" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ba84c211-04a1-4f9b-9cf2-343d658ed21d">

**Comment by yanguoyu** [comment]
Does the Linux Neuron version is same as Windows Neuron?

**Comment by silySuper** [comment]
The latest version in linux has changed copy style .The Style before is more harmonious  with other copy style，Why this changed  and  lead to in one page has different copy style?

**Comment by silySuper** [comment]
It is strange  that the copy style in all app is similar to the old style(which can copy through clicking information directly) except this transation hash.

**Comment by yanguoyu** [comment]
This change is a bug from https://github.com/Magickbase/neuron-public-issues/issues/246.
And the UI designer told that, when there exists an icon for copy, it's unnecessary to show the hover copy style.
