### ISSUE TITLE
Issues with add check ckb node update or compatibility

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#269]
1.In the first situation(the external ckb version should be bigger than v0.109.0):tips lost right parenthesis in Neuron v(0.110.1)
<img width="1351" alt="截屏2023-08-18 16 06 35" src="https://github.com/nervosnetwork/neuron/assets/25971273/c751e013-853b-43c7-ab0a-c3c4637c7315">

2.In the second situation( the external ckb version should not be 0.109 ~ 0.110):ckb node in local is ckb 0.108.1 (061a3d5 2023-04-04), neuron is 
<img width="280" alt="截屏2023-08-18 16 37 33" src="https://github.com/nervosnetwork/neuron/assets/25971273/53713f04-a562-4bb1-8b19-ee6b14d24399">

the window like this does not show:
![image](https://github.com/nervosnetwork/neuron/assets/25971273/ce421d35-50a7-4fe7-a7b9-a0f98d3f9739)

**Comment by yanguoyu** [comment]
1 fixed by https://github.com/nervosnetwork/neuron/pull/2807#issuecomment-1680478488.
For 2, please use https://github.com/nervosnetwork/neuron/pull/2808 pr package. https://github.com/nervosnetwork/neuron/pull/2808#issuecomment-1683586040

**Comment by silySuper** [comment]
Verified except  tip in not compatible situation.

**Comment by yanguoyu** [comment]
> Verified except tip in not compatible situation.

Fixed. https://github.com/nervosnetwork/neuron/pull/2808#issuecomment-1683586040.
https://github.com/nervosnetwork/neuron/pull/2807#issuecomment-1680478488

**Comment by silySuper** [comment]
Verified.
