### ISSUE TITLE
Issues with remove address and script convertion from ckb-sdk-js 

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#270]
1.Testnet send 606.1 ckb to address:ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0xkgap5m566mkfv3neu5alqmjls0k78zq7pggwr, after 
 send 707.1ckb to another addresss,the banlace in ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0xkgap5m566mkfv3neu5alqmjls0k78zq7pggwr become  0ckb.
<img width="1207" alt="截屏2023-08-23 17 39 21" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/e03be8c2-7dad-41cf-b00f-299298ee6ab7">

tx hash:0x646ab68721e4d180eca936d3ac82487bf949041c7f9843c1b8990d5bd809d96d
tx status:success
sysnc progress:100%

<img width="1054" alt="截屏2023-08-23 17 38 35" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/084a857b-cf22-41dd-b5a8-bb5fad7a9e59">

 what is the reason?

**Comment by yanguoyu** [comment]
Because https://pudge.explorer.nervos.org/transaction/0x9498b2c3a25baad44175106c5e3f12b6cb3568a9328f67cf4392c29268180fda has cost the `606.1 ckb`. Any problems?

**Comment by silySuper** [comment]
The logic is that next send  balance will cost last receive balance?

**Comment by yanguoyu** [comment]
> The logic is that next send balance will cost last receive balance?

Not exactly, it will use live cells to collect enough CKB.
