### ISSUE TITLE
Label of networks are not translated correctly

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#272]
Screenshort
![Pasted Graphic 11](https://github.com/Magickbase/neuron-public-issues/assets/7271329/fbe8467d-26f3-43e2-895a-5f1c4e6a36b0)

Design draft
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/18a72737-5555-4767-8f42-3cfb22e1edf7)

Package from https://github.com/nervosnetwork/neuron/pull/2808

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2811
