### ISSUE TITLE
Issues with label of networks are not translated correctly

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#274]
1.When add https://testnet.ckb.dev/,it does not show Devnet,but Testnet.
<img width="1007" alt="截屏2023-08-25 17 13 48" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/fc255296-b31a-49db-bea0-84ba635dd513">

2.When change network ,the Light Client Testnet shows abnormal which is devnet+networkname.
<img width="1157" alt="截屏2023-08-25 17 14 54" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/330da3c5-1d62-4670-a7ff-f6782ad76cb0">

**Comment by yanguoyu** [comment]
> When add https://testnet.ckb.dev/,it does not show Devnet,but Testnet.

Because the `get_blockchain_info` rpc result's chain is `ckb_testnet`.

By the way, we can attach the bug in the test PR or issue, then developers can quickly handle the bug and skip the PM assignment.

**Comment by yanguoyu** [comment]
> 2.When change network ,the Light Client Testnet shows abnormal which is devnet+networkname.

Fixed by https://github.com/nervosnetwork/neuron/pull/2811/commits/f643fcedd0343f824e60ef167a2d0fd6156922df commit.

**Comment by silySuper** [comment]
/package.

**Comment by silySuper** [comment]
Verified.
