### ISSUE TITLE
Issues with remove systemScripts from ckb-sdk-js

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#275]
1.Mutisig Address can not be deleted actually.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/158fb183-8225-4b32-ac97-d681037caf29

Log:

[neuron_debug_1693298738725.zip](https://github.com/Magickbase/neuron-public-issues/files/12462215/neuron_debug_1693298738725.zip)

**Comment by yanguoyu** [comment]
It may caused by https://github.com/nervosnetwork/neuron/pull/2811/commits/cd80dced5781a2ede8b5a2ff1c0b9e45cd5428cf. You can try to rebase the develop branch. @zhangyouxin

**Comment by silySuper** [comment]
Verified.
