### ISSUE TITLE
Problem found in package  6081308943 version

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#277]
1.packaging for test is done in [6081308943](https://github.com/nervosnetwork/neuron/actions/runs/6081308943)
In Asset Accounts/ Send ,when send to address equals Asset Accounts receive address ,the tip alert wrong place,maybe appear under send to input box is better.
<img width="1362" alt="截屏2023-09-06 10 47 40" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/84cabf9f-08f4-4514-a8cf-14df361923fb">

remark：the problem shows in other version also.

**Comment by devchenyan** [comment]
fixed: https://github.com/nervosnetwork/neuron/pull/2862

**Comment by silySuper** [comment]
Verified.
