### ISSUE TITLE
Delay on syncing the status of a transaction

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/neuron-public-issues#279]
The SUCCESS status of Neuron require a number of confirmed blocks from chain. Neuron shows you your latest balance from the latest block it retrieve from CKB network. 

And this will happen:

![Image](https://user-images.githubusercontent.com/85155313/266892725-6f3132c8-62c8-477b-80b7-cf54d8e691ca.png)

It showed that I had 2000 CKB in this wallet, however , when i tried to transfer 500 CKB, Neuron alerted that my balance was not enough.

**Comment by yanguoyu** [comment]
It's normal, the address balance is 2000 ckb, but some cells' transaction is pending, so we need to wait for the cell to be confirmed. Then we can use the balance. Once we can use pending cells(https://github.com/Magickbase/neuron-public-issues/issues/217), we will not need to wait for them.
