### ISSUE TITLE
Hide balances or amounts of transactions

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#28]
Support hiding balances or amounts for sharing screenshots or video records.

**Comment by Keith-CY** [comment]
Functions showing balances or amounts

1. Overview(Balance, Amounts)
![image](https://user-images.githubusercontent.com/7271329/179442590-7ea734e7-2f9f-4d14-82fd-bd68c5479eca.png)

2. Transfer(Balance)
![image](https://user-images.githubusercontent.com/7271329/179442635-ce64c436-e46c-47a3-89b8-411e43f311cb.png)

3. Address Book(Balances)
![image](https://user-images.githubusercontent.com/7271329/179442707-b02e40cb-e97d-48ca-8cae-469d4597314b.png)

4. Transaction History(Amounts)
![image](https://user-images.githubusercontent.com/7271329/179442757-1a5fe77a-f0ba-4bed-a096-df0d0da3d834.png)

5. Transaction Detail(Amounts)
![image](https://user-images.githubusercontent.com/7271329/179442818-db5a4896-cddd-49bb-b765-1411551ef5b6.png)

6. Nervos DAO(Balance, Amounts)
![image](https://user-images.githubusercontent.com/7271329/179443031-f93fb177-614b-43e8-93d2-74e8e0f185f8.png)

7. Custom Assets(Balance)
![image](https://user-images.githubusercontent.com/7271329/179443267-e0361963-d08c-4ea8-81d3-d267985e107a.png)

8. Asset Accounts(Balance)
![image](https://user-images.githubusercontent.com/7271329/179443308-0d75f5a8-36bb-4d08-986f-9b36ba26613a.png)

9. Transfer SUDT(Balance)
![image](https://user-images.githubusercontent.com/7271329/179443341-d1e005a6-1efd-456a-8b59-39dbb77d799d.png)

10. Multisig Address(Balance)
![image](https://user-images.githubusercontent.com/7271329/179443462-5c9d3aca-749a-44bf-b640-d87492801a83.png)

**Comment by Keith-CY** [comment]
Functions that show balances/amounts are picked out above.

For now, I've got requests to hide balance/amount in `overview`, `history`, `nervos dao` and they are exactly the functions that will be shared by screenshots most time. In this logic, `asset accounts` and `multisig addresses` should also support hiding balances too.

Besides, I think `address books` is similar to a sub-account list of the main account and their balances should be able to be hidden.

`Transaction Detail` is transparent to all users via explorer so it's redundant to hide amounts, but hiding them requires extra work for other users to view details so it makes sense.

Seldom see users sharing a screenshot of `transfer/sudt transfer` so I think it might be unnecessary to hide the balance in `transfer`, `sudt transfer`

Most records in `custom assets` are not related to `value` so we can pass it too.

How do you think about the analysis of in which functions the balance/amount could be hidden? @yanguoyu @Kirl70 @Cedar67 @FrederLu

**Comment by Kirl70** [comment]
I think from the point of view of the product, the function of hiding assets should be added uniformly. Since we do not know whether users will use this function on the page, it is a safe way to add the function uniformly and keep the function consistency of the product.

**Comment by yanguoyu** [comment]
As you said, the address's balance can be viewed via explorer. I think users only want to hidden all balance of the wallet, but not a simple address's balance.

But for development, I think we should provide a hidden function for all read-only balance.

**Comment by Keith-CY** [comment]
So for consistency of user experience and development, supporting hiding balances/amounts in all functions is the best choice for us.

Could you update this feature in the design @Kirl70 and we only implement this feature in the new UI @yanguoyu

**Comment by Kirl70** [comment]
> So for consistency of user experience and development, supporting hiding balances/amounts in all functions is the best choice for us.
> 
> Could you update this feature in the design @Kirl70 and we only implement this feature in the new UI @yanguoyu

Ok, I will update it on the new design draft.

**Comment by Kirl70** [comment]
Adjustments have been updated to the design draft.

**Comment by Cedar67** [comment]
@Keith-CY @Kirl70 @yanguoyu  Please help me confirm my understanding:

**Pages that need to hide:**
1. Overview - Total Balance
2. Overview - Recent activities Amount
3. Address book - Balance
4. History - Amount
5. Nervos dao
6. Asset accounts
7. Multisig addresses  - Address list Balance


**Pages that do NOT need to hide:**
1. History - Transaction Detail Amount
2. Transfer/sudt transfer
    - Send - Send Page
    - Send - Multisig addresses
    - Send - Asset accounts
3. Customized assets

**Comment by Keith-CY** [comment]
> @Keith-CY @Kirl70 @yanguoyu Please help me confirm my understanding:
> 
> **Pages that need to hide:**
> 
> 1. Overview - Total Balance
> 2. Overview - Recent activities Amount
> 3. Address book - Balance
> 4. History - Amount
> 5. Nervos dao
> 6. Asset accounts
> 7. Multisig addresses  - Address list Balance
> 
> **Pages that do NOT need to hide:**
> 
> 1. History - Transaction Detail Amount
> 2. Transfer/sudt transfer
>    
>    * Send - Send Page
>    * Send - Multisig addresses
>    * Send - Asset accounts
> 3. Customized assets

The feedback above(https://github.com/Magickbase/neuron-public-issues/issues/28#issuecomment-1186817914, https://github.com/Magickbase/neuron-public-issues/issues/28#issuecomment-1186820797) recommends keeping all behaviors of balances/amounts in neuron to be consistent, namely all balances/amounts are able to be hidden in the app.

**Comment by Cedar67** [comment]
> > @Keith-CY @Kirl70 @yanguoyu Please help me confirm my understanding:
> > **Pages that need to hide:**
> > 
> > 1. Overview - Total Balance
> > 2. Overview - Recent activities Amount
> > 3. Address book - Balance
> > 4. History - Amount
> > 5. Nervos dao
> > 6. Asset accounts
> > 7. Multisig addresses  - Address list Balance
> > 
> > **Pages that do NOT need to hide:**
> > 
> > 1. History - Transaction Detail Amount
> > 2. Transfer/sudt transfer
> >    
> >    * Send - Send Page
> >    * Send - Multisig addresses
> >    * Send - Asset accounts
> > 3. Customized assets
> 
> The feedback above([#28 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/28#issuecomment-1186817914), [#28 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/28#issuecomment-1186820797)) recommends keeping all behaviors of balances/amounts in neuron to be consistent, namely all balances/amounts are able to be hidden in the app.

Got it. It's much clearer. Thanks @Keith-CY
