### ISSUE TITLE
Issues with support spore nft

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#280]
1.In customized assets page,assets lost copy feature like this in reauirement document.
actual:

https://github.com/Magickbase/neuron-public-issues/assets/25971273/79bad5ad-e84f-412f-8b5b-bb5b82df8d9e

expect:
<img width="1128" alt="截屏2023-09-12 11 11 58" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ea2d0cd0-88c0-4a33-9528-53dc641562c0">

2.When spore does not bound to cluster ,does it need to show 【unbound】 or not?Developer picture shows【unbound】,but requirement document not.
develop picture:
![image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/ac932cb0-1620-4da6-aa46-dfc57b230cc1)

requirement document:(which is equal to actual result)
<img width="1088" alt="截屏2023-09-12 11 20 51" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/2f729b9b-5116-452d-b4ef-24eaaef26ccd">

3.What is the send feature in requirement document? This send button does not shown in customized assets page  actually.
requirement document:
<img width="1097" alt="截屏2023-09-12 11 16 00" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c2e81b33-7a71-4c34-bf34-b6cc780b8ba5">

actual:(which is equal to developer picture)

<img width="1125" alt="截屏2023-09-12 11 24 17" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/9f32004e-1c66-41a2-ab45-d64002e9178f">

4.Lost description of cluster：
actual：
https://github.com/Magickbase/neuron-public-issues/assets/25971273/20075f1d-ab47-4d9c-b81c-1b757f6cda74

requirement document：

<img width="1075" alt="截屏2023-09-12 15 47 21" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/29df7ae2-6b38-4e0a-bf70-122c71538664">

5.UI shows abnormal when cluster name is long:

<img width="1179" alt="截屏2023-09-12 16 20 09" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/2d0e3d07-43f7-43df-b4e9-e34badb84202">

**Comment by silySuper** [comment]
Add two problems in this issue.

**Comment by homura** [comment]
> 1.In customized assets page,assets lost copy feature like this in reauirement document.

I've make spore info copyable

> 2.When spore does not bound to cluster ,does it need to show 【unbound】 or not?Developer picture shows【unbound】,but requirement document not.

The original PRD is required, but it has been [removed lately](https://github.com/nervosnetwork/neuron/pull/2810#discussion_r1315437180)

**Comment by silySuper** [comment]
1.Verified.
3.I found a comment in requirement document:send feature does not need in this version  @Danie0918 
<img width="356" alt="截屏2023-09-22 14 53 18" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6f54e782-8e72-43ad-ac33-7723a862a3cf">

4.description of the cluster is hard to show because of the copy feature,may be we should consider the show operation @Danie0918 @homura 
5.Verified.

**Comment by silySuper** [comment]
Asset  hidden feature is invalid for spore nft.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/70740c7a-b68d-4da6-a2e1-e6e245985a94

**Comment by Danie0918** [comment]
> 1.Verified. 3.I found a comment in requirement document:send feature does not need in this version @Danie0918 <img alt="截屏2023-09-22 14 53 18" width="356" src="https://user-images.githubusercontent.com/25971273/269855054-6f54e782-8e72-43ad-ac33-7723a862a3cf.png">
> 
> 4.description of the cluster is hard to show because of the copy feature,may be we should consider the show operation @Danie0918 @homura 5.Verified.

3. Yes, due to current technical limitations, sending is not supported at this time.
4. Display both the description and the copied hover layer on mouseover.The description is just additional information and does not affect the copy function.

**Comment by homura** [comment]
> 4.description of the cluster is hard to show because of the copy feature,may be we should consider the show operation @Danie0918 @homura

<img width="270" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7511174/752cf29a-6236-4c2b-a0de-8c040a19a414">

Currently, the description of a cluster displays when the mouse is hovering, could you please check it again? 

If a spore isn't derived from a cluster, the hovering information is the same with the spore, but without truncating

<img width="395" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7511174/f75c4dcf-9edc-44d9-a693-7b961d9ab524">


---



https://github.com/Magickbase/neuron-public-issues/assets/7511174/4693b694-bbab-4f65-a510-f6a6043d00bb

**Comment by silySuper** [comment]
4.Verified
5.Asset hidden feature verified.
