### ISSUE TITLE
Issues with downplaying the address to strengthen the concept of the account

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#281]
1.In Receive pop up window,copy address feature lost copy success tip.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/d3038798-6684-48dc-b681-b10be43bda5e

2.In Address Book pop up window,the information is not centered.
<img width="1089" alt="截屏2023-09-13 15 47 52" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/21656742-fca5-4d5a-925f-ce7d62d037eb">

3.In send page,Initiate a transaction is different from UI design，is that done in next version？
actual：
https://github.com/Magickbase/neuron-public-issues/assets/25971273/29ce5478-aa99-4fff-852f-e7b5b196ff0d
UI design：
<img width="1277" alt="截屏2023-09-13 16 21 55" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/cb06c0ed-59c8-42d2-8b0a-16df6f4fecb7">

**Comment by devchenyan** [comment]
3、This version does not include optimisation of the send page.

**Comment by silySuper** [comment]
Verified.
