### ISSUE TITLE
Miss saving some inputs and outputs

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#282]
https://github.com/nervosnetwork/neuron/pull/2672 brings a bug that may miss some inputs and outputs owned to the current wallet.

If the current wallet has derived addresses, and these addresses have some balance. Once I would send all of the balance to the first address. When I sync from a new Neuron, the `send-all` transaction will sync from the first address but currently the input address may not have been derived. Then the derived address's input will not be saved into the database. After that, when the address has been derived, its input will not be saved because the transaction has synced.
I propose a solution to resolve this problem. The `indexer_tx_hash_cache` table's transactions are synced to the appointed blake160s. We'd better filter the inputs and outputs by the `blake160s`. 

Another problem is I save lastCachedBlockNumber with wallet ID, it also affects the derived addresses's transactions' synchronization. I should save the lastCachedBlockNumber with wallet ID and blake160s.

But I need more time to resolve these problems, If we need to release recently, I will remove the block number cache for wallet ID, and remove the cell filter when saving inputs and outputs into the database.

**Comment by yanguoyu** [comment]
@Keith-CY @Danie0918

**Comment by Danie0918** [comment]
This needs to be resolved before going live, but the timing of the release and the technical solution needs to be judged down by @Keith-CY

**Comment by Keith-CY** [comment]
> This needs to be resolved before going live, but the timing of the release and the technical solution needs to be judged down by @Keith-CY

The release date can be postponed until the product is really ready to go. cc @yanguoyu

**Comment by yanguoyu** [comment]
> > This needs to be resolved before going live, but the timing of the release and the technical solution needs to be judged down by @Keith-CY
> 
> The release date can be postponed until the product is really ready to go. cc @yanguoyu

OK, I will close https://github.com/nervosnetwork/neuron/pull/2840 and create a PR after I resolve this problem.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2841
