### ISSUE TITLE
A pop-up window is required when canceling a hardware wallet transfer.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/neuron-public-issues#283]
There is a missing pop-up window when canceling a hardware wallet transfer in the new version of Neuron. The prompt text and buttons refer to the previous version, but use the new version style.

<img width="791" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/25676576/40cc9fae-dc0c-4e49-9413-8e2b9dbcf78d">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2842

**Comment by FrederLu** [comment]
>https://github.com/nervosnetwork/neuron/pull/2842

Verified.
