### ISSUE TITLE
Light Client Mode with Main Network Support

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#284]
The main network light client will be released soon and we need to consider support for it when the new version of Neuron is released.

**Comment by Danie0918** [comment]
#200 

[PRD](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774561197)

**Comment by yanguoyu** [comment]
1. >【Network settings optimization 】 Internal node and light client node support manual switching between main and test network by clicking to switch to the corresponding network.

Should they choose network type when the users change the node data by settings? And, does this directory show the upper directory that includes mainnet and testnet data?
<img width="852" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/df5fd996-b513-47ac-bc8d-87770f3f7549">


2. >【Network settings optimization 】 Pop-up window interactions：Click to cancel ignoring alerts and still link internal network nodes.

Currently, if the user starts an external node that uses port 8114, do we need to start with another port and change the display of the internal network URL? 


3. >【Network settings optimization 】 When no external network is added, a pop-up prompt directs the user to add a network to enable the external node.
When external nodes have been added, a list of external nodes is displayed for the user to select, and the user can also choose to add new network nodes.

Should we only show the network that its URL equals the started ckb node URL?

4. Does the light client node also use these interactions? currently, the light client node can use an internal node.

@Danie0918

**Comment by Danie0918** [comment]
> Should they choose network type when the users change the node data by settings? And, does this directory show the upper directory that includes mainnet and testnet data? 

The data of different network types of the same node are under the same path by default, however, users can change it manually and change the path in relation to the network type.
 
> Currently, if the user starts an external node that uses port 8114, do we need to start with another port and change the display of the internal network URL?
 
Yes, need to use a different port and modify the front-end presentation.


> Should we only show the network that its URL equals the started ckb node URL?

I'm not so sure about that. Do you have any ideas? @Keith-CY 

> 4. Does the light client node also use these interactions? currently, the light client node can use an internal node.
> 

Yes, light client node is also internal node.

**Comment by Keith-CY** [comment]
> > Should we only show the network that its URL equals the started ckb node URL?
> 
> I'm not so sure about that. Do you have any ideas? @Keith-CY

Not bad, when there isn't a network matches the URL, users will be directed to add one

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28088%3A7597&mode=design&t=yomXbxOwCP9AVfOJ-1
<img width="1222" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/40e05e06-53fc-47b2-8847-83b261db5174">

**Comment by yanguoyu** [comment]
1. Saving the ckb node path as `ckbDataPath_${nodeType}`, and saving the light client data path as `testnetLightDataPath_${nodeType}`
2. Only start ckb or light client with monitor when the selected node is readonly. If an external node is running, send a message to UI process and notify users.
3. Add retry start ckb node with other port.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2921

**Comment by Keith-CY** [comment]
The `cancel` button in the dialog is confusing, it launches the internal node instead of an action of `cancel` e.g. do nothing until users select another network option.

I would suggest using a clear label, e.g. `connect to the internal node`, or `launch the internal node`

**Comment by Keith-CY** [comment]
> The `cancel` button in the dialog is confusing, it launches the internal node instead of an action of `cancel` e.g. do nothing until users select another network option.
> 
> I would suggest using a clear label, e.g. `connect to the internal node`, or `launch the internal node`

cc @Danie0918

**Comment by Danie0918** [comment]
> The `cancel` button in the dialog is confusing, it launches the internal node instead of an action of `cancel` e.g. do nothing until users select another network option.
> 
> I would suggest using a clear label, e.g. `connect to the internal node`, or `launch the internal node`

1. Change 'Cancel' to 'Ignore external node'.
2. Remove option prioritization and keep leveling.

@yanguoyu @Kirl70

**Comment by Kirl70** [comment]
> > The `cancel` button in the dialog is confusing, it launches the internal node instead of an action of `cancel` e.g. do nothing until users select another network option.
> > I would suggest using a clear label, e.g. `connect to the internal node`, or `launch the internal node`
> 
> 1. Change 'Cancel' to 'Ignore external node'.
> 2. Remove option prioritization and keep leveling.
> 
> @yanguoyu @Kirl70

The design draft has been adjusted.
<img width="594" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/3c4646a6-7c40-474f-87cc-f55c3f557508">

**Comment by Keith-CY** [comment]
Demonstration on YouTube: https://www.youtube.com/watch?v=Vl2LGRNqnvk
