### ISSUE TITLE
2 questions about migrating sudt asset to an account

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#285]
https://github.com/Magickbase/neuron-public-issues/assets/7271329/795a16bb-de58-42b1-b141-fa137456402e

1. Why is `sign & export` loading
<img width="1479" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/245d593a-ff0c-410c-ae0e-f0806babac14">

2. Why is `migrate to a sudt asset account` dialog open after actions
<img width="1479" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/b4b493dc-1202-4a74-888d-a069f5dff728">

**Comment by yanguoyu** [comment]
Https://github.com/nervosnetwork/neuron/pull/2849 has fixed 2.
The first question is previous logic.
