### ISSUE TITLE
Token name exceeds in the overview window

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#286]
<img width="1351" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/2927560a-8d8b-4b49-a6cc-627ee2377002">

Token name exceeds in the overview window.

Package of PR: https://github.com/nervosnetwork/neuron/pull/2845 or commit: https://github.com/nervosnetwork/neuron/pull/2845/commits/098ebf5b497bcca401f7dcb29af430906b7465ec

Environment: remote windows for neuron test

**Comment by Keith-CY** [comment]
Happens in sudt account window too
<img width="1403" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/9418021a-2a43-4ac8-a068-917b81e16cd2">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2849
