### ISSUE TITLE
Some issues of nervos dao in light client mode

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#289]
The video is large, so I uploaded it on wetransfer at https://we.tl/t-P7LGZpTqns

There are the following issues:
1. synchronization stopped after deposit; the light client was working;
2. synchronization became 0 after deposit;
3. synchronization recovered after switching network;

**Comment by yanguoyu** [comment]
This is caused by the sync process throwing an exception then the process stops. So I skip updating the transaction that calls `get_transaction(txHash)` throws an exception.
https://github.com/nervosnetwork/neuron/pull/2849/commits/fd42aa46090394a55d09b429bf22a063807cf90f
