### ISSUE TITLE
Some issues of regression in light client mode

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#293]
1.In Nervos Dao page ，sync process mainly affect 2 parts data : one is Locked data ,the other one is compensation cycle ends days.These 2 parts sometimes shows normally, then shows NaN or -- when is syncing.IMO,syncing process can not affect history data in expect,but actually it affects history data.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/89658ecb-cccb-46bc-a07b-ced6656bc744

<img width="1154" alt="截屏2023-10-07 10 12 09" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/2a6b87ab-cfb3-4c6e-a4c6-767e3c821272">

2.After  clicking clear all synchronized data,the molecule  can not change for a long time ,more than 20 minutes at the time when I have  submited this issue.I have tried to quit this app and open again ,but not affect.
<img width="1178" alt="截屏2023-10-07 10 26 13" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/595b005a-724b-419c-a3e7-151c26e7bd03">
 After quiting  this app and open again:
<img width="1302" alt="截屏2023-10-07 10 40 58" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/5e449bde-4f46-4ea9-80ff-521fc3e70a37">

**Comment by silySuper** [comment]
The second is still stay for about one hour ,how to make it syncing?

**Comment by yanguoyu** [comment]
Could you upload the debug information? Otherwise, I can not exactly get what happened to your Neuron.

**Comment by silySuper** [comment]
[neuron_debug_1696649152180.zip](https://github.com/Magickbase/neuron-public-issues/files/12836685/neuron_debug_1696649152180.zip)

This is the debug zip,and at this time  it still stay the same.

**Comment by yanguoyu** [comment]
> These 2 parts sometimes shows normally, then shows NaN or -- when is syncing

We can call rpc to ensure that light client rpc is running and `get_tip_header` call success:
```bash
curl http://localhost:9000/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "get_tip_header", "params": [], "id": 1}'
```

That number is based on the current epoch, if get_tip_header calls fail, it may show NaN.

**Comment by silySuper** [comment]
3.I have send a locktime transaction ,transaction hash is 0x39189b76094e69940312743daf1765e2890ae241a53f4b830dfc2eb63872f7b8,which  block number is 10869532.But I cannot see this in customized assets when sync block is 10872475
<img width="1101" alt="截屏2023-10-07 16 26 56" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/9cb63811-e934-4dba-83e8-538c7f1e16af">

<img width="1138" alt="截屏2023-10-07 16 27 07" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/b34bb79a-298c-4583-a729-707fee8d9864">

<img width="1328" alt="截屏2023-10-07 16 26 21" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/a2fad8bc-6399-4733-87ba-37a6bfac6252">

**Comment by silySuper** [comment]
> 3.I have send a locktime transaction ,transaction hash is 0x39189b76094e69940312743daf1765e2890ae241a53f4b830dfc2eb63872f7b8,which block number is 10869532.But I cannot see this in customized assets when sync block is 10872475 <img alt="截屏2023-10-07 16 26 56" width="1101" src="https://user-images.githubusercontent.com/25971273/273374422-9cb63811-e934-4dba-83e8-538c7f1e16af.png">
> 
> <img alt="截屏2023-10-07 16 27 07" width="1138" src="https://user-images.githubusercontent.com/25971273/273374430-b34bb79a-298c-4583-a729-707fee8d9864.png"> <img alt="截屏2023-10-07 16 26 21" width="1328" src="https://user-images.githubusercontent.com/25971273/273374441-a2fad8bc-6399-4733-87ba-37a6bfac6252.png">

Actual result：
In light client mode：
same wallet locktime transaction send: before clear cache show ,after clear cache  not show 
different wallet locktime transaction send(receive wallet):before clear cache show ,after clear cache  not show

In full client mode:
same wallet locktime transaction send: before clear cache show ,after clear cache  not show 
different wallet locktime transaction send(receive wallet):before clear cache show ,after clear cache  not show

They are same result,not show difference.
<img width="448" alt="截屏2023-10-08 09 32 53" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/846036a8-9a1a-44a6-a1d5-2880273cd0eb">

**Comment by silySuper** [comment]
> > These 2 parts sometimes shows normally, then shows NaN or -- when is syncing
> 
> We can call rpc to ensure that light client rpc is running and `get_tip_header` call success:
> 
> ```shell
> curl http://localhost:9000/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "get_tip_header", "params": [], "id": 1}'
> ```
> 
> That number is based on the current epoch, if get_tip_header calls fail, it may show NaN.

I have select from get_tip_header method ,and found that sync schedule always slower then current schedule,some data of these two parts show NaN  like this.Why not all data in these two parts show NaN?Maybe it may confuse user.
<img width="1298" alt="截屏2023-10-08 09 46 59" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/311e1fdd-5b75-4453-9d5d-c7340a9e8110">

**Comment by yanguoyu** [comment]
> 3.I have send a locktime transaction ,transaction hash is 0x39189b76094e69940312743daf1765e2890ae241a53f4b830dfc2eb63872f7b8,which block number is 10869532.But I cannot see this in customized assets when sync block is 10872475 <img alt="截屏2023-10-07 16 26 56" width="1101" src="https://user-images.githubusercontent.com/25971273/273374422-9cb63811-e934-4dba-83e8-538c7f1e16af.png">
> 
> <img alt="截屏2023-10-07 16 27 07" width="1138" src="https://user-images.githubusercontent.com/25971273/273374430-b34bb79a-298c-4583-a729-707fee8d9864.png"> <img alt="截屏2023-10-07 16 26 21" width="1328" src="https://user-images.githubusercontent.com/25971273/273374441-a2fad8bc-6399-4733-87ba-37a6bfac6252.png">

Fixed by https://github.com/nervosnetwork/neuron/pull/2860

**Comment by silySuper** [comment]
> > > These 2 parts sometimes shows normally, then shows NaN or -- when is syncing
> > 
> > 
> > We can call rpc to ensure that light client rpc is running and `get_tip_header` call success:
> > ```shell
> > curl http://localhost:9000/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "get_tip_header", "params": [], "id": 1}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That number is based on the current epoch, if get_tip_header calls fail, it may show NaN.
> 
> I have select from get_tip_header method ,and found that sync schedule always slower then current schedule,some data of these two parts show NaN like this.Why not all data in these two parts show NaN?Maybe it may confuse user. <img alt="截屏2023-10-08 09 46 59" width="1298" src="https://user-images.githubusercontent.com/25971273/273420520-311e1fdd-5b75-4453-9d5d-c7340a9e8110.png">

Link issue：https://github.com/Magickbase/neuron-public-issues/issues/294

**Comment by silySuper** [comment]
4.In Asset Accounts/Send,when  click - ，the style shows abnormal.
<img width="1198" alt="截屏2023-10-08 15 10 53" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ff11f4eb-83f4-4970-a6c9-f25fba3b2bd3">

**Comment by silySuper** [comment]
5.when window is smallest ,sign or verify message window  lost sign button

<img width="1037" alt="截屏2023-10-08 16 22 45" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/915838f3-c9de-4ac4-b8b4-535cad9e9ff9">

6.when window is smallest ,multisig address window shows abnormal.
<img width="677" alt="截屏2023-10-08 16 02 34" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/aa0ca7b4-3e7c-4068-b2ac-993ba8aaaf47">

**Comment by yanguoyu** [comment]
@silySuper 
> 4.In Asset Accounts/Send,when click full screen /not full screen，the style shows abnormal.
> 5.when window is smallest ,sign or verify message window lost sign button

They are fixed by https://github.com/nervosnetwork/neuron/pull/2860

**Comment by silySuper** [comment]
1.No.1 and No.3 will be optimized in later versions,others has been verified.
