### ISSUE TITLE
"Compare checksums" action should be updated due to github runner upgrade

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#295]
An annotation was found at https://github.com/nervosnetwork/neuron/actions/runs/6476114715

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by devchenyan** [comment]
finished: https://github.com/nervosnetwork/neuron/pull/2917
