### ISSUE TITLE
Font is rendered improperly in Neuron@v0.110.3 for Linux

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#296]
I've learned that the font is a bit ugly on Linux, and I've confirmed from the screenshot that the font is different from the design.

But I'm not sure if the font is not correctly rendered by Linux, or if the font doesn't take effect in Neuron on Linux

@frederlu  @silySuper please have a check on it

**Comment by Keith-CY** [comment]
It's how it looks like
<img width="223" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/34aaaad8-9522-45cd-8be6-cb4c9844ca5b">

**Comment by yanguoyu** [comment]
Except for some special fonts, others will use system fonts.

**Comment by Kirl70** [comment]
Communicate with @yanguoyu, perhaps we can embed the specified font file into the Linux installation package and then check the display effect.

Font file: [font-Inter.zip](https://github.com/Magickbase/neuron-public-issues/files/12876485/font-Inter.zip)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2873 @Kirl70 Please help me have a check.
