### ISSUE TITLE
Keep width of sidebar fixed

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#297]
https://github.com/Magickbase/neuron-public-issues/assets/7271329/16d3fc00-c5f8-4995-b2a9-8261a04a7e2a

The width of the sidebar changes when `experimental` collapses/expands. It's unusual in application and can be avoided by the following solution:
1. increase the min-width of the sidebar
2. decrease the left-padding of sub-items in `experimental`

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2870
