### ISSUE TITLE
Issues of  cell management testing

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#298]
These issues found in light client mode.
1.Icon shows wrong.
UI document:
<img width="890" alt="截屏2023-10-13 10 08 15" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/9c0d3aab-5984-474e-9a6d-3d81b24747b8">

Actual:
<img width="1007" alt="截屏2023-10-13 09 43 04" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6a56dcc9-5400-48a8-9ce8-60ff31773792">

2.Lost total number ：
UI document：
<img width="883" alt="截屏2023-10-13 10 07 04" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/b5cbed0b-865c-40b1-9fbd-d6f3e17b15a3">
Actual:
<img width="1006" alt="截屏2023-10-13 09 44 17" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/06d494b5-1960-4234-8612-3fd2b2969741">

3.When description is long UI shows abnormal:
<img width="1022" alt="截屏2023-10-13 09 45 41" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/f2ad1be9-706a-4952-b622-612468059e92">

4.Click anywhere in record line can pop up cell detail window actually ,but in expect only click detail icon can  pop up cell detail window.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/0ea59130-e88e-4382-8778-5a6f76445761

5.When lock cell it shows warn:
<img width="635" alt="截屏2023-10-13 10 12 50" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c67997e8-e6b3-4c49-a23c-c9e6320d4fbb">
but actually after lock cell ,then spend icon is not gray and can  jump to send page ,send transaction  successfully.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/79b2604c-ac80-4680-8ebb-a3409ccf12ea

6.When click locked balance it jump to cell management page which include locked cell and unlocked cell,may be jump to locked cell page is better.

<img width="1195" alt="截屏2023-10-13 09 59 43" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/1cc783b9-fb2a-46d6-b185-dedb51af34c1">

7.Locked  reason does not show like this is  requirement document:
<img width="827" alt="截屏2023-10-13 10 32 51" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/e4d13c64-d722-41ce-b6c5-123256b2c8a1">
Actual:
<img width="995" alt="截屏2023-10-13 10 01 17" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6575b4fb-32c8-4812-af31-e13cb0ceec5d">

**Comment by yanguoyu** [comment]
> 5. but actually after lock cell ,then spend icon is not gray and can jump to send page ,send transaction successfully.

IMO, it can not be used on others' pages, but I can use this cell in the cell manage page. @Danie0918 Can we use the locked cell in the cell manage page?

> 6. When click locked balance it jump to cell management page which include locked cell and unlocked cell,may be jump to locked cell page is better.

Neuron does not have a page that only shows locked cells, what do you think? @Danie0918 

> 7 .Locked reason does not show like this is requirement document:

Because of some cells are default locked, their locked reasons are different.

**Comment by silySuper** [comment]
To N0.7 issue ,my lock reason is same to requirement document,because I have sent a locktime transaction，requirement description is more clear than actual description.

**Comment by Danie0918** [comment]
> > 5. but actually after lock cell ,then spend icon is not gray and can jump to send page ,send transaction successfully.
> 
> IMO, it can not be used on others' pages, but I can use this cell in the cell manage page. @Danie0918 Can we use the manually locked cells in the cell manage page?
> 
Manually locked cells can't be spent.

> > 6. When click locked balance it jump to cell management page which include locked cell and unlocked cell,may be jump to locked cell page is better.
> 
> Neuron does not have a page that only shows locked cells, what do you think? @Danie0918
> 
Instead of adding a separate page, you can optimize it a bit by sorting by default to show the locked cells first.By the way, sorting is still in effect when there are no locked cells.

**Comment by yanguoyu** [comment]
> Instead of adding a separate page, you can optimize it a bit by sorting by default to show the locked cells first.By the way, sorting is still in effect when there are no locked cells.

Do you mean when I click the locked balance, then Neuorn should go to the cell manage page, and set default sort by locked field?

**Comment by yanguoyu** [comment]
> To N0.7 issue ,my lock reason is same to requirement document,because I have sent a locktime transaction，requirement description is more clear than actual description.

@Danie0918 Do we have tips for different default-locked cells? Currently, I remind users to operate the locked cells on the corresponding page.

**Comment by Danie0918** [comment]
> Do we have tips for different default-locked cells? Currently, I remind users to operate the locked cells on the corresponding page.

Yes.

**Comment by yanguoyu** [comment]
> > Do we have tips for different default-locked cells? Currently, I remind users to operate the locked cells on the corresponding page.
> 
> Yes.

Where can I find the tips for different default-locked cells?

**Comment by silySuper** [comment]
8.Type field in overview page is different from history page at the same transaction.
<img width="981" alt="截屏2023-10-13 11 08 53" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/cc3ad922-5552-4faa-b5da-72660e7bea01">
<img width="990" alt="截屏2023-10-13 11 09 09" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/5547749e-f281-4ef5-970e-bcc8eff306d1">

**Comment by Danie0918** [comment]
> > > Do we have tips for different default-locked cells? Currently, I remind users to operate the locked cells on the corresponding page.
> > 
> > 
> > Yes.
> 
> Where can I find the tips for different default-locked cells?

Are we currently without relevant tips? This hint in the requirements is what I found in the custom assets.

**Comment by Danie0918** [comment]
> I mean where can I find the document that describes tips content for different default-locked cells?

Currently it's not, my hints in the documentation are just examples.

If we don't have a default prompt, we may need to organize the use cases and then I'll provide the documentation.

**Comment by silySuper** [comment]
9.Order by status is opposite to icon.
<img width="1201" alt="截屏2023-10-13 15 18 36" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/3ce29b0d-208e-4601-b51b-26509250cb5c">

**Comment by yanguoyu** [comment]
> 9.Order by status is opposite to icon.

Order by status `ASC`, unlock cell will before than locked cell.

**Comment by silySuper** [comment]
> > 9.Order by status is opposite to icon.
> 
> Order by status `ASC`, unlock cell will before than locked cell.

Does it not order by English alphabet？In English alphabet L is before U,I see that order by type field satisfy English alphabet.
<img width="453" alt="截屏2023-10-13 15 26 54" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/031d0247-2d12-4d4f-bb4d-fbf5f851d04a">

**Comment by yanguoyu** [comment]
1.类型-CKB, UDT, NTF, Unknown
2.状态-解锁, 锁定
@silySuper S

**Comment by yanguoyu** [comment]
> > I mean where can I find the document that describes tips content for different default-locked cells?
> 
> Currently it's not, my hints in the documentation are just examples.
> 
> If we don't have a default prompt, we may need to organize the use cases and then I'll provide the documentation.

There are these default lock types:
1. lock script
    - Cheque
    - multisig-lock-time
    - multisig
    - anyone-can-pay
    - unknown
2. type script
    - nft
    - nft-issue
    - nft-class
    - sudt
    - dao
    - unknown

**Comment by yanguoyu** [comment]
1, 2, 3, 4, 5, 6 have been fixed by https://github.com/nervosnetwork/neuron/pull/2859/commits/8e3abb52cc2cad2298a2639987470a1d9a795777

**Comment by yanguoyu** [comment]
> 8.Type field in overview page is different from history page at the same transaction.

It's an issue on the develop branch, I opened a new PR to fix it. https://github.com/nervosnetwork/neuron/pull/2876

**Comment by silySuper** [comment]
9.Batch locking cells can be unlocked again after unlocking.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/ea64a27f-70f0-49eb-961b-49dab9705381


10.Batch consume send balance is not fit for max balance.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/22d08893-67a5-4027-b849-ef678e8f9a12

**Comment by yanguoyu** [comment]
> 9.Batch locking cells can be unlocked again after unlocking.

I guess it's normal, otherwise if users want to lock or unlock all cells, they should pick one by one. What do you think? @Danie0918

**Comment by silySuper** [comment]
> > 9.Batch locking cells can be unlocked again after unlocking.
> 
> I guess it's normal, otherwise if users want to lock or unlock all cells, they should pick one by one. What do you think? @Danie0918

To No.9 issue,another operation is the same result.Maybe judge status is better.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/4dceb0bc-2f12-4bb4-87e5-99a042b12309

**Comment by silySuper** [comment]
12.If I chosed cells include both locked and unlocked status.The balance in lock pop up window and in unlock pop up window show abnormal.In expect ,lock balance is about 236712,unlock balance is about 1513.8.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/9bd14d59-6f4f-481c-83fe-7a95ac32c7b9

**Comment by Danie0918** [comment]
> > > 9.Batch locking cells can be unlocked again after unlocking.
> > 
> > 
> > I guess it's normal, otherwise if users want to lock or unlock all cells, they should pick one by one. What do you think? @Danie0918
> 
> To No.9 issue,another operation is the same result.Maybe judge status is better.
> 
>  2023-10-17.15.25.26.mov

It may be a bit weird for the user, when the operation is not valid.

For batch operations, if all of them are unlocked or locked, the corresponding operations should be disabled.A batch operation should operate normally only if it can have a target to execute.

This means that when the cells selected in a batch are all unlocked, then the unlock operation should be disabled unless it contains cells that can be unlocked.

Again this applies to the lock.

**Comment by yanguoyu** [comment]
> > > > 9.Batch locking cells can be unlocked again after unlocking.
> > > 
> > > 
> > > I guess it's normal, otherwise if users want to lock or unlock all cells, they should pick one by one. What do you think? @Danie0918
> > 
> > 
> > To No.9 issue,another operation is the same result.Maybe judge status is better.
> > 2023-10-17.15.25.26.mov
> 
> It may be a bit weird for the user, when the operation is not valid.
> 
> For batch operations, if all of them are unlocked or locked, the corresponding operations should be disabled.A batch operation should operate normally only if it can have a target to execute.
> 
> This means that when the cells selected in a batch are all unlocked, then the unlock operation should be disabled unless it contains cells that can be unlocked.
> 
> Again this applies to the lock.

If users select locked and unlocked cells, could they batch lock or unlock these cells?

**Comment by Danie0918** [comment]
> > > > > 9.Batch locking cells can be unlocked again after unlocking.
> > > > 
> > > > 
> > > > I guess it's normal, otherwise if users want to lock or unlock all cells, they should pick one by one. What do you think? @Danie0918
> > > 
> > > 
> > > To No.9 issue,another operation is the same result.Maybe judge status is better.
> > > 2023-10-17.15.25.26.mov
> > 
> > 
> > It may be a bit weird for the user, when the operation is not valid.
> > For batch operations, if all of them are unlocked or locked, the corresponding operations should be disabled.A batch operation should operate normally only if it can have a target to execute.
> > This means that when the cells selected in a batch are all unlocked, then the unlock operation should be disabled unless it contains cells that can be unlocked.
> > Again this applies to the lock.
> 
> If users select locked and unlocked cells, could they batch lock or unlock these cells?

This is possible because unlock and lock can be applied to some of the cells.

**Comment by silySuper** [comment]
1.Verified
2.Verified
3.Verified
4.Verified
5.Although after lock cell ,then spend icon is  gray，but it can jump to send page ,send transaction successfully.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/96191984-5354-4160-805e-8dd921f17af7

6.Verified
8.Verified

**Comment by yanguoyu** [comment]
> 10.Batch consume send balance is not fit for max balance.

IMO, when consuming some cells on the send page, clicking max will cost all of the selected cells. Or send the max of the wallet? @Danie0918  cc @silySuper 
<img width="725" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/7eadd8cf-a43e-4206-a752-b6dc3c96cecc">

<img width="600" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/cde10926-b8dc-451b-bf44-f71c8cc5132d">

**Comment by yanguoyu** [comment]
> > > 10.Batch consume send balance is not fit for max balance.
> > 
> > 
> > IMO, when consuming some cells on the send page, clicking max will cost all of the selected cells. Or send the max of the wallet? @Danie0918 cc @silySuper <img alt="image" width="725" src="https://user-images.githubusercontent.com/12881040/276185049-7eadd8cf-a43e-4206-a752-b6dc3c96cecc.png">
> > <img alt="image" width="600" src="https://user-images.githubusercontent.com/12881040/276185492-cde10926-b8dc-451b-bf44-f71c8cc5132d.png">
> 
> Here the consume should be brought to the maximum value of the selected cell without the user manually clicking on max.

Okay, so the max value is the selected cells's total capacity but not wallet's total capacity.

**Comment by yanguoyu** [comment]
> 12.If I chosed cells include both locked and unlocked status.The balance in lock pop up window and in unlock pop up window show abnormal.In expect ,lock balance is about 236712,unlock balance is about 1513.8.

The title is unlocked balance, which means that total cell capacity will be unlocked. But not the current unlocked capacity.
I guess we should show all of the selected cells's capacity, what do you think? @Danie0918

**Comment by yanguoyu** [comment]
5,9 have been fixed. @silySuper

**Comment by silySuper** [comment]
I want to regress in full node mode，but app always shows 
<img width="364" alt="截屏2023-10-19 10 29 30" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/802497be-8c30-44f2-a50d-2686bd058400">

This is my log:
[neuron_debug_1697682503785.zip](https://github.com/Magickbase/neuron-public-issues/files/13036157/neuron_debug_1697682503785.zip)

**Comment by yanguoyu** [comment]
> I want to regress in full node mode，but app always shows <img alt="截屏2023-10-19 10 29 30" width="364" src="https://user-images.githubusercontent.com/25971273/276462253-802497be-8c30-44f2-a50d-2686bd058400.png">
> 
> This is my log: [neuron_debug_1697682768607.zip](https://github.com/Magickbase/neuron-public-issues/files/13036173/neuron_debug_1697682768607.zip)


This is the log. 
```
[2023-10-19 10:18:04.066] [error] Sync:ChildProcess: /private/var/folders/0g/2f1xzp_x46d7kr74mybk85jc0000gn/T/AppTranslocation/6C3F7234-9F9D-4D63-8FB0-9E95D4E8F132/d/Neuron 2.app/Contents/Resources/app.asar/node_modules/@ckb-lumos/rpc/lib/method.js:73
          throw new _exceptions.ResponseException(JSON.stringify(res.data.error));
                ^

ResponseException [Error]: {"code":-4,"message":"RPCModuleIsDisabled: This RPC method is in the module `Indexer`. Please modify `rpc.modules` in ckb.toml and restart the ckb node to enable it."}
```

It means you need to start ckb with `--indexer`, but the Neuron should show a dialog to notify users, I will check why the dialog is not shown.

**Comment by Danie0918** [comment]
> > 12.If I chosed cells include both locked and unlocked status.The balance in lock pop up window and in unlock pop up window show abnormal.In expect ,lock balance is about 236712,unlock balance is about 1513.8.
> 
> The title is unlocked balance, which means that total cell capacity will be unlocked. But not the current unlocked capacity. I guess we should show all of the selected cells's capacity, what do you think? @Danie0918

Sure, all of the selected cells's capacity should be shown here.

**Comment by silySuper** [comment]
> > > 12.If I chosed cells include both locked and unlocked status.The balance in lock pop up window and in unlock pop up window show abnormal.In expect ,lock balance is about 236712,unlock balance is about 1513.8.
> > 
> > 
> > The title is unlocked balance, which means that total cell capacity will be unlocked. But not the current unlocked capacity. I guess we should show all of the selected cells's capacity, what do you think? @Danie0918
> 
> Sure, all of the selected cells's capacity should be shown here.

It means that only show  all of the selected cells's capacity  when batch lock or unlock ,and not distinguish lock or unlock cell in this  window? @Danie0918 
<img width="643" alt="截屏2023-10-19 15 06 27" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c69b4cac-517d-4f5d-a50b-3773474d4cae">

**Comment by yanguoyu** [comment]
> > I want to regress in full node mode，but app always shows <img alt="截屏2023-10-19 10 29 30" width="364" src="https://user-images.githubusercontent.com/25971273/276462253-802497be-8c30-44f2-a50d-2686bd058400.png">
> > This is my log: [neuron_debug_1697682768607.zip](https://github.com/Magickbase/neuron-public-issues/files/13036173/neuron_debug_1697682768607.zip)
> 
> This is the log.
> 
> ```
> [2023-10-19 10:18:04.066] [error] Sync:ChildProcess: /private/var/folders/0g/2f1xzp_x46d7kr74mybk85jc0000gn/T/AppTranslocation/6C3F7234-9F9D-4D63-8FB0-9E95D4E8F132/d/Neuron 2.app/Contents/Resources/app.asar/node_modules/@ckb-lumos/rpc/lib/method.js:73
>           throw new _exceptions.ResponseException(JSON.stringify(res.data.error));
>                 ^
> 
> ResponseException [Error]: {"code":-4,"message":"RPCModuleIsDisabled: This RPC method is in the module `Indexer`. Please modify `rpc.modules` in ckb.toml and restart the ckb node to enable it."}
> ```
> 
> It means you need to start ckb with `--indexer`, but the Neuron should show a dialog to notify users, I will check why the dialog is not shown.

I have added a log when checking the external ckb node. You can package and try again without `--indexer` and wait for about 30s, if the dialog also can not show, upload the log again, then I will try to fix it. @silySuper

**Comment by Danie0918** [comment]
> > > > 12.If I chosed cells include both locked and unlocked status.The balance in lock pop up window and in unlock pop up window show abnormal.In expect ,lock balance is about 236712,unlock balance is about 1513.8.
> > > 
> > > 
> > > The title is unlocked balance, which means that total cell capacity will be unlocked. But not the current unlocked capacity. I guess we should show all of the selected cells's capacity, what do you think? @Danie0918
> > 
> > 
> > Sure, all of the selected cells's capacity should be shown here.
> 
> It means that only show all of the selected cells's capacity when batch lock or unlock ,and not distinguish lock or unlock cell in this window? @Danie0918 <img alt="截屏2023-10-19 15 06 27" width="643" src="https://user-images.githubusercontent.com/25971273/276518224-c69b4cac-517d-4f5d-a50b-3773474d4cae.png">

Yes, no distinction is made here.

**Comment by silySuper** [comment]
5.Verified
9.Verified.

**Comment by Danie0918** [comment]
> * anyone-can-pay

This can be categorized as follows:

1. [Lock time] The cell has a time lock and you can't use it until 2023-09-05.
2. [Lockscript ] This is a Cheque/ACP/Multisig  cell and does not support unlocking.
3. [Typescript ] This is a NFT/SUDT/Nervos DAO  asset and does not support unlocking.
4. [Unkonw] This is an uncataloged asset,please check and confirm before proceeding.

**Comment by yanguoyu** [comment]
> 1. [Lock time] The cell has a time lock and you can't use it until 2023-09-05.

@Danie0918  Sometimes this cell has reached the unlock time, but the user does not unlock it. Do you think we should change to another tip with this condition?

**Comment by Danie0918** [comment]
> > 1. [Lock time] The cell has a time lock and you can't use it until 2023-09-05.
> 
> @Danie0918 Sometimes this cell has reached the unlock time, but the user does not unlock it. Do you think we should change to another tip with this condition?

[Lock time - expires ] The time lock for this cell has expired and you need to claim it in Customized Assets before using it.

**Comment by yanguoyu** [comment]
@silySuper  Please verify the left issues with the latest package.

**Comment by silySuper** [comment]
1.No.10 Batch consume send balance is not fit for max balance does not need to change? @Danie0918 
2.No.7 
(1).verified
(2).verified
(3).Send NFT successful,but cell mangement shows  type  is unknown.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/71c2023e-66ca-4f0a-86a3-51ee7cff05c8




<img width="932" alt="截屏2023-11-22 17 29 40" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/fce59faf-ef69-42b4-9c34-8975c4955fe3">

(4).verified

**Comment by yanguoyu** [comment]
> Send NFT successful,but cell mangement shows type is unknown.

The Spore type has been adapted. 

> No.10 Batch consume send balance is not fit for max balance does not need to change? 

I can't get the point. Does the `batch consume` not send max?


https://github.com/Magickbase/neuron-public-issues/assets/12881040/f216459f-7d8a-4f93-a339-d5c9e402c9ca

**Comment by silySuper** [comment]
> > Send NFT successful,but cell mangement shows type is unknown.
> 
> The Spore type has been adapted.
> 
> > No.10 Batch consume send balance is not fit for max balance does not need to change?
> 
> I can't get the point. Does the `batch consume` not send max?
> 
>  2023-11-22.19.13.07.mov

<img width="998" alt="截屏2023-11-23 10 32 12" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/bc71718b-6fd2-4058-9224-079f2e6dab8e">

here need change to chosed balance ,the same to send page ?

**Comment by yanguoyu** [comment]
> > > Send NFT successful,but cell mangement shows type is unknown.
> > 
> > 
> > The Spore type has been adapted.
> > > No.10 Batch consume send balance is not fit for max balance does not need to change?
> > 
> > 
> > I can't get the point. Does the `batch consume` not send max?
> > 2023-11-22.19.13.07.mov
> 
> <img alt="截屏2023-11-23 10 32 12" width="998" src="https://user-images.githubusercontent.com/25971273/285086553-bc71718b-6fd2-4058-9224-079f2e6dab8e.png">
> here need change to chosed balance ,the same to send page ?

@Danie0918

**Comment by Danie0918** [comment]
> 1.No.10 Batch consume send balance is not fit for max balance does not need to change? @Danie0918 2.No.7 (1).verified 



> > > > Send NFT successful,but cell mangement shows type is unknown.
> > > 
> > > 
> > > The Spore type has been adapted.
> > > > No.10 Batch consume send balance is not fit for max balance does not need to change?
> > > 
> > > 
> > > I can't get the point. Does the `batch consume` not send max?
> > > 2023-11-22.19.13.07.mov
> > 
> > 
> > <img alt="截屏2023-11-23 10 32 12" width="998" src="https://user-images.githubusercontent.com/25971273/285086553-bc71718b-6fd2-4058-9224-079f2e6dab8e.png">
> > here need change to chosed balance ,the same to send page ?
> 
> @Danie0918

This does lead to some misunderstandings, can we hide the balance in this case? @yanguoyu

**Comment by yanguoyu** [comment]
> This does lead to some misunderstandings, can we hide the balance in this case?

It has been hidden when spending appointed cells. @silySuper
