### ISSUE TITLE
Support mail us in `menu -> help -> report issue`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#30]
It would be convenient for users who are not programmers.

**Comment by Keith-CY** [comment]
Add a `contact us` menu inside `help` which invokes the local mail client to `neuron@magickbase.com`

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2454

**Comment by Keith-CY** [comment]
We will update the workflow because there're so many exceptions on opening a local mail client
1. Operating system may not set the default client for Email
2. Operating system may set an invalid client for Email

So we are going the set the workflow as following:
1. Click `Menu -> Help -> Contact Us` to popup a dialog with message `Please email us with debug information exported by "Menu" -> "Help" -> "Export Debug Information".`, a `cancel` button, a `open email client` button and a `copy email address` button
2. click `cancel` to dismiss the dialog
3. click `open email client` to open the default email client with template `> Please append debug information exported by "Menu" -> "Help" -> "Export Debug Information".`
4. click `copy email address` to write `neuron@magickbase.com` into clipboard

**Comment by Cedar67** [comment]
This PR has been verified. It will be merged into the next release version.
