### ISSUE TITLE
Unify timezone in logs

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#300]
There are several logs in the debug information, and I'll compare `bundled-ckb.log` and `main.log` for some details. But their timezones are different. `bundled-ckb.log` uses **UTC+0** timezone while `main.log` uses **local timezone**. So, I have to compare the minutes to match the logs.

Here I suggest using UTC+0 timezone in `main.log` so it would be easy to match logs, and the logs will be timezone-agnostic.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2877
