### ISSUE TITLE
Issues of show the migrate ckb data dialog testing

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#301]
1.It  costs several  minitues to show migrate window again after I click cancel  or X button in migrate pop up window.It is hard to see this migrate window.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/5c85d7bf-03fe-4e54-b417-f784160ef4df

2.After I clear Users/${username}/Library/Application Support/Neuron/Local Storage,when I click the app,it requires to create a new wallet,then the migrate  pop up window show up in create wallet window.
<img width="1304" alt="截屏2023-10-16 15 55 38" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/589ffd23-1600-438c-8785-dd4672b8802b">

3.When I click migrate button ,it pop up an error window.

<img width="1002" alt="截屏2023-10-16 16 07 08" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/202ca7ec-5cfa-40ff-94c2-f99580a97969">

**Comment by silySuper** [comment]
1.To No.1 I have reopened neuron again,but it not show.
2.I mean it is suitable to show this migrate window  when create wallet?
3.Firstly,I do not know why my data has locked.Secondly ,IMO,to users tell them how to operate is better than just show error.

**Comment by yanguoyu** [comment]
>2 .I mean it is suitable to show this migrate window when create wallet?

This situation will not occur during normal operation

> 3.To No.3 issue ,Firstly,I do not know why my data has locked.Secondly ,IMO,to users tell them how to operate is better than just show error.

There may exist unknown conditions to cause migration failure, and this is one of the conditions, we can tell users how to do when the exception happens. But we can not know which the exception will come.

**Comment by yanguoyu** [comment]
https://github.com/Magickbase/neuron-public-issues/assets/12881040/bf64569c-d721-4d6c-ba56-fe0733e3e01b

From this video, we know that the migrate dialog will show after restarting the Neuron. Neuron was downloaded from https://github.com/nervosnetwork/neuron/actions/runs/6527826934.
Could you export your debug information when the dialog does not show after reopening the Neuron?

**Comment by silySuper** [comment]
> reopen-neuron.mov 
> From this video, we know that the migrate dialog will show after restarting the Neuron. Neuron was downloaded from https://github.com/nervosnetwork/neuron/actions/runs/6527826934. Could you export your debug information when the dialog does not show after reopening the Neuron?

I have deleted the lock file and local storage again ,then I reopen the app,it does not show the migrate dialog,this is the log.
[neuron_debug_1697445760277.zip](https://github.com/Magickbase/neuron-public-issues/files/12914116/neuron_debug_1697445760277.zip)

**Comment by yanguoyu** [comment]
> > reopen-neuron.mov
> > From this video, we know that the migrate dialog will show after restarting the Neuron. Neuron was downloaded from https://github.com/nervosnetwork/neuron/actions/runs/6527826934. Could you export your debug information when the dialog does not show after reopening the Neuron?
> 
> I have deleted the lock file and local storage again ,then I reopen the app,it does not show the migrate dialog,this is the log.
> 
> [neuron_debug_1697445832349.zip](https://github.com/Magickbase/neuron-public-issues/files/12914129/neuron_debug_1697445832349.zip)

From the log, it shows that your 8114 port has been used, could you check your 8114 port?
