### ISSUE TITLE
package by comment runs incorrect with incorrect commit

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#307]
run id: https://github.com/nervosnetwork/neuron/actions/runs/6657931841
commented on
https://github.com/nervosnetwork/neuron/issues/2913#issuecomment-1781578717
[ f3cc18a](https://github.com/nervosnetwork/neuron/commit/f3cc18a45cbfcf5a77c2d46630e49c096c8ff5ca)

It runs for commit "refactor: remove ckb-sdk-core and replace with lumos"

**Comment by yanguoyu** [comment]
This issue_comment will only trigger a workflow run if the workflow file is on the default branch. When the event has been triggered, the yml config is the config at the time of triggering.

**Comment by Keith-CY** [comment]
Make sense, so `update on Package for test` is an exception for running this action.
