### ISSUE TITLE
Neuron Help Center Home Page Document Sorting Rules

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#310]
![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/a70b5a2b-2c3e-4ed2-bd06-dd34655f1a75)

Document Sorting Rules:

1. Guide:Fixed display in document order.
2. FAQ:Sort the documents by the number of times they have been viewed, from highest to lowest.
3. Announcement:Sort chronologically from newest to latest.

**Comment by WhiteMinds** [comment]
Sorting for Guide and Announcement has been implemented in https://github.com/Magickbase/neuron-troubleshooting/commit/2194863b73d63576c0d4f0ac4901a68f76b05e0b.

For FAQ, it is temporarily sorted according to Guide, and I will investigate the implementation cost of the view count feature.

**Comment by WhiteMinds** [comment]
The sorting function for FAQ based on view count has been deployed.

Although the view count is calculated in real-time, this sorting only occurs during the deployment phase.

Currently, it is automatically redeployed at 0:00 in the +0 time zone every day.

This is to avoid the complexity of implementation and the computing resources required.
