### ISSUE TITLE
Download page: add 'check the checksum' documentation link

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#312]
![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/d8014243-c064-45e5-b291-5a2cdac5d7f6)

![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/6fe3addb-741b-4310-ad0b-5ba43cb73e7a)

When clicking on 'check the Checksum' in the float, it jumps to the document 'How to verify with Checksum ?'

**Comment by Danie0918** [comment]
@Kirl70 Currently there is only a bolded style here, and it needs to have a color added to give the user guidance that it is clickable.

**Comment by Kirl70** [comment]
> @Kirl70 Currently there is only a bolded style here, and it needs to have a color added to give the user guidance that it is clickable.

The design draft has been adjusted.
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=19033%3A39943&mode=design&t=pmZTIPCogeKrd7EO-1

<img width="991" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/5e7cc64c-02cc-475c-a62d-ae14ff478dd1">

**Comment by Danie0918** [comment]
PRD：https://lb84z6.axshare.com/#g=1&p=download  @WhiteMinds @Kirl70 @Keith-CY 

![download](https://github.com/Magickbase/neuron-public-issues/assets/122437870/b1e40e8b-a693-4d42-b65b-f275e6d16f83)

Because of the compatibility problems with versions below win10, we need to add a system tip to the download page.

**Comment by WhiteMinds** [comment]
Currently, the data for this table is parsed from the body of the release: https://github.com/Magickbase/websites/blob/de189515332c7b52a528cc13a109e1f350658c7c/packages/neuron/src/utils/github.ts#L237-L260 

So if you want to mark Windows as 10 / 11, it might be better to modify the release body as well.

Otherwise, the code here needs to do special processing, check if `os === 'windows'` and after a certain version (that supports earlier systems), then `os += '10 / 11'` and provide a tooltip.

If the body itself is changed, the logic here is to provide a tooltip when `os === 'windows 10 / 11'`, which is relatively more like a normal business logic.

**Comment by WhiteMinds** [comment]
If a JSON file containing OS/Arch/Package/Checksum/DownloadLink could be provided in each Release Assets, it might be more standardized.

And implementing a script to batch add this JSON file to old Releases might not be very difficult.

**Comment by yanguoyu** [comment]
> Currently, the data for this table is parsed from the body of the release: https://github.com/Magickbase/websites/blob/de189515332c7b52a528cc13a109e1f350658c7c/packages/neuron/src/utils/github.ts#L237-L260
> 
> So if you want to mark Windows as 10 / 11, it might be better to modify the release body as well.
> 
> Otherwise, the code here needs to do special processing, check if `os === 'windows'` and after a certain version (that supports earlier systems), then `os += '10 / 11'` and provide a tooltip.
> 
> If the body itself is changed, the logic here is to provide a tooltip when `os === 'windows 10 / 11'`, which is relatively more like a normal business logic.
> 
> @yanguoyu @Keith-CY What do you think?

Add the Windows version sounds better, and showing the tooltip should be controlled by `os.include('windows')`, because Microsoft may introduce Windows 12 later.

But I have no idea about how to add the Windows version in the release note.

**Comment by WhiteMinds** [comment]
> Add the Windows version sounds better, and showing the tooltip should be controlled by `os.include('windows')`, because Microsoft may introduce Windows 12 later.
> 
> But I have no idea about how to add the Windows version in the release note.

Consider using `Windows 10+`?

**Comment by Keith-CY** [comment]
> > Add the Windows version sounds better, and showing the tooltip should be controlled by `os.include('windows')`, because Microsoft may introduce Windows 12 later.
> > But I have no idea about how to add the Windows version in the release note.
> 
> Consider using `Windows 10+`?

We may open another issue for the annotation of Windows compatibility and close this one first because this one is only for guiding users how to verify checksums
