### ISSUE TITLE
Issues with adapt switch internal network type, and notify the user network type is not running external

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#313]
1.The pop up add network window can only add network name ,the URL  can not be added and is 127.0.0.1:8114 by default.
<img width="682" alt="截屏2023-11-06 15 52 18" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/dabe84de-5e3a-4e5b-992c-1638ee1299fa">

2.Must chose external node , or else the pop up window can not be closed. At this time ,my ckb node config is null.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/aa1641aa-c9fa-4876-abf3-cb3d60f70d3a

3.The change feature like a tip.May be click the change icon to change is better in user experience.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/7c1d8f52-69cf-400c-8f13-8e34f41ef27d

4.Switch internal and external nodes back and forth，the   internal node port can not be changed to 8116.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/342ccb7a-7139-4b5a-89b1-89d079999ece

**Comment by yanguoyu** [comment]
> 1.The pop up add network window can only add network name ,the URL can not be added and is 127.0.0.1:8114 by default.

Because the used port is 8114, setting the remote as 8114 is better. Otherwise, after the user adds a network, there will be no network to choose either. @Danie0918 what do you think?


For 2 and 4, which action package do you use?

**Comment by silySuper** [comment]
> > 1.The pop up add network window can only add network name ,the URL can not be added and is 127.0.0.1:8114 by default.
> 
> Because the used port is 8114, setting the remote as 8114 is better. Otherwise, after the user adds a network, there will be no network to choose either. @Danie0918 what do you think?
> 
> For 2 and 4, which action package do you use?

 Because I download and test before the  latest package:this package is my testing package: https://github.com/nervosnetwork/neuron/actions/runs/6766660238

**Comment by yanguoyu** [comment]
> > > 1.The pop up add network window can only add network name ,the URL can not be added and is 127.0.0.1:8114 by default.
> > 
> > 
> > Because the used port is 8114, setting the remote as 8114 is better. Otherwise, after the user adds a network, there will be no network to choose either. @Danie0918 what do you think?
> > For 2 and 4, which action package do you use?
> 
> Because I download and test before the latest package:this package is my testing package: https://github.com/nervosnetwork/neuron/actions/runs/6766660238

Could you test with https://github.com/nervosnetwork/neuron/actions/runs/6767347131?

**Comment by Danie0918** [comment]
> Because the used port is 8114, setting the remote as 8114 is better. Otherwise, after the user adds a network, there will be no network to choose either. @Danie0918 what do you think?

It's fine.

**Comment by silySuper** [comment]
> > > > 1.The pop up add network window can only add network name ,the URL can not be added and is 127.0.0.1:8114 by default.
> > > 
> > > 
> > > Because the used port is 8114, setting the remote as 8114 is better. Otherwise, after the user adds a network, there will be no network to choose either. @Danie0918 what do you think?
> > > For 2 and 4, which action package do you use?
> > 
> > 
> > Because I download and test before the latest package:this package is my testing package: https://github.com/nervosnetwork/neuron/actions/runs/6766660238
> 
> Could you test with https://github.com/nervosnetwork/neuron/actions/runs/6767347131?

The latest  does not show No.2 and No.4 problem.

**Comment by silySuper** [comment]
https://github.com/nervosnetwork/neuron/actions/runs/6781538780
1.This package does not see switching function
2.Internal node port does not change to 8116

https://github.com/Magickbase/neuron-public-issues/assets/25971273/c849241e-80c6-43d6-9441-eed254ed1b84

**Comment by silySuper** [comment]
5.When change to light mode ,"Switch to XXX" font is also black which is not obvious.

<img width="1016" alt="截屏2023-11-07 16 45 45" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c67956da-4967-4378-bc9c-3de000791c73">

**Comment by silySuper** [comment]
6.When change to light  client,the pop up window shows no  external network. And the port also changed from 9000 to 9001.
<img width="1004" alt="截屏2023-11-07 16 57 49" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/b1b9186a-5e98-424a-98d0-89bb6827e00c">

**Comment by Keith-CY** [comment]
> [nervosnetwork/neuron/actions/runs/6781538780](https://github.com/nervosnetwork/neuron/actions/runs/6781538780) 1.This package does not see switching function in internal node 2.Internal node port does not change to 8116
> 
>  2023-11-07.16.41.26.mov

Switch between mainnet full node and testnet full node has been disabled by https://github.com/yanguoyu/neuron/pull/98

Reason: 

> Testnet full node can be accessed by an external node, and it requires another assume valid target for fast sync.
> 
> Besides, it's prone to download massive data by accident.
> 
> So Testnet full node is removed from the built-in network options. And users may connect to an external one.

**Comment by yanguoyu** [comment]
> https://github.com/nervosnetwork/neuron/actions/runs/6781538780 1.This package does not see switching function in internal node 2.Internal node port does not change to 8116
> 
>  2023-11-07.16.41.26.mov

> 5.When change to light mode ,"Switch to XXX" font is also black which is not obvious.

https://github.com/nervosnetwork/neuron/pull/2921/commits/e97f8d67039df436b3783d0bb7c7ea00b0bdbcc1 has fixed 2 and 5.

**Comment by silySuper** [comment]
> https://github.com/nervosnetwork/neuron/actions/runs/6781538780 1.This package does not see switching function in internal node 2.Internal node port does not change to 8116
> 
>  2023-11-07.16.41.26.mov

It is easier to show when built-in light node service  change to internal node  back and forth ，but  ckb-light-client background process can not be closed.

<img width="942" alt="截屏2023-11-08 10 52 12" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/dafe22c5-4c1c-4544-83f5-c73e02e378d5">

**Comment by silySuper** [comment]
No.1 does not need changed.
No.2  and No.4 does not need changed  in external node.But shows up in light client network(No.6).
No.3 wait for verification.
No.5 has verified.

**Comment by yanguoyu** [comment]
No.3 has fixed by https://github.com/nervosnetwork/neuron/pull/2926.

**Comment by silySuper** [comment]
No.3 has verified.

**Comment by yanguoyu** [comment]
Please check the No.6 by https://github.com/nervosnetwork/neuron/pull/2928

**Comment by yanguoyu** [comment]
No.3 has been updated with the new UI https://github.com/nervosnetwork/neuron/pull/2926.

**Comment by silySuper** [comment]
No.6 has verified.

**Comment by silySuper** [comment]
No.3 has verified.
