### ISSUE TITLE
Neuron for Dev node

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#315]
This issue comes from the requirement for E2E testing of synchronization.

---

To facilitate E2E testing, a dev node full of test cases is preferable because it can be packed into the ephemeral runner of E2E.

To connect to a dev node, attributes of dev node, including genesis block hash, deployed contracts, should be registered in Neuron. They are mainly at https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env

**Comment by yanguoyu** [comment]
We will skip packaging the resources to an asar package when building a test target. Then if we want to test with dev mode, we can replace the testnet variable with dev in the `app/.env` file.
The `.env` file location.
Mac OS
<img width="502" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/1de76910-e5f4-41aa-b19f-082850e142d1">
Windows
<img width="853" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/e665aaaf-ba1f-4a05-a707-c2fa7357d9f3">
For Linux, we need to unpack the AppImage and then edit the `.env` file and pack AppImage.
Unpack Command: 
```bash
sudo ./Neuron.AppImage --appimage-extract
```
Pack Command should use `appimagetool-x86_64.AppImage` tools
```bash
appimagetool-x86_64.AppImage squashfs-root Neuron.AppImage
```

For testing the light client, we should add an external light client network by editing `setting.json`. The added item example is: 
```
{
"id":"light_client",
"name":"Light Client",
"remote":"http://127.0.0.1:9000",
"genesisHash":"0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5",
"type":2,
"chain":"light_client_dev",
"readonly":false
}
```

The `setting.json` file location:
Mac OS: `/Users/${username}/Library/Application Support/Neuron/networks/index.json`
Windows: `C:/Users/${username}/AppData/Roaming/Neuron/networks/index.json`
Linux: `/home/${username}/.config/Neuron/networks/index.json`

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/actions/runs/6848875010 is the unpack result.
