### ISSUE TITLE
Unlock DAO failed with light client

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#316]
RPC method `calculateDaoMaximumWithdraw` was not in the light client. After replacing `ckb-sdk-js` with `lumos`, it throws an error that `method not found`. The `calculateDaoMaximumWithdraw` method in `ckb-sdk-js` is not the same as the `lumos`.

`calculateDaoMaximumWithdraw` in `ckb-sdk-js`
https://github.com/ckb-js/ckb-sdk-js/blob/develop/packages/ckb-sdk-core/src/index.ts#L423-L452
`calculateDaoMaximumWithdraw` in `lumos`
https://github.com/ckb-js/lumos/blob/develop/packages/rpc/src/Base/experimental.ts#L10-L13

**Comment by Keith-CY** [comment]
The RPC https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-calculate_dao_maximum_withdraw will be removed in the future, so the amount should be calculated offline.

**Comment by homura** [comment]
Maybe we can migrate to this method [`calculateMaximumWithdrawCompatible`](https://github.com/ckb-js/lumos/blob/9fc2d671d4d28bcd7beb169ca5b89432ca6dbb4d/packages/common-scripts/src/dao.ts#L680), but it is a little more work than [before](https://github.com/nervosnetwork/neuron/blob/bc833ebbd4128f77e1c9bfa04a7e65140f0ad4ba/packages/neuron-wallet/src/services/transaction-sender.ts#L791-L799C4).

```diff
public calculateDaoMaximumWithdraw = async (
    depositOutPoint: OutPoint,
    withdrawBlockHash: string
  ): Promise<bigint> => {
    const currentNetwork = NetworksService.getInstance().getCurrent()
    const ckb = new CKBRPC(currentNetwork.remote)
-   const result = await ckb.calculateDaoMaximumWithdraw(depositOutPoint.toSDK(), withdrawBlockHash)
+   const depositHeader = await ckb.getHeader(depositBlockHash)
+   const withdrawHeader = await ckb.getHeader(withdrawBlockHash)
+   const withdrawCell = await ckb.getLiveCell(depositOutPoint.txHash)
+   return calculateMaximumWithdrawCompatible(withdrawCell, depositHeader.dao, withdrawHeader.dao)
  }
```

**Comment by Keith-CY** [comment]
> Maybe we can migrate to this method [`calculateMaximumWithdrawCompatible`](https://github.com/ckb-js/lumos/blob/9fc2d671d4d28bcd7beb169ca5b89432ca6dbb4d/packages/common-scripts/src/dao.ts#L680), but it is a little more work than [before](https://github.com/nervosnetwork/neuron/blob/bc833ebbd4128f77e1c9bfa04a7e65140f0ad4ba/packages/neuron-wallet/src/services/transaction-sender.ts#L791-L799C4).
> 
> ```diff
> public calculateDaoMaximumWithdraw = async (
>     depositOutPoint: OutPoint,
>     withdrawBlockHash: string
>   ): Promise<bigint> => {
>     const currentNetwork = NetworksService.getInstance().getCurrent()
>     const ckb = new CKBRPC(currentNetwork.remote)
> -   const result = await ckb.calculateDaoMaximumWithdraw(depositOutPoint.toSDK(), withdrawBlockHash)
> +   const depositHeader = await ckb.getHeader(depositBlockHash)
> +   const withdrawHeader = await ckb.getHeader(withdrawBlockHash)
> +   const withdrawCell = await ckb.getLiveCell(depositOutPoint.txHash)
> +   return calculateMaximumWithdrawCompatible(withdrawCell, depositHeader.dao, withdrawHeader.dao)
>   }
> ```

I found the method `calculateMaximumWithdraw` can be done with this feature implementation https://github.com/Magickbase/ckb-explorer-public-issues/issues/462 in CKB Explorer.

**Comment by yanguoyu** [comment]
> ```diff
> getLiveCell
> ```

The light client does not have the RPC named `get_live_cell`. Maybe it's better to get the live cell by another RPC method.

**Comment by Keith-CY** [comment]
Why not reuse the logic implemented at https://github.com/ckb-js/ckb-sdk-js/blob/develop/packages/ckb-sdk-core/src/index.ts#L423-L452

**Comment by homura** [comment]
> The light client does not have the RPC named `get_live_cell`. Maybe it's better to get the live cell by another RPC method.

you're right, we should use the piece of the logic below, by using `get_transaction` function instead

> Why not reuse the logic implemented at [ckb-js/ckb-sdk-js@`develop`/packages/ckb-sdk-core/src/index.ts#L423-L452](https://github.com/ckb-js/ckb-sdk-js/blob/develop/packages/ckb-sdk-core/src/index.ts?rgh-link-date=2023-11-16T10%3A21%3A04Z#L423-L452)

**Comment by Keith-CY** [comment]
> > The light client does not have the RPC named `get_live_cell`. Maybe it's better to get the live cell by another RPC method.
> 
> you're right, we should use the piece of the logic below, by using `get_transaction` function instead
> 
> > Why not reuse the logic implemented at [ckb-js/ckb-sdk-js@`develop`/packages/ckb-sdk-core/src/index.ts#L423-L452](https://github.com/ckb-js/ckb-sdk-js/blob/develop/packages/ckb-sdk-core/src/index.ts?rgh-link-date=2023-11-16T10%3A57%3A34Z#L423-L452)

Now it should be simple to fix because code snippets and test cases are ready, can we prioritize this fix in lumos so `unlock nervos dao` can be fixed by upgrading the SDK?

**Comment by homura** [comment]
> Now it should be simple to fix because code snippets and test cases are ready, can we prioritize this fix in lumos so `unlock nervos dao` can be fixed by upgrading the SDK?

I've tried to [fix the issue](https://github.com/nervosnetwork/neuron/compare/develop...homura:neuron:light-client-withdraw-dao) but I am struggling to verify it with the light client. It currently functions properly with the full node, but I'm unsure why the light client with devnet is unable to work with Neuron.


https://github.com/Magickbase/neuron-public-issues/assets/7511174/6a059395-79f4-4753-99e0-0ec06b32d536
