### ISSUE TITLE
Displaying DAO rewards when deposited into NervosDAO

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#317]
Original requirement：https://github.com/Magickbase/ckb-explorer-public-issues/issues/462

PRD：https://vs0cjf.axshare.com/?id=vsq6ym&g=1&p=_462_show_dao_rewards

In Neuron, when opening Nervos DAO/Deposit, the pop-up will include the following new fields:

- Estimated Rewards of 30 days: Estimated rewards for a 30-day deposit.

- Estimated Rewards of 360 days: Estimated rewards for a 360-day deposit.

- Estimated APC: Estimated Annual Percentage Compensation.

**Comment by Danie0918** [comment]
【Displaying DAO rewards when deposited into NervosDAO】

- Requirement Description: It's helpful to show rewards when depositing DAOs in Neuron.


![Image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/00bfc7f0-f3b1-4899-af8e-823d2254cef4)


- Requirement Contents
1. Adjust the 'Don't reserve any CKBytes' option and make it only show at maximum value.
2. Tips are not in constant manifestation and are included in the question mark icon. On mouseover of the question mark, the tips are displayed and an RFC hyperlink is provided.
3. When the amount is entered the rewards are calculated and displayed.
4. 'Estimated APC' adds a prompt message.

**Comment by Keith-CY** [comment]
> Adjust the 'Don't reserve any CKBytes' option and make it only show at maximum value.

Technically, it's hard to know the maximum value because the transaction fee is dynamic(due to dynamic fee rate and flexible transaction size), so the option may appear when the transaction cannot be constructed unless all cells are deposited.

**Comment by Keith-CY** [comment]
> > > Adjust the 'Don't reserve any CKBytes' option and make it only show at maximum value.
> > 
> > 
> > Technically, it's hard to know the maximum value because the transaction fee is dynamic(due to dynamic fee rate and flexible transaction size), so the option may appear when the transaction cannot be constructed unless all cells are deposited.
> 
> The expectation is judged based on the progress bar max, which was optimized in a previous issue.

Then it looks good to me

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32457%3A32071&mode=design&t=SrNnL97ARpTRla4j-1
<img width="1134" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/6a287101-4a62-4ca5-bef8-440263640737">

**Comment by Danie0918** [comment]
PR:https://github.com/nervosnetwork/neuron/pull/3054
