### ISSUE TITLE
Light client sync slowly with calling fetch_transaction much times. 

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#322]
The root cause is that the current syncing transaction includes many inputs, and the inputs are not belong to the current wallet, so we need to call `fetch_transaction` before getting these transactions' details. 
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts#L173-L176 do not kill the queue, these requests will still be sent after the queue is rejected,  so they will be many same `fetch_transaction` requests.

So, I will fix these in two steps:
1. fetch inputs' tx hashes before syncing the current transaction for the light client.
2. kill the queue after rejecting to avoid the queue still running after the current statement break

**Comment by Keith-CY** [comment]
It should be about https://github.com/nervosnetwork/neuron/issues/2941

But the first 2 cases don't include many inputs, they are simply cellbase transactions.

**Comment by yanguoyu** [comment]
> It should be about [nervosnetwork/neuron#2941](https://github.com/nervosnetwork/neuron/issues/2941)
> 
> But the first 2 cases don't include many inputs, they are simply cellbase transactions.

Neuron calls `fetch_transaction` because the transaction does not belong to the current wallet, so when syncing the transaction that costs the cell base output, the transaction has many inputs, and all of the inputs are cellbase output.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2944
