### ISSUE TITLE
Arch-detect not works well on neuron project page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#323]
I'm using arm64 but `macOS x64-DMG` is recommended
<img width="626" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/790a8887-143a-4dca-b138-ad2d17e88905">

```bash
~ uname -m
# arm64
```

**Comment by Keith-CY** [comment]
BTW, I found a typo in the hero image, `Mainnet default note` should be `Mainnet default node`, and now it's renamed `Internal Node`
<img width="491" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7271329/2acd8b04-d63a-4bd9-9010-62e2ffa11188">

cc @Kirl70

**Comment by Kirl70** [comment]
The image has been updated:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=18544%3A40132&mode=design&t=H0v7RrkWYs1rc6HQ-1
<img width="412" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/63297506-d908-4f22-b486-ec660c5fc516">

**Comment by Keith-CY** [comment]
Here is a solution for architecture detection

```js
await navigator.userAgentData.getHighEntropyValues(['architecture'])
// { architecture: 'arm' }
```
Ref: https://stackoverflow.com/a/75177111

**Comment by WhiteMinds** [comment]
PRs:
1. https://github.com/Magickbase/websites/pull/28
2. https://github.com/Magickbase/websites/pull/29

**Comment by Keith-CY** [comment]
Fixed by upgrading the library.
