### ISSUE TITLE
Should we add network type field when the user add network

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#324]
If the user starts an external `light client` node and the Neuron selects the `light client`, it will notify the user to create a new network to switch or ignore. Weirdly, the user can not create a light client network. Then they can only ignore the external node.
@Keith-CY @Danie0918

**Comment by Danie0918** [comment]
> If the user starts an external `light client` node and the Neuron selects the `light client`, it will notify the user to create a new network to switch or ignore. Weirdly, the user can not create a light client network. Then they can only ignore the external node. @Keith-CY @Danie0918

For the current situation, we need to label the type of network in subsequent releases.

**Comment by Keith-CY** [comment]
Connecting to an external light client is not allowed because the light client is based on different security assumptions.

Ref: https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781

**Comment by yanguoyu** [comment]
> Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> 
> Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)

So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.

**Comment by Keith-CY** [comment]
> > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> 
> So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.

If it's connected to an external light client, show the internal light client options as `show external network options on connecting to an external node` we have implemented.

**Comment by Danie0918** [comment]
> > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> 
> So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.

For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.

Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.

![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/ba455212-738f-41e7-a15a-2da1f215d657)

**Comment by Keith-CY** [comment]
> > > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> > 
> > 
> > So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.
> 
> For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.
> 
> Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.
> 
> ![image](https://user-images.githubusercontent.com/122437870/283706661-ba455212-738f-41e7-a15a-2da1f215d657.png)

The sentence `It has been switched to Neuron internal light client node for you` conflicts with `confirm` because `confirm` is a request while `...  has been ...` is a notification. What if `Would you like to connect to the internal CKB Light Client(mainnet/testnet)`, (mainnet/testnet) based on type of the external one.

**Comment by Danie0918** [comment]
> > > > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > > > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> > > 
> > > 
> > > So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.
> > 
> > 
> > For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.
> > Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.
> > ![image](https://user-images.githubusercontent.com/122437870/283706661-ba455212-738f-41e7-a15a-2da1f215d657.png)
> 
> The sentence `It has been switched to Neuron internal light client node for you` conflicts with `confirm` because `confirm` is a request while `... has been ...` is a notification. What if `Would you like to connect to the internal CKB Light Client(mainnet/testnet)`, (mainnet/testnet) based on type of the external one.

How about adjusting `confirm` to `OK`?
When an external node is not available, we should automatically switch to an available internal node for the user.

**Comment by Keith-CY** [comment]
> > > > > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > > > > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> > > > 
> > > > 
> > > > So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.
> > > 
> > > 
> > > For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.
> > > Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.
> > > ![image](https://user-images.githubusercontent.com/122437870/283706661-ba455212-738f-41e7-a15a-2da1f215d657.png)
> > 
> > 
> > The sentence `It has been switched to Neuron internal light client node for you` conflicts with `confirm` because `confirm` is a request while `... has been ...` is a notification. What if `Would you like to connect to the internal CKB Light Client(mainnet/testnet)`, (mainnet/testnet) based on type of the external one.
> 
> How about adjusting `confirm` to `OK`? When an external node is not available, we should automatically switch to an available internal node for the user.

I'm not sure, personally I don't like an automatic switch because it makes me feel out of control.

**Comment by Danie0918** [comment]
> > > > > > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > > > > > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> > > > > 
> > > > > 
> > > > > So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.
> > > > 
> > > > 
> > > > For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.
> > > > Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.
> > > > ![image](https://user-images.githubusercontent.com/122437870/283706661-ba455212-738f-41e7-a15a-2da1f215d657.png)
> > > 
> > > 
> > > The sentence `It has been switched to Neuron internal light client node for you` conflicts with `confirm` because `confirm` is a request while `... has been ...` is a notification. What if `Would you like to connect to the internal CKB Light Client(mainnet/testnet)`, (mainnet/testnet) based on type of the external one.
> > 
> > 
> > How about adjusting `confirm` to `OK`? When an external node is not available, we should automatically switch to an available internal node for the user.
> 
> I'm not sure, personally I don't like an automatic switch because it makes me feel out of control.

Ok, the plan is as follows:

Prompt the user when they start an external light client node and  selected  a Neuron internal node and guide them to use the Neuron internal light client. Click  `Confirm` to connect to the Neuron internal light client and  `Ignore external node` to continue linking to the selected Neuron internal node.

Text: Neuron does not support external light client nodes due to different security assumptions for light clients. Would you like to connect to the internal CKB Light Client?

![image](https://github.com/Magickbase/neuron-public-issues/assets/122437870/217d6f72-91ec-48c6-8e26-ae22026df1d4)

**Comment by Keith-CY** [comment]
> > > > > > > Connecting to an external light client is not allowed because the light client is based on different security assumptions.
> > > > > > > Ref: [#90 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781)
> > > > > > 
> > > > > > 
> > > > > > So, If the user starts an external light client node, it will be better to only provide the `Ignore external node ` option.
> > > > > 
> > > > > 
> > > > > For this case, our friendlier approach is to prompt the user that it is unavailable, which can be achieved by modifying the text based on a pop-up window detected by an external node.
> > > > > Text: Neuron does not support external light client nodes due to different security assumptions for light clients. It has been switched to Neuron internal light client nodes for you.
> > > > > ![image](https://user-images.githubusercontent.com/122437870/283706661-ba455212-738f-41e7-a15a-2da1f215d657.png)
> > > > 
> > > > 
> > > > The sentence `It has been switched to Neuron internal light client node for you` conflicts with `confirm` because `confirm` is a request while `... has been ...` is a notification. What if `Would you like to connect to the internal CKB Light Client(mainnet/testnet)`, (mainnet/testnet) based on type of the external one.
> > > 
> > > 
> > > How about adjusting `confirm` to `OK`? When an external node is not available, we should automatically switch to an available internal node for the user.
> > 
> > 
> > I'm not sure, personally I don't like an automatic switch because it makes me feel out of control.
> 
> Ok, the plan is as follows:
> 
> Prompt the user when they start an external light client node and selected a Neuron internal node and guide them to use the Neuron internal light client. Click `Confirm` to connect to the Neuron internal light client and `Ignore external node` to continue linking to the selected Neuron internal node.
> 
> Text: Neuron does not support external light client nodes due to different security assumptions for light clients. Would you like to connect to the internal CKB Light Client?
> 
> ![image](https://user-images.githubusercontent.com/122437870/283731876-217d6f72-91ec-48c6-8e26-ae22026df1d4.png)

LGTM

**Comment by Danie0918** [comment]
> ![image](https://user-images.githubusercontent.com/122437870/283731876-217d6f72-91ec-48c6-8e26-ae22026df1d4.png)
> 
> What is the difference between `Ignore external node` and `Confirm`? @Danie0918

 `Ignore external node`:Along with the chosen node, there is a possibility of  full node.
`Confirm`:Switch to the Neuron internal light client and switch to the same type of network depending on the type of external node (mainnet/testnet).

**Comment by yanguoyu** [comment]
> > ![image](https://user-images.githubusercontent.com/122437870/283731876-217d6f72-91ec-48c6-8e26-ae22026df1d4.png)
> > What is the difference between `Ignore external node` and `Confirm`? @Danie0918
> 
> `Ignore external node`:Along with the chosen node, there is a possibility of full node. `Confirm`:Switch to the Neuron internal light client and switch to the same type of network depending on the type of external node (mainnet/testnet).

If the user selects the light client, the external node must be a service whose remote is equal to the light client.
So I'm confused about the difference after clicking `Ignore` or `Confirm`.

**Comment by Danie0918** [comment]
> > > ![image](https://user-images.githubusercontent.com/122437870/283731876-217d6f72-91ec-48c6-8e26-ae22026df1d4.png)
> > > What is the difference between `Ignore external node` and `Confirm`? @Danie0918
> > 
> > 
> > `Ignore external node`:Along with the chosen node, there is a possibility of full node. `Confirm`:Switch to the Neuron internal light client and switch to the same type of network depending on the type of external node (mainnet/testnet).
> 
> If the user selects the light client, the external node must be a service whose remote is equal to the light client. So I'm confused about the difference after clicking `Ignore` or `Confirm`.

Yes, the results are the same when the internal light client is selected.

**Comment by yanguoyu** [comment]
> > > > ![image](https://user-images.githubusercontent.com/122437870/283731876-217d6f72-91ec-48c6-8e26-ae22026df1d4.png)
> > > > What is the difference between `Ignore external node` and `Confirm`? @Danie0918
> > > 
> > > 
> > > `Ignore external node`:Along with the chosen node, there is a possibility of a full node. `Confirm`:Switch to the Neuron internal light client and switch to the same type of network depending on the type of external node (mainnet/testnet).
> > 
> > 
> > If the user selects the light client, the external node must be a service whose remote is equal to the light client. So I'm confused about the difference after clicking `Ignore` or `Confirm`.
> 
> Yes, the results are the same when the internal light client is selected.

So, If the user selects `Light Client` and detects an external light client node, how about only showing the `Confirm` button, if there exist two same action options with different texts, users will be confused.

**Comment by Danie0918** [comment]
> So, If the user selects `Light Client` and detects an external light client node, how about only showing the `Confirm` button, if there exist two same action options with different texts, users will be confused.

This would still have the problem mentioned before: it would make the user feel out of control. It would also increase the complexity of the code, so it is recommended to keep the 2 options.

**Comment by Danie0918** [comment]
Will be fixed in #375
