### ISSUE TITLE
Issues of add a troubleshooting page

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#339]
1.When in Chinese，some parts in sidebar shows English.
<img width="1408" alt="截屏2023-12-18 11 04 14" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/46db885b-e7e2-40fe-acf4-1c5d6f7e442e">

2.When in daytime mode,the page show in light mode.
<img width="1431" alt="截屏2023-12-18 11 12 29" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/06d5fcb8-9429-40af-a1ac-a33c806a92b8">
Operation procedure video:

https://github.com/Magickbase/neuron-public-issues/assets/25971273/34f8555a-e377-4c4a-9e49-82d80c29c927

3.When help document is in night mode, and click index page,the  index page change to daytime mode,in expect,it should be light mode.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/5457779b-f326-4f41-8ed9-4a9eb1767666

4.When  no search results ,it shows like this:

<img width="559" alt="截屏2023-12-18 16 19 05" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/180f9fed-cbcd-40c1-bdb5-4743e4ade080">

then click Documentation link in pop up window,it search in 'Documentation' keyword.maybe like this in requirement document is better for users.

<img width="690" alt="截屏2023-12-18 16 21 55" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/08095562-36e0-449d-906f-daaa1a108563">

5.The icon meaning is not clear and UI is stange.

<img width="578" alt="截屏2023-12-18 16 26 12" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d4c1fd7e-af22-47e7-839c-cce6ab320189">

<img width="560" alt="截屏2023-12-18 16 36 00" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/b541cc6d-29ee-4e18-a68f-47a2459b910d">

6.All key words is rolled,and even some words in document is rolled.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/b4508933-4aed-44a7-af1d-a36737fcba61

https://github.com/Magickbase/neuron-public-issues/assets/25971273/f622a7a7-b60d-43d5-8cbb-941825a7759c

7.This two button is exit search window in mac.Maybe button for search is better to put here.
<img width="912" alt="截屏2023-12-18 16 45 24" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ab051560-9888-4bbc-8364-bf0ed2f4f0a4">

<img width="422" alt="截屏2023-12-18 16 43 32" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/2b4b925c-316f-4700-bc52-de2f1c0132fb">

8.It is strange to show parted  as full name.

<img width="1416" alt="截屏2023-12-18 16 46 45" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ed2f201a-7daa-442b-86fa-c11397cbad18">

**Comment by Danie0918** [comment]
> 8.It is strange to show parted as full name.
> 
> <img alt="截屏2023-12-18 16 46 45" width="1416" src="https://private-user-images.githubusercontent.com/25971273/291205807-ed2f201a-7daa-442b-86fa-c11397cbad18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDc3MDQsIm5iZiI6MTcwMjk0NzQwNCwicGF0aCI6Ii8yNTk3MTI3My8yOTEyMDU4MDctZWQyZjIwMWEtN2RhYS00NDJiLTg2ZmEtYzExMzk3Y2JhZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAwNTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlN2E5ODc5ZmZhNjBkMGJhYTdmYjI5NzhhZDZiMjkxNDA1OWE5MGFmYmFiZmZmMGQ5ZTE0Y2Y0ZmI2ZTljMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDCPJXtEkNbXYeqI1JwMaM08VRmKtft5Z3HxlGMqm_s">

@Kirl70  Please take a look at this question

**Comment by Kirl70** [comment]
> > 8.It is strange to show parted as full name.
> > <img alt="截屏2023-12-18 16 46 45" width="1416" src="https://private-user-images.githubusercontent.com/25971273/291205807-ed2f201a-7daa-442b-86fa-c11397cbad18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDc3MDQsIm5iZiI6MTcwMjk0NzQwNCwicGF0aCI6Ii8yNTk3MTI3My8yOTEyMDU4MDctZWQyZjIwMWEtN2RhYS00NDJiLTg2ZmEtYzExMzk3Y2JhZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAwNTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlN2E5ODc5ZmZhNjBkMGJhYTdmYjI5NzhhZDZiMjkxNDA1OWE5MGFmYmFiZmZmMGQ5ZTE0Y2Y0ZmI2ZTljMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDCPJXtEkNbXYeqI1JwMaM08VRmKtft5Z3HxlGMqm_s">
> 
> @Kirl70 Please take a look at this question

There is no issue here, this is the design of the logo.
Reference:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1896%3A10732&mode=design&t=znxto8NLv0AXF6Qz-1
<img width="1324" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/403581e8-e9a6-4ff8-be90-4530a34ca088">

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/websites/pull/35

> 1.When in Chinese，some parts in sidebar shows English.
> 2.When in daytime mode,the page show in light mode.
> 3.When help document is in light mode, and click index page,the index page change to daytime mode,in expect,it should be light mode.

Fixed by PR.

> 4.When no search results ,it shows like this:

Currently, the search functionality is implemented using the component provided by DocSearch.

Customizing it to match the design specifications would be costly, so this requirement has been postponed.

The only quick implementation available is as follows, but it performs poorly, so it was not included in the PR:

![image](https://github.com/Magickbase/neuron-public-issues/assets/9160743/c59518cf-a6ad-4265-914b-02f6e1e12ef5)

> 5.The icon meaning is not clear and UI is stange.

This is the default style of DocSearch, as shown in the image below.

The first numbered marker represents the search result, where the search keyword matches a section title within an article.

The second numbered marker represents the titles of subsections within that section, allowing for quick navigation.

The third numbered marker represents the parent section of that subsection.

![image](https://github.com/Magickbase/neuron-public-issues/assets/9160743/8968a5d2-0d95-4258-a3c1-2fe65115f15e)

> 6.All key words is rolled,and even some words in document is rolled.

This is a design requirement, but I forgot where this requirement was raised.

@Kirl70 Do you know which issue this was?

> 7.This two button is exit search window in mac.Maybe button for search is better to put here. 

I didn't understand the issue here.

@FrederLu You can see the preview website address in the PR.

**Comment by Kirl70** [comment]
> > 6.All key words is rolled,and even some words in document is rolled.
> 
> This is a design requirement, but I forgot where this requirement was raised.
> 
> @Kirl70 Do you know which issue this was?

This is the design requirement, but I believe that the document details page doesn't need this effect. Please remove this effect on the document details page.
<img width="1079" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/b56313b8-398f-40f1-8cc7-374fe4064751">

**Comment by Kirl70** [comment]
The element positions do not match the design draft.
<img width="1441" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/34e8b938-277d-49c8-8f77-c5221285a547">


The spacing and line spacing are too congested. Please refer to the design draft and make adjustments accordingly.

<img width="1542" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/1e06ff3e-08aa-4b23-9abf-0676136dc434">

The document details page is the same.

<img width="1984" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/857be7d4-ec2f-4fb7-8b6d-f977f03c095d">

**Comment by Kirl70** [comment]
Currently, when navigating to the document details page, it opens directly within the existing browser tab. Given the differing styles between the document page and the main website page, I believe it would be more appropriate to open a new browser tab upon accessing the document details page to better inform users. cc @Danie0918 

![image](https://github.com/Magickbase/neuron-public-issues/assets/106060898/1e56f8e7-fb20-4a0d-a362-b881716142e5)

**Comment by Danie0918** [comment]
> Currently, when navigating to the document details page, it opens directly within the existing browser tab. Given the differing styles between the document page and the main website page, I believe it would be more appropriate to open a new browser tab upon accessing the document details page to better inform users. cc @Danie0918
> 
> ![image](https://private-user-images.githubusercontent.com/106060898/291806870-1e56f8e7-fb20-4a0d-a362-b881716142e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjA1OTAsIm5iZiI6MTcwMzA2MDI5MCwicGF0aCI6Ii8xMDYwNjA4OTgvMjkxODA2ODcwLTFlNTZmOGU3LWZiMjAtNGEwZC1hMzYyLWI4ODE3MTYxNDJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwODE4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmUxZTYwZTA0ZjkzOWViYWM3MzFjNzM1NjE5NWVlN2MwNTkxY2NmNmI3YjA5YzQxNzc5YTk5ZjBlM2M4OWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8MFhujNrQ4ie_QpcrFgyhiuSjNOMqsWrhas3byjUJk8)

Yes, that would be better. cc @WhiteMinds

**Comment by WhiteMinds** [comment]
PR has been updated:
1. Removed the hover animation of the links in the article detail page.
2. Adjusted the layout of the changelog page to match the design specifications.
3. Adjusted the style of the release log details in the changelog page to match the design specifications.
4. Only text-based links in the release log details will have the animation now.
5. Added hover effect to the dropdown list header in the sidebar of the article detail page.
6. Open the article detail page in a new tab when opened from the help center.

Remaining known issues:
1. Content styling in the article detail page needs to be adjusted.

**Comment by WhiteMinds** [comment]
PR has been updated:
1. Content styling in the article detail page needs to be adjusted.

@FrederLu @Kirl70 Please check.

**Comment by Kirl70** [comment]
> PR has been updated:
> 
> 1. Content styling in the article detail page needs to be adjusted.
> 
> @FrederLu @Kirl70 Please check.


Spacing does not match the design draft.
<img width="925" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/8e19b1dd-56a6-4979-a9dd-c222c227b0d5">
<img width="659" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/a7d3be68-033d-416c-81ea-0996d252217f">
Design Draft:
<img width="620" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/0d025599-940c-46a9-babb-bedb1152eba9">

Need to add a hover effect and ensure consistency with other hover effects on this page.
<img width="354" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/530cba34-ff67-410e-b296-37f1676406de">

The text and icons inside the three buttons need to have a hover effect.
<img width="593" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/eebe1422-2391-4b97-ab95-30001ebf251e">
<img width="458" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/45b82763-41b0-4843-99ae-b527181c8d89">
<img width="280" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/106060898/09d6cea2-8c76-49eb-b451-ac2da0805a0e">

**Comment by silySuper** [comment]
The testing website is this?:https://neuron.magickbase.com/help-center
No.1 same as before.
<img width="1237" alt="截屏2023-12-22 09 56 20" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6f471769-dfcb-4f7c-a9b5-562e5e11ab77">
No.2 same as before
<img width="1425" alt="截屏2023-12-22 09 58 25" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/6cd54a1f-8d25-45ef-b07d-cd0de61ee5a0">
No.3 same as before.
No.4 same as before.
No.7 same as before.

**Comment by WhiteMinds** [comment]
> The testing website is this?:https://neuron.magickbase.com/help-center

@silySuper Please use the preview link provided in the PR: https://github.com/Magickbase/websites/pull/35#issuecomment-1862402258

**Comment by WhiteMinds** [comment]
PR has been updated:
1. Enable scrolling for the Table of Contents in the post detail page when it becomes too long.
2. Adjust the top spacing of the help center and download pages to match the latest design specifications.
3. Add entry points for several pages in the mobile menu.
4. Implemented the mobile version of the help center.
5. Implemented button components according to the design specifications for buttons.
6. Adapted the Footer component to the latest design specifications.

@silySuper @Kirl70 Please check.

**Comment by WhiteMinds** [comment]
The PR https://github.com/Magickbase/websites/pull/35 has been merged, and the mentioned changes have been deployed to https://neuron.magickbase.com/

**Comment by silySuper** [comment]
No.1 is verified.
No.2 is verified.
No.3 is same as before.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/dfc4e20c-916d-4bd7-a2a4-b812c1accb1a

No.6 is verified.

**Comment by WhiteMinds** [comment]
> 3.When help document is in night mode, and click index page,the index page change to daytime mode,in expect,it should be light mode.

> No.3 is same as before.
> 
> https://github.com/Magickbase/neuron-public-issues/assets/25971273/dfc4e20c-916d-4bd7-a2a4-b812c1accb1a

Based on the video, it appears that the previously mentioned issue 3 has been fixed, and the current behavior is as expected.

**Comment by silySuper** [comment]
> > 3.When help document is in night mode, and click index page,the index page change to daytime mode,in expect,it should be light mode.
> 
> > No.3 is same as before.
> > 
> >   
> >     
> >     
> > 
> >     2023-12-28.16.06.24.mov
> 
> Based on the video, it appears that the previously mentioned issue 3 has been fixed, and the current behavior is as expected.
> 
> @silySuper @Kirl70 Please check.

when in daytime mode,click home tab ,the background is black，I saw white background before,why  in this situation  the background is  not white?

**Comment by WhiteMinds** [comment]
> when in daytime mode,click home tab ,the background is black，I saw white background before,why in this situation the background is not white?

The home page only has a dark theme and does not have a light theme. The appearance of the light theme previously was a bug, which has now been fixed.

**Comment by silySuper** [comment]
OK
