### ISSUE TITLE
Organize test case for UI test automation

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#35]
- [x] Identify existing automated test cases.
- [x] List the automated test cases that need to be added or adjusted.

**Comment by Cedar67** [comment]
The following list is the currently implemented automated test cases.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/64718893/174713079-c67c1634-2e9c-4ed2-93df-3cf15aee2b05.png">

**Comment by Cedar67** [comment]
The test cases that need to be automated **`in regression testing`** are listed in the sheet below. Please review. @Keith-CY @yanguoyu @FrederLu 

123 test cases are planned for automation, including:

- High priority: 68 test cases
- Medium priority: 43 test cases
- Low priority: 12 test cases

https://docs.google.com/spreadsheets/d/1J2ENPt3lkikBncv-NN_cSaquhsX_0xDSR1GiVhBBNho/edit#gid=1295470201

**Comment by Keith-CY** [comment]
@Keith-CY @yanguoyu @FrederLu please have a review
