### ISSUE TITLE
Transfer Neuron Jenkins environment

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#36]
- [x] Task 1. Server resources
- [x] Task 2. Transfer Jenkins environment ([Jenkins package](https://drive.google.com/file/d/1ZcOoV638DjU6yPnNoIMi_fu_6Z766Ggs/view?usp=sharing) It is deployed on a Linux server)
- [x] Task 3. Transfer Neuron-Build job
- [x] Task 4. Transfer Neuron-Release job
- [x] Task 5. Transfer UI automated test Job - Estimated 1 day

**`The following figure shows the jobs to be migrated:`**

![image](https://user-images.githubusercontent.com/64718893/176089086-ecdb4e7c-4b84-413f-add1-8f64f390d9c6.png)

**`The following figure shows the recommended server resource configuration requirements:`**

- Linux server:  Linux 2.1903 LTS 64bit
- Windows server:

![image](https://user-images.githubusercontent.com/64718893/176089105-40952238-12e9-4d0b-b7ca-0d769f25fbaf.png)

**Comment by Keith-CY** [comment]
It's said that Jenkins and jobs are ready to be transferred
![image](https://user-images.githubusercontent.com/7271329/176102483-676b372d-3258-4525-8ff7-39e23d370b27.png)
Do you know that @Cedar67 @ShiningRay

**Comment by Cedar67** [comment]
> It's said that Jenkins and jobs are ready to be transferred ![image](https://user-images.githubusercontent.com/7271329/176102483-676b372d-3258-4525-8ff7-39e23d370b27.png) Do you know that @Cedar67 @ShiningRay

It’s the first time I knew about it. I hadn't been contacted before.

**Comment by Cedar67** [comment]
We have got Jenkins package and stored it in the following location:
https://drive.google.com/file/d/1ZcOoV638DjU6yPnNoIMi_fu_6Z766Ggs/view?usp=sharing
It is deployed on a Linux server. The original version of Linux where it was deployed was `Alibaba Cloud Linux  2.1903 LTS 64bit`.  Please refer to this info to apply for server resources. @ShiningRay

**Comment by Keith-CY** [comment]
Postponed to 07/13 because Neuron will be released this week

**Comment by Keith-CY** [comment]
Any update on transferring automated testing to our own servers?

**Comment by Cedar67** [comment]
The resources needed are not fully available. We need a Windows server and a Linux server. The Windows server is ready, and the Linux server is being applied for.

**Comment by Cedar67** [comment]
The Linux server is now ready. Plan to start deploying the Jenkins compressed package on Linux servers today.

**Comment by Keith-CY** [comment]
> The Linux server is now ready. Plan to start deploying the Jenkins compressed package on Linux servers today.

How is the transfer going

**Comment by Cedar67** [comment]
Jenkins is currently being installed on the Linux Server. Full transfer is expected this week.

**Comment by Cedar67** [comment]
Transaction completed. The Jenkins server and all Neuron Jenkins Jobs have been transferred. 
The Jenkins domain name is being configured. 
The new Jenkins access address is http://43.198.21.52:8081

**Comment by Cedar67** [comment]
The new Jenkins domain name is set up: https://neuron-test.nervosnet.org/
