### ISSUE TITLE
Version update video - Iteration 5

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/neuron-public-issues#363]
https://github.com/Magickbase/neuron-public-issues/assets/122437870/0d03c7fe-2300-4fd6-b1b5-29549a6c949d

@Keith-CY Please have a review.

**Comment by Keith-CY** [comment]
The title `send` and `history`, `synchronization` could be more descriptive, the functions of `send`, `history`, `synchronization` have been supportd long time ago, the title should deliver the update on these functions

**Comment by Danie0918** [comment]
> The title `send` and `history`, `synchronization` could be more descriptive, the functions of `send`, `history`, `synchronization` have been supportd long time ago, the title should deliver the update on these functions

https://github.com/Magickbase/neuron-public-issues/assets/122437870/19a69037-9cef-43ca-b35b-de72580d0ecd

Updated.

**Comment by Keith-CY** [comment]
> > The title `send` and `history`, `synchronization` could be more descriptive, the functions of `send`, `history`, `synchronization` have been supportd long time ago, the title should deliver the update on these functions
> 
>  Iteration5.mp4 
> Updated.

I found another typo that `Brocast Transaction` should be `Broadcast Transaction`

**Comment by Danie0918** [comment]
> > > The title `send` and `history`, `synchronization` could be more descriptive, the functions of `send`, `history`, `synchronization` have been supportd long time ago, the title should deliver the update on these functions
> > 
> > 
> > Iteration5.mp4
> > Updated.
> 
> I found another typo that `Brocast Transaction` should be `Broadcast Transaction`
> 
> If we have another opportunity to update the video, I would suggeste updating `Send add transaction details page` to `View transaction detail before sending a it`


https://github.com/Magickbase/neuron-public-issues/assets/122437870/3ebc1a19-693b-4a20-8299-7a515448c356
> 
> Updated. BTW,`View transaction detail before sending a it` should be `View transaction detail before sending it`
