### ISSUE TITLE
CKB explorer UI  shows abnormal

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#365]
In history page , click view on explorer,jump to https://pudge.explorer.nervos.org/transaction/0x5ad59f79cef0c9c38d656ac7eb5368f9d9c546992c9222330cea8d8fe31c87f1  and fee UI shows abnormal in safari explorer and not full screen mode. 

<img width="604" alt="截屏2024-03-06 17 14 50" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/5efb25ca-0c01-4589-885a-c535fc4a1d74">

testing package: https://github.com/nervosnetwork/neuron/actions/runs/8166078017

**Comment by yanguoyu** [comment]
It's better to move to https://github.com/Magickbase/ckb-explorer-public-issues/issues.
