### ISSUE TITLE
Neuron update shows error

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#373]
1.In full node mode,when update from v0.114.0 to v0.114.2,it shows 
<img width="290" alt="截屏2024-03-28 10 36 03" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d80b811d-d865-4827-9a0f-865b3e157aac">
<img width="864" alt="截屏2024-03-28 10 36 38" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/d34ca918-8fe7-4287-a660-4e0b68925b9b">

2.After click neuron icon quit,and open neuron ,it shows 
<img width="1367" alt="截屏2024-03-28 10 41 36" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/edbcb885-4d77-4c98-9a08-c7d965a4dd8e">

**Comment by Keith-CY** [comment]
The certificate for Apple was updated in v0.101.3(https://github.com/nervosnetwork/neuron/releases/tag/v0.101.3) on 2022-03-01. But the origin version mentioned above is v0.112.0, so it's unexpected.

Please share the origin app if possible so we can verify the upgrading locally.

**Comment by Keith-CY** [comment]
Besides, I notices that Neuron version is v0.112.0 while the CKB node is v0.114.0, it's also weird because Neuron keeps the `minor version`(second number) the same as its built-in node

**Comment by silySuper** [comment]
It is  a regression package before last version publish.I will download the latest package to compare firstly.

**Comment by silySuper** [comment]
When neuron is v0.114.0,the update shows error also.
<img width="1361" alt="截屏2024-03-28 11 06 21" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/4a8f28a5-294c-4543-a7a9-54ab7bbc8e39">

https://github.com/Magickbase/neuron-public-issues/assets/25971273/549dc664-04d2-42bb-b4ed-3c71023be5a3

**Comment by Keith-CY** [comment]
> When neuron is v0.114.0,the update shows error also. <img alt="截屏2024-03-28 11 06 21" width="1361" src="https://private-user-images.githubusercontent.com/25971273/317579815-4a8f28a5-294c-4543-a7a9-54ab7bbc8e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTY0NzksIm5iZiI6MTcxMTU5NjE3OSwicGF0aCI6Ii8yNTk3MTI3My8zMTc1Nzk4MTUtNGE4ZjI4YTUtMjk0Yy00NTQzLWE3YTktNTRhYjdiYmM4ZTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTI3ZmExMTA1MWE4MDA0MTliNWY1YTM5ZDY5ZDNlMjJmNzUyY2JlZTE4ZTA5MmYyMzVjZGM3ZWQ5NDRiNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cX1SSVwJzwPWRKyINGg4p6ygUf5JxZkb19Du6uFAEC0">
> 
>  2024-03-28.11.06.49.mov

The error message changed, it's about the network quality and expected to be fixed by VPN
