### ISSUE TITLE
Check new address format and deprecated address format simultaneously for compatibility

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#38]
Ref: https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/VerifyHardwareAddress/index.tsx#L142

Issue: https://github.com/nervosnetwork/neuron/issues/2431

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2441

**Comment by Cedar67** [comment]
Verified. Automatically converted to short address on hardware wallet. The short address can be verified successfully on the hardware wallet.
Hard wallet: Ledger Nano X
Nervos app on the Ledger: 0.5.0
Neuron:  v0.103.2 draft
