### ISSUE TITLE
Issues of regression v116

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#391]
Windows：
After set lock window  password（1234）first time ,it locked automatically ，and after fill in 1234 ,it can not unlock.

<img width="824" alt="截屏2024-05-21 14 49 52" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/607ce43f-6a36-45da-b63a-14df5dcd0ed1">

lockWindow is saved in C:\Users\Administrator\AppData\Roaming\Neuron\settings.json  lockWindow field.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/3162

**Comment by silySuper** [comment]
<img width="723" alt="截屏2024-05-21 16 59 48" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/9cbf19c5-f395-4cfa-b06c-d60f9d1ec469">
The bug is still stay

**Comment by Keith-CY** [comment]
> <img alt="截屏2024-05-21 16 59 48" width="723" src="https://private-user-images.githubusercontent.com/25971273/332357156-9cbf19c5-f395-4cfa-b06c-d60f9d1ec469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODIzNTEsIm5iZiI6MTcxNjI4MjA1MSwicGF0aCI6Ii8yNTk3MTI3My8zMzIzNTcxNTYtOWNiZjE5YzUtZjM5NS00Y2ZhLWIwNmMtZDYwZjlkMWVjNDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YTE3MDk1MGFlMzA3ODhiNDQxNjhjY2QzMTg3MjU1ZDRlNDI1ZTFiNjY5Y2MyODc4ZGQ2ZGVjMmNmNDA0NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.boJir_IQvNItI5_7EKNKSYwzjzKBf0UT1Y3FRVV6TiI"> The bug is still stay

Should be cache been cleared before the second test? @yanguoyu

**Comment by yanguoyu** [comment]
https://github.com/Magickbase/neuron-public-issues/assets/12881040/6832adc3-4b64-4746-8c0b-7e2856434294

I have tried on the windows, and it works well.

**Comment by silySuper** [comment]
Uploading 录屏2024-05-21 17.05.00.mov…

This is mine

**Comment by silySuper** [comment]
In Mac OS
<img width="1126" alt="截屏2024-05-22 15 08 08" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/cc9bca31-a54e-4da9-8503-d8063c1603a2">
When I paste my wallet password into this textbox,it shows this error.

**Comment by yanguoyu** [comment]
> In cell management 1.In Mac OS <img alt="截屏2024-05-22 15 08 08" width="1126" src="https://private-user-images.githubusercontent.com/25971273/332694923-cc9bca31-a54e-4da9-8503-d8063c1603a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjI0MTEsIm5iZiI6MTcxNjM2MjExMSwicGF0aCI6Ii8yNTk3MTI3My8zMzI2OTQ5MjMtY2M5YmNhMzEtYTU0ZS00ZGE5LTg1MDMtZDgwNjNjMTYwM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MGY4MGFmZmMzOGE3NDFiNDVjNDYzZDBmZDE4MDVjMWRjNTRjZDZjMjdiNDBjMzhiMGRlZDQzZWNmMzZiZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jD9tFHFH1y74ApbG2hsw5bgQ1aS9opp3kX4eVC30c4I"> When I paste my wallet password into this textbox,it shows this error.

Fixed by https://github.com/nervosnetwork/neuron/pull/3164

**Comment by yanguoyu** [comment]
> 2.When consume two cells,in amend page submit button is grey

Please check it @devchenyan

**Comment by devchenyan** [comment]
> In cell management 1.In Mac OS <img alt="截屏2024-05-22 15 08 08" width="1126" src="https://private-user-images.githubusercontent.com/25971273/332694923-cc9bca31-a54e-4da9-8503-d8063c1603a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzY5NTYsIm5iZiI6MTcxNjQzNjY1NiwicGF0aCI6Ii8yNTk3MTI3My8zMzI2OTQ5MjMtY2M5YmNhMzEtYTU0ZS00ZGE5LTg1MDMtZDgwNjNjMTYwM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTBjZmM3YmM0ZTM5YTMzZDA3YWE3MzYwNDAzNDkxMTk1MWMwYzg0MTkzOGNjYWZkNzMzNzcwNTNkMDEyMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmxNkQRSNorQ-Zd-bLE6HR3ASOMUn_dYkRIVw4cYC_o"> When I paste my wallet password into this textbox,it shows this error.
> 
> 2.When consume two cells,in amend page submit button is grey <img alt="截屏2024-05-22 15 12 41" width="1141" src="https://private-user-images.githubusercontent.com/25971273/332696985-9cd82cbf-13fb-451a-9a3d-c6644359a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzY5NTYsIm5iZiI6MTcxNjQzNjY1NiwicGF0aCI6Ii8yNTk3MTI3My8zMzI2OTY5ODUtOWNkODJjYmYtMTNmYi00NTFhLTlhM2QtYzY2NDQzNTlhNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOGFjNmYxNWEyZDg5OGEwYWQ3YjNhNmZkMWEyNGZjZjE3ZWUyNzMxY2EwZGE2NmQ4OGYxOWM4ODQwM2RlM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H17qLvNqrWvurUrdeXZ_i18CQIDSrZmlKn16Zfgej8g">

fixed: https://github.com/nervosnetwork/neuron/pull/3166

**Comment by silySuper** [comment]
verified
