### ISSUE TITLE
Debug timeout of `LedgerHQ/app-nervos`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#406]
There are 2 components for connection between Neuron and Ledger Wallet

1. SDK running in the Client: https://github.com/obsidiansystems/hw-app-ckb
2. App running in the Ledger Device: https://github.com/LedgerHQ/app-nervos

The App is being maintained at https://github.com/LedgerHQ/app-nervos and it was forked from https://github.com/obsidiansystems/ledger-app-nervos

Recently, the ledger team has tried to enable the CI of building the app(https://github.com/LedgerHQ/app-nervos/blob/develop/.github/workflows/continuous-integration-workflow.yml) but it failed (https://github.com/LedgerHQ/app-nervos/actions/runs/9211189099/job/25340021172) because of timeout.

The tests are written in JavaScript, so they want us to check if we can fix it.

**Comment by Keith-CY** [comment]
I've run the CI of the original repo, and it failed due to the same reason
https://github.com/obsidiansystems/ledger-app-nervos/blob/develop/.github/workflows/continuous-integration-workflow.yml

**Comment by homura** [comment]
## Setup the Development Environment

1. `git clone https://github.com/LedgerHQ/speculos.git`
2. `docker build -f build.Dockerfile -t speculos-builder:latest .`
3. Patch Dockerfile

```patch
diff --git a/Dockerfile b/Dockerfile
index 1ab457b..8305c93 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,7 +4,7 @@
 #
 # Building the Speculos environment
-FROM ghcr.io/ledgerhq/speculos-builder:latest AS builder
+FROM speculos-builder:latest AS builder
```
4. `docker build -f Dockerfile -t speculos:latest .`

## Get the Compiled File from GitHub Artifact

Choose a app file from the workflow https://github.com/LedgerHQ/app-nervos/actions/workflows/continuous-integration-workflow.yml

<img width="925" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/7511174/89b62f63-d962-438f-ac20-7b00ce6833bd">

## Try the Speculos

```sh
docker run \
  -it \
  --rm \
  -v \
  $(pwd)/apps:/speculos/apps \ 
  --publish 8888:8888 \
  --publish 8899:8899 \
  --publish 9999:9999 \
    speculos apps/app.elf \
    --sdk 2.0 \
    --display headless \
    --button-port 8888 \
    --automation-port 8899 \
    --apdu-port 9999
```

## Problems

### Async Calls are not Robust

https://github.com/LedgerHQ/app-nervos/blob/5089b38d1551205928aba41a1c72b623e04b9d35/tests/sudt.js#L194-L202

```js
      while((policy = await screens.next()).header != "Allow contract data") {
        speculos.button("Rr");
      }
      while(policy.body != target) {
        speculos.button("RLrl");
        policy = await screens.next();
      }
      do { speculos.button("Rr") } while((await screens.next()).body != "Main menu");
      speculos.button("RLrl");
```

The code here attempts to press buttons to navigate to a specific screen. However, the async function is not always predictable. The test snippet above shows its attempt to press the `Rr` button to reach a screen displaying "Allow contract data", but it might skip the target screen if Speculos fails to respond in time, resulting in pressing the button twice

### Often Crash with Exit Code 255

**Comment by homura** [comment]
https://github.com/LedgerHQ/app-nervos/pull/31
