### ISSUE TITLE
Setting language does not effect when it is changed.

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#408]
Setting language does not effect when it is changed,exit neuron can save the change.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/055e0177-a466-4215-b38d-8d0264ccf57d

<img width="283" alt="截屏2024-07-04 16 32 06" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/5fa3c149-f514-46b8-b5f4-5678450f085e">

[main.log](https://github.com/user-attachments/files/16095998/main.log)

first abnormal is related to single sign/multisig address

video upload slow，so zip it 

[录屏2024-07-04 18.08.25.zip](https://github.com/user-attachments/files/16097211/2024-07-04.18.08.25.zip)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/3201
