### ISSUE TITLE
Support Request: Review the Finalization of Channel Service and the Concept for Virtual Channels on CKB

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#415]
**Question or Problem**
This is a design and solution that supports payment channels in Neuron. `Finalization of Channel Service` and `Concept of Virtual Channel` are added at this stage.

**Relevant Files**
Docs: https://docs.google.com/document/d/1k5D1R49i5oLrP1ugxFPICN4KKhkm189PXRlgricvj1Q/

**Additional context**
Check if it should be reviewed by the core team

**Comment by Danie0918** [comment]
@yanguoyu @devchenyan Please have a review.
