### ISSUE TITLE
Regression bugs

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#417]
1.In multisig sign，when send transaction ,an abnormal confirm shows  after sign.

https://github.com/user-attachments/assets/4696721b-1216-4e2f-86a4-d3be2417a2e7

pay attention to 00:25 in video

**Expected behavior**
no confirm window shows again

**Comment by silySuper** [comment]
2.In testnet node，amend function is lost
<img width="1143" alt="截屏2024-08-01 10 28 03" src="https://github.com/user-attachments/assets/4a3915eb-4c3a-44c3-9d60-cbf29e58ee34">

PR:https://github.com/nervosnetwork/neuron/pull/3218

**Comment by yanguoyu** [comment]
> 1.In multisig sign，when send transaction ,an abnormal confirm shows after sign.
> 
>  2024-07-31.13.58.05.mov 
> pay attention to 00:25 in video
> 
> **Expected behavior** no confirm window shows again

https://github.com/nervosnetwork/neuron/pull/3219

**Comment by silySuper** [comment]
3.In Windows  , set start block number is not effective.
In mac ,after set start block number,it will change soon in block number,but windows not.


https://github.com/user-attachments/assets/0c1a05a2-0cc4-4373-9548-6a78a9bf9af5



[bundled-ckb-lignt-client-testnet.log](https://github.com/user-attachments/files/16464421/bundled-ckb-lignt-client-testnet.log)



[main.log](https://github.com/user-attachments/files/16464422/main.log)

**Comment by silySuper** [comment]
[main.log](https://github.com/user-attachments/files/16464743/main.log)

**Comment by silySuper** [comment]
4.In Windows  sync data is different  from Mac when start block number is same in  light client node(unit and account info is different).

Windows :
![Image](https://github.com/user-attachments/assets/2d65987b-c5dd-4edd-ba0d-01929e73cf0a)


Mac:
![Image](https://github.com/user-attachments/assets/30d98361-0100-47d9-b1a4-637b88bfc7ab)


@yanguoyu bug-level is 1 ,fix this after fix set block number sync.（not need to change）

**Comment by yanguoyu** [comment]
> 4.In Windows sync data is different from Mac when start block number is same in light client node(unit and account info is different).
> 
> Windows : ![Image](https://private-user-images.githubusercontent.com/25971273/354515074-2d65987b-c5dd-4edd-ba0d-01929e73cf0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODYxNzMsIm5iZiI6MTcyMjU4NTg3MywicGF0aCI6Ii8yNTk3MTI3My8zNTQ1MTUwNzQtMmQ2NTk4N2ItYzVkZC00ZWRkLWJhMGQtMDE5MjllNzNjZjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTU0OGQyNDA3MmJmZmU0ZjUzYzI1NDE1MzUzYzc4Mjc2MTgwNWRhMDBjZmI0NzA4YTIwOTYyM2Q1Y2I4ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myf4iInkwO0PVDZitwPPMOsx2mTfo1u6L8ayOEnagHA)
> 
> Mac: ![Image](https://private-user-images.githubusercontent.com/25971273/354515075-30d98361-0100-47d9-b1a4-637b88bfc7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODYxNzMsIm5iZiI6MTcyMjU4NTg3MywicGF0aCI6Ii8yNTk3MTI3My8zNTQ1MTUwNzUtMzBkOTgzNjEtMDEwMC00N2Q5LWIxYTQtNjM3Yjg4YmZjN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjZkM2M5MTUzMGVlYmIxYjEyMmNjY2JkMTM5ZjAzNThlMDBhMTI3MTdmOGQyMzdmN2RlZTk4YjI5ZjQyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z3BWEkCZ7EJAGnI4LQMDyNSe7fzxXbv69HzsLDQhNSk)
> 
> @yanguoyu bug-level is 1 ,fix this after fix set block number sync.

It's normal, it shows differently maybe because you did not set the account info.

**Comment by silySuper** [comment]
> > 4.In Windows sync data is different from Mac when start block number is same in light client node(unit and account info is different).
> > Windows : ![Image](https://private-user-images.githubusercontent.com/25971273/354515074-2d65987b-c5dd-4edd-ba0d-01929e73cf0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODYxNzMsIm5iZiI6MTcyMjU4NTg3MywicGF0aCI6Ii8yNTk3MTI3My8zNTQ1MTUwNzQtMmQ2NTk4N2ItYzVkZC00ZWRkLWJhMGQtMDE5MjllNzNjZjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTU0OGQyNDA3MmJmZmU0ZjUzYzI1NDE1MzUzYzc4Mjc2MTgwNWRhMDBjZmI0NzA4YTIwOTYyM2Q1Y2I4ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myf4iInkwO0PVDZitwPPMOsx2mTfo1u6L8ayOEnagHA)
> > Mac: ![Image](https://private-user-images.githubusercontent.com/25971273/354515075-30d98361-0100-47d9-b1a4-637b88bfc7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODYxNzMsIm5iZiI6MTcyMjU4NTg3MywicGF0aCI6Ii8yNTk3MTI3My8zNTQ1MTUwNzUtMzBkOTgzNjEtMDEwMC00N2Q5LWIxYTQtNjM3Yjg4YmZjN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjZkM2M5MTUzMGVlYmIxYjEyMmNjY2JkMTM5ZjAzNThlMDBhMTI3MTdmOGQyMzdmN2RlZTk4YjI5ZjQyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z3BWEkCZ7EJAGnI4LQMDyNSe7fzxXbv69HzsLDQhNSk)
> > [@yanguoyu](https://github.com/yanguoyu) bug-level is 1 ,fix this after fix set block number sync.
> 
> It's normal, it shows differently maybe because you did not set the account info.

Why  unit is different ?
It is history data,I have operated in mac before,do I need to set account again in windows?It means that the accout info can be different even if they are from same data?Same wallet but used in different os,so they can change account info? I do not know why user need to change account info just change os.

**Comment by yanguoyu** [comment]
> 3.In Windows , set start block number is not effective. In mac ,after set start block number,it will change soon in block number,but windows not.
> 
>  2024-08-02.10.03.30.mov 
> [bundled-ckb-lignt-client-testnet.log](https://github.com/user-attachments/files/16464421/bundled-ckb-lignt-client-testnet.log)
> 
> [main.log](https://github.com/user-attachments/files/16464422/main.log)

Fixed by https://github.com/nervosnetwork/neuron/pull/3220

**Comment by silySuper** [comment]
5.In windows ，claim button is invalid.



[main.log](https://github.com/user-attachments/files/16468755/main.log)




[bundled-ckb-lignt-client-testnet.log](https://github.com/user-attachments/files/16468762/bundled-ckb-lignt-client-testnet.log)

**Comment by yanguoyu** [comment]
> 5.In windows ，claim button is invalid.
> 
> [main.log](https://github.com/user-attachments/files/16468755/main.log)
> 
> [bundled-ckb-lignt-client-testnet.log](https://github.com/user-attachments/files/16468762/bundled-ckb-lignt-client-testnet.log)

Fixed by https://github.com/nervosnetwork/neuron/pull/3221

**Comment by silySuper** [comment]
verified all bugs
