### ISSUE TITLE
The alias of the Multisig address may be cleared unexpectedly

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#43]
**`Version`**
Neuron 0.103.2 MacOS & Windows

**`Reproduce`**
Step 1 -  Create an alias
Step 2 -  Re-open the Multisig address window
Step 3 -  Click the alias text box
Step 4 -  Click anywhere on the page

**`Unexpected`**
Alias name was cleared.

https://user-images.githubusercontent.com/64718893/178892880-1aed576f-01af-4b51-b7ac-571b130a5cf5.mov

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2451

**Comment by Cedar67** [comment]
Verified in the PR https://github.com/nervosnetwork/neuron/pull/2451

**Comment by Cedar67** [comment]
This PR will be merged into the next release version.
