### ISSUE TITLE
Improve unlock message when less than a day left.

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/neuron-public-issues#430]
I often encounter Neuron users who believe that they can already unlock the deposit (second step of the withdrawal process) when the deposit has less than 24 hours left to be unlocked. This confusion usually comes from this sentence: "Compensation cycle ends in approximately 0 days"

![image](https://github.com/user-attachments/assets/1ed0aeaa-ac80-4e51-b792-8c1f205edc36)

**Describe the solution you'd like**
I think it would be advisable to rephrase the sentence so that we can be more precise and not create confusion.

**Describe alternatives you've considered**
I understand that epochs are estimates and therefore we always talk about an estimated time remaining, but we could use as an alternative sentence, for example: "The compensation cycle ends in approximately less than a day" or "The compensation cycle ends in less than a day, approximately", or equivalent.

**Comment by devchenyan** [comment]
> I often encounter Neuron users who believe that they can already unlock the deposit (second step of the withdrawal process) when the deposit has less than 24 hours left to be unlocked. This confusion usually comes from this sentence: "Compensation cycle ends in approximately 0 days"
> 
> ![image](https://private-user-images.githubusercontent.com/94946624/386397389-1ed0aeaa-ac80-4e51-b792-8c1f205edc36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzc3MTgsIm5iZiI6MTczNDkzNzQxOCwicGF0aCI6Ii85NDk0NjYyNC8zODYzOTczODktMWVkMGFlYWEtYWM4MC00ZTUxLWI3OTItOGMxZjIwNWVkYzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzliYWNlNzY4YjkzMWViYWM2OGNhODUzNjI2NDFkZTVmZDBkOTA2ZmQxN2RlNDZiNGFjNjIwMGMzMjQ2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rxUI0tgIYX4tez2lFEg4qGx2bNGlBhT9BG3F66TUgXs)
> 
> **Describe the solution you'd like** I think it would be advisable to rephrase the sentence so that we can be more precise and not create confusion.
> 
> **Describe alternatives you've considered** I understand that epochs are estimates and therefore we always talk about an estimated time remaining, but we could use as an alternative sentence, for example: "The compensation cycle ends in approximately less than a day" or "The compensation cycle ends in less than a day, approximately", or equivalent.

 What version of Neuron are you using?  We have supported displaying the remaining hours when the compensation cycle is less than one day in Neuron v0.116.0

![image](https://github.com/user-attachments/assets/257f36d3-5605-4fc9-9f24-08719c0aac56)

**Comment by alejandroRbit** [comment]
> > I often encounter Neuron users who believe that they can already unlock the deposit (second step of the withdrawal process) when the deposit has less than 24 hours left to be unlocked. This confusion usually comes from this sentence: "Compensation cycle ends in approximately 0 days"
> > ![image](https://private-user-images.githubusercontent.com/94946624/386397389-1ed0aeaa-ac80-4e51-b792-8c1f205edc36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzc3MTgsIm5iZiI6MTczNDkzNzQxOCwicGF0aCI6Ii85NDk0NjYyNC8zODYzOTczODktMWVkMGFlYWEtYWM4MC00ZTUxLWI3OTItOGMxZjIwNWVkYzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzliYWNlNzY4YjkzMWViYWM2OGNhODUzNjI2NDFkZTVmZDBkOTA2ZmQxN2RlNDZiNGFjNjIwMGMzMjQ2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rxUI0tgIYX4tez2lFEg4qGx2bNGlBhT9BG3F66TUgXs)
> > **Describe the solution you'd like** I think it would be advisable to rephrase the sentence so that we can be more precise and not create confusion.
> > **Describe alternatives you've considered** I understand that epochs are estimates and therefore we always talk about an estimated time remaining, but we could use as an alternative sentence, for example: "The compensation cycle ends in approximately less than a day" or "The compensation cycle ends in less than a day, approximately", or equivalent.
> 
> What version of Neuron are you using? We have supported displaying the remaining hours when the compensation cycle is less than one day in Neuron v0.116.0
> 
> ![image](https://private-user-images.githubusercontent.com/11756869/399086017-257f36d3-5605-4fc9-9f24-08719c0aac56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MTA2MTEsIm5iZiI6MTczNTQxMDMxMSwicGF0aCI6Ii8xMTc1Njg2OS8zOTkwODYwMTctMjU3ZjM2ZDMtNTYwNS00ZmM5LTlmMjQtMDg3MTljMGFhYzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDE4MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzVhMThhMGU3NzAyNzA0YTA5NTc2NDMyN2JiOWM2NDEwYWQ0NTE5MzE1MTQzNjU5MDE0YjFjYjZlNTNlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KT-Rg0pYDngoZi9JiEgPfvJYQvkzoAkNmEw8Q7ZWlJw)

I'm using the latest version but I haven't made any withdrawals from NervosDAO for a long time. This issue comes from other users, I suppose with versions prior to v0.116.0 (unfortunately I can't know for sure since the user has deleted his TG account and in the conversation he doesn't mention the version used). Since the functionality is already implemented in Neuron since that version (I didn't know that) I proceed to close the issue satisfactorily. Thank  you
