### ISSUE TITLE
An exception transfer due to the multisig address generated by the ckb cli

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#44]
#### **`Version`**
https://github.com/nervosnetwork/neuron/pull/2442

#### **`Unexpected`**
![image](https://user-images.githubusercontent.com/64718893/178895055-42e8c1f8-12bf-4ad9-a66d-b2f02c7c6b5b.png)

![image](https://user-images.githubusercontent.com/64718893/178895381-4e3e38c1-9f5e-4356-b4d7-2ba991e3ef70.png)

#### **`Reproduce`**
ckb-cli-11 and ckb-cli-12 are both generated by the  [CKB cli (v1.0.0)](https://github.com/nervosnetwork/ckb-cli/releases/tag/v1.0.0).

![image](https://user-images.githubusercontent.com/64718893/178895126-c56f2330-0b89-4395-9024-228a8bfaae0f.png)

![image](https://user-images.githubusercontent.com/64718893/178895439-53f37c68-304c-4dde-8a3a-67565023df8e.png)

#### **`Attach`**

Multisig address and Transaction file:
[attach.zip](https://github.com/Magickbase/neuron-public-issues/files/9108321/attach.zip)

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2450

**Comment by Cedar67** [comment]
Verified in the PR https://github.com/nervosnetwork/neuron/pull/2450

**Comment by Cedar67** [comment]
This PR will be merged into the next release version.
