### ISSUE TITLE
Import/Create wallet with new design.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#46]
View Design https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1864%3A13007

Related to https://github.com/Magickbase/neuron-public-issues/issues/45

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2463

**Comment by Cedar67** [comment]
On the page for importing mnemonic words, when enter the wrong mnemonic word and click Next, the system prompt box is thrown. About the pop window, is there a need to improve the UI here? @Kirl70 


![Image](https://user-images.githubusercontent.com/64718893/187389995-82709060-f487-4034-bdb0-d972c2c45432.png)

**Comment by Kirl70** [comment]
> On the page for importing mnemonic words, when enter the wrong mnemonic word and click Next, the system prompt box is thrown. About the pop window, is there a need to improve the UI here? @Kirl70
> 
> ![Image](https://user-images.githubusercontent.com/64718893/187389995-82709060-f487-4034-bdb0-d972c2c45432.png)

> 
In the design draft, there are prompt box designs in different states (the copy inside can be adjusted according to different situations), I suggest using these to achieve a unified page style. @Cedar67 @yanguoyu 

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1299%3A9436
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/106060898/187390781-3cb2a9fa-b569-495a-a8b1-3a2c787b7c2d.png">

**Comment by Cedar67** [comment]
> > On the page for importing mnemonic words, when enter the wrong mnemonic word and click Next, the system prompt box is thrown. About the pop window, is there a need to improve the UI here? @Kirl70
> > ![Image](https://user-images.githubusercontent.com/64718893/187389995-82709060-f487-4034-bdb0-d972c2c45432.png)
> 
> > 
> 
> In the design draft, there are prompt box designs in different states (the copy inside can be adjusted according to different situations), I suggest using these to achieve a unified page style. @Cedar67 @yanguoyu
> 
> https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1299%3A9436 <img alt="image" width="1410" src="https://user-images.githubusercontent.com/106060898/187390781-3cb2a9fa-b569-495a-a8b1-3a2c787b7c2d.png">

got it. Thanks.

**Comment by Cedar67** [comment]
Verified.
