### ISSUE TITLE
Update Nervos DAO rules

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#47]
Since `Cell Mature` mechanism has been updated on hardfork, the `4 epochs` rule should be deprecated, and withdraw cells can be unlocked earlier.

We should check the new rule and update the workflow in neuron. Setup a draft of the new workflow first for @quake and then update the code

Ref: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0036-remove-header-deps-immature-rule/0036-remove-header-deps-immature-rule.md

**Comment by Keith-CY** [comment]
The `4 epochs` requirement is only added in the UI(https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/utils/getDAOCellStatus.ts#L65) and not included in [startWithdrawFromDao](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/transaction-sender.ts#L582-L619) and [withdrawFromDao](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/services/transaction-sender.ts#L621-L720), instead, it throws an error if `dao cell` is immature.

So we can simply update the validation in UI and leave backend intact for this change.

**Comment by Keith-CY** [comment]
This feature is required by community, maybe we could finish it with the current version and then merge it into the new UI version @yanguoyu

**Comment by yanguoyu** [comment]
This is also no need `4 epochs`. https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/utils/getDAOCellStatus.ts#L79
Nervos DAO can be withdraw right now after deposit, then can be unlock after `180 epoch`.

**Comment by yanguoyu** [comment]
Because Nervos DAO can only unlock after `180 epoch`, `David` account has two deposits can be unlock after `1 day`, I will test unlock tomorrow.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2461

**Comment by Cedar67** [comment]
> [nervosnetwork/neuron#2461](https://github.com/nervosnetwork/neuron/pull/2461)

Verified.
