### ISSUE TITLE
Allow `UAN` and `Display name` in Neuron

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#48]
The limit of token info in neuron is as following:
1. Token name is up to 16 chars;
2. Token symbol is up to 8 chars.

With the `UAN` adoption, `Token name` would easily break the `16 chars` limit, e.g. `WBTC (via Forcebridge from ETH)` uses 31 chars, and `uan` would break the `8 chars` limit, too, e.g. `ETH.gw|gb.ckb|fb.eth` uses 20 chars

To allow users to use `UAN`, we should loosen the limit on the length of `token name` and `symbol`, and because they are just attributes for the view layer and have nothing to do with chain data, we can set them much larger for broader usage, maybe 200 chars for token name and 100 chars for `UAN` is enough for the near future.

How do you think about it @yanguoyu @Cedar67 

Universal Asset Notation: https://github.com/nervosnetwork/rfcs/blob/a092218b8f3ba9b6616ff41bd56a5a75d42efaf7/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2465

**Comment by yanguoyu** [comment]
After adding token info, if at `overview`, `history`, `send asset`, `receive asset`, `custommized assets` pages, we will analyze the symbol by `UAN` rule, if it matches `UAN` rule, it will show the `UAN Diaplay name`, and show the full name when hovering over the element, else wrap display when it's too long.

**Comment by yanguoyu** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/12881040/185565186-f0c8340b-058b-4489-a040-d3bf9a1ceb18.png">
This will show full symbol because it's hover event has been used by copy balance.

**Comment by Keith-CY** [comment]
> <img alt="image" width="1210" src="https://user-images.githubusercontent.com/12881040/185565186-f0c8340b-058b-4489-a040-d3bf9a1ceb18.png">
> 
> This will show full symbol because it's hover event has been used by copy balance.

I think it’s good enough for most users

**Comment by yanguoyu** [comment]
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/12881040/185580509-bf5936f4-b0d5-4314-b705-186c31fc7883.png">
There may be no need for hover to display the full name because the full name can be shown when hovering the title.
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/12881040/185580739-79a8f990-46c3-4661-9414-d2b086371cdf.png">

**Comment by yanguoyu** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/12881040/185740487-db763e73-ca86-4c35-8bb5-6aa7deaadd3f.png">
This also will show full symbol without tips because it need copy event.

**Comment by Cedar67** [comment]
> nervosnetwork/neuron#2465

UAN rule and user defined rule have been verified.
