### ISSUE TITLE
Rename `ckb node data` label

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#49]
Users are confused by different behaviors from specifying directory of ckb node and ckb indexer.

Specifying the target directory of ckb node will create a `data` sub-directory in it and store chain data there, while specifying the target directory of ckb indexer will store data in it directly, that's the difference.

Neuron creates `data` inside the target directory of ckb node because `configurations` such as `ckb.toml` are  treated as data and will be initialized in the same directory where `data` is created, namely the `target directory`.

Maybe we could rename `ckb node data` to clarify it. I thinks `ckb node config & storage` is a good choice

![Pasted Graphic](https://user-images.githubusercontent.com/7271329/182287359-75351136-07e0-443e-b411-bc487bd3918f.png)

Ref: https://github.com/nervosnetwork/neuron/issues/2459

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2464

**Comment by Cedar67** [comment]
Verified.
