### ISSUE TITLE
Resynchronizing the CKB node from scratch resets the indexer data

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#50]
When Neuron re-synchronizes CKB node data from scratch, Neuron automatically removes the original Indexer synch data from the corresponding network and re-synchronizes Indexer from scratch.

The Data path Settings prompt information needs to be modified, especially to remind users. Because the previous Indexer data will be deleted:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/64718893/182797290-e717e67c-3c5e-4c5e-9a15-d20ffd6b0ec6.png">

Ref: https://github.com/nervosnetwork/neuron/issues/2459#issuecomment-1202671640

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2464

**Comment by Cedar67** [comment]
The Indexer error log info found.
Ref: https://github.com/nervosnetwork/neuron/pull/2464#issuecomment-1225122885

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2478

**Comment by Cedar67** [comment]
> [nervosnetwork/neuron#2478](https://github.com/nervosnetwork/neuron/pull/2478)

Verified.
