### ISSUE TITLE
Disable node path Settings under certain conditions

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#51]
Certain condition: CKB node are running locally instead of Neuron started CBK node.

Corresponding response: 

- Disable node path Settings.
- Add the (i) symbol to tell reason.

**Comment by yanguoyu** [comment]
I only add tips for changing the CKB Node Data path, I found it may not check the node is working outside or in the Neuron accurately.
https://github.com/nervosnetwork/neuron/pull/2464

**Comment by Cedar67** [comment]
The tips has been validated. 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/64718893/183795556-e33fe1a3-873d-4b3d-be6c-fdf7e38de74f.png">
