### ISSUE TITLE
Preview functions and design of light client

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#52]
The light client is designed to mitigate data/network/computing loading on a user's client, which improves the performance and user experience of DApps indirectly. It is possible to adopt the light client in Neuron instead of ckb-indexer so we could have a quick peek at it.

https://github.com/nervosnetwork/ckb-light-client

**Comment by yanguoyu** [comment]
I have try to start [ckb-light-client](https://github.com/nervosnetwork/ckb-light-client) locally.
Now that `ckb-light-client` is developing, some RPC APIs can't return expected values. After it releases, ckb-indexer will not depend on running a `ckb-node` locally.
Now we can collect the APIs we have used, then after the ckb-light-client is released, we can know can we use it to instead of `ckb` and `ckb-indexer`.

**Comment by Keith-CY** [comment]
We're going to verify if neuron works well with the light client after Neuron@v0.106.0 has been released, please read the relevant materials @JeffreyMa597

**Comment by JeffreyMa597** [comment]
> We're going to verify if neuron works well with the light client after Neuron@v0.106.0 has been released, please read the relevant materials @JeffreyMa597

I got it. Could you please give me some more information about the `light client` and other materials maybe I will use? Thank yu.

**Comment by Keith-CY** [comment]
> > We're going to verify if neuron works well with the light client after Neuron@v0.106.0 has been released, please read the relevant materials @JeffreyMa597
> 
> I got it. Could you please give me some more information about the `light client` and other materials maybe I will use? Thank you.

The repo(https://github.com/nervosnetwork/ckb-light-client) mentioned in the first message is all we have now. It includes source code, API document, and 2 RFCs about the design.

**Comment by JeffreyMa597** [comment]
> The repo(https://github.com/nervosnetwork/ckb-light-client) mentioned in the first message is all we have now. It includes source code, API document, and 2 RFCs about the design.

Yeah, thanks. 
After replied to you, I just realized that the repo address was in the description.  ^_^

**Comment by Keith-CY** [comment]
Workflow of synchronizing data from ckb light client

```mermaid
sequenceDiagram
  participant keys
  participant scripts
  participant transactions
  participant light client
keys->>keys: init [20 receivings,10 changes]
keys->>scripts: mapping to 30 secp256k1 lock and 30 acp lock
scripts->>light client: subscribe 60 scripts
light client->>light client: sync scripts
light client->>transactions: txs of 60 scripts
transactions->>keys: which keys have been used
keys->>keys: derive to [40 receivings, 20 changes] if last than 3 receivings or changes remain
```

The logic is quite different from what Neuron is using now.

Currently, Neuron scans blocks one by one and updates transactions within each block on succession. Along with processing a transaction, Neuron has to check if more keys should be derived because the new key may be used in the next transaction.

Working with the light client, Neuron could sync each key separately because each key has its own cursor/progress. That means it's safe to postpone key derivation until the derived keys are all processed totally. With this characteristic, Neuron could divide synchronization into groups of keys instead of each block, which is efficient.

**Comment by Keith-CY** [comment]
We'll start this feature once Neuronv0.106.0 is released if there are no more questions about the design.

**Comment by yanguoyu** [comment]
> Working with the light client, Neuron could sync each key separately because each key has its own cursor/progress.

I don't know what means about `each key has its own cursor/progress.`. I think the difference between `light` and `full` node is:  The `Light client` can sync some scripts that have been set, but the full node shoud sync all scripts.
But `Light client` also uses `RPC` to get transactions. It seems not to provide a listener to get transactions.

**Comment by Keith-CY** [comment]
> > Working with the light client, Neuron could sync each key separately because each key has its own cursor/progress.
> 
> I don't know what means about `each key has its own cursor/progress.`. I think the difference between `light` and `full node` is: The `Light client` can sync some scripts that have been set, but the full node should sync all scripts. But `Light client` also uses `RPC` to get transactions. It seems not to provide a listener to get transactions.

The cursor mentioned here is the `block number` field in response of `get_scripts`, each subscribed `script` has its own progress. Say there're 4 scripts subscribed, and the target block number as a milestone of synchronization is 30000, now:
- script 1 has synchronized to block 30000
- script 2 has synchronized to block 25000
- script 3 has synchronized to block 20000
- script 4 has synchronized to block 15000

Then it's clear script 1 has fully synchronized and cells/transactions returned by the light client is up to date, while script 2, 3, 4 don't have synchronized fully, so fetching their cells/transactions could be postponed. For simplicity, these 4 scripts could be regarded as a group and their transactions/cells could be fetched when the group has fully synchronized.

Once the group of scripts has reached the target block number, fetch its transactions(since the last milestone, `block_range` params in `get_transactions` RPC) and check if a new group of scripts should be derived.

With this process, `checking and deriving scripts` will be simple and low-frequent(from checking per transaction to checking per block).

What's more, each `script` could have its own progress bar and refresh itself independently. If the user declares address A has an invisible asset, he/she could resync the group only.

And the most common issue `dead cell used in transaction` could be resolved too, if a dead cell is used in a transaction, its script could be refreshed.

----

Actually, working with `light client` is quite similar to working with `indexer`, it should be

1. subscribe `scripts`(light client only)
2. wait for `scripts` synchronized in light client/indexer
3. fetch transactions/cells from light client/indexer

step 2 and 3 work as a loop

And working with light client/indexer is quite different from working with full node because light client/indexer works from the perspective of scripts, while full node works from the perspective of blocks.

**Comment by Keith-CY** [comment]
> > > Working with the light client, Neuron could sync each key separately because each key has its own cursor/progress.
> > 
> > 
> > I don't know what means about `each key has its own cursor/progress.`. I think the difference between `light` and `full node` is: The `Light client` can sync some scripts that have been set, but the full node should sync all scripts. But `Light client` also uses `RPC` to get transactions. It seems not to provide a listener to get transactions.
> 
> The cursor mentioned here is the `block number` field in response of `get_scripts`, each subscribed `script` has its own progress. Say there're 4 scripts subscribed, and the target block number as a milestone of synchronization is 30000, now:
> 
> * script 1 has synchronized to block 30000
> * script 2 has synchronized to block 25000
> * script 3 has synchronized to block 20000
> * script 4 has synchronized to block 15000
> 
> Then it's clear script 1 has fully synchronized and cells/transactions returned by the light client is up to date, while script 2, 3, 4 don't have synchronized fully, so fetching their cells/transactions could be postponed. For simplicity, these 4 scripts could be regarded as a group and their transactions/cells could be fetched when the group has fully synchronized(if light client/indexer supports batch request).
> 
> Once the group of scripts has reached the target block number, fetch its transactions(since the last milestone, `block_range` params in `get_transactions` RPC) and check if a new group of scripts should be derived.
> 
> With this process, `checking and deriving scripts` will be simple and low-frequent(from checking per transaction to checking per block).
> 
> What's more, each `script` could have its own progress bar and refresh itself independently. If the user declares address A has an invisible asset, he/she could resync the group only.
> 
> And the most common issue `dead cell used in transaction` could be resolved too, if a dead cell is used in a transaction, its script could be refreshed.
> 
> Actually, working with `light client` is quite similar to working with `indexer`, it should be
> 
> 1. subscribe `scripts`(light client only)
> 2. wait for `scripts` synchronized in light client/indexer
> 3. fetch transactions/cells from light client/indexer
> 
> step 2 and 3 work as a loop
> 
> And working with light client/indexer is quite different from working with full node because light client/indexer works from the perspective of scripts, while full node works from the perspective of blocks.

Various groups of scripts could be synchronized to different block numbers, that's the `cursor/progress of each script` feature mentioned above.

**Comment by yanguoyu** [comment]
> subscribe scripts(light client only)

I didn't find that `light client` has provided a subscribe script API.
Do you mean we first call `set_script` to filter and then implement a subscribe by `RPC`?
If so, I think we can also implement a subscribe by `RPC` but without `set_script` to filter script synchrony.

**Comment by Keith-CY** [comment]
> > subscribe scripts(light client only)
> 
> I didn't find that `light client` has provided a subscribe script API. Do you mean we first call `set_script` to filter and then implement a subscribe by `RPC`? If so, I think we can also implement a subscribe by `RPC` but without `set_script` to filter script synchrony.

`set_script` makes `light client` subscribe to specific scripts so that data will be stored inside the light client. And we can poll data from the light client periodically.

---

I didn't get the point of

> If so, I think we can also implement a subscribe by `RPC` but without `set_script` to filter script synchrony.

As I know, the light client cannot work without `set_script` because it doesn't know which data to store locally if `script list` is not set.

**Comment by Keith-CY** [comment]
> Will we poll data with `RPC`?

Yes, poll data with `get_scripts` and fetch data once `get_scripts` indicates a `script` has been fully synchronized.

> If use RPC to poll data, I mean we can suppose the full node is called set_script with all scripts?

Exactly, that's the why I mentioned working with `light client` is quite similar to working with `ckb indexer`, and quite different from working with `full node`

**Comment by yanguoyu** [comment]
> > Will we poll data with `RPC`?
> 
> Yes, poll data with `get_scripts` and fetch data once `get_scripts` indicates a `script` has been fully synchronized.
> 
> > If use RPC to poll data, I mean we can suppose the full node is called set_script with all scripts?
> 
> Exactly, that's the why I mentioned working with `light client` is quite similar to working with `ckb indexer`, and quite different from working with `full node`
> 
> ![image](https://user-images.githubusercontent.com/7271329/210295421-f341f8ce-87b9-40f7-afc3-debd1f1ae019.png)

Got it, no problem now.

**Comment by Keith-CY** [comment]
Implementation is tracked by https://github.com/Magickbase/neuron-public-issues/issues/90
