### ISSUE TITLE
Upgrade deps for security

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#53]
https://github.com/nervosnetwork/neuron/security/dependabot

**Comment by Keith-CY** [comment]
@yanguoyu could you visit the page mentioned above

**Comment by yanguoyu** [comment]
> @yanguoyu could you visit the page mentioned above

404

**Comment by Keith-CY** [comment]
> > @yanguoyu could you visit the page mentioned above
> 
> 404

How is it now

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/security is the security setting, What's `dependabot`? It's also 404

**Comment by Keith-CY** [comment]
> [nervosnetwork/neuron/security](https://github.com/nervosnetwork/neuron/security) is the security setting, What's `dependabot`? It's also 404

It lists deps require upgrade for security issues
<img width="877" alt="image" src="https://user-images.githubusercontent.com/7271329/186092733-166a261b-78fc-407f-91ed-906c6d72fc69.png">

**Comment by Keith-CY** [comment]
I've updated access config of dependabot

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2490 update `lerna` to 5.5.2.
Now I'm upgrading `storybook` to 6.5.12, it has some breaking changes, and I need more time to change stories.
