### ISSUE TITLE
Release v0.104.0 on 08/31

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#55]
- [x] rc on <del>08/24</del> 09/02
- [ ] release on <del>08/31</del> 09/07

**Comment by Keith-CY** [comment]
RC: https://github.com/nervosnetwork/neuron/pull/2481

**Comment by Keith-CY** [comment]
Hold on due to ckb node not running on M1

Ref: https://github.com/Magickbase/neuron-public-issues/issues/57

**Comment by doitian** [comment]
Try portable binaries for CentOS, Linux, macOS in v0.104.1

**Comment by Keith-CY** [comment]
Hold on due to https://github.com/Magickbase/neuron-public-issues/issues/58

**Comment by Keith-CY** [comment]
Hold on until CKB@v0.105.2 is release, CKB@v0.105.1 has a performance issue

**Comment by Keith-CY** [comment]
> Hold on until CKB@v0.105.2 is release, CKB@v0.105.1 has a performance issue

The performance issue is fixed by https://github.com/nervosnetwork/ckb/pull/3705

**Comment by doitian** [comment]
> > Hold on until CKB@v0.105.2 is release, CKB@v0.105.1 has a performance issue
> 
> The performance issue is fixed by [nervosnetwork/ckb#3705](https://github.com/nervosnetwork/ckb/pull/3705)

CKB v0.106.0 will include these fixes

https://github.com/nervosnetwork/ckb/issues/3710

**Comment by Keith-CY** [comment]
[CKB@v0.106.1-rc1](https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc1) has been released and Neuron should be tested with it @yanguoyu @Cedar67

**Comment by Cedar67** [comment]
> [CKB@v0.106.1-rc1](https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc1) has been released and Neuron should be tested with it @yanguoyu @Cedar67

Updated the ckb node to v0.106.0-rc1, there were still unexplained disk space error messages and blocking migration. Please confirm.

![image](https://user-images.githubusercontent.com/64718893/203064340-35bd099d-0bec-4869-be55-6736c4588d0c.png)

**Comment by Cedar67** [comment]
Looks like there's still a performance exception.  @Keith-CY @doitian 
The memory usage of the ckb process continues to increase and can cause PC crashes. 
The CPU usage of the ckb process is high.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/64718893/203090334-6de7cf62-c90c-42c7-9b48-c1e0e5934570.png">

![image](https://user-images.githubusercontent.com/64718893/203090600-0c498683-70dc-4483-8c55-42b0d12afcca.png)


<img width="226" alt="image" src="https://user-images.githubusercontent.com/64718893/203090885-a30a33d1-4834-4888-8142-fa753ec2f806.png">

**Comment by doitian** [comment]
https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc2 is out

**Comment by Cedar67** [comment]
> https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc2 is out

Verified. Performance tests were performed on this release (v0.106.0-rc2) and no performance exception could be found.


<img width="639" alt="Activity Monitor" src="https://user-images.githubusercontent.com/64718893/203999404-e3dd830c-4235-4e5e-8cb3-f2e1342e5e46.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/64718893/203090885-a30a33d1-4834-4888-8142-fa753ec2f806.png">

**Comment by Cedar67** [comment]
> https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc2 is out

@doitian @Keith-CY There is another exception to be concerned about:

- During CKB data synch, the memory usage of the ckb process continues to increase. 
- After the synch is complete, no memory is released.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/64718893/204071063-9f5bce79-6612-4231-9b93-732644b6d9fa.png">

**Comment by doitian** [comment]
> > https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0-rc2 is out
> 
> @doitian @Keith-CY There is another exception to be concerned about:
> 
> * During CKB data synch, the memory usage of the ckb process continues to increase.
> * After the synch is complete, no memory is released.
> 
> <img alt="image" width="969" src="https://user-images.githubusercontent.com/64718893/204071063-9f5bce79-6612-4231-9b93-732644b6d9fa.png">

cc @zhangsoledad

**Comment by doitian** [comment]
ckb [v0.106.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0) released

**Comment by Keith-CY** [comment]
> ckb [v0.106.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0) released

Will be updated by https://github.com/nervosnetwork/neuron/pull/2555

**Comment by Keith-CY** [comment]
PR of releasing Neuron@v0.106.0 on 2022/12/28: https://github.com/nervosnetwork/neuron/pull/2556

**Comment by Keith-CY** [comment]
Neuron@v0.106.0 has been released: https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0
