### ISSUE TITLE
Resize of multisig address window should be disabled

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#6]
https://user-images.githubusercontent.com/7271329/161193639-8d7d4432-8232-42cc-90d9-f035f5bb4a4c.mov

Other sub-windows are disabled to be resized.

**Comment by yanguoyu** [comment]
https://github.com/nervosnet/neuron-internal/issues/1289#issue-710809985

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2357
