### ISSUE TITLE
Locate the cause of UI automated test failure

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#60]
Sometimes, UI automated test results are failed and needed to confirm the reason.

http://neuron-test.nervosnet.org/job/Neuron-qa-test/125/console

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/64718893/192679105-57932007-cfca-4a71-b821-e11f625a4b02.png">

**Comment by Keith-CY** [comment]
How is it going

**Comment by Cedar67** [comment]
The factor of current localization is the execution environment, not a bug in the Neuron version. After debugging the test environment, there has been no recurrence of exceptions for several days. It needs to be observed for a while.
<img width="213" alt="image" src="https://user-images.githubusercontent.com/64718893/195118953-003d1c1c-8793-4d64-9f69-a44c08d62cfa.png">

**Comment by Cedar67** [comment]
Fixed.

**Comment by Keith-CY** [comment]
Is this issue fixed by https://github.com/nervosnetwork/neuron-automation/pull/12

**Comment by Cedar67** [comment]
> Is this issue fixed by [nervosnetwork/neuron-automation#12](https://github.com/nervosnetwork/neuron-automation/pull/12)

yes
