### ISSUE TITLE
Update `react-router` to v6 before update `storybook`

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#61]
Related to https://github.com/Magickbase/neuron-public-issues/issues/45

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2499
@Cedar67 This pr update react-router to v6, and features keep unchanging compared with https://github.com/Magickbase/neuron-public-issues/issues/46.
It means need to test full about `Import/Create Wallet`, and other pages only need to verify functions and ignore styles.

**Comment by Cedar67** [comment]
> [nervosnetwork/neuron#2499](https://github.com/nervosnetwork/neuron/pull/2499) @Cedar67 This pr update react-router to v6, and features keep unchanging compared with #46. It means need to test full about `Import/Create Wallet`, and other pages only need to verify functions and ignore styles.

ok, I'll run a regression test on the `Import/Create Wallet` features.

**Comment by Cedar67** [comment]
full testing has been done on the `Import/Create` Wallet features.
