### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#62]
Package for Apple Silicon: https://www.electronjs.org/blog/apple-silicon

<del>Could have a try on building a universal app: https://github.com/electron-userland/electron-builder/pull/5481</del>

Pay attention to a bug of auto update: https://github.com/electron-userland/electron-builder/issues/5689#issuecomment-946528612

**Comment by yanguoyu** [comment]
We will build another package for M1 when we release neuron?
Does apple Silicon applications run on intel? I don't have Apple Silicon hardware currently.

**Comment by Keith-CY** [comment]
> We will build another package for M1 when we release neuron? Does apple Silicon applications run on intel? I don't have Apple Silicon hardware currently.

Yes, there will be two packages for MacOS as some apps do, e.g. *Or, for Macs with Apple Silicon chips, click [here](https://zoom.us/client/5.12.0.11129/zoomusInstallerFull.pkg?archType=arm64) to download* on https://zoom.us/download

The app could be packaged as a universal one but the size will be doubled because it simply includes one for intel and one for arm64. It might not be a good idea for users(but we can provide this version if possible)

I'm using M1 so I can test the package.

**Comment by JeffreyMa597** [comment]
> > We will build another package for M1 when we release neuron? Does apple Silicon applications run on intel? I don't have Apple Silicon hardware currently.
> 
> Yes, there will be two packages for MacOS as some apps do, e.g. _Or, for Macs with Apple Silicon chips, click [here](https://zoom.us/client/5.12.0.11129/zoomusInstallerFull.pkg?archType=arm64) to download_ on https://zoom.us/download
> 
> The app could be packaged as a universal one but the size will be doubled because it simply includes one for intel and one for arm64. It might not be a good idea for users(but we can provide this version if possible)
> 
> I'm using M1 so I can test the package.

I can test the package also.

**Comment by yanguoyu** [comment]
@JeffreyMa597 Do you have time to try to finish it?

**Comment by JeffreyMa597** [comment]
> @JeffreyMa597 Do you have time to try to finish it?

sure.

**Comment by Keith-CY** [comment]
How is it going

**Comment by JeffreyMa597** [comment]
> How is it going

@Keith-CY I've fixed this issue. I'll package the app on my machine and perform a local verification to verify whether the modification is successful.

I earned two problems: 1、The appleId is not found. 2、I can't sign when I commit my code.   I'm trying to resolve them.

**Comment by Keith-CY** [comment]
> > How is it going
> 
> @Keith-CY I've fixed this issue. I'll package the app on my machine and perform a local verification to verify whether the modification is successful.
> 
> I earned two problems: 1、The appleId is not found. 2、I can't sign when I commit my code. I'm trying to resolve them.

Cool, I would suggest proposing a draft PR first, so we can have a review. Besides, apple id is not so important to block this issue because we can verify it by CI.

For the signature of commit, we can force push the PR once it's been fixed.

**Comment by JeffreyMa597** [comment]
> 

Okay

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2510
