### ISSUE TITLE
Shall we build our `Calendar` component to remove primereact dependency?

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#66]
We only use `Calendar` with `primereact`. Shall we build our `Calendar` component in the new UI works?
@Keith-CY What do you think?
https://github.com/Magickbase/neuron-public-issues/issues/45

**Comment by Keith-CY** [comment]
Implementing the component without a third-party dependency is cool, let's do it 🤘

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2592

**Comment by Cedar67** [comment]
There is an issue that needs to be solved or confirmed. Now move this task to the `In Progress` status.

https://github.com/nervosnetwork/neuron/pull/2592#issuecomment-1457941157
