### ISSUE TITLE
Array.prototype.map requires a return statement

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#67]
![image](https://user-images.githubusercontent.com/7271329/196368575-5883a485-39cd-4471-8195-46e1dd62c523.png)
`Array.prototype.forEach` should be used

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2507

**Comment by Cedar67** [comment]
Is the related function verification required?

**Comment by Keith-CY** [comment]
> Is the related function verification required?

These updates are just refactoring tests so they are not necessary to be verified with a packaged application.
