### ISSUE TITLE
Remove @uifabric/experiments and @uifabric/styling with new UI.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#68]
`@uifabric/experiments` only uses in https://github.com/nervosnetwork/neuron/blob/4de122604aef9f5d13f593a6344061994022aa38/packages/neuron-ui/src/components/SpecialAssetList/index.tsx#L4 with `Pagination`
`@uifabric/styling` only uses in https://github.com/nervosnetwork/neuron/blob/4de122604aef9f5d13f593a6344061994022aa38/packages/neuron-ui/src/utils/icons.ts#L1 with `icons`.
Related to https://github.com/Magickbase/neuron-public-issues/issues/45

**Comment by JeffreyMa597** [comment]
I'll update the version of `sqlite` to v5.1.2.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/22511289/203514300-7bffa625-4aac-4de6-9248-696512d1f58a.png">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2537

**Comment by Cedar67** [comment]
Verified.
