### ISSUE TITLE
Regression Testing of Neuron

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#7]
Test cases https://docs.google.com/spreadsheets/d/1J2ENPt3lkikBncv-NN_cSaquhsX_0xDSR1GiVhBBNho

We should test Neuron fully through the cases listed in the excel by 04/18

Any refactor or optimization could be committed, including code quality or UI improvement

**Comment by Keith-CY** [comment]
Test cases about recently added functionalities will be complemented soon.

**Comment by Keith-CY** [comment]
Any update? @Cedar67

**Comment by Cedar67** [comment]
当前进展：
1. 分析了测试用例文档，统计用例分布情况见下图所示。
<img width="844" alt="image" src="https://user-images.githubusercontent.com/64718893/165422285-ffbca33e-787e-4bdd-9d04-aafcc41a944c.png">

2. 和商柯咨询了回归测试的范围和工作量。回归范围是基础用例（256个），预计2周~3周。
3. 整理和核对了自动化测试代码，共计44个测试点，见下图所示：
<img width="811" alt="image" src="https://user-images.githubusercontent.com/64718893/165422567-f65acf18-5d6c-4b33-b339-7b3d0b8cfd12.png">

**Comment by Cedar67** [comment]
当前进展：
1. 回归测试状态
![image](https://user-images.githubusercontent.com/64718893/167747114-91cba3a5-7551-4dd7-9195-92fb2dd5f773.png)
2. 在远程windows完成搭建本地UI测试自动化开发环境并调试成功，以便维护和开发自动化测试工程。
3.

**Comment by Cedar67** [comment]
当前测试进展：
![image](https://user-images.githubusercontent.com/64718893/168940605-7227769b-c988-48b3-b5e8-2efc8ede140c.png)
