### ISSUE TITLE
Update for ckb@0.105.0 which integrates ckb-indexer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#71]
ckb@0.105.0: https://github.com/nervosnetwork/ckb/blob/pkg/v0.105.0/CHANGELOG.md will be released on 10/25 so we can start the work on adopting it.

The main update for Neuron is that `ckb-indexer` is integrated into `ckb-node` so we don't have to launch 2 servers before synchronization.

There will be 3 updates in Neuron

1. Remove launching ckb-indexer on the start;
2. Data of ckb-node and ckb-indexer may be in the same place so `CKB Node Data` and `CKB Indexer Data` setters in `Settings -> Data` could be combined into one, and migration of existing data should be considered;
3. `Clear Cache` may change according to the update.

More features could be added after the ckb@0.105.0 is released and questions about these updates could be attached in this issue.

**Comment by Keith-CY** [comment]
CKB@0.105.0 pre-release: https://github.com/nervosnetwork/ckb/releases/tag/v0.105.0-rc1

**Comment by yanguoyu** [comment]
1. Reference this https://github.com/nervosnetwork/ckb/pull/3609. We can start indexer and ckb by `ckb run -C <path>  --indexer`.
2. [get_tip](https://github.com/nervosnetwork/ckb-indexer#get_tip) was renamed to get_indexer_tip, to avoid ambiguity. We should replace the function name.
3. The `ckb` data and `indexer` data are all saved in the directory which is the -C parameter we start ckb

**Comment by yanguoyu** [comment]
> > 
> 
> > 1. Reference this [ merge indexer nervosnetwork/ckb#3609](https://github.com/nervosnetwork/ckb/pull/3609). We can start indexer and ckb by `ckb run -C <path>  --indexer`.
> > 2. [get_tip](https://github.com/nervosnetwork/ckb-indexer#get_tip) was renamed to get_indexer_tip, to avoid ambiguity. We should replace the function name.
> > 3. The `ckb` data and `indexer` data are all saved in the directory which is the -C parameter we start ckb
> 
> Will there be any change points in terms of user functionality and interaction? Such as data setting parameters and methods.

`Ckb node data path` and `indexer data path` will merge into a path.

**Comment by yanguoyu** [comment]
We should keep the functions `Refresh` or `Rebuild` for the indexer data. Because removing all `ckb` data will use much time to rebuild. @Keith-CY

**Comment by yanguoyu** [comment]
If we run 0.105 ckb on old path, it will throw error like this `For optimal performance, CKB wants to migrate the data into new format.` So we need to guide user to migrate data to new version.

**Comment by Keith-CY** [comment]
> If we run 0.105 ckb on the old path, it will throw an error like this `For optimal performance, CKB wants to migrate the data into new format.` So we need to guide users to migrate data to the new version. What should we do to guide users? @Keith-CY
> 
> <img alt="image" width="719" src="https://user-images.githubusercontent.com/12881040/198869587-9f20d2e1-65e5-4304-8e1f-fb2f1e5b36d8.png">
> 
> I think we can delete all data and synchronize them again. Because migration will take quite a long time.

As mentioned in the [comment](https://github.com/Magickbase/neuron-public-issues/issues/71#issuecomment-1290302786) that migration took 20 minutes on Macbook Pro 2019 i9 mode. Tt depends on the performance of the platform but synchronizing ckb node from scratch requires more than 20 minutes obviously.

Migration is about rebuilding `new data` from `old data` so it doesn't rely on the network, and the [PR](https://github.com/nervosnetwork/ckb/pull/3609) said a built-in indexer has prominent optimization on performance. Theoretically `migration` should be quicker than the function of `clear cache(rebuild index)` neuron has added.

These two cases quite contradict the prompt message from ckb node so we may ask @doitian for some advice.

Besides, I found the migration is triggered by interactive progress, is there a cli option to start the migration?

**Comment by yanguoyu** [comment]
> Besides, I found the migration is triggered by interactive progress, is there a cli option to start the migration?

Ok, I will try to migrate testnet data to test how much time will cost.
Yes, we can run `./ckb migrate -C path --force` to force migrate.

**Comment by doitian** [comment]
The message is misleading. We don't have bias towards any method, since some migration jobs may take longer than re-sync. Since user has already start the migration, it's better to let try re-sync only when migration fails.

**Comment by Keith-CY** [comment]
The migration message could be delivered by the global dialog which has been used to tell users about migration from 0.32 to 0.33, the estimation of time to consume could be updated.

Code: 
- https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/types/App/index.d.ts#L121
- https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/widgets/GlobalDialog/index.tsx#L17-L31

PR: https://github.com/nervosnetwork/neuron/pull/1743

Neuron@0.33 release note: https://github.com/nervosnetwork/neuron/releases/tag/v0.33.0

**Comment by Keith-CY** [comment]
> The message is misleading. We don't have bias towards any method, since some migration jobs may take longer than re-sync. Since user has already start the migration, it's better to let try re-sync only when migration fails.

Got it, let's take `migration failure` as an exception and tell the user to `clear sync data` in `menu -> tools` @yanguoyu

**Comment by doitian** [comment]
[0.105.1](https://github.com/nervosnetwork/ckb/releases/tag/v0.105.1) is out, which has fixed a performance issue related to migration.

**Comment by yanguoyu** [comment]
Migrating testnet data cost 21 minutes. (MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)) @Keith-CY 

@doitian Is there any way to get the progress of migrating? When I run migrate with Node.js, I didn't found any logs, and after migrate finish, there is also no content in the migrate.log.

**Comment by quake** [comment]
the migration progress is output to the stdout, you may try redirecting the ckb process' stdout to the UI.

**Comment by doitian** [comment]
I'm not sure whether the progress bar is available after redirection. It may detect whether the stdout is tty.

**Comment by yanguoyu** [comment]
If I cannot get the migration process log. I will treat the migration process end with code 0 as finished, otherwise treat it as failed.
Is it reasonable?

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2517

**Comment by Cedar67** [comment]
> [nervosnetwork/neuron#2517](https://github.com/nervosnetwork/neuron/pull/2517)

Verified.
Ref https://github.com/nervosnetwork/neuron/pull/2517#issuecomment-1327647847

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2541
