### ISSUE TITLE
Bump Node.js from 16 to 18

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#72]
Node 18 has been TLS since Oct. 25 and Node 16's end time has been brought forward to Sep. 11, 2023.

Now neuron is specified to run with Node 16 so some updates may be required for Node 18

Updates needed in:
1. CI as https://github.com/nervosnetwork/neuron/blob/develop/.github/workflows/package.yml#L15
2. Runtime as https://github.com/nervosnetwork/neuron/blob/develop/package.json#L18

Refs:
https://nodejs.org/ar/blog/announcements/nodejs16-eol/

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2518
