### ISSUE TITLE
Bump React.js from 16 to 18

### ISSUE THREAD

**Issue by JeffreyMa597** [Magickbase/neuron-public-issues#73]
Since React.js 16.8, there exists a few important changes, the latest version of react.js is v18.2.0. So it seems necessary for us to update our React version.

Updating the react version may involve a number of other dependencies that need to be upgraded simultaneously,
such as react-dom, react-script, node, typescript, etc. I'll update the version to 17 first, and then up to 18 if possible.

**Comment by JeffreyMa597** [comment]
PR:https://github.com/nervosnetwork/neuron/pull/2519

**Comment by yanguoyu** [comment]
React-router has updated on the `new-ui` branch. It maybe will create many conflicts. What shall we do, update `react` on the `new-ui` branch or resolve conflicts later? @Keith-CY
I think maybe updating it on the `new-ui` branch is a good point, because it makes changes less.

**Comment by Cedar67** [comment]
Validation is blocked on Windows OS.
https://github.com/nervosnetwork/neuron/pull/2519#issuecomment-1330627522

**Comment by Cedar67** [comment]
Verified on Mac and Windows OS.
