### ISSUE TITLE
Neuron should catch uncaughtException in the main process.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#74]
The uncaughtException shouldn't show to users. Because they also don't know what it means?

**Comment by yanguoyu** [comment]
We should do this because https://github.com/nervosnetwork/neuron/issues/2527

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2531

**Comment by Cedar67** [comment]
> [nervosnetwork/neuron#2531](https://github.com/nervosnetwork/neuron/pull/2531)

The issue has not been reproduced. After it is merged into `develop`, verify it again.
