### ISSUE TITLE
Update electron to 22.0.0

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#82]
It's better to update the dependence to the latest stable version.
Finish it to close https://github.com/nervosnetwork/neuron/pull/2525.

**Comment by yanguoyu** [comment]
1. [sandbox preloads by default](https://github.com/electron/electron/pull/35125)
2. https://github.com/nervosnetwork/neuron/pull/2525#issuecomment-1338792873

**Comment by yanguoyu** [comment]
There is an issue https://github.com/electron/electron/issues/33685, but it seems not to affect functions.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/12881040/207217463-6c82abe3-b576-454f-a446-3fd241578778.png">

**Comment by Keith-CY** [comment]
> There is an issue [electron/electron#33685](https://github.com/electron/electron/issues/33685), but it seems not to affect functions. <img alt="image" width="717" src="https://user-images.githubusercontent.com/12881040/207217463-6c82abe3-b576-454f-a446-3fd241578778.png">

It would be fine if UI is rendered as expected. I've tracked some issues of this bug and found UI should be broken into a blank screen if this it is triggered.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2544
