### ISSUE TITLE
Support dynamic fee rate based on `fee_rate_statistics`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#87]
An RPC to fetch `fee_rate_statistics` is added since CKB@v0.106.0, which returns `mean` fee rate and `median` fee rate of the specified block range.

With the historic data, Neuron could offer more precise fee rate recommendations for users.

PRD will be added by 12/16

Ref: https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_fee_rate_statics

**Comment by Keith-CY** [comment]
Neuron adopted 2 strategies for fee rate selection

1. custom fee rate
![image](https://user-images.githubusercontent.com/7271329/210598273-65cd9202-49c1-4565-8b83-222d49df0919.png)
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/Send/hooks.ts#L64
![image](https://user-images.githubusercontent.com/7271329/210598354-67ace783-d9c0-4680-bb50-ac9f5f70d038.png)
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/SUDTSend/index.tsx#L220

With the custom fee rate mode, the user can input an arbitrary fee rate or pick one from the suggested fee rate dropdown list (1000, 2000, 5000)

2. fixed fee rate
![image](https://user-images.githubusercontent.com/7271329/210598411-b5e35c8a-27aa-42dc-9fb9-90e41bd84061.png)
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/NervosDAO/hooks.ts#L56
![image](https://user-images.githubusercontent.com/7271329/210598445-2f98398a-78e3-467a-9ee4-d90d051389c0.png)
(actions on customized assets are all based on a fixed fee rate)
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/NFTSend/index.tsx#L125
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/components/SpecialAssetList/index.tsx#L251
![image](https://user-images.githubusercontent.com/7271329/210599692-07c6e819-cf3f-49ee-8bf3-6e9ebc1bf499.png)
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-ui/src/utils/hooks/createSUDTAccount.ts#L45

---

With the new RPC [get_fee_rate_statics](https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_fee_rate_statics), `median` and `mean` fee rate of the last 21 blocks could be fetched from the ckb node. These two values could be regarded as the base of fee rate suggestions.

Suppose the `suggested fee rate` is `max(1000, mean_fee_rate, median_fee_rate)`(1000 is the minimal fee rate set in ckb node config)

For case 1, 
1. rename `advanced fee settings` to `custom fee rate`
2. if `custom fee rate` is unchecked, the fee rate dropdown list is displayed with 3 options
	1. Fast: fee rate is `2 * suggested_fee_rate - 1000`
	2. Standard: fee rate is `suggested_fee_rate`
	3. Slow: fee rate is `1000`

	Each option is displayed with `priority`(fast, standard, slow), `fee rate`, and `fee`. The `standard` one is selected by default.
	
3. if `custom fee rate` is checked, a text field is displayed and the dropdown list is hidden. The text field allows the user to input a custom fee rate.
    1. the `suggested fee rate` is displayed beneath the text field if it's empty
    2. the `fee` is displayed (instead of the `suggested fee rate`) beneath the text field if it's not empty
    3. an error message is displayed (instead of the fee/suggested fee rate) if the custom fee rate is invalid(not a number, less than 1000)

4. the `suggested fee rate` is refreshed every 10 blocks

For case 2,
The `suggested fee rate` will be used instead of the `medium value` in the current version

**Comment by Keith-CY** [comment]
The feature request of dynamic fee rate was updated, please have a review @yanguoyu @JeffreyMa597 @Cedar67

**Comment by yanguoyu** [comment]
> the suggested fee rate is refreshed every 10 blocks

How about refreshing it by a fixed time frequency? For example, every 30s to refresh it.

**Comment by Keith-CY** [comment]
> > the suggested fee rate is refreshed every 10 blocks
> 
> How about refreshing it by a fixed time frequency? For example, every 30s to refresh it.

LTGM, if it's refreshed in a fixed tempo, a countdown could be appended nearby as 
![image](https://user-images.githubusercontent.com/7271329/211190201-5cfe5b5d-b57c-40f6-ab2d-45e2e902bab6.png)

**Comment by Keith-CY** [comment]
UI will be updated in https://github.com/Magickbase/visual-style-guide/issues/21

**Comment by Keith-CY** [comment]
Implementation is tracked by https://github.com/Magickbase/neuron-public-issues/issues/new
