### ISSUE TITLE
Update actions

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/neuron-public-issues#88]
Some action functions are deprecated. We should use the latest functions to update it.
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/12881040/206390271-6b149c15-13fb-4271-84dc-13effbc412eb.png">
https://github.com/nervosnetwork/neuron/actions/runs/3646157224

**Comment by Keith-CY** [comment]
Actions will be updated by renovate as it did in this PR https://github.com/nervosnetwork/neuron/pull/2514, and it will propose more once there's a room in the PR pool
