### ISSUE TITLE
Destroy an ACP asset account

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#9]
When the ACP asset account has 0 balance, it would allow the user to destroy it to take 162 CKBytse back.

1. When the balance of ACP asset account is 0, add a `destroy` button in the sending panel(just as the one in sending panel of CKB asset account)
![image](https://user-images.githubusercontent.com/7271329/163742140-4488991c-aa4e-4a67-99ee-bf7ba9245e40.png)

3. Click the `destroy` button, lock script of the ACP asset will be replaced by a secp256k1 lock, namely the cell occupying 162 CKBytes would regress to a normal CKB cell.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2337
