### ISSUE TITLE
Remove data of the independent ckb-indexer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#91]
CKB indexer of CKB node has been used since Neuron@v0.106.0(https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0) and the data of indexer are stored in a new directory(inside ckb directory).

However, data of the deprecated independent ckb indexer have not been removed and they cannot be cleared by `clear cache`.

To remove the outdated data, Neuron should add a task to check and remove them.

**Comment by yanguoyu** [comment]
Should we add choose for users to delete, or delete indexer data by default? @Keith-CY

**Comment by Keith-CY** [comment]
> Should we add choose for users to delete, or delete indexer data by default? @Keith-CY

I think it's safe to delete because Neuron@0.106.0 doesn't have an independent ckb indexer, so the data will not be used by any service. If the user runs ckb indexer by own, the indexer data will be stored elsewhere.

Namely, the `indexer data` is only accessible to the independent ckb indexer inside Neuron.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2565

**Comment by Keith-CY** [comment]
Sorry for adding a new detail, a precondition is expected to be added that the removal of old data should only be executed after the migration is fulfilled(the new path was set).

**Comment by yanguoyu** [comment]
> Sorry for adding a new detail, a precondition is expected to be added that the removal of old data should only be executed after the migration is fulfilled(the new path was set).

Add this with https://github.com/nervosnetwork/neuron/pull/2565/commits/2c876c04eefa16c3f595b8ccfb89b50abbecf9b2
