### ISSUE TITLE
Support custom installation path on windows

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#92]
This feature request comes from https://github.com/nervosnetwork/neuron/discussions/2564 and it expects that Neuron can be installed in a user-specified directory instead of the default directory.

This feature is expected to be enabled by setting `allowToChangeInstallationDirectory: true` in `nsis options`, but it should be verified because many related issues/complaints are found

Ref: https://www.electron.build/generated/nsisoptions

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2568

**Comment by Cedar67** [comment]
Verified.
