### ISSUE TITLE
Integrate with CKB node for arm64

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#93]
// TODO: check if it's possible to request CKB node to release with an arm64 version, or can we compile one for Neuron

**Comment by doitian** [comment]
Not sure whether https://github.com/nervosnetwork/ckb/releases/download/v0.107.0-rc1/ckb_v0.107.0-rc1_aarch64-unknown-linux-gnu.tar.gz works for macOS

**Comment by Keith-CY** [comment]
An arm64-based version of CKB node will be released in the next release.

**Comment by Keith-CY** [comment]
Seems that arm64 for mac is not delivered with [v0.108.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.108.0) @doitian

**Comment by doitian** [comment]
https://github.com/nervosnetwork/ckb/issues/3817

**Comment by Keith-CY** [comment]
CKB node for arm64 will be delivered in the next version

**Comment by doitian** [comment]
Released https://github.com/nervosnetwork/ckb/releases/tag/v0.108.1

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2627
