### ISSUE TITLE
Implement dynamic fee rate based on `fee_rate_statistics`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#95]
PRD: https://github.com/Magickbase/neuron-public-issues/issues/87
UI: https://github.com/Magickbase/visual-style-guide/issues/21

**Comment by JeffreyMa597** [comment]
PR: https://github.com/nervosnetwork/neuron/pull/2587

**Comment by JeffreyMa597** [comment]
@Keith-CY @Kirl70 To confirm, I think the countdown of this place is misplaced. It should be in the tab of custom price, right?
<img width="904" alt="image" src="https://user-images.githubusercontent.com/22511289/220385216-258097dc-d4d0-4abb-bcd5-830ad065fa23.png">

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=319%3A4539&t=CWzeBjkusAhZL7SX-0

**Comment by Keith-CY** [comment]
> @Keith-CY @Kirl70 To confirm, I think the countdown of this place is misplaced. It should be in the tab of custom price, right?

The countdown should be placed with the pre-defined 3 gears of prices, these 3 gears update automatically.

When the custom price is active, the price is from what entered by users and won't update automatically

> PS: should the price in the dropdown also need update based on the data from the server? If so, I want to know how can I compute the total fee we should pay. <img alt="image" width="800" src="https://user-images.githubusercontent.com/22511289/220515996-f794fee7-190f-44de-bdf1-c0cef2767bfc.png">
> 
> [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=319%3A4539&t=CWzeBjkusAhZL7SX-0](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=319%3A4539&t=CWzeBjkusAhZL7SX-0)

The `fee` changes along with the price. `fee = tx_size * price`, the `tx_size` could be get from a serialized transaction, ref: https://github.com/nervosnetwork/neuron/blob/ce2c08f00269aba13979853a38cb72ae42b12b6a/packages/neuron-wallet/src/services/transaction-sender.ts#L709

When the tx is invalid, it cannot be serialized, and the fee is `0` or `-`(better to confirm with @Danie0918)

**Comment by JeffreyMa597** [comment]
The new PR is here: https://github.com/nervosnetwork/neuron/pull/2599

**Comment by Cedar67** [comment]
> The new PR is here: [nervosnetwork/neuron#2599](https://github.com/nervosnetwork/neuron/pull/2599)

Custom prices and unit prices are only displayed in Simplified Chinese, and cannot be switched to English or Traditional Chinese.

![image](https://user-images.githubusercontent.com/64718893/227796958-32f901bf-3a3e-450c-bbbd-3c03d6ec2e98.png)
